### ISSUE TITLE
[PC] vid_fullscreen_standalone draws Window under Windows taskbar

### ISSUE THREAD

**Issue by TrueNightmare** [nzp-team/nzportable#1]
Tested when using 1080p which is native to my monitor.

**Comment by MotoLegacy** [comment]
Please provide screenshots for more detail.

**Comment by TrueNightmare** [comment]
![image](https://user-images.githubusercontent.com/51242703/161967355-ed38f494-4f7d-4857-b2fb-9fb42a57597d.png)

Build version is current nightly. all settings are on screen

**Comment by MotoLegacy** [comment]
Fixed in [quakec/f2a80afd](https://github.com/nzp-team/quakec/commit/f2a80afd3be25272a1d40ebfb20aa74e71190bc4)
