### ISSUE TITLE
[MENU] Map description cut off at default window size

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#10]
The custom map description text is cut off at the right side of the screen at the default window size as shown here:

![fte-20220429154804-0](https://user-images.githubusercontent.com/29164668/165968809-d4c154f0-c6d6-4928-ba48-937295e1a7e0.png)

**Comment by MotoLegacy** [comment]
Closing as all potential menu issues will be addressed with https://github.com/nzp-team/nzportable/issues/7.
