### ISSUE TITLE
[PSP] Unable to disable fullbright

### ISSUE THREAD

**Issue by TheSubPlayer** [nzp-team/nzportable#100]
Once fullbright is activated, it is not possible to deactivate it, however, when exiting the game and entering again, the option is deactivated. (On windows, the effect is activated/deactivated in real time. On the psp, fullbright is activated in real time but it is no longer possible to deactivate it, the option gets stuck).

Tested on PSP 3000 and Win64

1. Go to 'Settings'
2. Click on 'Graphics Settings'
3. Scroll down to 'Fullbright'
4. Toggle to 'Enable'
5. Is not possible toggle to 'Disable'

Expected behavior:

Fullbright should be disabled and effect applied after entering/restarting any map.

https://user-images.githubusercontent.com/110436924/212245556-a75b8471-7e06-4450-a8a0-c69c07d97572.mp4

**Affected Platforms:**

- PSP

Not Tested on:

- PS VITA
- Nintendo Switch
- 3DS

**Comment by MotoLegacy** [comment]
Can you try pressing `CROSS` instead of `RIGHTARROW`? Using `RIGHTARROW` for non-slider options is deprecated and has slightly different functionality as a result.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/fddb0859dc61d5867f39816d422470e2fbb87972
