### ISSUE TITLE
Waypoint sprite not rendered fullbright

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#1000]
**Describe the bug**
waypoint sprite itsn't fullbright

**To Reproduce**
1. open a map like ndu
2. go into waypoint mode
3.  see bug 

**Expected behavior**
they should be fullbright

**Screenshots/Footage**

![image](https://github.com/user-attachments/assets/30b646fc-bec7-4e79-a591-2c0577af84a1)

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/b0f30c38240e03bb6e5fe0843bd773f94d707ddb
