### ISSUE TITLE
Incorrect binds shown in waypoint menu

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#1002]
**Describe the bug**
For most of the default binds in the waypoint menu it shows Left click as the bind

**To Reproduce**
1. Open a map 
2. Turn on waypoint mode
3. It should be visible

**Expected behavior**
It should show whatever the binds are set to

**Screenshots/Footage**

![image-37.png](https://github.com/user-attachments/assets/cb6c98bf-5f17-426f-a63c-1cc345df78ce)

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
This was caused by moving away from the old archaic CSQC menu

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/28b25b42dc873459988e7e44d5d0c0df016320b0
