### ISSUE TITLE
[FTE] Volume key binds are able to take volume beyond slider limit

### ISSUE THREAD

**Issue by JCR64** [nzp-team/nzportable#1003]
**Describe the bug**
Using the keys for volume up and volume down you can control the master volume and go beyond the limits of what the slider allows in Audio Options.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a keyboard with `volup` and `voldown` buttons
2. Load a map
3. Use the volume up or down buttons on your keyboard a bunch of times 
(a few presses of `voldown` should be enough to go below 0 and past the minimum the slider allows)
4. Check the audio settings in the menu to see where the slider is at

**Expected behaviour**
Not be able to go beyond limits of what the slider allows for and/or possibly change the default binds `volup inc volume 0.1` and `voldown inc volume -0.1` as they will be used for system volume controls (on Windows at least).

**Screenshots/Footage**

https://github.com/user-attachments/assets/3d696228-b3f1-4958-b057-d2f6e6b3a82b

**Affected Platforms**
- FTEQW (Windows 10/11)

Untested on other OS

**Additional context**
- Not affected when playing in a web browser (tested: Edge and Firefox)

**Comment by MotoLegacy** [comment]
Wontfix, doesn't seem to be on my end. FTE should clamp this to not allow over/under 0-1. Feel free to report upstream
