### ISSUE TITLE
PSP-PC bug

### ISSUE THREAD

**Issue by Real-Eragamer** [nzp-team/nzportable#1005]
Zombies stuck to the walls or just goes  to the corner until player arrive and sometimes in some maps , they respawn in locked room.

i played in PC and PSP version and all i can tell you is this. i hope you guys do great because i enjoyed and suggested everyone of my friends.

**Comment by Peter0x44** [comment]
You should fill out the issue template properly.

**Comment by Real-Eragamer** [comment]
**Expected behavior**
i expected to zombies come for me and attack me 

**Screenshots/Footage**
not available right now.

**Affected Platforms**
# PSP.
# PC.

- PSP 
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**
is psp they just run toward a wall in nacht der untoten and another map which i forgot the name, zombies respawn in a locked room.  in pc the stuck to the walls ( they dont run toward the walls like psp ) .
