### ISSUE TITLE
[WEB] UI Turns Black/Silhouetted

### ISSUE THREAD

**Issue by rinkachi-rinkitata** [nzp-team/nzportable#1008]
**Describe the bug**
Sometimes when using the WebGL build and upon loading in the UI will be matt black - does not happen all the time (maybe caused by shaders failing?)

**To Reproduce**
- go to the WebGL version https://nzp.gay
- load into a solo game on any map
- refresh site until glitch occurs (not sure if refreshing has anything to do with fixing it)

1. Go to '....'

**Expected behavior**
UI/HUD should appear in the standard colours

**Screenshots/Footage**
![image](https://github.com/user-attachments/assets/e721ce7e-8f5c-455a-b977-7d80695702b7)
HUD

![image](https://github.com/user-attachments/assets/13e40e71-445e-4ea5-b1c8-0fecf6d9c339)
Game Over Text

![image](https://github.com/user-attachments/assets/a4e9643c-7f27-4bcf-8f3d-c860b6d5858a)
Pause Menu

**Affected Platforms**
Only experienced on the WebGL version (https://nzp.gay)

**Comment by MotoLegacy** [comment]
I've reported this to Spike
