### ISSUE TITLE
[PSP] Texture issues in some enemies

### ISSUE THREAD

**Issue by TheSubPlayer** [nzp-team/nzportable#101]
Some enemies have the loading screen texture instead of the default texture.
(This occurs in any map)

Tested on PSP 3000

1. Just play and see the magic

Expected behavior:
This should not happen ¯\_(ツ)_/¯

![RemoteJoyLite_en 2023-01-12 23-31-59-454](https://user-images.githubusercontent.com/110436924/212263680-89a4dae2-d0cc-4b16-a38a-b1a596ab9f0a.jpg)
![RemoteJoyLite_en 2023-01-12 23-43-54-689](https://user-images.githubusercontent.com/110436924/212263684-37261479-528f-415c-aaf1-92b6c42ea508.jpg)
![pic_0035](https://user-images.githubusercontent.com/110436924/212264462-6f32cbce-8d01-459b-9f6a-6a46820d1668.png)
![pic_0041](https://user-images.githubusercontent.com/110436924/212264465-ad858723-7b3f-4fa1-89c2-ea216c4f7ca1.png)
![pic_0042](https://user-images.githubusercontent.com/110436924/212264963-d32488e6-4dfb-4aa5-a7ba-2e4f6ec319a2.png)
![pic_0043](https://user-images.githubusercontent.com/110436924/212264966-3ae17dc1-1bbc-461f-869f-8552083ca7f9.png)

**Affected Platforms:**

- PSP

NOT tested on:

- PS VITA
- Nintendo Switch
- 3DS

**Comment by MotoLegacy** [comment]
Looks like your assets are out of date (telling by the *very* old placeholder load screen for B1ooDv3). Make sure you're updating more than just the EBOOT or the QuakeC when downloading the game files. Our `README` for each component states this explicitly. Update your assets and let me know if this is still an issue.

**Comment by BCDeshiG** [comment]
The placeholder for B1ooDv3 still exists (used for the loading screen instead of the menu thumbnail where it used to be) so this is a fairly recent build.

**Comment by MotoLegacy** [comment]
Oops. Thanks for confirming.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/c2a101cb9b9c841bbe4e598fa9db8e69943968fb
