### ISSUE TITLE
[PSP] All controls including sprint and crouch unbound after exiting during loading

### ISSUE THREAD

**Issue by masterpl4n** [nzp-team/nzportable#1010]
**Describe the bug**
All controls besides look, unfortunately including sprint and crouch which can’t be rebound conventionally are unbound when quitting during loading

**To Reproduce**
Boot up NZP (this is essentially the latest version as I did a reinstall a week ago) on PSP
Wait on the initial loading screen until the tooltip is present but the loading bar disappears (which is what I did)
Press home and Exit to XMB
Re-enter into a game and everything is unbound

**Affected Platforms**
# PSP 1000

**Comment by MotoLegacy** [comment]
Can't reproduce given the steps provided. Please re-open if you are able to find concrete steps
