### ISSUE TITLE
sv_listen_qw being on allows others to view and join your solo games in WebGL

### ISSUE THREAD

**Issue by JCR64** [nzp-team/nzportable#1011]
**Describe the bug**
When playing solo games via web version, games are being displayed in the server browser and are joinable. 

Turning `sv_listen_qw` off for solo games was done before the menu update https://github.com/nzp-team/nzportable/issues/526#issuecomment-1852398962 to fix a similar issue but not with latest menu.

**To Reproduce**
1. Start a solo game in the web browser
2. Check console to see that it is `Listening on /NZP-REBOOT-WEB/...`
3. Test again but with `sv_listen_qw` set to `0`

**Expected behaviour**
Not allowing connections when in solo mode or displaying game in the server browser.

**Affected Platforms**
- FTEQW (WebGL)

**Additional context**
Doesn't happen on non-web build of FTE (tested Windows)

**Comment by MThsola** [comment]
[cant replicate?](https://streamable.com/1zc6ym) you mightve included incorrect reproduction steps or something

**Comment by katniny** [comment]
> [cant replicate?](https://streamable.com/1zc6ym) you mightve included incorrect reproduction steps or something

you didnt actually test the issue reported. you just checked if `Listening to /NZP/REBOOT-WEB/id` was there, which doesn't confirm what the bug was reporting
the bug states "`When playing solo games via web version, games are being displayed in the server browser and are joinable.`"
you didn't confirm to see if it was joinable or visible in the server browser

**Comment by MThsola** [comment]
>  you didn't confirm to see if it was joinable or visible in the server browser

that is correct and is my mistake, and i apologize. however, in my defense:

> 2. Check console to see that it is Listening on /NZP-REBOOT-WEB/...

i was just following replication steps that OP did but i did completely miss the entire point of the issue though so its still partially my fault
[here](https://streamable.com/p70vyv) is it properly replicated to my understanding however still somehow not able to replicate

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/7203fbef966ff22691c6946732bcc0b59aebb9a9
