### ISSUE TITLE
No `show_speed` or equivalent

### ISSUE THREAD

**Issue by n4htx** [nzp-team/nzportable#1013]
**To Reproduce**
1. Open any map
2. Open console and type in `show_speed 1`

**Expected behavior**

A debug/polished hud element with players velocity to appear.

**Platforms I haven't tested on:**

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

Was wondering if this was intended or if there is another command for the same purpose that I should use?

**Comment by MotoLegacy** [comment]
@erysdren has offered to take a look at this.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/317da957640aabc82288d535c4ef251d2fcb1314
