### ISSUE TITLE
Pixel Walk God Spot in Fegefeuer

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#1014]
**Describe the bug**
_A clear and concise description of what the bug is._

You can Pixel Walk on top of the Right Side of Spawn's Trench.

**To Reproduce**
1. Go to Fegefeuer.
2. Mash A and D while Facing directly at the Fence and before landing Press W.
3. See if you can Walk to the Left without falling off.

**Expected behavior**
_A clear and concise description of what you expected to happen._

You cannot Pixel Walk.

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://youtu.be/_AdKSL5yDGg

**Affected Platforms**
_State which platform(s) you've seen the bug occur._
- FTEQW (Windows, Mac, **Linux**, WebGL etc)

_Please also make note of any platforms you DID NOT test on._
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional context**

This could very well be a Engine Error, since it also exists in the Source Engine, which was like a Fork of the Quake Engine, which FTE, alongside all other Platform Ports were based of.

**Comment by MotoLegacy** [comment]
@DerpedCrusader can you take a look at this?

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/542b68eba9a15ad3de0387543f01ef9ced5c53f7
