### ISSUE TITLE
[SUGGESTION] Make the social links in the main menu clickable

### ISSUE THREAD

**Issue by MThsola** [nzp-team/nzportable#1015]
**Describe your suggestion**
When any of the social links in the bottom right in the main menu get pressed (for example, BlueSky), it should open the social link in a new tab

Not really practical or needed in any way just QoL

<sub><sup>I just want to get to the docs fast man<sup><sub>

**Expected behavior**
Click social link button, opens that social link in a new tab

**Screenshots/Footage**
N/A

**Additional context**
N/A

**Comment by MotoLegacy** [comment]
I don't believe FTEQW has this functionality, and if it did I'd personally find it a bit invasive.
