### ISSUE TITLE
Crash with `chase_active` enabled

### ISSUE THREAD

**Issue by JCR64** [nzp-team/nzportable#1018]
**Describe the bug**
Playing with `chase_active 1` leads to soft crash, the game will lock after some time and then kick you out to the main menu.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into a map
2. Turn `chase_active 1` on and move around
3. Give it some time and eventually it will lock
4. See crash error in console

**Screenshots/Footage**

<img width="642" alt="chase_error" src="https://github.com/user-attachments/assets/08451b6f-057a-4bbc-823c-c60554f66bcc">

https://github.com/user-attachments/assets/21f25052-9ca6-495c-9183-3743b9f2520b

**Affected Platforms**
- FTEQW (Windows, Mac, Linux, WebGL etc)

Not affected in PPSSPP

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/6357ee3226bbef1c62bfff29bb9c6e2f14bfd6fc
