### ISSUE TITLE
Multiplayer is not working on WebGL

### ISSUE THREAD

**Issue by w4tersp1ll** [nzp-team/nzportable#1020]
**The bug**
Multiplayer isn't working on WebGL, or at least for me and my friends, looking at the console it says that it's trying to "connect to XXXX" for a long time...we used VPNs at first, then we used our home wifi (we were trying it at school thats why it we were using vpns since it was blocked), we tried other laptops and disable firewalls, still no luck, we decided with hotspots and still. Does anybody have any clue whats going on?. It works if I do it locally (connect to my own game in the same browser).

**Expected behavior**
To connect/download map

**Screenshots/Footage**
![image](https://github.com/user-attachments/assets/0843916a-cc5c-48f8-b64e-57516aff54f1)

**Affected Platforms**
WebGL, tried on Chromebook, and Windows with disabled firewall 
Browsers: Chrome, and Edge after failing with Chrome on Windows.

**Comment by w4tersp1ll** [comment]
![image](https://github.com/user-attachments/assets/4fa87a24-9ed1-4ec5-985c-42eeb49eef47)
Dont know if this is useful, but here it is...

**Comment by MotoLegacy** [comment]
This is an issue with your network configuration, not a build issue
