### ISSUE TITLE
Possible memory leak in Windows build

### ISSUE THREAD

**Issue by JCR64** [nzp-team/nzportable#1021]
**Describe the bug**
This is just from observing Task Manager in the background while playing but memory usage of the game seems to be consistently increasing while playing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Play the Windows build
2. Observe memory usage with Task Manager in the background

**Screenshots/Footage**
Video of it going from ~350MB to ~950MB after 20 minutes (task manager at the bottom):

https://github.com/user-attachments/assets/bba30671-041a-4b64-a576-5f13953847b4

Settings for game seen in video:
<img width="402" alt="settings" src="https://github.com/user-attachments/assets/adb686cd-93ee-4751-a4f5-d880451a462a">

**Affected Platforms**
- FTEQW (Windows)

Tested on 2 different computers, one Windows 10 and one Windows 11, with same issue appearing. No issue when tested on web build (Firefox).

**Additional context**
- Memory usage increases on main menu too and if in pause menu during a game
- I couldn't test to see what happens at 100% usage but maybe someone else can

**Comment by Peter0x44** [comment]
What GPU and what GPU drivers are you using?

**Comment by JCR64** [comment]
> What GPU and what GPU drivers are you using?

Computer 1 (Windows 11): 
GPU: Intel Iris Xe Graphics (Alder Lake-P 282 GT2)
Driver Version: 31.0.101.4502

Computer 2 (Windows 10):
GPU: NVIDIA GeForce RTX 3060 Ti
Driver Version: 565.90

**Comment by MotoLegacy** [comment]
I've forwarded this over to spike
