### ISSUE TITLE
[CSQC] Inconsistent/Stuttery interpolation on viewmodels with low framerate animations

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#103]
**Describe the bug**
The animations of some guns are stuttery (video down below)

it seems to be an issue with interpolation of the lower framerate animation being stretched out unevenly when timed to the reload timing

it also seems to be tied to the frame rate the game is running at, if the game hits a solid 60, you almost never see it, 120, you see it once or twice *maybe*, but at the standard 500FPS for PC... it jumps around a lot

**To Reproduce**

It's kind of hard to explain how to create it yourself, but I'll just mention problem weapons

1. get the M1Garand (after the update)
2. reload the gun
3. really look at the animation, and look for inconsistencies

i know some people have issues seeing frame rate dips, but you need to really look for it

**Expected behavior**
I would expect the interpolation to handle the stretching properly, and for it to be smooth regardless of the framerate of anything

**Screenshots/Footage**

https://user-images.githubusercontent.com/13917665/212393028-619c29c5-22fd-440b-aec5-d20ab7d5bcfc.mp4

this shows it off in the extremes, but it does happen subtly on other weapons

**Affected Platforms:**

This affects almost every platform to some extent, but its most noticeable on PC due to its higher framerate cap

i tested on PC, and 3DS though for now, I might update with further testing down the line

**Comment by blubs** [comment]
Fixed in: https://github.com/nzp-team/quakec/commit/8a34ab4da21927e9e25dd6f7c97713c7ac0a0e00
