### ISSUE TITLE
Decrementing functionality via `trigger_relay`

### ISSUE THREAD

**Issue by F0mx** [nzp-team/nzportable#1030]
[Akin to the functionality from HL, ability to decrement `game_counter` through use of a `trigger_relay` with Trigger State set to OFF.](https://twhl.info/wiki/page/game_counter)

Would add a lot of potential to adding game logic via entities, allowing for more complex events / easter eggs.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/0cee4480aa9dd0bd11f011ba9607fd8784489c94 https://github.com/nzp-team/quakec/commit/b5ecd5dafdc25948af662a39482c85a2b7b55076
