### ISSUE TITLE
Zombies can land on your head. Assuming you could land on the zombies head then.

### ISSUE THREAD

**Issue by Lolinburgs** [nzp-team/nzportable#1036]
I know this isn't an official map nor one of the user maps but a mod you have to get. BUT I think this highlights an issue present with the actual game. Please correct me if I'm wrong. Zombies can land on your instead of simply falling. It's fairly inconsistent but I show it here. I can assume you can land on there heads and that could result in glitch spots. 

https://github.com/user-attachments/assets/2f3c03b0-c312-4adb-a1d0-9104ebbd9dec

**Comment by MotoLegacy** [comment]
Does not follow template.
