### ISSUE TITLE
Pathfinding glitch

### ISSUE THREAD

**Issue by Lolinburgs** [nzp-team/nzportable#1037]
So this is a path finding glitch. I know its on a custom map but please correct me if I'm wrong but I think this is just an issue with path finding and not the map itself. A similar thing happens when you go up stairs on an official map they just get real confused. 

https://github.com/user-attachments/assets/c4d51cc8-b1d6-43a7-b71a-96ac92b24752

**Comment by Peter0x44** [comment]
I think this map is missing waypoints, which is why this happens. Not an nzp issue.

**Comment by MotoLegacy** [comment]
Does not follow template.
