### ISSUE TITLE
downing while reviving someone will pick up both you and the person you're reviving

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#104]
**Describe the bug**
if you try to revive someone. and at the same time go down. the revive bar continues filling up and you can't cancel it. once its filled, both you and the person you were reviving both get up. was tested with 4 players

**To Reproduce**
1. go into a coop match with 3 or 4 players
2. let another player go down.
3. attempt to revive them
4. go down
5. see the revive bar fill up
6. you both get up

**Expected behavior**
should stop reviving and you both stay downed

**Affected Platforms:**
only tested on PC

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/88c08e24b4028739c518fb6ad3c8ac32fc3a40d1
