### ISSUE TITLE
Zombies lighting issue on warehouse

### ISSUE THREAD

**Issue by Lolinburgs** [nzp-team/nzportable#1041]
On warehouse on windows 10 exe they turn dark if you go under the stairs which doesn't make sense in terms of how lighting works. I bet this could be replicated on other maps I'm not sure though. 

https://github.com/user-attachments/assets/a3001c92-5e01-4f46-82de-9e7ab13912d4

**Comment by MotoLegacy** [comment]
Does not follow template.
