### ISSUE TITLE
Shooting after you are dead.

### ISSUE THREAD

**Issue by Lolinburgs** [nzp-team/nzportable#1042]
On any map on windows 10 exe build I can shoot zombies as I am down. Also I still have a hud, target that turns red when looking at zombies, etc. 

https://github.com/user-attachments/assets/04384fc4-718f-40d5-b481-983e25bfc3fc

**Comment by Peter0x44** [comment]
To add some more context
When I tested this, I could only fire one shot that showed a hitmarker (that's also the case in the video). I don't think the shot did any damage, I tested a headshot with kar98k on a round one zombie and it didn't die.

The crosshair did draw, and would disappear if I ADS'd

**Comment by MotoLegacy** [comment]
Does not follow template.
