### ISSUE TITLE
[NX] Opening console from menu will show a distorted terminal

### ISSUE THREAD

**Issue by Naievil** [nzp-team/nzportable#105]
**Describe the bug**
The terminal from the main menu will distort the home menu screen and present a bloom effect instead of a black screen (or darkened background for readability)

**To Reproduce**
1. Install latest NX version 
2. Start NZPortable, go to Settings -> Console
3. Observe bloom effect

**Expected behavior**
Should show darkened terminal instead of bloomed effect

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/13153090/212448981-55db8953-ca11-4e47-a290-72b93012560e.jpeg)
**Affected Platforms:**

# Please make note of any platforms you DID NOT test on.
Non NX

**Comment by Naievil** [comment]
Also, for some reason the net icon is there?

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakespasm/commit/cc76d04b841c442f22288ed174419988b01e289e
