### ISSUE TITLE
[3DS] Failed to allocate SOC_Buffer

### ISSUE THREAD

**Issue by ConstantinZpher** [nzp-team/nzportable#1052]
The previous build worked fine on the 3DS XL Classic, but this new release no longer launches and is stuck on a blank screen that reads:
![image](https://github.com/user-attachments/assets/dd8afeea-4c10-42fb-85ab-3036698fabf3)

Sys_Error: Failed to allocate SOC_Buffer

**Comment by Peter0x44** [comment]
Dup of  #995

**Comment by ConstantinZpher** [comment]
@Peter0x44 Sorry about that, the previous version worked fine on real hardware, do you guys provide downloads of previous builds?

**Comment by Peter0x44** [comment]
No, AFAIK. I have a working build that required reducing the amount of memory quake allocates for its heap, but I noticed some weird graphics corruption in some maps.
The long term solution is going to be making a CIA, which allows making extra memory.

**Comment by ConstantinZpher** [comment]
I see. Thanks for providing a detailed explanation as to why this occurs, I had no idea there were setbacks when using 3dsx as opposed to CIA. Good luck!
