### ISSUE TITLE
[SERVER] Bumping into walls or props interrupts sprinting

### ISSUE THREAD

**Issue by Peter0x44** [nzp-team/nzportable#1053]
**Describe the bug**
If you bump into walls or props, your sprint gets interrupted. I think the game simply stops your sprint if you ever go below the sprinting speed while doing it.

**To Reproduce**

Load up any map
Begin sprinting into objects and walls
Notice your sprint stops if you do

Video:
https://youtu.be/i6SbFATYjPk

**Expected behavior**
The sprints wouldn't get interrupted.
Here is some behavior from black ops 2:
https://youtu.be/QJjBW8Troow

**Affected Platforms**
I only tested FTE, but I assume this affects everything

**Comment by MotoLegacy** [comment]
This seems clear to be bug and/or undefined behavior within CoD, if you do this same experiment on a game with viewlegs you can see them play back at a low rate presumably tied to velocity, perpetually "running" into a wall with no movement. It's pretty broken all around.
