### ISSUE TITLE
Maps menu shows things that are not maps

### ISSUE THREAD

**Issue by Naievil** [nzp-team/nzportable#106]
**Describe the bug**
In the custom maps menu, there are maps that are not displayable (meaning there is no shading over any name) and when hit with the A button, we instantly crash

**Expected behavior**
No unsupported maps should display and we should definitely not be able to click on them 

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/13153090/212449191-57e5c4ea-0ca3-4af6-af31-8b17fe7c35fb.jpeg)
**Affected Platforms:**

# Please make note of any platforms you DID NOT test on.

Non NX

**Comment by MotoLegacy** [comment]
potentially fixed in https://github.com/nzp-team/quakespasm/commit/5850ad9da7a559d0c3bba1e63cd83bb3f8ebd3b6
