### ISSUE TITLE
player names for revive messages get mixed up

### ISSUE THREAD

**Issue by poVoq** [nzp-team/nzportable#1061]
**Describe the bug**
Despite the recent fix to make NZ:P stop confusing player names in multiplayer coop games on a dedicated server, it seems like the player names specifically in revival related messages still get mixed up some times resulting in strage messages that you need revival yourself, or that your revived yourself etc.

**To Reproduce**
1. Play a multiplayer game with multiple people on a dedicated server
2. See strange revival messages with mixed up player names after a while

**Expected behavior**
I guess the previous bug-fix for this needs to be also applied to the part of the code that deals with revival messages.

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc) <- dedicated server

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/3c79565a50d819db105c1960cb0c7404a9be0032
