### ISSUE TITLE
Can't connect to server from in-menu server browser when address begins with `/udp/`

### ISSUE THREAD

**Issue by poVoq** [nzp-team/nzportable#1062]
**Describe the bug**
When trying to connect to a server from the in-game browser it shortly loads and then drops back to the menu.

Looking at the console it tries to connect to `/udp/*serverip*:port` and then finally says unable to connect, giving up.

Using the console to connect to `*serverip*:port` without the `/udp/` part seems to work.

**To Reproduce**
1. Open server browser in menu
2. Click on on server you want to connect to
3. See short loading screen and then get dropped back to menu

**Expected behavior**
It should behave the same as a `connect *serverip*:port` command does in the console.

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc) on Linux, latest nightly release.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/9e5546b27b776cb47e562609f7c25e068ba82d5d
