### ISSUE TITLE
It is possible to get stuck in spectator mode when the map doesn't reload.

### ISSUE THREAD

**Issue by poVoq** [nzp-team/nzportable#1065]
**Describe the bug**
When a player joins a game and then leaves again, the next player joining seems to be automatically put in spectator mode and when this happens the level does not restart and the player is stuck spectating.

**To Reproduce**
1. Join a coop game on a dedicated server then leave again
2. Join a second time and be automatically put in spectator mode (waiting for the round to finish)
3. The round never finishes and you are stuck.

**Expected behavior**
When there are no other players in a match, it should automatically restart when a new player joins.

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc) <- dedicated server on latest nightly QC release.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/2cc0ca7ed377f9d8c2525ae1651cb278a886f515

**Comment by poVoq** [comment]
Works well, but for some reason it also seems to get triggered when the last person leaves the server (according to the server logs). Not really an issue, but a bit odd.
