### ISSUE TITLE
[PSP] [3DS] Forced walking forward, needs restart to stop

### ISSUE THREAD

**Issue by RCZaku** [nzp-team/nzportable#1067]
I'm not sure exactly whats causing it but usually in the first couple rounds something triggers and i can no longer stop walking forward, i can fight against it and move back very slowly though.

I have had this happen on both the PSP and 3DS versions (haven't played the others). Not sure if using the stick for movement is possibly effecting this? Havent tested that. Either way this bug is making the game fairly unplayable.

Last 2 times it happened were close range with zombies, on "Nacht Der Untoten" opening a mystery box and trying to shoot a zombie while moving, suddenly cant stop walking forward.
Another when on "Bunker" (i think that was the name) i simply tried aiming down and shooting a zombie at close range and then couldnt stop walking forward

**Comment by MotoLegacy** [comment]
Does not follow template.
