### ISSUE TITLE
[NX] Clicking Wahnsinn from custom maps will menu lock the game

### ISSUE THREAD

**Issue by Naievil** [nzp-team/nzportable#107]
Clicking Wahnsinn from custom maps will get the user into a menu they cannot continue from. Pressing plus will move the menu screen but not allow to exit

![image](https://user-images.githubusercontent.com/13153090/212449368-8d44966d-89ab-4ddd-a6ae-e8d442099d32.jpeg)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakespasm/commit/04d4e532fadf05ceb6d9c42890ae1fcd79367d5f
