### ISSUE TITLE
[NX] Map loading screen is improperly scaled

### ISSUE THREAD

**Issue by Naievil** [nzp-team/nzportable#109]
Loading screen for even NDU is improperly scaled. 

![image](https://user-images.githubusercontent.com/13153090/212449622-7fd3bf52-b950-4e8d-81ae-a8bcf2aa59e4.jpeg)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakespasm/commit/8a21d114d400154090be11a834b5d0eaa5591cb8
