### ISSUE TITLE
[NX] Powerup sprites are all black

### ISSUE THREAD

**Issue by Naievil** [nzp-team/nzportable#111]
When getting a powerup spawn in any map, its sprite is all black 

![image](https://user-images.githubusercontent.com/13153090/212449956-c2ffa4a5-23eb-48ba-acaf-9a9753dce839.jpeg)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakespasm/commit/d8d27719a9145ea15d0a4702dc48271c571ca172
