### ISSUE TITLE
QMB displays the full particle sheet instead of individual particle

### ISSUE THREAD

**Issue by Naievil** [nzp-team/nzportable#116]
Only on 3DS, all QMB particles are displayed in their full state as opposed to the individual offset within the particle sheet 

![image](https://user-images.githubusercontent.com/13153090/212463474-30e6d3c4-cc89-4057-8cd3-02ed734300cc.jpeg)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/glquake/commit/d6aefb4aa21d05165adfea9254f746e339fb356e
