### ISSUE TITLE
[3DS] control change for new 3ds users

### ISSUE THREAD

**Issue by shadowspike74** [nzp-team/nzportable#117]
Any chance for a control change for [new 3ds] users like the right nub turns the cam and the left analog moves the player. it would be nicer then using the default psp controls on the [new 3ds models]

**Comment by Paindeluxe** [comment]
I‘ll just say this due to the Issues title you can technically change the controls but I don’t know how to bind the stick to aiming the config to change it is in nzpportable/nzp/CONFIG.CFG

**Comment by terrariauser** [comment]
> Any chance for a control change for [new 3ds] users like the right nub turns the cam and the left analog moves the player. it would be nicer then using the default psp controls on the [new 3ds models]

I was just about to request this too. I currently have my controls set to ABXY movement and Circle pad for Camera but using the nub for camera and circle pad for movement would be much preferable.

**Comment by Naievil** [comment]
Hi, 3DS porter here. This would be a great addition. Unfortunately I do not own a N3DS and thus cannot guarantee this feature to be added. However I understand the importance of the request. 

I will keep this issue open until another user can help to add this feature.

**Comment by terrariauser** [comment]
The Homebrew port of Quake 2 that's available on the universal updater has adjustable C-Stick and Circle Pad controls. Perhaps if you were to try implementing this code I'm sure many people in the community including myself would be happy to test it out.

**Comment by Naievil** [comment]
If you are interested in testing it, please send me a message on the discord directly and I will work with you to get this feature enabled.

**Comment by MotoLegacy** [comment]
implemented with https://github.com/nzp-team/glquake/pull/2
