### ISSUE TITLE
[PC] Lens blocks view momentarily when zooming in with scoped kar98k

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#118]
When zooming in with the scoped kar9k, for a brief moment the model of the scope blocks the player's view while zoomed in.

1. Obtain scoped kar98k
2. Zoom in

Video demonstration:

https://user-images.githubusercontent.com/29164668/212544334-ad96147f-921f-4534-a82b-a3c9cb081dda.mp4

This was tested on Linux, I haven't tested on the other platforms or with the PTRS though.

**Comment by TheSubPlayer** [comment]
This is normal, I believe this happens on all platforms (tested on PSP)

**Comment by MotoLegacy** [comment]
I'm unable to reproduce this issue when zooming *in* on FTE. I've attached a sample video. I *can* get the viewmodel to flash when I get out of Aim Down Sight, so I can add a delay for the viewmodel spawning back in.

https://user-images.githubusercontent.com/26030250/212955461-08e6c63b-5451-4d64-8ea1-905d01523738.mp4

For the sake of clarification I should also say the viewmodel obstructing the vision up until the scope overlay is drawn is intended behavior:
https://youtu.be/pkE6S2k0s8w?t=15

**Comment by MotoLegacy** [comment]
I've added the aforementioned change with https://github.com/nzp-team/quakec/commit/4105d57c13beb8a92c1e17a575f4b20ba3aa7a05. Let me know if this issue still occurs.

**Comment by TheSubPlayer** [comment]
> I'm unable to reproduce this issue when zooming _in_ on FTE. I've attached a sample video. I _can_ get the viewmodel to flash when I get out of Aim Down Sight, so I can add a delay for the viewmodel spawning back in.
> 
>  2023-01-17.11-25-55.mp4 
> For the sake of clarification I should also say the viewmodel obstructing the vision up until the scope overlay is drawn is intended behavior: https://youtu.be/pkE6S2k0s8w?t=15


There is no delay on the PSP, it appears instantly when you hold the button

https://user-images.githubusercontent.com/110436924/212968334-fcd5a54b-db5d-47f2-9086-1722f644bc48.mp4

**Comment by MotoLegacy** [comment]
> On PSP the scope overlay appears immediately when I press the aim button

This issue is for PC specifically. I went ahead and opened up a separate issue for you here: https://github.com/nzp-team/nzportable/issues/127. Please be mindful of the tags on issues, thanks :)
