### ISSUE TITLE
[PC] System sleep disables mouse input in game [WORKAROUND FOUND]

### ISSUE THREAD

**Issue by barnzify** [nzp-team/nzportable#12]
when ever I close my laptop and I have the game running, it will basically disable the mouse in game forcing me to quit the program, so no clicking in the menus, no looking around in game, and no firing guns. I hope that this gets fixed cause this bug has made me throw so many games away that I was doing well on.

**Comment by MotoLegacy** [comment]
Could you try running `in_restart` in the console after waking up your system to see if the touchpad/mouse begins responding again?

**Comment by barnzify** [comment]
> Could you try running `in_restart` in the console after waking up your system to see if the touchpad/mouse begins responding again?

gonna try this now. gonna give you results here in a minute

**Comment by barnzify** [comment]
> Could you try running `in_restart` in the console after waking up your system to see if the touchpad/mouse begins responding again?

okay! good news, it fixes it. everything back to normal, thank you for the help!

**Comment by MotoLegacy** [comment]
Re-opening this issue as this is not a permanent fix. One needs made.

**Comment by barnzify** [comment]
ah, gotcha.
