### ISSUE TITLE
[PSP] Sleep mode crash

### ISSUE THREAD

**Issue by TheSubPlayer** [nzp-team/nzportable#120]
The game crashes when returning from sleep mode.

Tested on PSP 3000 in latest build (2.0.0-indev+20230115071719)

1. Put your PSP in sleep mode
2. Turn on your PSP
3. Voilá

**Expected behavior:**

The game should continue normally.

**Screenshots/Footage**

![pic_0048](https://user-images.githubusercontent.com/110436924/212573471-c151e4a7-5e60-4c3c-a77f-6076c9e89faf.png)

**Affected Platforms:**

- PSP

# NOT tested on:

- PS VITA
- Nintendo Switch
- 3DS

**Comment by TheSubPlayer** [comment]
Seems to be working normally now

https://user-images.githubusercontent.com/110436924/213879208-be52a09d-7f4b-4dcb-96af-352b7d29a216.mp4

**Comment by TheArachnidGamer** [comment]
If you play on a map that doesn't have a .mbox file, it won't crash, I tested it on Dungeon, Loop, and Boxxer, and Firing Range, all not crashing after booting back up from sleep mode!

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/02d23e2a1e45e8d0cc6e1ed194bd182c80dd9322
