### ISSUE TITLE
Deadshot sometimes does the opposite

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#121]
**Describe the bug**
sometimes when you're using Deadshot, instead of snapping to zombie heads, it will snap to their legs, or the ground. 

**To Reproduce**
1. go to any map that has deadshot
2. get deadshot
3. player a few rounds and you'll notice that it won't always aim at heads

**Expected behavior**
it should always snap to heads

**Screenshots/Footage**
still unsure how to do screenshots and videos

only tested on PSP

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/973d60eb9bdcf5478ca96212c3bc281fba1b8a06
