### ISSUE TITLE
Multiple issues in graphics settings menu

### ISSUE THREAD

**Issue by TheSubPlayer** [nzp-team/nzportable#122]
Initially, it was just the brightness that wasn't working properly, but as I tested it, I realized that almost every option in the menu has some problem. 
So, to avoid flooding, I thought it best to edit the topic that was already open and list all the problems here:

1. It is not possible to change the brightness of the game through the options. The game's brightness is set to maximum by default. 
Update: The brightness of the game changes, but only the brightness of the barriers (??????)

2. The decals and particles option do not work, despite the options being enabled by default, the menu shows it as disabled, not being able to disable them.

3. The 'retro' option is not being applied to map textures, only to weapon and enemy models.

Tested on PSP 3000 and Win64 in latest build (2.0.0-indev+20230116071843)

1. Go to 'settings'
2. Click on 'graphics settings'
5. Scroll down to 'brightness'
6. Nothing happens

**Expected behavior:**

1. The brightness of the game should change depending on the position of the slider.
2. Decals and particles should toggle on/off with no problems.
3. Texture filter should be enabled/disabled on all in-game models

**Screenshots/Footage**

1. Brightness Issue:

https://user-images.githubusercontent.com/110436924/212741637-3b35ba71-31e7-4deb-96c2-15a03656b6f6.mp4

2. Decals and particles issues:

https://user-images.githubusercontent.com/110436924/212779150-306f2312-ab05-4650-a64b-90cd87dd36a7.mp4

3: Retro Issue:

https://user-images.githubusercontent.com/110436924/212572605-61bba2cb-24e2-4ebe-a22b-64f4b45f2053.mp4

**Affected Platforms:**

- PSP

# NOT tested on:

- PS VITA
- Nintendo Switch
- 3DS

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/dquakeplus/commit/4ea173efc5531692c5fc44cf8b17c4fae931ff2f
