### ISSUE TITLE
[PSP/PC] Kar98k's scope doesn't disappear when throwing a grenade

### ISSUE THREAD

**Issue by TheSubPlayer** [nzp-team/nzportable#123]
The title is self-explanatory ¯\_(ツ)_/¯ 
This occurs on PSP and Windows, probably occurs on all other platforms.

Tested on PSP 3000 and Win64 in latest build (2.0.0-indev+20230116071843)

1. Get a Scoped Kar98K
2. Throw a grenade

**Expected behavior:**

Kar's scope should disappear along with the weapon.

**Screenshots/Footage**

https://user-images.githubusercontent.com/110436924/212749102-7f4fd8de-33ac-40c9-aff0-402688c9a679.mp4

**Affected Platforms:**

- PSP
- Windows
- All other platforms (probably)

# NOT tested on:

- PS VITA
- Nintendo Switch
- 3DS

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/9ac309ecfc2839f376c3c4e21c52f67557df6c2a
