### ISSUE TITLE
Add forced respawn to AI if stuck

### ISSUE THREAD

**Issue by Naievil** [nzp-team/nzportable#125]
We can check the origin of each zombie and force them to respawn if they get stuck. COD zombies does this already if they haven't left a certain distance even if they haven't been killed. 

We can set the timeout to be fairly small (30s) in case we have backlog at barriers or way pointing error

**Comment by blubs** [comment]
I'll take this into account with the current AI efforts!

Possibly related is the zombie bleedout system in COD. I'm a fan of the BO2 system, where they can bleed-out based on distance / visibility, but if they are undamaged, they respawn and don't progress the rounds.

Versus the BO4 system it's timer-based and doesn't respawn, always progressing the round.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/b4a2ce2ac57ede8efbf32f8419925a8f2a9056b3
