### ISSUE TITLE
[SERVER] zbc#.mdl isn't preached, causing crash

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#126]
**Describe the bug**
When you make a crawler, the game crashes on 3ds, and probably other platforms 

**To Reproduce**
1. Yeet grenade
2. Make crawler
3. Cry

**Expected behavior**
The zombie, legless, to fall to the ground

**Screenshots/Footage**

![IMG_20230117_094325](https://user-images.githubusercontent.com/13917665/212959467-67be47f6-a46b-43c5-865e-51cd4473dd05.jpg)

**Affected Platforms:**
All I believe, but only 3ds/PSP should crash

**Additional context**

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/cf9466ed0f0e6694cbbfb7bda405a7124d00edac
