### ISSUE TITLE
[SUGGESTION] Scope parity with WaW

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#128]
**Describe the suggestion**
attempt to do exactly what waw does with its scopes to be more acccurtae

Things to look for:
the view model disappears far before the gun gets fully scoped in, most of the zooming happens while the scope overlay is appearing

**Screenshots/Footage**

How it is right now:

https://user-images.githubusercontent.com/13917665/212987787-ea51d1e5-ba67-4509-93d4-31a84543c6ac.mp4

How it looks in COD:

https://user-images.githubusercontent.com/13917665/212987867-ec18e162-4be0-46c6-8e27-1bd56dd339a6.mp4

**Additional context**
I made this after seeing 2 other posts about the scope and was wondering how it worked exactly in WaW

**Comment by MotoLegacy** [comment]
boop https://github.com/nzp-team/quakec/commit/0812781cb7d71c7e559905c95e75f22a3825b15c
