### ISSUE TITLE
[VITA] Granade Blackout

### ISSUE THREAD

**Issue by MaeUwU** [nzp-team/nzportable#129]
in the vita version, when you throw a granade, sometimes the screen can just went black soon as the granade explode

**Comment by Paindeluxe** [comment]
I‘m pretty sure your referring to post #126

**Comment by Paindeluxe** [comment]
Not sure though …

**Comment by MotoLegacy** [comment]
Yes, this is a duplicate of https://github.com/nzp-team/nzportable/issues/126, which has been resolved.
