### ISSUE TITLE
[SUGGESTION] enable "Z" axis positioning for Handheld ADS

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#130]
**Describe the suggestion**
For ADS positioning, you can only move the Guns left/right, or Up/down, you can't move it forward/backwards, which has become a requirement for some guns... Ooops

It'd be nice to make sure I can make all ADS look good, especially for some guns with sights that are a bit further away than others, like the STG, who's sights are in the middle of the gun, rather than the rear

**Comment by Naievil** [comment]
Hi @DerpedCrusader we already support z offset for ADS, no? ADS_Offset is defined as a vector and I can see it take effect in view.c within the engine

`		ADSOffset[0] = sv_player->v.ADS_Offset[0];
		ADSOffset[1] = sv_player->v.ADS_Offset[1];
		ADSOffset[2] = sv_player->v.ADS_Offset[2];`

**Comment by DerpedCrusader** [comment]
To my knowledge, that's only for PC, and doesn't work on handheld systems at all

I had a talk with Moto, and he said we're probably going to look into a whole revamp of the current ADS system/gamefeel

**Comment by blubs** [comment]
Confirmed it shouldn't be working on PSP:
https://github.com/nzp-team/dquakeplus/blob/2fa179a206b790b86fa11e64eeaa31535a3b4a2b/source/view.c#L1141

Only X/Y ADS ofs is taken into account on PSP.

**Comment by MotoLegacy** [comment]
added in https://github.com/nzp-team/quakespasm/commit/3ffcd046bafc4d86d1e2f52150b5d87a391999de https://github.com/nzp-team/dquakeplus/commit/862718afd69cd98fc0feb69b8e9b6a8eb2189ec2 https://github.com/nzp-team/glquake/commit/0232a32c80b60eaa92aa5c2836a82e55d527b981
