### ISSUE TITLE
[VITA] blackout still happening

### ISSUE THREAD

**Issue by MaeUwU** [nzp-team/nzportable#132]
shooting with a paped ppsh made the screen black

**Comment by BCDeshiG** [comment]
Gonna need to be a bit more detailed than that. Try pressing the `START` button when it happens and if that takes you to the main menu, head to the settings menu and open the console then screenshot it.

If it's just straight up frozen and unresponsive however, see if you can record a video of the bug happening.

**Comment by DerpedCrusader** [comment]
I was unable to reproduce this bug on the latest build

could you give more detailed instructions?

**Comment by MaeUwU** [comment]
it happaned 1 time on the most recent build, i was shooting with the pack a punched ppsh and at one shot the screen just went black, this never happened to me again after that
