### ISSUE TITLE
Unable to buy perk when rotation value is negative

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#133]
If the `angles` property of the perk entity features a negative component (e.g. `0 -90 0`), then the player cannot buy the perk.

1. Create a test map.
2. Place a perk entity.
3. Rotate the perk clockwise so that the second value in the `angles` property is negative.
4. Compile and Launch the map.
5. Attempt to buy the perk.

**Expected behavior**
The player should be able to buy the perk.

![image](https://user-images.githubusercontent.com/29164668/213818589-ab08ce90-2402-46e4-a1b6-3d80dd355b24.png)

![fte-20230120224714-0](https://user-images.githubusercontent.com/29164668/213818712-fd44269d-cd72-47d6-87cb-a9651a972eb5.png)

**Affected Platforms:**
Only tested on PC.

**Additional context:**
Applies to all perks and and orientations, not just upright.
One workaround is to rotate the perk to the equivalent positive value (so 270 degrees instead of -90 for example).

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/dfa9313eb93b7bad780937726adfa12124659086
