### ISSUE TITLE
[Handheld] Raygun shots curve dramatically

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#135]
**Describe the bug**
The raygun shots believe its the year 2008 and are curving around zombies (and other stuff)

it seems to be tied to aim assist in some way 

**To Reproduce**

1.  get the raygun
2. shoot it a med-long distance (might require a zombie nearby)
3. watch it curve

**Expected behavior**

You'd expect the shot to more or less go straight forward, 

**Screenshots/Footage**

Sorry, have to do a youtube link, as the video was too long, Taken on switch
https://youtu.be/WG92mRHqldM

**Affected Platforms:**

Switch, Vita, 3DS, PSP

Should be stated, i only tested this on 3DS, and Switch, but the QC matches up to the PSP and Vita respectively, so i assume they'd also have it

I tested it on PC, and it was not present on there

**Comment by TheSubPlayer** [comment]
Yes, this also happens on PSP, I thought it was a feature LOL

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/assets/commit/db53fce984e74a1c06c513594860c10d3f3fdc9c

**Comment by DerpedCrusader** [comment]
this is happening on PSP again,

clean install, when i type `sv_maxvelocity` into the console, it comes out with 2000, not the 10000 as suggested in the Fix listen above

**Comment by MotoLegacy** [comment]
strange.. it's definitely in the config.. can you open it in your local copy and ensure its there too?

https://github.com/nzp-team/assets/blob/547ed544aabbb52cedc5d8c7b77730609fafbbea/psp/nzportable/nzp/config.cfg#L116

**Comment by DerpedCrusader** [comment]
okay, i readded that config file, and the raygun worked, but once i quit, and start the game again, its reset

and when i check the config, its gone from the bottom of the list
