### ISSUE TITLE
[PSP] Weapon angle issue

### ISSUE THREAD

**Issue by TheSubPlayer** [nzp-team/nzportable#136]
I really don't know how to describe this, better see it to understand.

Just look up and down 

https://user-images.githubusercontent.com/110436924/213881942-c063c6d2-713b-4729-ba48-8dc443b32196.mp4

**Affected Platforms:**

- PSP

# NOT TESTED ON.

- PS VITA
- 3DS
- Nintendo Switch

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/0f6f274e29257a39c1d4e80d7ce3a807d41d96cb
