### ISSUE TITLE
[SUGGESTION] Gameplay tweak/improvement on PSP

### ISSUE THREAD

**Issue by TheSubPlayer** [nzp-team/nzportable#137]
To jump, just press DOWN ARROW twice while sprinting, but when jumping, the player lies down after the jump (like a dive), and that's really annoying.
Is this intentional or was it a mistake? 
It is possible to crouch/prone by pressing X twice, which makes it even more useless.

My suggestion is to remove the 'dive' after jump, this would make the gameplay smoother.

https://user-images.githubusercontent.com/110436924/213899168-b4f72524-3238-4e23-a220-f3fa5da78bc8.mp4

**Comment by MotoLegacy** [comment]
You are not jumping -- you are performing a dolphin dive. This is done by pressing +MELEE while sprinting. Standard jumping is configurable within the game's controls menu. Most people bind it to UPARROW to replace grenade tossing. Closing as this was a misunderstanding.
