### ISSUE TITLE
[VITA] most buttons don't work after sleep (+Workaround)

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#139]
**Describe the bug**
When you put the vita to sleep, and turn it back on, a majority of buttons stop working, you can still move/look with the sticks

**To Reproduce**

1. boot into a map
2. put the system into sleep
3. take out of sleep
4. panic

**Expected behavior**
I would expect the game to pick up exactly where i left off, no difference

**Affected Platforms:**

Only tested on vita

### WORKAROUND

simply press the home button, and go back into the game, and the buttons continue to work

**Comment by MotoLegacy** [comment]
I'm unable to reproduce this issue, do you have any active plugins that could be interfering with input after waking up from sleep?
