### ISSUE TITLE
[PC] Scope is squished

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#14]
When zooming in with either sniper, the scope image is squished as seen here:

![unknown](https://user-images.githubusercontent.com/29164668/166949387-2a6dc1a5-6397-4a76-a07c-889c7978645e.png)

This bug is not present on PSP though:

![unknown2](https://user-images.githubusercontent.com/29164668/166949489-ef1af7f9-1a3c-4f6f-a2d3-1d3c77fc5386.png)

**Comment by BCDeshiG** [comment]
I should add this occurs regardless of FOV (both screenshots are at 90).

**Comment by MotoLegacy** [comment]
Fixed in:
* https://github.com/nzp-team/quakec/commit/6f25b07c1f791d50c2c9be1366475d0bf06cd49b
* https://github.com/nzp-team/assets/commit/313c1851ec4931819f638fc51b36579c07566736
