### ISSUE TITLE
[PC/MENU] The Crosshair scales badly to higher resolutions.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#141]
**Describe the bug**
_A clear and concise description of what the bug is._

The Crosshair isn't centered in all 4 directions so you may not have a chance to hit the broad side of the Barn when you try to hit a noscope from far away.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Bootup NZP.
2. Click on you favorite map.
3. Play a few rounds normally.
4. Notice you didn't play on 4k.
5. Notice that the Crosshair looks bad to the point where you make this Issue Report on Github.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Crosshair stays Centered in all 4 directions.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

![fte-20230125144651-0](https://user-images.githubusercontent.com/104042185/214582536-1372eeb1-d714-4ee8-8468-49cc36135734.png)
![fte-20230125144722-0](https://user-images.githubusercontent.com/104042185/214582574-2a8ae057-f6ca-4d12-9a10-33116774fcde.png)
![fte-20230125144726-0](https://user-images.githubusercontent.com/104042185/214582584-d0f39700-1aca-4b79-910c-e1ee51f06a21.png)
![fte-20230125144756-0](https://user-images.githubusercontent.com/104042185/214582589-8178fa43-eba3-45ac-9d08-036aa69393f5.png)

_Those are some huge Hitboxes!_

**Default to 4k Resolution Comparision**

![fte-20230125150616-0](https://user-images.githubusercontent.com/104042185/214584950-c5e9aa43-6b75-4129-b317-e8e44e293781.png)
![fte-20230125150635-0](https://user-images.githubusercontent.com/104042185/214584968-3efd0cf7-15f6-4e2a-8c8c-7dcf1a90894b.png)
![fte-20230125150646-0](https://user-images.githubusercontent.com/104042185/214584994-70e1594a-4285-4b5b-9030-5ac537a67c4e.png)
![fte-20230125150659-0](https://user-images.githubusercontent.com/104042185/214585001-71928bd7-c381-4096-8245-17f22d076e50.png)

**Affected Platforms:**

# Please make note of any platforms you DID NOT test on.

- FTEQW (Windows, _Mac?_, Linux, etc)

**Additional context**
_Add any other context about the problem here._

While the crosshair could be always off by 1-2px this much is a bit insane. my Resolution is 3840x2160 so this is really odd...
Also this was a issue for many months I was just extremely lazy when it comes to reporting it.

_Also is it just me or does the resolution also affect the spread... Only judging this via the crosshair._

**Comment by Paindeluxe** [comment]
**Writing a DARN Essay over here!** Just because of a singular bug.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/a0ae78c1506663dd72dad221e54882c466ae7cc2
