### ISSUE TITLE
Bullet Penetration

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#142]
there's no bullet penetration for PC version. simple as that.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/b4f8a15cc3a620187662f3741759c5f3ca5e8657

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/3de18c324ce55cd0910ed69f5e7fa2003fd59e56
