### ISSUE TITLE
[SERVER/COOP] Infinite ammo when downed

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#143]
**Describe the bug**
When you go down with little to no ammo, the game gives you some, when you get up, it takes it away, giving you negative ammo, which goes down practically infinitely 

**To Reproduce**
1. Open a multiplayer game, because you have to be able to go down with your current weapon
2. Have to have someone connect and alive
3. Fire all the shots in your gun (colt, 357, possibly raygun?)
4. Go down
5. Fire all your shots
6. Get picked up
7. Negative ammo

**Expected behavior**
Id expect the ammo to either be missing, or go back to original values, I'm not 100% sure what cod does, but parity should be kept in mind

**Affected Platforms:**

Only tested on FTE

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/578fa2d44e8f1b4ec9fb120646157c262f712f42
