### ISSUE TITLE
Incomplete HUD

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#144]
**Describe the bug**
The hud for switch is a bit messed up at the moment 

The points and points background are on the wrong side

**To Reproduce**
Boot up the game, and load up a map

**Expected behavior**
I'd expect the hud to look similar to other consoles

Like the vita for example

![vita_perks-1](https://user-images.githubusercontent.com/13917665/214754615-000f7cb0-66ef-46b4-9a33-e895f63dde53.PNG)

**Screenshots/Footage**

![IMG_20230125_204442](https://user-images.githubusercontent.com/13917665/214754634-a0686f7d-4e3a-4a82-8f12-3537924c3296.jpg)

Notice placement of the points being on the wrong side, also the placement of things like grenade's and weapon names

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakespasm/commit/bc28b5c593c8207f58302cfb831edb9bd0418d3f
