### ISSUE TITLE
[SERVER] You can hover mid-air while Reviving somebody.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#145]
**Describe the bug**
_A clear and concise description of what the bug is._

All movement gets halted during a revive even gravity based movement so you can hover for as long as you can revive the downed person.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to your favorite map.
2. Either open a 2nd Window and join yourself or type in cl_splitscreen 1?
3. Let the second marine get slapped to death.
4. Jump and revive.
5. See that you learned how to hover in mid-air.

**Expected behavior**
_A clear and concise description of what you expected to happen._

Gravity does it’s thing and pulls you back to the ground while you are reviving someone. 

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

I wanted to but eh _(Enter Generic Excuse Number 163)_

**Affected Platforms:**

# Please make note of any platforms you DID NOT test on.

- FTEQW (Windows, _Mac?_, Linux, etc)

**Additional context**

**Issac Newton would be furious!**

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/9f0df7617d268a52119413eec2dce9b44424d44b
