### ISSUE TITLE
[Server/CO-OP] You can switch guns and shoot them while Reviving somebody.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#146]
**Describe the bug**
_A clear and concise description of what the bug is._

While your Reviving somebody you can freely switch weapons with their full functionality while continuing the reviving process.

**To Reproduce**
1. Go to your favorite map
2. Open your console and type in cl_splitscreen 1
3. Let the second marine get B#### slapped to death
4. Keep the zombie alive and revive
5. Equip your gun during the revive and _get some Revenge!_

**Expected behavior**
_A clear and concise description of what you expected to happen._

You are locked into the reviving syringe.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

Sorry no can do!

**Affected Platforms:**

Everything with Multiplayer support.

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch
- FTEQW (Windows, Mac, Linux, etc)

**Additional context**
_Add any other context about the problem here._

**Comment by MotoLegacy** [comment]
This technically isn't a bug -- this is intended behavior that existed from World at War to Black Ops III Zombies. However, there was a misparity in which when you stopped facing the downed client on the X(?) axis, the revive wouldn't cancel. I went ahead and fixed that with https://github.com/nzp-team/quakec/commit/2de12f679177ff2a8a4e5492ea2e53c3f25ae0cd

Here is a video showcasing this in Black Ops II:
https://www.youtube.com/watch?v=2oGNwnZGoM4
