### ISSUE TITLE
Zombies can get stuck in downed Players.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#147]
**Describe the bug**
_A clear and concise description of what the bug is._

Zombies get stuck on a downed Player as they jump through the window therefore putting them into the player

**To Reproduce**
1. Go to favorite map like Nacht der Untoten
2. Open the console and type in cl_splitscreen 1
3. Move to a window and let yourself get downed there
4. See the zombies doing a Victory Dance on you

**Expected behavior**
_A clear and concise description of what you expected to happen._

The zombies push the downed player away.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

Sorry can’t do it right now!

**Affected Platforms:**

Everything with Multiplayer support.

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch
- FTEQW (Windows, Mac, Linux, etc)

**Additional context**

I didn’t know they can dance this good.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/619980e88c0bbf9aac91e70d0f38c182b8a45eec
