### ISSUE TITLE
[CO-OP/SERVER] If you exit the revive range during a revive unintended consequences occur.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#148]
**Describe the bug**
_A clear and concise description of what the bug is._

You can "revive" somebody from far away keeping them alive but you sacrifice your walking speed

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to your favorite map.
2. Open the console and type in cl_splitscreen 1.
3. Get the other Marine die of whatever you prefer.
4. Get near the Marine.
5. Jump away from him while also starting the revive.
6. You are now his life support if you let his Bleedout Timer run out

**Expected behavior**
_A clear and concise description of what you expected to happen._

During a revive you lose all your vertical speed while still being affected by gravity therefore making leaving the revive zone nearly impossible.
Or you just check if you still in the revive radius. 

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://youtu.be/hlmWZLVm_ks

**Affected Platforms:**

**Every Platform with Multiplayer support.**

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch
- 3DS

**Additional context**
_Add any other context about the problem here._

_Pls_ fix this.

_It's getting boring having to make the bug reports about the same thing..._

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/2de12f679177ff2a8a4e5492ea2e53c3f25ae0cd
