### ISSUE TITLE
[SERVER] Grenades fall through transparent textures while they shouldn't.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#149]
**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**
1. Go to Firing Range.
2. Go to the Stairs leading up to the Metal Walkway.
3. Throw Grenade.
4. See the Grenade using the Bullets Collision checks?

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Grenade bounces off the transparent textured brush.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://youtu.be/qdqBCgC9Bww

**Affected Platforms:**

- FTEQW (Windows, Mac, Linux, etc)

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch

**Additional context**
_Add any other context about the problem here._

Stop making the Grenades use the Bullets Collision checks?????????

Idk I'm too lazy to look at the code.

**Comment by MotoLegacy** [comment]
This isn't a bug, `SOLID_NOT` is the intended solid state for `func_illusionary`. You can view this in the Quake QC here:
https://github.com/id-Software/Quake/blob/bf4ac424ce754894ac8f1dae6a3981954bc9852d/qw-qc/misc.qc#L618
