### ISSUE TITLE
[PC] Clicking wont work in menu on laptop.

### ISSUE THREAD

**Issue by barnzify** [nzp-team/nzportable#15]
so a few of my friends have seen me playing NZP and want to play it too, I send them the link to the github, they download it, open it, then when they are on the menu, can't select Solo, Settings, or anything on the menu. All of the people I send this to don't have a mouse, they use the mousepad, and the menu doesn't work for any of them.

**Comment by MotoLegacy** [comment]
Do they all share the same hardware..? I've never encountered touchpad unresponsiveness. If this is a reoccurring thing for everyone they likely all have the same (or similar) models, am I right? What are said model(s)? This is important information.

**Comment by barnzify** [comment]
> Do they all share the same hardware..? I've never encountered touchpad unresponsiveness. If this is a reoccurring thing for everyone they likely all have the same (or similar) models, am I right? What are said model(s)? This is important information.

yes, we all have the same type of laptop, it only works on mine for some reason, the laptop that we all use is linked below:
https://www.newegg.com/p/36B-000D-009R5?item=9SIA77GJ064033&nm_mc=knc-googleadwords&cm_mmc=knc-googleadwords-_-business%20laptops-_-lenovo-_-9SIA77GJ064033&source=region

**Comment by MotoLegacy** [comment]
I'm not sure whether to classify this as a proper issue if it is functioning for you and not them, and you all have the same hardware. It leads me to believe there is nothing broken with the touchpad input functionality in FTEQW. Have you tried going through touchpad and mouse settings to identify a potential option that brings/removes functionality?

**Comment by barnzify** [comment]
> I'm not sure whether to classify this as a proper issue if it is functioning for you and not them, and you all have the same hardware. It leads me to believe there is nothing broken with the touchpad input functionality in FTEQW. Have you tried going through touchpad and mouse settings to identify a potential option that brings/removes functionality?

sorry, yes we've gone through the touchpad and mouse settings and everything is working, no settings removes functionality in  nzp

**Comment by MotoLegacy** [comment]
> sorry, yes we've gone through the touchpad and mouse settings and everything is working, no settings removes functionality in nzp

I don't understand, so you are saying no parties have this issue anymore?

**Comment by MotoLegacy** [comment]
Closing as it's been 15 days without a response and user is providing contradictory details.
