### ISSUE TITLE
[CO-OP/SERVER] The Game may choose the same Spawn for multiple Players.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#150]
**Describe the bug**
_A clear and concise description of what the bug is._

You spawn into another Players location due to the game choosing only 1 spawn for 2 players.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Type cl_splitscreen 3 into the console.
2. Start Firing Range.
3. See error.
3.5 If you don't see the error restart the map.

**Expected behavior**
_A clear and concise description of what you expected to happen._

A Collision Check or a player assigned Spawn to spawn correctly

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://youtu.be/fMOjRPBV9kM

**Affected Platforms:**

Every Platform with Multiplayer Support

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch

**Additional context**
_Add any other context about the problem here._

_Why must I report every bug individually..._

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/19e119945c934a8972ba49083b7a6caa69a61f68
