### ISSUE TITLE
[CO-OP/SERVER] If a downed Player Leaves mid revive you get stuck reviving until you die or get downed?

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#151]
**Describe the bug**
_A clear and concise description of what the bug is._

During a Revive if the Downed Player leaves the Revive is unable to complete therefore locking you into the Revive until things that cancel revives occur like _dying_ or getting _downed_.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to your favorite map Firing Range.
2. Type in cl_splitscreen 1.
3. Get your kick bind or cl_splitscreen 0 ready.
4. Get the other Marine downed.
5. Revive and kick the other Marine.
6. Get stuck in the Revive.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Revive either finishes without any consequenses or the Revive ends prematurely due to the game checking if the downed player is still in the game or by canceling all revives if a person leaves.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://youtu.be/sTQKVdZjHko

**Affected Platforms:**

- FTEQW (Windows, Mac, Linux, etc)

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch

**Additional context**
_Add any other context about the problem here._

Reviving is busted...

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/549df8f7e089660bea91c95e674e65b5de4a4988
