### ISSUE TITLE
Game crashes when you exit from menu

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#152]
**Describe the bug**
when you exit the game from main menu, the game crashes to the home screen

**To Reproduce**

1. Start up the game
2. go down to exit
3. exit
4. Crash

**Expected behavior**
I would expect the game to exit to the home brew menu

**Affected Platforms:**

Just Switch

**Comment by MotoLegacy** [comment]
From testing I've concluded that exiting from any manner not called by horizon regardless of return status, it'll show the "crash" notification. So I've removed the button entirely in https://github.com/nzp-team/quakespasm/commit/e71195feefc3f801b1d9dbf53c5e5449a1b41b89
