### ISSUE TITLE
[NX] Game crash on map load

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#153]
**Describe the bug**
when starting a map, it crashes during the load

**To Reproduce**

1. boot up the game
2. open a map
3. wait

**Expected behavior**
i would expect the load to finish and get into the game

**Screenshots/Footage**

[qconsole.log](https://github.com/nzp-team/nzportable/files/10523947/qconsole.log)

no error log was generated

**Affected Platforms:**

Switch

Additional notes:

I downloaded a build on janurary 20th and it had loaded up fine, so it might have been something changed between then and now (the build i downloaded might not have been made on the 20th, it was just the latest build at the time)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakespasm/commit/60201120b098ddaac63642597456c4d607f04a95
