### ISSUE TITLE
[SUGGESTION] Animated Place_models

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#154]
Giving Place_Models the ability to animate if targeted by an entity. it would be a nice addition in my opinion. it can be used with a Transparent func_door_nzp to make it seem like the door is actually opening in cool ways or cool designs for doors. it'd probably be possible to use something like this with the power switch too, or whatever anyone wants to do with it.

**Comment by MotoLegacy** [comment]
So you just want to be able to give `place_model` a targetname, so other entities can target them on use, right?

This sounds like something that might already exists for Half-Life/Quake mods.. so maybe we should deprecate `place_model` for a proper implementation of that entity!

**Comment by Revnova** [comment]
yeah. something like that. will that also animate them? also, giving the option to loop the animation or not would be good too.

**Comment by MotoLegacy** [comment]
Found `misc_model` in the progs_dump 3.0.0 manual which seems to be what we want to base off of. Is there anything here you think should be added aside from looping?

![image](https://user-images.githubusercontent.com/26030250/215299121-128c6f9b-5317-4fb4-bc64-36d49b399cea.jpeg)
![image](https://user-images.githubusercontent.com/26030250/215299122-49d1fff0-5602-47fa-8671-1101307b50dd.jpeg)

**Comment by Revnova** [comment]
this is perfect. unless you mean to pick from here. then Spawnflags: "Back and Forth", "Play count times", and "Start Hidden" for sure.

**Comment by MotoLegacy** [comment]
Nope all of these would be implemented. Just making sure there weren't any additional needs!

**Comment by Revnova** [comment]
then yeah. this is very much perfect

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/7d842bc7209cd99ebcdd591d5f2855d5f4b05e2e
