### ISSUE TITLE
[PSP/SERVER] PSP Crash When loading a map

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#156]
**Describe the bug**
on psp, when you load a map. the game crashes. Error says: "The following error occured: Cache_Alloc: already allocated" it seems to only be the 32mb eboot.

**To Reproduce**
1. be sure to have the 32mb eboot
2. start the game
3. pick a map
4. get error

**Expected behavior**
should just load and play the game.

**Affected Platforms:**
only tested on psp

**Comment by DerpedCrusader** [comment]
So, i did some testing, and i found 2 things

the crash happens a frame or two after the game loads up, you can see a bit, and some sound starts playing before the crash

and,

the crash doesn't happen on every map. it does happen on NDU, but, it doesn't on Bloodv3

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/cd3b08018e57d4320768bb61c4995afa222a2d10
