### ISSUE TITLE
[PSP] Game Crash when attempting to activate God mode

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#16]
When I open the console and try to use the God mode command, the game crashes with the following error: 

![IMG_20220509_160102](https://user-images.githubusercontent.com/29164668/167439714-879f46aa-40a6-400b-89a2-da1aa8c9e668.jpg)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/0ccb6357f0d43a94898774fa183b7a2f7c3f3c8a
