### ISSUE TITLE
O3DS Stability Issues Always Crashes before round 7 usually round 6 (have not tested on N3DS)

### ISSUE THREAD

**Issue by k-kpog** [nzp-team/nzportable#165]
~~Other issues game will freeze temporarily after showing new model For the first time (such as zombie head  exploding pulling out knife throwing grenades etc) occasionally the frame rate will become unstable for a moment (or just crash)
only tested on o3ds will try to provide images of crash screens at some point.~~

MOTO: trimmed all this out because it's all separate from the posted issue..

**Comment by k-kpog** [comment]
wut the

**Comment by k-kpog** [comment]
should i have deleted that? idk dosent matter

**Comment by k-kpog** [comment]
added new info

**Comment by MotoLegacy** [comment]
Closing as can not reproduce as it's been several days without a response. Feel free to re-open if this becomes an issue.
