### ISSUE TITLE
Hard crash when attempting to activate `r_showtris`

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#17]
The PSP locks up and powers off when I try to run the `r_showtris` command in the console.
Trying the same thing in PPSSPP displays the following error in the debug output:

![image](https://user-images.githubusercontent.com/29164668/167459877-225cce07-79f5-4644-b1ea-dd782404e63c.png)

**Comment by BCDeshiG** [comment]
Returning to this one almost a year later, it's not the command itself that crashes the game. I tried it again in a different spot and seemingly nothing happened until I looked at the fence which then hard crashed the PSP.

![Untitled (1)](https://user-images.githubusercontent.com/29164668/234986599-c372c6d3-1825-4eb3-8697-c61460c79594.png)

**Comment by BCDeshiG** [comment]
Okay yeah this one seems rather odd, this time when I tested the command, it didn't crash looking at another gate but as soon as I killed a zombie it did.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/dquakeplus/commit/e3202ef9a5c1f24da5026e313ab7f9c3d164f841
