### ISSUE TITLE
[VITA] Mouse 1 unbound message when tapping the screen

### ISSUE THREAD

**Issue by techboy04** [nzp-team/nzportable#170]
**Describe the bug**
When playing on the PSVita, whenever I touch the screen while in a map, it gives me the "Mouse1 not Bound" prompt. Text is a little small so it aint that distracting, it could be annoying when you accidentally touch it. Luckily it doesnt effect gameplay.
The controls are still functional like normal.

**To Reproduce**
1. Open the Game
2. Go into a map
3. When In Game tap the screen

**Expected behavior**
I expected the prompt to not show up at all.

**Affected Platforms:**
- PS VITA

**Comment by MotoLegacy** [comment]
Do you think tapping the screen to place a Bouncing Betty would be appropriate? Trying to find a way to actually utilize the "button".

**Comment by techboy04** [comment]
I feel like it should, I rarely tap on the screen and rarely use em so it would probably be perfect, worth experimenting

**Comment by MotoLegacy** [comment]
went ahead and implemented this in https://github.com/nzp-team/assets/commit/d21d3b57e7572d81eb33c4246029bc07103fafba
