### ISSUE TITLE
[PSP] Perma Select

### ISSUE THREAD

**Issue by TheArachnidGamer** [nzp-team/nzportable#171]
**Bug**
It seems that sometimes the game registers Select as being held down when it shouldn't, it also persists when restarting a map or changing map, when the player passes by something they can interact with, it automatically does
Another thing is that once this bug occurs, the mystery box can only be used once before not working anymore, any other interactable things will auto interact when in contact.
Only way to bypass the glitch is to type in console -use after it's active
Workaround found by: Paindeluxe

**To Reproduce**
Hit select twice in quick succession

**Expected behavior**
Intractable things shouldn't be interacted with unless you are holding select

**Suspected Cause**
I'd guess it has something to do with the code that toggles between bouncing betties and grenades

**Affected Platforms:**
Played on PSP Go using 64mb version
Not tested on Vita, NX, or PC

**Comment by TheArachnidGamer** [comment]
> I know a fix for this (only in-game) type in -use in the console and you have your select back.

I'll give it a try, glad to know I'm not the only one with this problem

**Comment by TheSubPlayer** [comment]
> 
I also have this problem, pain's tip was very useful

**Comment by MotoLegacy** [comment]
(finally) fixed in https://github.com/nzp-team/assets/commit/5bf5d96aa56ae085468b287b821dbae9d045002b
