### ISSUE TITLE
[PC] The NZP Desktop/Program Icon is missing

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#172]
**To Reproduce**
_Steps to reproduce the behavior:_
1. Download the newest Build.
2. Extract.
3. See the default FTEQW Icon on the .exe/.app

**Expected behavior**
_A clear and concise description of what you expected to happen._

The NZP Logo is on the games .exe/.app
**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

Can’t do that right now I‘m walking with my dog.

**Affected Platforms:**

Computers.

**Additional context**
_Add any other context about the problem here._

The Icon went missing for a few weeks now.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/fteqw/commit/5faa97bbfc950dd0acee221386798a740c4523c1
