### ISSUE TITLE
[SERVER] Perk_Random uses a purple glow for every Perk Machine

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#176]
**Describe the bug**
_A clear and concise description of what the bug is._

Perk_Random won't use the Perk Machines Signature Glow.

**To Reproduce**
1. Open TrenchBroom.
2. Make a Map with Perk_Random.
3. Compile and Launch the Map.
4. See error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Perk Machine uses it's correct Glow.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

![fte-20230204235355-0](https://user-images.githubusercontent.com/104042185/216793091-c53c4016-a83a-4125-9abb-f70b29749ca7.png)
![fte-20230204235346-0](https://user-images.githubusercontent.com/104042185/216793095-7e436aaf-6e19-4d01-a739-9b37b1236ada.png)

**Affected Platforms:**
All

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch

**Additional context**
_Add any other context about the problem here._

**No.**

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/593e63d56c4cd34374988381c57edabe2ac50bf8
