### ISSUE TITLE
[PSP] Black Dots appear on Textures

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#177]
**To Reproduce**
_Steps to reproduce the behavior:_
1. Download my [Map](https://github.com/nzp-team/nzportable/files/10611034/Alleyway.zip). (Maybe some other maps have this issue aswell I don't know...)
2. Start the map.
3. See error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Textures look exactly like on PC

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

![PSP](https://user-images.githubusercontent.com/104042185/216821473-6cf93d0b-993e-42d7-aa83-3d36a4ab9915.png)
![PC](https://user-images.githubusercontent.com/104042185/216821485-ec9a39d0-a28b-44b8-a346-be7012d6e425.png)

**Affected Platforms:**

> PSP

**Additional context**
_Add any other context about the problem here._

This also occurs on PSP (Not only PPSSPP)

**Comment by DerpedCrusader** [comment]
I would like to say, I have seen it happen on PPSSPP

**Comment by GJVBCHJV** [comment]
Ghg

**Comment by DerpedCrusader** [comment]
in a recent update, this actually is changes, and now those dots are transparent

![image](https://user-images.githubusercontent.com/13917665/219754617-1fc12a86-c42a-4fe8-9334-a47ea43cec17.png)

I don't know what caused it, but i figured I'd update this post about it

**Comment by MotoLegacy** [comment]
> in a recent update, this actually is changes, and now those dots are transparent
> 
> I don't know what caused it, but i figured I'd update this post about it

This seems like a separate (non-issue?) with the texture used for those targets, not a decoding(?) issue with the wad3 textures causing those black pixels (which i can also clearly see on the floor in that shot).

**Comment by MotoLegacy** [comment]
> Darn now my map looks like someone went in and used a minigun while being drunk. How can I fix the issue in my textures?

Please keep irrelevant issues out of here.. I shouldn't have to repeat myself on this. I made a change with https://github.com/nzp-team/dquakeplus/blob/main/source/psp/video_hardware_surface.cpp. If it still happens, make a separate issue. Keep issues clean.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/assets/commit/40eb98d10a618ed8f33657eede53d249d605404d
