### ISSUE TITLE
AI stuck at stairs.

### ISSUE THREAD

**Issue by DxsSucuk** [nzp-team/nzportable#178]
**Describe the bug**
The AI of the Zombies doesn't allow the to continue moving when staying at the chest on Nacht der Untoten.
**To Reproduce**
1. Go to the chest with only opening the upper doors
2. Look at the stairs you went down seconds ago
3. Enjoy zombies running against the ceiling.

**Expected behavior**
Zombies going down to chase you

**Screenshots/Footage**
Here a Video https://youtu.be/Akr31XHH2M4

**Affected Platforms:**
- Web (I did not test anything else)

**Additional context**
None

**Comment by MotoLegacy** [comment]
(finally) fixed in https://github.com/nzp-team/quakec/commit/fcadbeb7c569a35117fa6ce27d898bc261dc6ebb

https://github.com/nzp-team/nzportable/assets/26030250/36f7378a-f1fd-4a05-8f86-e20757326c89

**Comment by DxsSucuk** [comment]
I forgot that I even found this bug, but damn them zombies be silly and need some breaks while going down stairs.
