### ISSUE TITLE
Clients bounce with packet loss

### ISSUE THREAD

**Issue by DxsSucuk** [nzp-team/nzportable#179]
**Describe the bug**
The character model started to bug around and move the arms up and down.

**To Reproduce**
I can not provide any since I could not reproduce this after it happening 2 times in a row.

**Expected behavior**
Characters arms to stand still.

**Screenshots/Footage**
https://youtu.be/mKfxiV8FzoA

**Affected Platforms:**

- Web (Didnt test anything else)

**Additional context**
None

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/3ec7db82992175264e29c95287f6fd1b078e962e
