### ISSUE TITLE
[PSP] Revive Bar won't go away after Restarting the Map.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#182]
**To Reproduce**
1. Get Quick Revive.
2. Get downed.
3. Restart.
4. See error... Unless your playing co-op for obvious reasons.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Restart completely reverts everything back to the state it was when the map was started.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://youtu.be/u_J5ZDAxVy0

**Affected Platforms:**

PSP

**Additional context**
_Add any other context about the problem here._

I would've left a comment on #59 but you removed the PSP from the Label so I decided to make a new Issue

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/d28699f37c69cdc21b7ec7b0ca000b48884014ac
