### ISSUE TITLE
[PSP] The "Decals" option has disappeared from graphics menu

### ISSUE THREAD

**Issue by TheSubPlayer** [nzp-team/nzportable#183]
This report is a complement for issue #122 
The last build has disappeared with decals option in graphics settings menu.

**To Reproduce**
Just go to graphical settings

**Screenshots/Footage**

https://user-images.githubusercontent.com/110436924/217434862-1babd912-edad-44d2-b9f9-48c430d1ff75.mp4

**Affected Platforms:**

- PSP

# Please make note of any platforms you DID NOT test on.

- 3DS
- PS VITA
- Nintendo Switch
- FTEQW (Windows, Mac, Linux, etc)

**Comment by MotoLegacy** [comment]
Not a bug, Particles & Decals have been combined to form `r_runqmbparticles`, which disables most QMB effect functionality. I've fixed that menu option offset oversight with https://github.com/nzp-team/dquakeplus/commit/d4e899995054843ec1cf2410ad0fdb1ddda97d50, though.
