### ISSUE TITLE
[SERVER/CO-OP] Player Names don't lock onto unrendered players.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#184]
**Describe the bug**
_A clear and concise description of what the bug is._

The name does not snap to the Player's Character/Model

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go onto any map
2. Type cl_splitscreen 1 into the console
3. Move away from the player so that he's unrendered

**Expected behavior**
_A clear and concise description of what you expected to happen._

The name is still at the location of the Player

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://youtu.be/05z748hZHd4

**Additional context**
_Add any other context about the problem here._

Maybe the Name defaults to 0,0,0 when it's target is null? So you should somehow keep the Target while the player is unrendered.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/13985760d26812891584f742d9d79f063c5923b9
