### ISSUE TITLE
[PSP] You can reload twice?

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#185]
**Describe the bug**
_A clear and concise description of what the bug is._

Uh you can reload again during the first reload.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go any map.
2. Shoot your gun empty.
3. Spam Reload.
4. See error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

You may not reload again during a reload.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://youtu.be/Oax1orwRkyo

**Affected Platforms:**

-PSP

-Maybe FTEQW?

# Please make note of any platforms you DID NOT test on.

- 3DS
- PS VITA
- Nintendo Switch

**Additional context**
_Add any other context about the problem here._

I recorded it a long time ago and I don't remember any useful info...

**Comment by DerpedCrusader** [comment]
This is the same bug as #79 

it was fixed in fixed in https://github.com/nzp-team/quakec/commit/efc577410eba4a6a45deaf7987b3c1cf0bf6f020

Make sure to double check submitted bugs before reporting new ones
