### ISSUE TITLE
Powerups aren't being randomised

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#186]
The player always gets a nuke first, then instakill, double points, carpenter and finally max ammo before it cycles back around to nuke.

1. Open any map
2. Play the game as normal
3. Observe which powerups appear

**Expected behavior**
The powerups should appear in a random order.

**Screenshots/Footage**
[Video demonstration here (though it's very long).](https://youtu.be/hDZiG8YRsfs)
Nuke shows at 2:03, then insta at 3:17, double points at 5:05, carpenter at 5:32, max ammo at 5:45, then nuke again at 6:46.

**Affected Platforms:**
PC, PSP, haven't tested the others but probably present there too.

**Additional context**
This is one of those bugs that have been around for a while but haven't been reported.
A [quake demo of my full run](https://drive.google.com/file/d/1BUy3FL5L72HN2YL-dE7I9VSz9JXj-LDM/view?usp=share_link) has also been linked, along with the [WIP copy of 4all I was playing on](https://github.com/nzp-team/nzportable/files/10713887/4all.zip) (pull request soon:tm:).
Nightly 11th February 2023 in case the demo breaks with a later update.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/1498f61986f47c0c1b2b470beb32161eaa0443fb
