### ISSUE TITLE
[PC] Map start text too high up

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#187]
There's a large gap between the map start text and the points display.
I'm not sure if this is because the other players would show there in co-op but it looks kinda jarring.

![image](https://user-images.githubusercontent.com/29164668/218271569-f1a28232-2ed4-4c6d-a7bf-211f2227eb84.png)

**Comment by MotoLegacy** [comment]
confirming that this isn't an issue and is made to account for other co-op players. if you have any alternative options for how to handle the text feel free to reopen marked as a suggestion.

sidenote - use the template please, thanks!

**Comment by BCDeshiG** [comment]
You'll wanna be updating the template then since it still references the platforms as separate.
That aside, here's a mockup for one potential solution (though the text should probably be right aligned here):

![image](https://user-images.githubusercontent.com/29164668/218272693-59a2c09c-6294-4fbc-91e0-79fb3d779826.png)

Alternatively, you could lower the position depending on the number of players currently connected.
