### ISSUE TITLE
[WEB] Crash when restarting the map via the menu

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#188]
WebGL version crashes when restarting a map from the pause menu.
Exiting and re-entering the map works fine however, save for the skybox not loading in ndu.
The `restart` and `reconnect` commands also work fine along with changing maps via the `map` command.

1. Open up [WebGL version](https://nzp.gay) of game
2. Load up any map
3. Pause and restart the map
4. Observe crash

**Expected behavior**
The map should restart.

**Screenshots/Footage**

https://user-images.githubusercontent.com/29164668/218273366-68a8f68e-a6a3-49ad-af8b-186c852c04dd.mp4

**Comment by MotoLegacy** [comment]
this seems to be some sort of core FTE issue, i've went ahead and reported it but in the meantime web will just use the soft restart function: https://github.com/nzp-team/quakec/commit/976a1844a5164834ef987de4ed356e910f4cf073. note that the feature isn't perfect, see this for more details: https://github.com/nzp-team/nzportable/issues/59
