### ISSUE TITLE
Shooting the flame thrower obstructs vision

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#19]
When using the M2 Flamethrower, the fire effects block most of the screen, making it very hard to use:

https://user-images.githubusercontent.com/29164668/167647676-3a90383e-6567-449a-a445-8bd157f8f80c.mp4

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/e45b74eaed178a771d4816e6b36a77c8d3f04e1c, https://github.com/nzp-team/assets/commit/a72c0a249ae1ba1138dadafbdda6cf53d2026a8d
