### ISSUE TITLE
[CSQC] Knifing with a Pack a Punched Weapon make's the PAP'ed and unPAP'ed Sparks.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#190]
**Describe the bug**

Knifing a wall with a PAP'ed weapon in your hand's makes 2 different Sparks appear one from the gun and one from the knife?

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to Firing Range.
2. Pap a Bullet Shooting Weapon.
3. Stab an Innocent Wall to death.
4. See error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

Only the Knifes Sparks appear.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://www.youtube.com/watch?v=jaS3Qs_0lZs

**Affected Platforms:**

Possibly all.

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch
- 3DS

**Additional context**
_Add any other context about the problem here._
Sadly idk shit.

**Comment by MotoLegacy** [comment]
fixed this happening at all in https://github.com/nzp-team/quakec/commit/199f38dc024866f7ca4332ee805622d77a5aadab
