### ISSUE TITLE
[CSQC] Knifing with a Raygun doesn't Produce Sparks nor Bullet Holes?

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#191]
**Describe the bug**
_A clear and concise description of what the bug is._

Knifing a Wall with a Raygun won't produce Bullet Holes? and Sparks.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go Firing Range.
2. Buy a Raygun.
3. Stab a Innocent Wall.
4. See error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Knife does Bullet Holes? and Sparks.

**Screenshots/Footage**
If applicable, add screenshots or video to help explain your problem.

https://www.youtube.com/watch?v=13ObAi7xGIQ

**Affected Platforms:**

 PC but I think it's every Platform.

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch
- 3DS

**Additional context**
_Add any other context about the problem here._

Wild theory but...
The game considers the knife to be in the Explosives Catagory therefore disabling Bullet Holes and Sparks to be made?

**Comment by MotoLegacy** [comment]
Working as intended in the case of the Ray Gun. No weapon should be creating bullet decals and particles.
https://user-images.githubusercontent.com/26030250/219158231-9fb00cbb-7a87-43df-9201-06c062ed8e2b.mp4
