### ISSUE TITLE
Shooting a Zombie and hitting it produces Bullet decals

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#192]
**Describe the bug**
_A clear and concise description of what the bug is._

Shooting a Bullet Based Weapon at a Horde of Zombies produces Bullet Holes on the Wall but it does not Penetrate, Hit and Damage Zombies behind the First Zombie that got Hit.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go any Map.
2. Shoot a Zombie with a Bullet Firing Gun while also Facing a Wall while also making sure to hit both in one Shot.
3. See error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Zombie Blocks the Bullet Decal to be Made due to the Bullet being stuck inside of the Zombie.

Else it would hit the zombies that are behind him.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://www.youtube.com/watch?v=Hk58U9VfTwM

**Affected Platforms:**

- FTEQW

# Please make note of any platforms you DID NOT test on.

- PS VITA
- Nintendo Switch
- 3DS

**Additional context**

Yes this is about Wallbanging technically not existing on PC.

**Comment by MotoLegacy** [comment]
Not sure what's going on with the title here, reverting your change.

**Comment by MotoLegacy** [comment]
Going to go ahead and mark this as wont fix since this is behavior that occurs everywhere
