### ISSUE TITLE
[CSQC] The HUD doesn't scale very well for High Resolutions?

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#193]
**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**
_Steps to reproduce the behavior:_
1. Have a 5k Display.
2. See the Round Counter is wrong on Round 11+
3. See that Perks are in eachother aswell.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The HUD remains correctly Positioned as in 4k or 1440p or 1080p.

**Screenshots/Footage**
If applicable, add screenshots or video to help explain your problem.

Round 35
![fte-20230213220116-0](https://user-images.githubusercontent.com/104042185/218860031-10faa60c-484a-45b8-bd3f-dc2800357b32.png)

**Affected Platforms:**

- FTEQW

_**Unneeded Comment**_

_Funky 5k Display produces Funky Issues how unexpected!_

**Comment by DerpedCrusader** [comment]
I believe it has to do with the scaling you were showing earlier

250% scaling could mess it up 

![image-51.png](https://user-images.githubusercontent.com/13917665/219177127-7af355df-f54a-4096-9b19-9b232f49434d.png)

**Comment by MotoLegacy** [comment]
I've already explained why this is not an FTE/NZ:P issue, please do not revive this.

![fte-20230215165158-0](https://user-images.githubusercontent.com/26030250/219177368-1796db2a-2aa6-4151-b4ff-33750cdfab5e.png)
