### ISSUE TITLE
`vid_reload` doesn't load the Skybox.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#194]
**Describe the bug**
_A clear and concise description of what the bug is._

The Skybox disappears when going from Fullscreen to Windowed

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go any Map.
2. Go from Fullscreen to Windowed.
3. See error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Sky stays the same.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://youtu.be/TQkniZ-9elY

**Affected Platforms:**

- PC

**Additional context**
_Add any other context about the problem here._

Maybe it's a issue with vid_reload?

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/fteqw/commit/d1ccfd83d6c3a519f6826b8cbe95c59c3eb86e05
