### ISSUE TITLE
[SERVER] Running doesn't cancel ADS.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#195]
**Describe the bug**
_A clear and concise description of what the bug is._

While Aiming you can begin to run causing ads to toggle on until you either get forced out of ADS or by trying to ADS again when your not running.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to any Map.
2. Aim.
3. Run and let go of your ADS Key/Button while continuing to Run.
4. See error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

Running Cancels your ADS.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

https://youtu.be/_GZZGQjF030

**Affected Platforms:**

- FTEQW (Windows, Mac, Linux, etc)

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch
- 3DS

**Additional context**
_Add any other context about the problem here._
It also let's you aim twice!

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/fc9d62fc9fd2da287eaf014e06d56c14f0556829
