### ISSUE TITLE
[CLIENT] Muzzleflashes are Inconsistent 

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#196]
**To Reproduce**

1. Pick up a gun
2. Shoot a few times

**Expected behavior**
I would expect a flash to occur everytime the gun is fired

**Screenshots/Footage**

https://user-images.githubusercontent.com/13917665/219756508-c0330c0c-20bf-4ecf-b998-cfda33c02e7e.mp4

**Affected Platforms:**

Just PC, i tested on handheld

**Additional context**
This happened recently, as it worked fine in a build a few days old

Muzzleflashes are a bit borked on PPSSPP, but look fine on hardware, so idc

**Comment by MotoLegacy** [comment]
Not able to reproduce. Please make sure your steps to reproduce are consistent. Feel free to re-open if you can.


https://user-images.githubusercontent.com/26030250/219761076-e35e86a3-84b9-4bda-a683-a8bb2206b8ec.mp4
