### ISSUE TITLE
[SERVER] The wunderwaffe will kill you after killing zombies

### ISSUE THREAD

**Issue by bignoobus** [nzp-team/nzportable#198]
**Describe the bug**
After using the waffe to kill some zombies, shooting zombies with normal weapons will down you

**To Reproduce**
1. Grab the waffe via any way (e.g box or cmds)
2. kill some zombies with it
3. immediately shoot a zombie with a weapon that shoots bullets (e.g thompson)
4. die a stupid death

**Expected behavior**
Waffe shouldn't kill you like that, if it would kill you it would be to splash damage

**Screenshots/Footage**

https://user-images.githubusercontent.com/105007743/219878423-a9d19d48-8a31-4b7e-914d-ca1f9cfc7925.mp4

**Affected Platforms:**
- FTEQW
# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch

**Additional context**
`the code that appears when you get waffe-downed is:
- Set pr_debugger to trace
assignment to read-only entity 0 in Parse_Damage (body_ent.hitamount)
../progs/../source/server/weapons/weapon_core.qc:833: Parse_Damage
    body_ent.washit: 0
    body_ent.hitamount: 0
../progs/../source/server/weapons/weapon_core.qc:1088: FireTrace
../progs/../source/server/weapons/weapon_core.qc:1520: W_Fire
../progs/../source/server/weapons/weapon_core.qc:2418: Weapon_Logic
../progs/../source/server/player.qc:318: PlayerPreThink
QC Exception: assignment to read-only entity 0 in Parse_Damage (body_ent.hitamount)
that should be it i think

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/92a68870aa41f24e672bddfa531a232e1b64f64c
