### ISSUE TITLE
nzportable not playable quad touch

### ISSUE THREAD

**Issue by abdogm** [nzp-team/nzportable#2]
there is an app called "quad touch" this app is quake 1 2 3 engines ported to android by open touch gaming
FTEQW engine is included in this app but the nzportable doesn't work correctly so i was wondering if you can make it playable on quad touch

**Comment by MotoLegacy** [comment]
This seems to be moreso a problem with the maintainers of the FTEQW port rather than us, as the project runs fine on every official FTEQW platform (for now, until we make more major modifications to it, at least). Closing this issue as it feels out of scope.
