### ISSUE TITLE
[SERVER/CO-OP] Zombies still target downed players

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#20]
literally had a timer for this. bleed out time is about 45 seconds. also, zombies that were originally targeting the downed player will just roam around/walk into walls until the player fully bleeds out. they will then finally target the other player(s)

**Comment by barnzify** [comment]
> literally had a timer for this. bleed out time is about 45 seconds. also, zombies that were originally targeting the downed player will just roam around/walk into walls until the player fully bleeds out. they will then finally target the other player(s)

wait how did you get co-op? (sorry to ask here but i have no other way of asking)

**Comment by MotoLegacy** [comment]
> wait how did you get co-op? (sorry to ask here but i have no other way of asking)

Please do off-topic discussion in the Discord, or through GitHub discussions. Not in bug reports.

**Comment by MotoLegacy** [comment]
Bleed out timer fixed in https://github.com/nzp-team/quakec/commit/68a8fcb4acc1f24cc44b763846e92376e893e9c9.
