### ISSUE TITLE
[SERVER] Speed cola doesn't effect the second part of partial reloads

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#200]
**To Reproduce**

1. Get the garand (or M1Browning after it's update)
2. squeeze off a few rounds
3. reload
4. carefully inspect the second half of reload for its timings

**Expected behavior**
For the second part to also be affected by speed cola

**Screenshots/Footage**

https://user-images.githubusercontent.com/13917665/219977329-0a116545-e02f-451f-8814-b8b7c61d25e5.mp4

**Affected Platforms:**

Only tested on FTE, but could affect others

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/41c108e33a8fd96ac4d9d82856841c546b764286
