### ISSUE TITLE
[SERVER] Can't scope in with weapons that have Scopes

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#201]
**To Reproduce**

1. boot up firing range
2. grab the ScopedKar/PTRS
3. try to scope

**Expected behavior**

to be able to scope

**Affected Platforms:**

Only tested on PC

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/2ba93494068dd903b2fbf53d16cd5bad07d118f8
