### ISSUE TITLE
[SERVER] Inconsistency with auto-reload

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#203]
If you empty your mag and then switch weapons/knife before the reload, pressing the shoot button no longer reloads the weapon. This is a regression from previously.

1. Start up any map.
2. Buy a weapon off the wall.
3. Shoot your weapon until the clip is ready.
4. Switch weapons or knife to interrupt the reload before it happens.
5. Switch back to the empty weapon.
6. Press the shoot button.

**Expected behavior**
The weapon should reload when you try to shoot it.

**Affected Platforms:**
I tested this on PC, though Derped has experienced it on 3DS as well.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/c3c2bfe65ca9d62b7861a8031a69684f3adf65d3

**Comment by BCDeshiG** [comment]
Reopening this one since i've encountered the same behaviour when you sprint before the reload.
Knifing however at least triggers the reload as intended.

https://user-images.githubusercontent.com/29164668/226208601-b2700769-d66f-477f-a803-6d83bec2fda9.mp4

**Comment by BCDeshiG** [comment]
In hindsight I should probably just open a new issue for the above.
