### ISSUE TITLE
[PSP] Some Black/Dark pixels are Transparent

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#205]
**To Reproduce**

1. Boot up Firing Range (weapon_test.bsp)
2. go to the shooting area, and look at the ceiling
3. look at all the tiny holes into the void

**Expected behavior**

I would expect them to be dark, and not invisible

**Screenshots/Footage**

![image](https://user-images.githubusercontent.com/13917665/219987212-4f2da503-80e3-4c8c-bfd6-bc6209f1df67.png)
![image](https://user-images.githubusercontent.com/13917665/219987222-9b128265-77d4-4277-b789-af46603d8a21.png)
![image](https://user-images.githubusercontent.com/13917665/219987243-583518cd-d14c-469d-a737-92b65e2d2755.png)

**Affected Platforms**

- PSP (1k, 2k, 3k, Go, Street)

might be other "standard" builds... but I've only tested PSP

the pixels that used to turn black in #177 now turn transparent, i was told it was a seperate issue, so here we are

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/assets/commit/40eb98d10a618ed8f33657eede53d249d605404d
