### ISSUE TITLE
[SERVER] A Grenade Exploding in a Horde crashes you.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#207]
**Describe the bug**

Letting a Grenade explode in a big Horde crashes you.

**To Reproduce**
_Steps to reproduce the behavior:_ (Just guessing here)
1. Get a big Horde.
2. Throw a Grenade into the Horde
3. Make sure everyone will be in the Explosion Radius.
4. Explode and see that the NZP mod in FTEQW is unloaded?

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Grenade Explodes Kills/Hurts the Zombies and that's it.

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

This is the aftermath of this.
![grafik](https://user-images.githubusercontent.com/104042185/220119877-f8462aaf-4ddc-4650-bcd1-30bf25fc73ff.png)

![grafik](https://user-images.githubusercontent.com/104042185/220862339-4c9901a0-44aa-4da7-af63-f0baf2c1d032.png)

[Demo](https://github.com/nzp-team/nzportable/files/10784764/F4lling_to_my_doom.qwd.gz)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

I have seen it occur on PC.

# Please also make note of any platforms you DID NOT test on.

I didn't test on all these down below.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional context**

I am on the 10.02.2023 Build.

**Comment by DerpedCrusader** [comment]
What happens when you open the console?

(Go to options, and then console)

I'd check the demo myself, but I'm not able to atm
