### ISSUE TITLE
[PSP] Points gained/lost affect the environment.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#208]
**Describe the bug**
_A clear and concise description of what the bug is._

While either obtaining or losing Points the World gets tinted either
Red when losing or Yellow when obtaining Points.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to any Map.
2. Shoot a Zombie.
3. See error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Points do not affect anything that isn't a part of the UI.

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

I sadly cannot provide a screenshot of it due to ppsspp crashing upon screenshotting.

**Affected Platforms**

_Tested and affected._

- PSP (Street)

_Tested and unaffected._

- Nintendo 3DS (Old, New)
- FTEQW (Windows, Mac, Linux, WebGL etc)

_Untested._
- PSP (1k, 2k, 3k, GO)
- PS Vita (1k, 2k)
- Nintendo Switch

**Additional comment on this**
_Add any comment about this here._

I should've reported this _weeks_ ago...

**Comment by BCDeshiG** [comment]
I should've reported this months ago lol. Can confirm this is present on my PSP 2k as well as PPSSPP.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/b7e4db4a595c41676c9c63e601e07f606d1736af
