### ISSUE TITLE
[SERVER] game crashes when choosing new powerup cycle

### ISSUE THREAD

**Issue by bignoobus** [nzp-team/nzportable#209]
Its in the title, the game will crash when it completes a powerup cycle and tries to pick a new one

**To Reproduce**
1. load up any map
2. play through the game as normal, note the powerups you get (there are 5 in the game)
3. game crashes after 5th powerup

**Expected behavior**
The game should be able to `finish the current cycle and pick a new one without crashing the game

**Screenshots/Footage**
![fte-20230221021744-0](https://user-images.githubusercontent.com/105007743/220230978-2db898db-2c1b-4e82-9ea1-5aa8f05bc189.png)

the error log in the console upon crashing

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
FTEQW (windows)
# Please also make note of any platforms you DID NOT test on.

- PSP
- PS Vita 
- Nintendo Switch
- Nintendo 3DS

**Additional context**
the error log is :

../progs/../source/server/entities/powerups.qc:114: PU_PopulateArray
    amount: 4
    i: 0
    temp.id: 4
    temp.occupied: 1
    temp.flash_screen: 0
    temp.model_path: models/pu/maxammo!.mdl
    temp.voiceover_path: sounds/pu/maxammo.wav
    temp.__function: 0:PU_MaxAmmo()
    temp.__function: 0:PU_NullRequirement()
     unk(12470): 0===0
../progs/../source/server/entities/powerups.qc:134: PU_GetNextPowerUp
../progs/../source/server/entities/powerups.qc:622: Spawn_Powerup
../progs/../source/server/ai/zombie_core.qc:1157: Zombie_Death
../progs/../source/server/damage.qc:410: DieHandler
../progs/../source/server/damage.qc:468: DamageHandler
../progs/../source/server/weapons/weapon_core.qc:810: Parse_Damage
../progs/../source/server/weapons/weapon_core.qc:1070: FireTrace
../progs/../source/server/weapons/weapon_core.qc:1502: W_Fire
../progs/../source/server/weapons/weapon_core.qc:2400: Weapon_Logic
../progs/../source/server/player.qc:318: PlayerPreThink
bad array read in PU_PopulateArray (index -1082130432)
QC Exception: bad array read in PU_PopulateArray (index -1082130432)
Set pr_debugger to trace
SV_Error: bad array read in PU_PopulateArray (index -1082130432)
Host_EndGame: SV_Error: bad array read in PU_PopulateArray (index -1082130432)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/93258d8f4b02201d49f86b621b654f7856d35b3d
