### ISSUE TITLE
[CO-OP] Grenades sent to other players damage Thrower

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#21]
if you throw a grenade to a teammate, the grenade will hurt you instead. the teammate will take no damage from it.

**Comment by DerpedCrusader** [comment]
This also includes other explosives like Raygun

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/b58b25de5e4c90e02b39888128f8f5a535f5abcd
