### ISSUE TITLE
[SERVER/PC] The sensitivity Value for your Mouse can go below 0.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#210]
**Describe the bug**

The Sensitivity Option does not have a cap on how far it can go.

**To Reproduce**
1. Go to Settings.
2. Click on Control Settings.
3. Right Click exactly 6 or 7 times on Look Sensitivity.
4. See error(s).

**Expected behavior**

Maybe cap it at 0?

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

https://youtu.be/3nVA53EapXk

Affected Platforms

Tested and affected.

   FTEQW (Windows, Mac, Linux, WebGL, etc)

Untested.

    PSP (1k, 2k, 3k, GO, Street)
    PS Vita (1k, 2k)
    Nintendo Switch
    Nintendo 3DS (Old, New)

**Additional context**

It's not really an Issue for _some_ but for most it is a Problem.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/3493722b023ec9e7843dc939e2b7d0a268ef03c1
