### ISSUE TITLE
[PSP] The Gamma does not match up to other Platforms with the same Value.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#211]
**Describe the bug**
_A clear and concise description of what the bug is._

The Gamma does not match up to other Platforms with the same Value.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to any Map.
2. See error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Brightness looks the same just as the other Versions.

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

![grafik](https://user-images.githubusercontent.com/104042185/220731486-fa198d42-91e6-4893-a52e-782addb5ad25.png)

![fte-20230222195906-0](https://user-images.githubusercontent.com/104042185/220731716-fac61f93-b170-4bbf-ae0c-54f06ba8a5ea.png)

**Affected Platforms**

Tested and affected.

-   PPSSPP

Tested and unaffected.

-   FTEQW (Windows, Mac, Linux, WebGL etc)

Untested.

-  Nintendo 3DS (Old, New)
-  PSP (1k, 2k, 3k, GO, Street)
-  PS Vita (1k, 2k)
-  Nintendo Switch

**Additional context**
_Add any other context about the problem here._

No I don't think I will.

**Comment by LukoCiphre** [comment]
psp 3001 has it, although not as bad as THAT, slightly too dark or slightly too bright
