### ISSUE TITLE
[3DS/NX/VITA] Handling of bprint is done improperly

### ISSUE THREAD

**Issue by Naievil** [nzp-team/nzportable#215]
**Describe the bug**
I first noticed that we will crash on 3DS when disconnecting with the match. I have boiled down the issue to bprint being the cause of the issue in ClientDisconnect. This is because in our pr_cmds we do not read the level of the print and instead go straight to reading the string. This is improper. I see the same faulty code in the Quakespasm repo but did not test.

For 3DS, the fix for this is in glquake:ryan_bprint_fix

**To Reproduce**
1. Start match
2. In Pause menu, select Main menu, which sends CL_Disconnect command, which sends ClientDisconnect prog command
3. Observe crash
4. (optional) comment out bprint in ClientDisconnect progs, observe no crash when leaving game

**Expected behavior**
Client disconnect successfully 

**Affected Platforms**
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Comment by MotoLegacy** [comment]
3DS PR merged. Will handle quakespasm soon.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakespasm/commit/aff753308bf27629f66b7bd52e61e48749d5b7e7
https://github.com/nzp-team/dquakeplus/commit/84835d334afa2d7db75717e338175141a787e933
