### ISSUE TITLE
[SERVER] Touching Zombies while they are raising from the Floor skips the Raising Animation/State

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#217]
**Describe the bug**
_A clear and concise description of what the bug is._

Touching a Zombie during its Raising State causes the Zombie to skip raising out of the floor and immediately puts the Zombie into the Attacking State.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Find a Map that has zombies with the spawn flag of 6 (Start Inside, Ground Raise)
2. Touch the Zombie while it's raising.
3. See that the Zombie is immediately attacking you.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Zombie can only start to attack you after it finished raising from the Floor.

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

[Youtube Video](https://youtu.be/XSMjZpON7vs)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

- FTEQW
- PSP (Street)
- Nintendo 3DS (New)

# Please also make note of any platforms you DID NOT test on.

I didn't test on all these down below.

- PSP (1k, 2k, 3k, Go)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old)

**Additional context**
_Add any other context about the problem here._

This may occur due to the game not checking if the Zombie is finished raising in the Zombie Attacking code?

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/eeab4dd4c2b5f6b52fd22302c1fc156146cb3b68
