### ISSUE TITLE
[SERVER] Pack a Punching the M1911 with no other guns let’s you take 2 Mustang and Sallys

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#219]
**Describe the bug**
_A clear and concise description of what the bug is._

Pack a Punching the M1911 While having no secondary Weapon gives you a second Mustang and Sally when your grabbing the Mustang and Sally. 

_My theory on what’s going on._

As the game assumes that you have 2 guns and putting 1 into PAP the game just fills up all the empty slots with the PAP’d weapon(s) without checking if you already have 1 of the 2 (3 With mulekick) filled with a gun.
(Basically the game doesn’t give you 1 gun but as many as it can.)

**To Reproduce**
1. Go to any Map with PAP.
2. Do not fill up any Weapon Slot.
3. Grind up to 5k Points in order to use the PAP machine.
4. Throw your M1911 into PAP
5. Take out 2 Mustang and Sallys.

**Expected behavior**

The game only gives me 1 Mustang and Sally regardless of how many free slots I currently have.

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

Sorry can’t do that as I currently don’t have access to my PC.

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.

I‘ve seen it happen on 

- PC (FTEQW)

I didn’t test it on any of the devices below.
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional comment**
Add any comment here.

Sorry for the bad formatting I‘m writing this on my Phone.

**Comment by BCDeshiG** [comment]
I thought this was patched ages ago. You can see it here in this ancient footage: https://youtu.be/SUnbY3XMcBo

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/8fc831684b01d1e5fae6e7c74277b4ee93cda4ac
