### ISSUE TITLE
[FTE] Waypoints do not link to each other when saving waypoints from the Waypoint Editor.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#220]
**Describe the bug**
_A clear and concise description of what the bug is._

Waypoints that were linked in the editor won't save as Targets for Waypoints

**To Reproduce**
_Steps to reproduce the behavior:_
1. Open the Waypoint Editor.
2. Make Waypoints.
3. Link them.
4. Save.
5. Look at the .way and see they aren't assigned targets.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Waypoints have Targets in the .way

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

![fte-20230301175616-0](https://user-images.githubusercontent.com/104042185/222210838-bb38b18b-0329-462e-a2b0-5a0f0256df98.png)

[Alleyways.txt](https://github.com/nzp-team/nzportable/files/10863656/Alleyways.txt)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

- FTEQW

**Additional context**
_Add any other context about the problem here._

It's very annoying.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/b8b54c06ac553245309aebc43358e7b9083169f5
