### ISSUE TITLE
[PSP] Transparent Textures

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#221]
**Describe the bug**
Transparent Textures have dark areas where it should be see through when they're func_wall or func_illusionary.

**To Reproduce**
1. Go to a map that has transparent textures
2. look at the transparent textures
3. see darkened areas

**Expected behavior**
there shouldn't be any dark areas. the texture should be the only thing visible.

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/34180180/222293336-2676a459-d4df-4ef8-9514-2782a55e3b93.png)

**Affected Platforms**
only seen on PSP

**Additional context**
I'm terrible at describing... sorry D:

**Comment by LukoCiphre** [comment]
transparent textures are generally fine on 3001, sometimes seeing a faint yellow/greed/red shading to them
