### ISSUE TITLE
[ASSETS] Old World Model textures are misaligned 

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#222]
**To Reproduce**

1. open the box
2. look at the beta weapon world models

**Expected behavior**

I'd expect them to look prim and proper 

**Screenshots/Footage**

![image](https://user-images.githubusercontent.com/13917665/222777727-c3834416-f9fe-4657-a09f-13ad0daf657d.png)

![image](https://user-images.githubusercontent.com/13917665/222778026-11961767-17bb-40e3-be05-dcbccd9d3d74.png)

**Affected Platforms**

All

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/assets/commit/bf22d8502b522484ec9db3019a380b929e8c0f03
