### ISSUE TITLE
[PSP] WAD3 to RGBA conversion doesn't preserve alpha masking

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#223]
**Describe the bug**
textures that were transparent in the wad3 don't maintain transparency when converted to pcx

**To Reproduce**

1. open a map using transparent textures on PSP
2. observe

**Expected behavior**
I'd expect them all to be transparent

**Screenshots/Footage**

![image](https://user-images.githubusercontent.com/13917665/222778476-ab78a2ac-1498-454c-a0bb-d7fccc1bd2c7.png)

**Affected Platforms**

Only tested on PSP (via PPSSPP but it shouldn't matter)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/43c260a156a5f8ea2ab27ae4f5613f5a5b46a0fc
