### ISSUE TITLE
[PSP/SERVER] Sprites don't have proper translucency 

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#224]
**Describe the bug**
Sprites, specifically had a significant reduction in quality recently losing all translucency 

**To Reproduce**

1. kill zombies until a power up spawns
2. observe

**Expected behavior**
It'd maintain its appearance 

**Screenshots/Footage**

![image](https://user-images.githubusercontent.com/13917665/222779183-32a5d716-6538-423c-8f88-fa63979bf73a.png)

**Affected Platforms**

PSP

**Additional context**

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/631448a73df296d971472a976d27eb53b0ae5f92
