### ISSUE TITLE
[SUGGESTION] Add func_train, func_rotate_train and func_rotate support to NZP

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#225]
**Describe your suggestion**
A clear and concise description of what feature you'd like to be added.

Due to something I don't know, func_train, func_rotate_train and func_rotate don't work or even show up in NZP.

**Expected behavior**
What you expect to happen or how it'll work in-game.

These func brushes appear just like in Quake 1 or Quake 2.

**Screenshots/Footage**
If applicable, add screenshots as a mock-up to help demonstrate what you want.

![fte-20230303234619-0](https://user-images.githubusercontent.com/104042185/222846530-71c19b8a-218c-4944-bcb3-41853c4e5110.png)

![grafik](https://user-images.githubusercontent.com/104042185/222847280-34429327-2f3b-47a2-86a3-33863143dcad.png)

**Additional context**
Add any other context about the suggestion here.

If this gets fixed, my locomotive dreams will come true.

**Comment by MotoLegacy** [comment]
couldn't find anything about `func_rotate_train` in Quake or Half-Life. but i added the others here: https://github.com/nzp-team/quakec/commit/5da6fcf87e97adb7c2f00ffff7d392c294e38499
