### ISSUE TITLE
Apply glColor to entities

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#226]
**Describe the bug**
every texture with the `{` prefix (used to denote transparency) is full bright when rendered on 3DS

**To Reproduce**

1. boot up NDU or Bunker Defence
2. look at transparent textures

**Expected behavior**
I would expect them to match the lighting from the light map

**Screenshots/Footage**

![image](https://user-images.githubusercontent.com/13917665/223290585-0fb9a670-c2e8-477f-980c-7293feadb771.png)

**Affected Platforms**

Just 3DS

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/glquake/commit/02bd20e9c8c65f69a479cefb61c30d2793debce2 and https://github.com/nzp-team/glquake/commit/0d918e6be6d0a9975f6f1a436f5f5a54040ade7c
