### ISSUE TITLE
[CS9C]? Game crashes after clicking the Master Volume text

### ISSUE THREAD

**Issue by Mantas22XYT** [nzp-team/nzportable#227]
**Describe the bug**
 Game crashes after clicking the Master Volume text, reporting a bounds check failure (0 <= 1 < 1 is false).

**To Reproduce**
1. Load into a map.
2. Go to settings.
3. Go to the volume settings.
4. Click Master Volume text.
5. Open console.
6. Error :)

**Expected behavior**
The master volume to change?

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/75636222/223519295-95ffa8ef-661c-4675-a5a3-75255e96b984.png)

**Affected Platforms**
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**
Also managed to crash the game when restarting in a custom map, funni

**Comment by MotoLegacy** [comment]
closing, see this: https://github.com/nzp-team/nzportable/issues/242
