### ISSUE TITLE
[SERVER] Zappers are ignoring `calc_time`

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#228]
**Describe the bug**
When making a map, set up zappers (I copied some from Warehouse) you can set the time it takes for the zappers to run, but it ignores them and just plays for a second or two

**To Reproduce**

1. download this map and put it in your maps folder
[zaptest.zip](https://github.com/nzp-team/nzportable/files/10914033/zaptest.zip)
2. run the map
3. compare to the source file provided for timing (90 seconds)
[zaptest.zip](https://github.com/nzp-team/nzportable/files/10914040/zaptest.zip)

**Expected behavior**
I would expect the trap to last as long as the timer specifies

**Screenshots/Footage**

https://user-images.githubusercontent.com/13917665/223555744-b1c7dbc3-1487-4de9-ba7f-61feb850cfd0.mp4

**Affected Platforms**
Only tested on FTE, however, i have no reason to belive this won't happen on other platforms

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/e7a78fae5b879a35275aedf7bbaee0c380159032
