### ISSUE TITLE
[SERVER] Zappers ignore `Requires Power` spawnflag

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#229]
**Describe the bug**
when setting the spawnflags value to 1 (Requires Power) the zapper trap still functions fine without it

**To Reproduce**
1. download the map (its different than the other one)
[zaptest2.zip](https://github.com/nzp-team/nzportable/files/10914098/zaptest2.zip)
2. buy the zapper

**Expected behavior**
I would expect the zapper to tell me that it requires power, and to be unable to turn on

**Screenshots/Footage**

heres the spawn flags values
![image](https://user-images.githubusercontent.com/13917665/223557967-247bcdc0-1db3-4ec9-bc1b-a740c8f91d7a.png)

**Affected Platforms**

only tested on FTE, however, It's probably the same on other platforms

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/848541ca286db4cc66814ada05e32689b568c925
