### ISSUE TITLE
[CO-OP/CSQC] Point Adjustments only draw on first client position

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#23]
The Points Numbers that show up when you hit/kill a zombie only show up next to white's points 
![image](https://user-images.githubusercontent.com/34180180/168829344-0310867a-fa9d-4194-b722-602537807f9d.png)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/ad6a0cc25e0730e01608d445abd90908dbcd017b
