### ISSUE TITLE
[ASSETS] M1 Garand sprint clipping

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#231]
**Describe the bug**
_A clear and concise description of what the bug is._

The clip for the M1 Garand pokes out of the M1 Garand when starting to run while holding it.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Buy the M1 Garand.
2. Start to run.
3. See Issue.

**Expected behavior**
_A clear and concise description of what you expected to happen._

There isn't anything that pops out when you start to run

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://youtu.be/eTo0RLZ2bjM

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

I think every Platform is affected.

**Additional context**
_Add any other context about the problem here._

Got none for that, sorry.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/assets/commit/0ffb5675c5ddbf2ee3390f7a5d5cdd3d061fc7d0
