### ISSUE TITLE
[SERVER] func_door_nzp has no collisions for bullets.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#232]
**Describe the bug**
_A clear and concise description of what the bug is._

The func_door_nzp brush has no collisions for bullets

**To Reproduce**
_Steps to reproduce the behavior:_
1. Find a map with doors.
2. Shoot the Door.
3. See that there aren't any impact particles or bullet holes.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The brush gets treated like a wall and has impact particles or bullet holes when it gets shot.

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://youtu.be/0NYpLTbA4e8

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

I have seen it occur on PC.

# Please also make note of any platforms you DID NOT test on.

I didn't test on all these down below.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional context**
_Add any other context about the problem here._

I did not test if bullets shot through the door could hit the zombies that are behind the door.

**Comment by MotoLegacy** [comment]
Marking this as wontfix. This is standard behavior for entities, they aren't brushes, they just render the same.
