### ISSUE TITLE
[FTE] Cannot ADS properly while having ADS mode on toggle

### ISSUE THREAD

**Issue by n4hw3ll** [nzp-team/nzportable#233]
**Describe the bug**
when trying to ADS while having ADS mode on TOGGLE, the gun will start glitching out till you let go of the ADS button.
Sometimes the gun reaches ADS mode, sometimes doesn't.

**To Reproduce**
1. Start a game on any map
2. Switch ADS mode to TOGGLE (while in game)
3. Try to ADS with any gun

**Expected behavior**
gun switches to ADS or hip fire mode with the touch of the ADS button and it doesn't spam the command while holding the key

**Screenshots/Footage**
https://www.youtube.com/watch?v=wCd1VTUpLqo

**Affected Platforms**
Tested only on Windows

**Additional context**
ADS mode can only be changed while in game and it won't save settings after closing game

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/0a631fb74d051790504ceac1bd4d882b7341d475
