### ISSUE TITLE
[SERVER] Sprinting then drinking a perk before canceling the Sprinting causes your view model to fly around.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#234]
**Describe the bug**
_A clear and concise description of what the bug is._

If you buy and drink a perk while running, the game semi thinks that you're still running, causing your view model to shake quite a lot

**To Reproduce**
_Steps to reproduce the behavior:_
1. Run.
2. (Maybe unneeded) Jump.
3. Grab Perk before landing on the floor
4. _Knees weak arms are heavy there's vomit on my sweater already, moms spaghetti._

**Expected behavior**
_A clear and concise description of what you expected to happen._

You don't shake your arms around like a lunatic (or like a coward, it depends on the situation.)

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://youtu.be/1-LfUa_RW1g

[Demo](https://github.com/nzp-team/nzportable/files/10935202/SHAKYHANDS.qwd.gz)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

I have seen it occur on PC.

# Please also make note of any platforms you DID NOT test on.

I didn't test on all these down below.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional context**
_Add any other context about the problem here._

_Knees weak arms are heavy there's vomit on my sweater already, moms spaghetti._

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/73dc723a70b2b2a48956700ef57789fbea2dbff0
