### ISSUE TITLE
[PC/SERVER] You can spectate yourself after buying an ending, therefore causing some visual issues.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#235]
**Describe the bug**
_A clear and concise description of what the bug is._

After buying a buyable end, if you don't die, you can spectate yourself and cause some slight visual issues.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Play a map with a buyable end.
2. Buy it.
3. Spectate yourself.
4. Get funky with your Mouse.

**Expected behavior**
_A clear and concise description of what you expected to happen._

You may not spectate yourself after buying an end.

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://youtu.be/xtI2mjl1B3A

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

I have seen it occur on PC.

# Please also make note of any platforms you DID NOT test on.

I didn't test on all these down below.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional context**
_Add any other context about the problem here._

This technically isn't a bug, but an oversight.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/a347cfee3f815a4c1573d6be52821db98417cce9
