### ISSUE TITLE
[SERVER] Drinking a Perk while Scoped in with the PTRS plays the PRTS Reload animation while also letting you scope and unscope freely.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#236]
**Describe the bug**
_A clear and concise description of what the bug is._

You can drink a perk while staying scoped in (If you're already scoped) causing some mild visual issues including
scoping with no scope, not drinking the perk and reloading without reloading.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Get a PTRS.
2. Scope.
3. Buy a perk.
4. (Optional) Unscope.

**Expected behavior**
_A clear and concise description of what you expected to happen._

You get out of the ADS state and drink the perk normally without any magic tricks.

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://youtu.be/ZnFXZnm_JDw

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

I have seen it occur on PC.

# Please also make note of any platforms you DID NOT test on.

I didn't test on all these down below.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional petty remark**
_Add any complaining about your small problem here._

I hate making bug reports while I'm in the middle of making my maps!

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/e5e4e1637e00385b456fc3d6a4cd5f29a0875fb8
