### ISSUE TITLE
[SERVER] Buying/Grabbing a new weapon while scoped in with the PTRS causes some visual issues.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#237]
**Describe the bug**
_A clear and concise description of what the bug is._

Scoping with a PTRS then trading it in with a new weapon causes the scope.png to stay on the screen, with some other mild issues.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Get PTRS.
2. Scope.
3. Buy a **new** gun.
4. Where'd my hands + gun go?

**Expected behavior**
_A clear and concise description of what you expected to happen._

You unscope while holding your new gun

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://youtu.be/721EAm45hC0

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

I have seen it occur on PC.

# Please also make note of any platforms you DID NOT test on.

I didn't test on all these down below.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional context**
_Add any other context about the problem here._

Uh no.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/e5e4e1637e00385b456fc3d6a4cd5f29a0875fb8
