### ISSUE TITLE
[SERVER] The Scope image for the PTRS stays too long on the screen when scoping/unscoping.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#238]
**Describe the bug**
_A clear and concise description of what the bug is._

If you scope/unscope you may see the world through your eyes instead of the scope while retaining the Scope Image Overlay

**To Reproduce**
_Steps to reproduce the behavior:_
1. Get PTRS.
2. Scope and unscope like a maniac.
3. See a mild visual issue.
4. (Optional) Fix this bug.

**Expected behavior**
_A clear and concise description of what you expected to happen._

When you see the scope of the PTRS, you no longer see the Overlay of the scope.

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://youtu.be/IISKr4D8DSM

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

I have seen it occur on PC.

# Please also make note of any platforms you DID NOT test on.

I didn't test on all these down below.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional context**
_Add any other context about the problem here._

I click too much...

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/0812781cb7d71c7e559905c95e75f22a3825b15c
