### ISSUE TITLE
[CO-OP] Improper handling of mid-game session joining

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#24]
When you join a game thats already started you start with the Game Over message but can still spectate
![image](https://user-images.githubusercontent.com/34180180/168831708-34f13d6e-2457-42b6-a743-2487248f877f.png)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/220253d1b979dfea478d023a263fbcb5fe0a2d93
