### ISSUE TITLE
[SERVER] Waypoints don't load correctly

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#240]
**Describe the bug**
After waypointing a map and saving it, you cannot load it (to edit it), nor do zombies follow the waypoints

**To Reproduce**

1. make a map
2. waypoint it
3. play the map / load the file in the editor

**Expected behavior**
I'd expect zombies to follow the waypoints set up / be able to load existing waypoints

**Affected Platforms**
Only tested on PC

**Comment by MotoLegacy** [comment]
confirmed not a bug
