### ISSUE TITLE
[PC(windows)] issues with resolution changes

### ISSUE THREAD

**Issue by toiletman74** [nzp-team/nzportable#241]
**Describe the bug**
Changing the resolution in the graphics menu works in a really weird way. The text that's displayed in the resolution option doesn't seem to represent what the actual resolution of the game is. If you left click on the resolution option the resolution gets higher and if you right click it makes the resolution lower.

**To Reproduce**
1. load into a map
2. pause the game
3. go to settings
4. go to graphics settings
5. right click on resolution a bunch of times and you'll see what I'm talking about

**Expected behavior**
the resolution text should match up with what the resolution actually is

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.
-Only tested on windows

**Comment by MotoLegacy** [comment]
are you hitting save and apply?

**Comment by toiletman74** [comment]
yeah even after hitting save & apply the resolution still won't match what the game says. Here's a picture of after hitting save & apply. The resolution says 1920x1080 but as you can see in the background it's not.
![image](https://user-images.githubusercontent.com/91436591/224457895-4cae4e6e-3fdd-4dd4-8cfd-b8a8e1008f5f.png)

**Comment by toiletman74** [comment]
didn't mean to click close whoops

**Comment by MotoLegacy** [comment]
closing, explanation found in the new issue i created here: https://github.com/nzp-team/nzportable/issues/242

`r_renderscale 1` in the console fixes the render scaling. the resolution is technically 1080p as shown by the actual screenshot dimensions. internal scale is just being manipulated because of attached issue.
