### ISSUE TITLE
[SERVER] ADS during knifing animations

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#244]
You can aim down sights during the knifing animation which ends up looking awkward.

1. Start any map.
2. Knife (V on keyboard or D-pad DOWN on PSP).
3. Aim down sights during the animation (Hold Right click on PC or L button on PSP).

**Expected behavior**
For the knifing animation to play out without zooming in.

**Screenshots/Footage**
None currently.

**Affected Platforms**
Tested on PC and PPSSPP, though it's far less jarring on the latter.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/da21c6021a7abf391b21c87610f12fbbf5eeb475
