### ISSUE TITLE
[SERVER] Box Glow stays after the box moves

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#246]
**Describe the bug**
When you get a teddy bear from the box and it moves, the glow models stay behind

**To Reproduce**
1. roll the box until a teddy bear
2. wait for it to move
3. hopefully the glow stays

**Expected behavior**
I'd expect the glow to disapere with the box

**Screenshots/Footage**

![image](https://user-images.githubusercontent.com/13917665/224863669-05c2f4f5-a5ce-4579-9659-2c49d43d7818.png)

**Affected Platforms**

tested on FTE

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/adc1b21c21cbbf7a871b2a38560ffe3bf69cc43a
