### ISSUE TITLE
[PSP] Zombie's texture glitches when dismembering a zombie

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#247]
**Describe the bug**

Sometimes, when you kill a zombie on PSP by shooting off their limbs, the limb will disapere, and the entire skin will turn black

**To Reproduce**
1. boot up firing range
2. get a strong gun
3. start headshotting

While this isn't 100% consistent, its consistent enough to where it should be easy enough to reproduce

**Expected behavior**
I'd expect the zombie to stay the same texture when it dies

**Screenshots/Footage**

https://user-images.githubusercontent.com/13917665/224864760-096bd9fe-d167-47cf-be81-b1ee31d5a8b7.mp4

**Affected Platforms**

Only on PSP

tested on FTE and 3DS

**Additional context**

this seems to stem from an earlier bug that did something similar with the seperated zombie parts, i think they need to be re-exported with more skins? but im not 100% sure,

if that is the case, i think i can do that myself

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/2cf0d01544ec0b9d56b17a838d0124984f7aef65
