### ISSUE TITLE
ADS does not decrease look sensitivity when using Analog Strafe (CNub Aim)

### ISSUE THREAD

**Issue by 0xLLUUKKEE** [nzp-team/nzportable#248]
**Describe the bug**
If the Analog Strafe (CNub Aim) option is enabled, aiming down sights does not reduce look sensitivity.

**To Reproduce**
1. Enable Analog Strafe (CNub Aim) option in settings menu
2. Aim down sights
3. Look around

**Expected behavior**
The look sensitivity should be reduced the same way it is reduced when using the circle pad to aim

**Affected Platforms*
- Nintendo 3DS (New)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/glquake/commit/ed4c09de73227739b87c3c97fb1452e5fa1bb675
