### ISSUE TITLE
Sideways Zapper wrong hitbox

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#249]
**Describe the bug**
When placing zappers sideways, the hitbox doesn't match the electricity effect, making it non-functional.

**Screenshots/Footage**
![fte-20230314205112-0](https://user-images.githubusercontent.com/29164668/225133609-b10de64d-d5fb-4285-a4ae-c88006eb88ec.png)
![image](https://user-images.githubusercontent.com/29164668/225133870-91ad1927-9541-42c9-b11e-ecf764c784f9.png)

**Affected Platforms**
Tested on PC.

**Additional context**
We had a discussion about this before but I can't remember what was said then.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/0504f1d8d164d53214266f9f6b019f6f17db77c6
