### ISSUE TITLE
[CO-OP] Player Entity remains after Disconnect

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#25]
When a player disconnects, their player model and hitbox remains. zombies will still target them. if a player disconnects while dead, another "player" will spawn next round as if it was them.

![image](https://user-images.githubusercontent.com/34180180/168835094-2f827051-a0b8-424e-8189-a5d76e81b81a.png)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/6d8202b8e55fcc0bd560e94b51d25f2069589e91
