### ISSUE TITLE
[CO-OP/CLIENT] Points display overlap

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#250]
**Describe the bug**
Playing coop, both player's points overlap (at least on player 2's screen).

1. Join another player's match.
2. See error.

**Expected behavior**
The points display to be separated from each other.

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/29164668/225139144-85b30ad1-03f9-41d0-9eea-0f8849b5e6d8.png)

**Affected Platforms**
Only tested on the web version.

**Additional context**
Issue apparently doesn't occur on host's end, though will want screenshot evidence.

**Comment by DerpedCrusader** [comment]
the left is player one, the right is player 2

![image](https://user-images.githubusercontent.com/13917665/225139451-8af405f5-8579-491a-b4d9-744e537c324d.png)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/a063935abadbd0bc752eb7f493df28ccef26ed37
