### ISSUE TITLE
[server] negative (infinite) ammo on magnum

### ISSUE THREAD

**Issue by toiletman74** [nzp-team/nzportable#252]
**Describe the bug**
negative (infinite) ammo on magnum

**To Reproduce**
1. buy magnum
2. buy quick revive
3. simultaneously die and kill a zombie that drops max ammo
4. pick up max ammo while downed
5. wait to be revived
6. infinite ammo

**Expected behavior**
Expected my ammo to not be in the negative after being revived

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/91436591/225491415-00bb6e5b-0fc3-4f17-93b6-a3e098157561.png)
![image](https://user-images.githubusercontent.com/91436591/225491693-4533fc2c-aa0f-4990-a47c-8db3524ab47c.png)

**Affected Platforms**
Only tested on windows

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/28d769c48e97822a4310edf3b97a776fba294531
