### ISSUE TITLE
[server] Magnum ammo gets taken away after being revived

### ISSUE THREAD

**Issue by toiletman74** [nzp-team/nzportable#253]
**Describe the bug**
If you have a magnum and get revived you have less ammo than intended

**To Reproduce**
1. Buy quick revive
2. Buy magnum
3. Get downed
4. Wait to be revived
5. and bam you have a lot less ammo than before

**Expected behavior**
To be revived with the same ammo I got downed with (minus any I shot while I was down)

**Affected Platforms**
Only tested on PC (windows)

**Additional context**
I didn't test this in co-op

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/6e16bb264ff14ec8a81719275d744685c287b387
