### ISSUE TITLE
Dog rounds sometimes never end

### ISSUE THREAD

**Issue by notrickzdumbo** [nzp-team/nzportable#257]
**Describe the bug**
Dog rounds sometimes don't end

**To Reproduce**
Play a map with dog rounds
Get to a dog round
Be unlucky and have it not end

**Expected behavior**
For me to kill a dog and have the round end

**Affected Platforms**
Only tested on FTE

**Additional context**
Happened to me on the Yellowpill map. First time I've ever encountered this so it could be very rare

**Comment by BCDeshiG** [comment]
I've encountered it while testing F4ll on PPSSPP.

**Comment by MotoLegacy** [comment]
Played 8 dog rounds in succession and couldn't reproduce this issue, please feel free to re-open if producible steps are discovered.
