### ISSUE TITLE
[SERVER] Doors don't load properly when editing waypoints

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#258]
**Describe the bug**
When you load a waypoint file, the door waypoints become normal waypoints *once you interact with the points in any way*

**To Reproduce**

1. load up an existing waypointed map
2. enter waypoint mode
3. load waypoints
4. look at a door point, and how its marked
5. watch it change to normal when you select *any* point

**Expected behavior**
I'd expect the points to retain their door function and ID when loaded, so you can just save it after making your changes

**Screenshots/Footage**

https://user-images.githubusercontent.com/13917665/226208227-694b3443-90c0-4465-9a13-7b093fbfeabb.mp4

**Affected Platforms**

PC

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/28001a1209e72ee1e4a14c2d315610ccf12d837b
