### ISSUE TITLE
[SERVER] `not here` spawnflag for Mystery box doesn't work

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#259]
**Describe the bug**
when spawnflag for the mystery box is set to `not here` the box is still there instead of a random location

**To Reproduce**

1. make a map with multiple box TPs
2. have 1 standard box location
3. set spawnflag to `not here`
4. launch map

**Expected behavior**

I'd expect the box to not be at the specified location, and to instead be on one of the other random spots

**Affected Platforms**

Only tested on PC

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/cce17fc764e20438772af111908fd2e6aeea3619
