### ISSUE TITLE
[Server] fog doesn't leave after dog rounds

### ISSUE THREAD

**Issue by toiletman74** [nzp-team/nzportable#260]
**Describe the bug**
The fog from the dog rounds doesn't leave after the dog round is over

**To Reproduce**
1. Open a map with dogs rounds enabled
2. Get to a dog round
3. Beat the round

**Expected behavior**
The fog is supposed to leave after the dog round is over

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/91436591/226248809-71b6dd3f-a1ef-499b-a1ef-ca0b15a31574.png)

**Affected Platforms**
Only tested on PC(windows)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/db3ec15fe7aa61322a396208309dab8e52c01118
