### ISSUE TITLE
[ASSETS] Kar 98k sprinting animation bug

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#261]
Describe the bug

The Ammo of the Kar 98k appears out of the side of the player's FOV when starting to run while holding it.

To Reproduce

1. Buy the Kar 98k.
2. Start to run.
3. See Issue.

Expected behavior

There isn't anything that randomly appears when you start to run with the Kar 98k.

Screenshots/Footage
If applicable, add screenshots or a video to help explain your problem.

![fte-20230320214257-0](https://user-images.githubusercontent.com/104042185/226461722-7b2f880b-ad9c-42fb-a826-53ed15307a29.png)

Affected Platforms
State which platform(s) you've seen the bug occur.

I think every Platform is affected.

Additional context

Got none for that, sorry.

**Comment by BCDeshiG** [comment]
What's your FOV?

**Comment by Paindeluxe** [comment]
> What's your FOV?

90 for the Viewmodel
