### ISSUE TITLE
[ASSETS] The Mustang and Sally is missing a Run Cycle.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#266]
**Describe the bug**
_A clear and concise description of what the bug is._

The Mustang and Sally is missing a run cycle, and it can be seen when starting to run while holding it and also making it look odd.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Buy the Mustang and Sally.
2. Run with it.
3. See Issue.

**Expected behavior**
_A clear and concise description of what you expected to happen._

There should be a run cycle to make it look like you are running with them in your Hands,
Instead of oddly holding them without really moving them around much.

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._
![fte-20230320221840-0](https://user-images.githubusercontent.com/104042185/226468228-8f46bcab-20ce-43c8-88ee-96e25f75651e.png)
![fte-20230320221843-0](https://user-images.githubusercontent.com/104042185/226468243-77259586-b690-41f4-88a1-579c46570f4f.png)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

I think every Platform is affected.

**Additional context**
_Add any other context about the problem here._

This was screenshotted in r_viewmodel_fov 70

**Comment by MotoLegacy** [comment]
This is a model left over from NZ:P Beta. Please do not make issues for these models as they're going to be completely replaced in the future.
