### ISSUE TITLE
[SUGGESTION] Generate ach.dat instead of including it

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#268]
**Describe your suggestion**
Right now, every time you update, unless you make an effort to do so, your achievements get wiped every single time you update

So I'd like the game to generate an ach.dat at launch when there's none, so that one doesn't have to be included 

So  it won't overwrite existing achievements 

**Expected behavior**
At launch of the game, it'll check for an existing file, if there is none, it makes one

**Comment by MotoLegacy** [comment]
already does this. closing.

https://github.com/nzp-team/quakec/blob/203efa1d3e5f1f4a1f53bdef3317d8870b351ccf/source/client/achievements.qc#L83

https://github.com/nzp-team/dquakeplus/blob/3b19d805e08013122b8d27748eb48335533bd7d4/source/menu.c#L1404
