### ISSUE TITLE
[CSQC] Audio settings menu & Control settings menu go to the main menu instead of settings menu

### ISSUE THREAD

**Issue by toiletman74** [nzp-team/nzportable#269]
**Describe the bug**
If you press Back on the Audio settings menu or Control settings menu, you will be taken to the main menu instead of the Settings menu.

**To Reproduce**
1. Go to the settings menu
2. Open the Audio settings or Control settings
3. Press Back

**Expected behavior**
Pressing Back in either of those menus should take you to the settings menu.

**Affected Platforms**
Only tested on PC(windows)

**Comment by MotoLegacy** [comment]
seems to be related to https://github.com/nzp-team/nzportable/issues/242. closing, keep track of that one for updates.
