### ISSUE TITLE
[SERVER] Bowie Knife

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#27]
Buying the Bowie Knife wall buy will not take money and the Knife animation won't show. 

![image](https://user-images.githubusercontent.com/34180180/168949213-50648eea-fa48-45fd-8bda-313185de136f.png)

(https://youtu.be/xMQ1Fk-aOs8)

**Comment by MotoLegacy** [comment]
Solved in:
* https://github.com/nzp-team/quakec/commit/6b33819c7b9f138d3f5721fb9d7a199089d9abc5
* https://github.com/nzp-team/quakec/commit/f25b8dbe19920b5cd8ced46d1a57b9a447bd7c9a
