### ISSUE TITLE
The Raygun model isn't correctly culled.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#272]
Describe the bug

The Raygun is missing a face, and it can be seen when starting to run while holding it.

To Reproduce

1. Get the Raygun.
2. Start to run.
3. See Issue.

Expected behavior

There isn't anything of the gun that's missing from the player's FOV when you start to run

Screenshots/Footage
If applicable, add screenshots or a video to help explain your problem.

![fte-20230325121309-0](https://user-images.githubusercontent.com/104042185/227714374-3716fd98-6152-470a-b967-4c6a9eae2a8a.png)

Affected Platforms
State which platform(s) you've seen the bug occur.

I think every Platform is affected.

Additional context
This was screenshotted in r_viewmodel_fov 70

**Comment by Paindeluxe** [comment]
Here
![07B38AF1-3AB6-43B8-A852-ADFBA170DE03](https://user-images.githubusercontent.com/104042185/227717954-8d694bf6-bb8f-426a-af90-6f4137880c9b.jpeg)

**Comment by DerpedCrusader** [comment]
fixed in https://github.com/nzp-team/assets/commit/25ec730b1a9f8d1e29d9178d7967ab4faa8ab251
