### ISSUE TITLE
[SUGGESTION] Add a trigger that can execute console commands on a client.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#273]
**Describe your suggestion**
A clear and concise description of what feature you'd like to be added.

A Trigger Brush which can execute a set command upon touching the brush while only affecting the client that touched it.

**Expected behavior**
What you expect to happen or how it'll work in-game.

Upon touching the trigger a set command gets executed on the client/player who touched it for an example...

A Multiplayer lobby is hosted and player 1 touches a trigger which changes the fog.

Player 1 has a different fog but player 2 is unaffected by player 1 touching that brush.

**Screenshots/Footage**
If applicable, add screenshots as a mock-up to help demonstrate what you want.

https://user-images.githubusercontent.com/104042185/227733231-3de9080d-a439-4385-a07c-0b0c700d6a32.mp4

**Additional context**
Add any other context about the suggestion here.

Trigger_command doesn't affect a single client ):

**Comment by Paindeluxe** [comment]
It seems like the video won't play darn.

**Comment by MotoLegacy** [comment]
Implemented, use `trigger_stuffcmd`.
https://github.com/nzp-team/assets/commit/dcbec5b3105fff11b1dd9217da0e5c3faa377fb6
https://github.com/nzp-team/quakec/commit/6df8c971e884b4b8f68ea4c3b24e5cbc970f555a
