### ISSUE TITLE
[SERVER] Zombies spawn not where spawn points are

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#274]
**Describe the bug**

Pretty inconsistently, zombies will spawn in a spot other than where they're supposed to spawn and will run twoards the window, and then eventually despawn

I'm providing files that i used to reproduce this on my map

[HalfCrapFiles.zip](https://github.com/nzp-team/nzportable/files/11070112/HalfCrapFiles.zip)

**To Reproduce**

So, this isn't 100% consistent, but its consistent enough to put in a report, i saw it 13/13 times, but its never the same way

1. boot up HalfCrapUncut (it probably happens on other maps, but I found it happening on this quite often)
2. immediately press `=` twice to progress the round to round 9, the faster spawning makes it more apparent
3. run through the 500 point door
![image](https://user-images.githubusercontent.com/13917665/227741348-b9a1f684-6e73-4de4-9a72-1aa9bbf237b0.png)
4. go over to this area
![image](https://user-images.githubusercontent.com/13917665/227741355-db52322f-513f-4095-8ce5-0d4474aa38e0.png)
5. use `god`/`give 20` to kill the zombies that spawn to progress to the next round
6. there should be zombies spawning outside the barriers somewhere, but this spot is good for seeing them

**Expected behavior**
I'd expect all zombies to spawn in the spawn they are given

**Screenshots/Footage**

Sorry, its youtube footage, sadly that 10mb limit

https://youtu.be/z1r1tUYetP8

**Affected Platforms**

I've only noticed this on FTE,

i haven't properly tested on other platforms

**Additional context**

i thought that it might have been the ground risers, but it wasn't

it's easier to tell when it happens if you set them to ground risers, so i'd suggest giving that a shot to find them easier

**Comment by BCDeshiG** [comment]
We found out this was because the zombie spawns were too close to the walls.
After adjusting them, the issue stopped happening.
