### ISSUE TITLE
[SUGGESTION] Add Texlights to the FGD

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#275]
**Describe your suggestion**
simply. just add texlights to the fgd. and allow for func_wall and func_illusionary to use them.

**Expected behavior**
textures should glow/emit light if their texture is selected in the texlight entity

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/34180180/227810835-32b63d1f-6338-47f7-b0e8-612ef6737fdd.png)

**Comment by MotoLegacy** [comment]
added in https://github.com/nzp-team/assets/commit/6f90de83ff3363da04d244b1b68e938951454c4f
