### ISSUE TITLE
[SERVER] `give` commands break ADS

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#277]
**Describe the bug**

When you use the `give` command, the ADS values don't work, and the gun just zooms in a smidge

**To Reproduce**

1.  load up natcht
2. open console
3. type `give 20` (raygun)
4. ADS

**Expected behavior**
I'd expect the Gun to ADS properly

**Screenshots/Footage**

https://user-images.githubusercontent.com/13917665/228101998-f4d4c3d8-b343-4d25-b1b3-f64ca619dd53.mp4

**Affected Platforms**

Only tested on FTE

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/8516fb22e906c65f048f70c3817416199b86e38b
