### ISSUE TITLE
Deleting Waypoints causes a crash.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#278]
**Describe the bug**
_A clear and concise description of what the bug is._

Deleting a Waypoint causes a crash.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Open the console.
2. Type in "Impulse 100".
3. Make a waypoint.
4. Delete said waypoint.
5. See Error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

It deletes the waypoint without any problems.

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.

I have seen it occur on the PS Vita with Adrenalin 6.61.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/d4995b5b0cd324e331e0c7fe44da293fb0dbb57a
