### ISSUE TITLE
You cannot walk up steps with low FPS

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#285]
**Describe the bug**
_A clear and concise description of what the bug is._

The Player cannot walk up a small step, but rather treats it as a wall.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Start up Nacht der Untoten.
2. Set your FPS to a low value.
3. Try to walk upstairs.
4. See Error.

**Expected behavior**
_A clear and concise description of what you expected to happen._

I am able to walk up steps like I can with a higher FPS.

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://youtu.be/7cI3P1wLiPg

**Affected Platforms**
# State which platform(s) you've seen the bug occur.

I have seen it occur on PC.

# Please also make note of any platforms you DID NOT test on.

I didn't test on all these down below.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional comment**
_Add any other comments about the problem here._

This has been an issue for a few months now, but I only reported it now.

**Comment by MotoLegacy** [comment]
Wasn't able to reproduce this in my own testing on stream day 3
