### ISSUE TITLE
Explosives don't trigger easter egg teddy

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#292]
**Describe the bug**
Explosive weapons such as the raygun and panzershreck don't activate the easter egg teddy bears.
The Wunderwaffe does however.

**To Reproduce**
1. Load up a map with easter egg teddies (e.g. F4ll).
2. Obtain a raygun.
3. Shoot the teddy.

**Expected behavior**
The teddy bear disappears.

**Affected Platforms**
Tested on FTE Linux though this probably affects all platforms.

**Additional context**
Not sure if this is intentional behaviour since I don't know how COD does it.
I can understand why it would be though.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/27066a33c737a68e0e6929e122f81456229195c8
