### ISSUE TITLE
Zombies get stuck in water

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#294]
**Describe the bug**
When playing Dung3on, the zombies get stuck and ballerina pose sometimes when they're in the water. 

**To Reproduce**
1. Load up Dung3on.
2. Reach a room with water in it.
3. Attempt to horde some zombies. 

**Expected behavior**
The zombies should behave the same as they do without water.

**Screenshots/Footage**

https://user-images.githubusercontent.com/29164668/234412214-e412d016-c91f-40a1-b7ba-285962d344fe.mp4

**Affected Platforms**
Observed on FTE Windows, Linux and WebGL.
I vaguely remember it happening on PSP too though my memory is foggy.

**Additional context**
This issue has been around for years and I've only just gotten around to reporting it. Also unsure if the water height affects things since I don't know of any other maps that utilise water other than Dung3on.

**Comment by LukoCiphre** [comment]
this isnt present on psp 3001 :3

**Comment by Laser327** [comment]
i was playing this map quite a bit but it looks like the PSVita version is the only one that doesnt have this bug (tho no one tested this on switch yet so were gonna see eventually if its working exclusively on Vita)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/152ccb40dd7fc3a5b93e48c2d509514c8bc2fbd5
