### ISSUE TITLE
PSP Memory Thread

### ISSUE THREAD

**Issue by pato4mmc** [nzp-team/nzportable#295]
**Describe the bug**
when zombies knock the player down it works for like 5 seconds and then crashes with memory alloc error

**To Reproduce**
get knocked out by zombie

**Expected behavior**
not crash

**Affected Platforms**
psp 1000, fat, phat

**Comment by Laser327** [comment]
It happenes to me as well, but mainly on a map "Fegefeuer" on a PSVita Version [Model 1104] tho its not consistent it appears that on this map it crashes as soon as i either turn on the power or buy Jug.

**Comment by LukoCiphre** [comment]
only crashes on psp 3001 64mb due to pushtype with a non bsp model

**Comment by MotoLegacy** [comment]
Looking for more status reports as I recently made more memory optimizations.
