### ISSUE TITLE
Game splits into 4 clonned screens

### ISSUE THREAD

**Issue by pato4mmc** [nzp-team/nzportable#296]
**Describe the bug**
Game splits into 4 clonned screens randomly and colors change to some garbage pic related

**To Reproduce**

1. play game peacefully
2. wait some time, kill some zombies, make some progress 
3. see glitch

**Expected behavior**
not split 

**Screenshots/Footage**
![IMG_5157](https://user-images.githubusercontent.com/128759103/235878105-25a2b31d-15a7-4819-a44c-bf8e72577946.jpeg)

**Affected Platforms**
- PSP (1k, fat, phat)

**Additional context**
didnt saw that glitch on windows build

**Comment by LukoCiphre** [comment]
this happens on psp 3001, but theres no color other than black, white, and purple

**Comment by BCDeshiG** [comment]
This has happened to me on my PSP 2000. I'm not sure what exactly caused it but a powerup did spawn around the same time (not sure if related).

**Comment by botnumber3** [comment]
Im on Psp go and the same thing happens mainly when i reach the higher levels. Its random but sometimes it seems like something triggers it whether I'm being hit by a zombie, picking up a power up, buying a gun, ect. Idk if there is anything to fix it but r they working on getting this fixed or no?

**Comment by VaporUwU** [comment]
this issue still happens with the new release, however i was able to get to round 11 on warehouse before it occurred and cashed a crash

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/cfbf7f509854d5577e4f7cdb559835d0b4ecc445
