### ISSUE TITLE
[CLIENT] [FTE] Trackpad does not work

### ISSUE THREAD

**Issue by Mechaedelescaleras** [nzp-team/nzportable#299]
**Describe the bug**
Clicking on anything with the trackpad does not work in menus, and when using a console command to load into a map, I cannot either shoot my weapon or look around. (Edit: It seems to be an issue on my end)

**To Reproduce**
1. Launch the game
2. Try clicking on anything
3. Nothing will happen

**Expected behavior**
I expect the trackpad to work in the menus, and in-game like a mouse would.

**Screenshots/Footage**
[N/A]

**Affected Platforms**
FTEQW Windows

**Additional context**
[N/A]

**Comment by Paindeluxe** [comment]
I have never encountered this issue on my Laptop trackpad.

Have you tried restarting NZP or your Laptop?

**Comment by Mechaedelescaleras** [comment]
> I have never encountered this issue on my Laptop trackpad.
> 
> Have you tried restarting NZP or your Laptop?

No matter how many types I restart my Laptop, restart NZP, or reinstall the game, the problem still persists. The issue is on my end then.

**Comment by MotoLegacy** [comment]
Unfortunately, this seems to be an FTE issue, not an NZ:P issue. We aren't in charge of hardware interface support for FTE, but you can post an issue at https://github.com/fte-team/fteqw with more information about your OS, and laptop model.
