### ISSUE TITLE
Extra Zombie at the End of Rounds

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#3]
every so often. an extra zombie spawns at the end of a round.  at least on PC. been told it happens when you kill in non-standard ways such as explosions and the waffe. but i also got them when i kill zombies normally. might be DT?

**Comment by BCDeshiG** [comment]
Looking into this further, yeah I abused the raygun quite a bit in my test run and not once did I encounter an extra zombie spawn at the end of the round. I also didn't have Double Tap in this run yet in most of my other test runs where I did encounter extra zombies, I did have Double Tap.

**Comment by toiletman74** [comment]
This happened to me a few times in a run I was doing. But what was different for me was I had no "special" weapons like raygun or wunderwaffe in the map at all. Got a video of it happening tho.

https://user-images.githubusercontent.com/91436591/225476325-7a93eb0e-23fd-411a-a29d-dd06e65657db.mp4

**Comment by toiletman74** [comment]
got the extra zombie glitch again, this time on round 11. no double tap and I haven't shot any zombies while nukes are going off. I did have the wunderwaffe tho

**Comment by BCDeshiG** [comment]
I feel like if we wanna debug this thing, having an option to display the number of zombies left would be pretty helpful (kinda like what certain WaW custom maps do).

**Comment by MotoLegacy** [comment]
potentially resolved in https://github.com/nzp-team/quakec/commit/d156216f42108699b8e56ad86d3bd347880ec7ab#diff-40fcfb4a6d4851594817cbeff95f152e4a2e70de26b368d0504c897345261332
feel free to re-open if its confirmed to still be an issue
