### ISSUE TITLE
[SUGGESTION] Speed Cola also Speeds Up fixing Barriers

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#305]
**Describe your suggestion**
just as the title says. i think it'd be a nice buff if Speed Cola also sped up repairing barriers.

**Comment by MotoLegacy** [comment]
It already does this, as taken from Call of Duty: Black Ops.
https://github.com/nzp-team/quakec/blob/7ead10e568de8878d8c5c06287ad32f65ed4b201/source/server/entities/window.qc#L269
