### ISSUE TITLE
Make FOV increase when sprinting, not decrease 

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#315]
Honestly, not sure if this is a bug or intentional, but right now when sprinting, the FOV decreases, making the screen feel tighter and the player slower. In other games, the FOV increases when going faster to add to the sense of speed.

**Comment by MotoLegacy** [comment]
added to glquake with https://github.com/nzp-team/glquake/commit/9dda9b48ef369a2ff34f900a6f94807afa0cd3e7

**Comment by MotoLegacy** [comment]
added to quakespasm with https://github.com/nzp-team/quakespasm/commit/481d4a02e1086e0fffbbd429551c2f7345bfa96d

**Comment by MotoLegacy** [comment]
added to dquake with https://github.com/nzp-team/dquakeplus/commit/60103d3bb33048973e3b2df76f0b1ca3c74b574b
