### ISSUE TITLE
misc/buy.wav used for Warehouse teddy bears

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#316]
Tested on warehouse. Collecting a nuke shows the message Kaboom.wav is missing. Shooting the teddy bears shows the message Buy.wav is missing.

**Comment by MotoLegacy** [comment]
kaboom restored with https://github.com/nzp-team/assets/commit/f9152241864325040217b5970848da972ee18290

**Comment by MotoLegacy** [comment]
buy.wav fixed in https://github.com/nzp-team/quakec/commit/72631d96a81be00d361859373475be609318fd6d
