### ISSUE TITLE
Die whenever I throw a grenade (even if I'm not in the blast)

### ISSUE THREAD

**Issue by SilentShadows77** [nzp-team/nzportable#317]
**Describe the bug**
Whenever I throw a grenade, after the grenade sits there it then explodes. If I am far from the grenade blast, I still die. I may even die a second or two afterward.

**To Reproduce**
1. Go to any map
2. Click on grenade button to throw
3. Wait to blow up as you are safe distance away
4. DIE

**Expected behavior**
Not to die when away from blast
**Affected Platforms**
New 3ds xl

**Comment by MotoLegacy** [comment]
I had buffed the size of the grenade radius recently to better match World at War, the particle effect might not correctly represent this. Are you sure you're back far enough?

**Comment by MotoLegacy** [comment]
Confirmed not an issue. I did do some tweaking to grenades in https://github.com/nzp-team/quakec/commit/b3388f382f96fb1605b9f11562980ed3510d6575 however, including a very subtle radius decrease. Closing, let me know if there's an issue with just the decal/scale of the ffect
