### ISSUE TITLE
NEW 3ds xl doesnt have 2.0.0 update available on universal updater 

### ISSUE THREAD

**Issue by SilentShadows77** [nzp-team/nzportable#319]
**Describe the bug**
The UU allowed me to download the update. After downloading UU crashed upon exit. Nzp is not updated to 2.0.0. Cant download nzp on UU anymore, doesn't show update option as well as no green arrow indicating an update can be made.

On new 3ds xl

**Comment by MotoLegacy** [comment]
Universal Updater moves our 3DSX out of place and this causes some issues when using it to update, I need to take that up to them. Delete both `sdmc:/3ds/nzportable.3dsx` and `sdmc:/3ds/nzportable/nzportable.3dsx` and you should be able to re-download the archive and receive the up to date binary.
