### ISSUE TITLE
[SUGGESTION] Make Zombie AI follow players better and also add more weapons from other versions of COD zombies 

### ISSUE THREAD

**Issue by mrmoderate28** [nzp-team/nzportable#329]
Make zombies actually chase use BO1 or 2 for examples on how to fix AI and weapon additions

**Expected behavior**
What you expect to happen or how it'll work in-game.

**Screenshots/Footage**
If applicable, add screenshots as a mock-up to help demonstrate what you want.

**Additional context**
Add any other context about the suggestion here.

**Comment by LukoCiphre** [comment]
horse react this man

**Comment by Paindeluxe** [comment]
> Make zombies actually chase use BO1 or 2 for examples on how to fix AI and weapon additions

There is a Work In Progress feature that’s currently on hold called a navmesh idk when it’s done but it is in the works although last time the branch got updated was in 7th February of this year.

Also all of the cod:waw features need to be finished in order for BO1 and BO2 features to get added

**Comment by MotoLegacy** [comment]
Sure, support development and I can get right on that.

**Comment by mrmoderate28** [comment]
Also could you try to add a maps downloader built in to all versions of nzp
if possible and if compatible with 3ds or psp

**Comment by MotoLegacy** [comment]
Sure, support development and I can get right on that.
