### ISSUE TITLE
Use quake enemy ai to improve zombie ai

### ISSUE THREAD

**Issue by SilentShadows77** [nzp-team/nzportable#332]
**Describe your suggestion**
The quake enemies never seem to be stuck and have a great path finding ai. Currently the zombies dont have as good pathfinding ai, so the ai of the quake enemies should be used instead or as an addition to the zombie ai.

**Comment by Paindeluxe** [comment]
I found this [Video](https://youtu.be/wVj2MxOtbhk) about quake AI

while this isn’t concrete proof it does show some limitations to it

**Comment by SilentShadows77** [comment]
> I found this [Video](https://youtu.be/wVj2MxOtbhk) about quake AI
> 
> while this isn’t concrete proof it does show some limitations to it

Could it still be better than the current ai, and/or could it be fixed

**Comment by SilentShadows77** [comment]
> I found this [Video](https://youtu.be/wVj2MxOtbhk) about quake AI
> 
> while this isn’t concrete proof it does show some limitations to it

Great video thanks. While maybe we shouldn't copy the quake ai, we can see the enemies problem solving,

Hit wall, go in different direction to go around, if that doesn't work, ho back and try again, and finally go in different directions until you hit another wall, then go in different directions and try problem solving on that wall. It is slow but FAR more improved, and atleast they make it in the end

**Comment by Paindeluxe** [comment]
That is a pretty good idea as it also takes the platform parity into account.

I guess we‘ll have to wait what system will finish, your idea or the navmesh

**Comment by SilentShadows77** [comment]
What's navmesh

**Comment by MotoLegacy** [comment]
Quake's vanilla AI and "pathing" requires mostly straightaways to be effective. Pre-alpha versions of NZ:P used Quake Monsters and they flat out don't work. blubs can vouch for that.

Your idea of just bouncing them around is a _weird_ bandaid but this problem you're describing only occurs when the map maker's waypoints allow for it. If there **IS** an instance where the pathfinding algorithms fail, fixing that would be faster to deploy, lighter in code weight, and not increase resource consumption. 

Thanks for the thought experiment, but this is not beneficial to the project.

**Comment by SilentShadows77** [comment]
> Quake's vanilla AI and "pathing" requires mostly straightaways to be effective. Pre-alpha versions of NZ:P used Quake Monsters and they flat out don't work. blubs can vouch for that.
> 
> Your idea of just bouncing them around is a _weird_ bandaid but this problem you're describing only occurs when the map maker's waypoints allow for it. If there **IS** an instance where the pathfinding algorithms fail, fixing that would be faster to deploy, lighter in code weight, and not increase resource consumption.
> 
> Thanks for the thought experiment, but this is not beneficial to the project.

Interesting. Thanks for letting me know.
