### ISSUE TITLE
Deadshot forcing me to look at the ground 

### ISSUE THREAD

**Issue by Ellis243454** [nzp-team/nzportable#335]
So I have experienced this a couple of times and have no clue the cause and it has gotten me killed a couple of times 

The steps to recreate this are 
1. Buy deadshot 
2. Ads 

It doesn't seem to happen alot but it happens the most I noticed when all zombies that can be spawned in are spawned or almost all are dead  the best way to describe it is when I ads near a group of zombies it either does 1 of 2 things either aims at the zombies head which is 95% of the time or it forces me to look at the ground where no zombie is or spawning 

What I think is happening is it's trying to track maybe a dead zombies corpse or maybe a zombie that isn't there or was previously I have no clue what's happening

I can't provided video evidence as I have no way to screen record my DS 

I have tested it on
3ds 

Haven't tested on 
PC 
Switch 
Psp

**Comment by MotoLegacy** [comment]
Please make sure you aren't reporting duplicate issues. 
https://github.com/nzp-team/nzportable/issues/121
