### ISSUE TITLE
Oops achivement without dying to fall damage.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#338]
**Describe the bug**

When falling from a great height you take fall damage, if you die by it, you would get the oops achievement.

However, you don't have to die to the fall damage to receive it.

**To Reproduce**
1. Go to a map where you can fall a great height
2. Jump down a great height.
3. See error

**Expected behavior**

I either die or not get the achievement.

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

![fte-20230820161749-0](https://github.com/nzp-team/nzportable/assets/104042185/3bd47fbf-cd85-468a-a82d-adcdaeac02fc)
![fte-20230820161738-0](https://github.com/nzp-team/nzportable/assets/104042185/9f891186-15f9-426e-b289-df1707420c29)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.

I have tested it on PC.

I have not tested it on the platforms below.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional context**

**Comment by MotoLegacy** [comment]
This is a very lame predicament where this achievement was suggested and then implemented without proper assurance it was actually supposed to be possible. Now that fall damage works properly it is *not possible* to die from fall damage. I have changed the achievement description from "Die from" to "Nearly die from", and tweaked the stats in https://github.com/nzp-team/quakec/commit/c9c8c310128c9f5e891dd6be25c25c36687bd214
