### ISSUE TITLE
Electric Barrier bounding box is pass-able

### ISSUE THREAD

**Issue by oStarist** [nzp-team/nzportable#345]
**Describe your suggestion**
Traps currently only kill zombies when they hit the actual electric beam, and can live when they walk in between them. What I propose is that they would always kill zombies that go through them, instead of just when they hit the beam.

**Expected behavior**
The zombies will always die regardless if they hit the beam or not when going through the trap.

**Comment by MotoLegacy** [comment]
Is there a map in particular where this tends to happen? The beams being the bounding box makes sense logistically, and there is enough space for a bit of freedom between them for mappers typically.

**Comment by oStarist** [comment]
> Is there a map in particular where this tends to happen? The beams being the bounding box makes sense logistically, and there is enough space for a bit of freedom between them for mappers typically.

just any map that has electric traps really

**Comment by MotoLegacy** [comment]
I did some investigating and found some broken bounding box logic, and fixed it. Let me know if that solves your issue (https://github.com/nzp-team/quakec/commit/901ee7121e7dd52ca9ada7232399730892da8189)

**Comment by MotoLegacy** [comment]
Closing as requested follow-up was not received. Feel free to re-open the issue if it persists.
