### ISSUE TITLE
[VITA] Version has white censor lines instead of text

### ISSUE THREAD

**Issue by masterpl4n** [nzp-team/nzportable#346]
This only happens on my Vita, and it’s a 1000 model. 
![IMG_9885](https://github.com/nzp-team/nzportable/assets/143304484/da16de3c-20e6-4db9-973d-4dc7ea7905b5)
Most text (not including text for purchasing things) is just replaced with white bars.

**Comment by MotoLegacy** [comment]
Can you try reinstalling? It looks like it didn't install correctly

**Comment by MotoLegacy** [comment]
![image](https://github.com/nzp-team/nzportable/assets/26030250/e106ecef-1afc-4ebe-8d2b-0f6df6d2592e)
Works fine for me via VitaDB, maybe an issue with downloading/extraction on your end. Closing.
