### ISSUE TITLE
[SUGGESTION] DT 2.0 Skin for the Double Tap Machine

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#347]
**Describe your suggestion**
just thought it makes sense that we use the skin for the Double Tap 2.0 Perk Machine since we use Double Tap 2.0

**Expected behavior**
The Skin on Double Tap Perk Machine to at least have the 2.0 icon instead the 1.0 icon. or have the option to switch between them.

**Comment by DerpedCrusader** [comment]
I'm pretty sure we have a whole separate model to differentiate between 1.0 and 2.0

**Comment by MotoLegacy** [comment]
^ What Derped said, it's in the hl_scale directory. We do not replace the old ones for compatibility
