### ISSUE TITLE
[PC] Shooting gun during game start music interrupts it

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#349]
When loading into a map, if you shoot your gun while the starting music plays, it interrupts it.

This is on latest version, so have not tested on other platforms :3

https://github.com/nzp-team/nzportable/assets/139988968/3b472c69-beb2-4cd1-aa8e-8160d73b5175

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/ddc845f44702ab7bc3655985689de5859c826139

**Comment by LexiAshe** [comment]
Nice one!!
