### ISSUE TITLE
[SERVER] Camera Height Changes When Downed back2back in CO-OP

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#35]
when you have a horde of zombies on you and go down. then get picked up, and go immediately down again, your camera gets stuck lowered. if it keeps happening, your camera will just be under the map and you won't be able to see the zombies very well. its mostly tested on Co-op/PC because only in co-op do the zombies stick on you when you're down.

The expected behavior should be that the camera goes back to normal height
![image](https://user-images.githubusercontent.com/34180180/171503048-f31cb50d-69b8-4a58-8b58-3b03458a75f7.png)

Only tested on PC.

**Comment by MotoLegacy** [comment]
wasn't able to reproduce this with the steps listed after ~10 attempts. closing, feel free to re-open if you're able to give new reproduction methods.

**Comment by Paindeluxe** [comment]
> wasn't able to reproduce this with the steps listed after ~10 attempts. closing, feel free to re-open if you're able to give new reproduction methods.

You have already fixed this in Issue #60  https://github.com/nzp-team/nzportable/issues/60#issuecomment-1362966734
