### ISSUE TITLE
Mystery Box moving causes crash

### ISSUE THREAD

**Issue by SSleeet** [nzp-team/nzportable#350]
**Describe the bug**
QuakeC crashes after the Mystery Box changes locations enough times. Believed to be caused by box attempting to move to an unavailable spot.

**To Reproduce**
1. Move box many times
2. One of those many will cause a crash

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.
![image_2023-08-27_133614138](https://github.com/nzp-team/nzportable/assets/27873551/60f4fe27-dac8-4319-a9f6-54ae72d51f78)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.
Discovered on PC only, likely on other builds.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/ad23cd79337f27fc87662b1ff567bbd408c8cf98
