### ISSUE TITLE
Server Stopwatch Not Resetting Minutes

### ISSUE THREAD

**Issue by itzxil** [nzp-team/nzportable#351]
# When giving your report a title, please prepend a [LABEL], example [LABEL]s include:
# [SERVER] (for game code), [CLIENT] (for HUD elements or other client side stuff),
# [PSP/3DS/NX/VITA/FTE] (for engine based code specific to the platform).
# If related to CO-OP, prepend "CO-OP/" to the label, (e.g. [CO-OP/SERVER]).
**Describe the bug**
After reaching the hour mark the minute counter resets to 54 instead of 0. This makes it so that a new hour is counted every 6 minutes.

**To Reproduce**
1. Play the game with stopwatch enabled
2. Let an hour pass

**Expected behavior**
Minute counter should reset to 0

**Screenshots/Footage**
[If applicable, add screenshots or a video to help explain your problem.](https://clips.twitch.tv/ReliableBoringUdonOpieOP-f6wYVLC8SyvO0DHI)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.
FTE Windows

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**

**Comment by MotoLegacy** [comment]
Nice catch, sorry to have ruined your stream with that :( fixed in https://github.com/nzp-team/quakec/commit/10418b38f70393b72b10399882692b0f29138998
