### ISSUE TITLE
Zombies don't run away from the player when downed

### ISSUE THREAD

**Issue by Ascension240** [nzp-team/nzportable#352]
**Describe your suggestion**
Zombies should at least run away from the player to make sure they have a fighting chance when they down. They currently just stay in the same spot.

**Expected behavior**
They’ll run away in random directions when a player downs.

**Comment by MotoLegacy** [comment]
This is actually a programmed feature which is broken, marking this as a bug.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/619980e88c0bbf9aac91e70d0f38c182b8a45eec
