### ISSUE TITLE
Toggle aim broken 

### ISSUE THREAD

**Issue by zombiw** [nzp-team/nzportable#353]
When switching to the toggle aim option in settings it breaks the menu, and also doesn't work in game.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/006c82e025a39e449f93cdfb7ad0c5eec81f8ca9 and https://github.com/nzp-team/quakec/commit/30758dd3893f75392cca53fc5d728afd8201ba6a

**Comment by LukoCiphre** [comment]
toggle dosent work with trackpads, probably not even at all
