### ISSUE TITLE
Christmas Special Waypoints

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#355]
Am able to softlock the game, jumping into an area with no doors purchased, thus meaning zombies cannot reach me and I have no means of escaping (unless I have the points needed to exit). Some zombies stuck in unlocked rooms also become unkillable.

Get to the second floor by going the route of the 750 point door (as shown in video). Was able to recreate on both PC and Vita. 

https://github.com/nzp-team/nzportable/assets/139988968/1d4e25b5-8710-4cc3-a525-9ba574575e8e

https://github.com/nzp-team/nzportable/assets/139988968/0dbe8e2b-54af-4e4d-ad4a-a2454b72589a

**Comment by MotoLegacy** [comment]
Good catch, it looks like they're missing the waypoints required to drop down from the hole in the wall.

**Comment by MotoLegacy** [comment]
Making this a general waypoint issue

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/6fb41be229e3a76b21bfd7b250d446b6e5521898
