### ISSUE TITLE
[SUGGESTION] Bullet penetration

### ISSUE THREAD

**Issue by oStarist** [nzp-team/nzportable#359]
**Describe your suggestion**
Currently, only one zombie can get hit from the same bullet, causing you to only get 10 points per bullet, which can make building points a bit difficult

**Expected behavior**
Bullets would penetrate only 2 zombies, as a result hitting 3 at a time to allow for better building of points

**Comment by MotoLegacy** [comment]
Already available in-game, just bugged in FTE. Tracked in #142
