### ISSUE TITLE
Face Button Look on PSP doesn't modify Look Sensitivity

### ISSUE THREAD

**Issue by masterpl4n** [nzp-team/nzportable#363]
**Describe your suggestion**
For Stick To Move on PSP, look movement is slower when ADS than regular.

**Expected behavior**
When aiming down sights with button controls for looking the look movement is slowed a bit.

**Additional context**
And also maybe fix Stick to Move, it’d be pretty cool 👍

**Comment by Naievil** [comment]
I did this on GP. We should implement a similar sensitivity. I think it would be a lot more fun.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/dquakeplus/commit/077a809f23992bb10360a34d2a721f36ea386782
