### ISSUE TITLE
Gyro is always on when set to ADS only

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#364]
**Describe the bug**

When Gyro is set to ADS only it's always active

**To Reproduce**
- go to options and turn Gyro to ADS only
- go to the game
- move the console along multiple axi in 3d space

**Expected behavior**
I'd expect gyro to only be on when holding the ADS button

**Screenshots/Footage**

N/A

**Tested Platforms**

- PS Vita

**Comment by MotoLegacy** [comment]
Please avoid text like "it's self explanatory" and "wiggle it around". Thanks.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakespasm/commit/8ad380f6b34941a09165c778a3e6dbf104403767
