### ISSUE TITLE
Question: Unrelated to Development

### ISSUE THREAD

**Issue by Bhood23** [nzp-team/nzportable#366]
On the github page, What is this map called and where can i get it?
https://github.com/nzp-team/nzportable/blob/main/screenshots/4.webp

**Comment by Bhood23** [comment]
It looks similar to "FIVE" but i dont know where I can download it... I have been searching all over google but found nothing.

**Comment by MotoLegacy** [comment]
Yes this is FIVE. Unreleased officially at the moment. I have the first floor completed with half of the War Room following. Some game adjustments need pursued before it can be finished (proper elevators..). 

In the future, please contain queries like this in Discussions and not in Issues. Thanks!

**Comment by Bhood23** [comment]
> Yes this is FIVE. Unreleased officially at the moment. I have the first floor completed with half of the War Room following. Some game adjustments need pursued before it can be finished (proper elevators..).
> 
> In the future, please contain queries like this in Discussions and not in Issues. Thanks!

Thanks for your fast reply!
Cant wait for FIVE to come out!
