### ISSUE TITLE
Raygun Triggers Betties

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#368]
**Describe the bug**
shooting the raygun at a betty directly or splash will trigger the betty to activate.

**To Reproduce**
1. go to any map that has bouncing betties.
2. get raygun and betties
3. put down a betty
4. shoot at it

**Expected behavior**
raygun should not trigger bouncing betties

**Affected Platforms**
# Tested on Browser

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/925662c384fc7473a3711d9f80b0ae4ead2fa76c
