### ISSUE TITLE
Bouncing Betties hurt the player

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#369]
**Describe the bug**
the bouncing betties hurt the player if it explodes near them.

**To Reproduce**
1. go the any map that has bouncing betties
2. get bouncing betties
3. place bouncing betties
4. stand next to or on top of. and wait for it to explode

**Expected behavior**
in CoD the betties don't hurt the player.

**Video**
https://www.xbox.com/play/media/5ZBZL95BBR

**Affected Platforms**
# Tested on Browser

**Comment by MotoLegacy** [comment]
Can you provide a video demonstrating the player's immunity to bouncing betty damage?

**Comment by Revnova** [comment]
posted video link of WaW

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/bf4afd4ae34a31d4e963fe8a7a2f188ebab8c147
