### ISSUE TITLE
[PSP/PC] Parity difference with map start text

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#37]
The text that shows up on the bottom left is slightly different for PC and PSP despite being the same map file.

PC:
![image](https://user-images.githubusercontent.com/29164668/175815644-63662992-662a-4695-9ce8-4e1237748c0f.png)

PSP:
![image](https://user-images.githubusercontent.com/29164668/175815665-c9243e5c-cc40-450a-a600-9e5d21154e44.png)

worldspawn entity fields:
![image](https://user-images.githubusercontent.com/29164668/175815727-c47d2d70-cf65-4069-8074-b18092e55f5e.png)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/cded49861ef4f6f5a8a5cc455ab35cb85db28407
