### ISSUE TITLE
Player Can Run Over Crawlers

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#370]
**Describe the bug**
the player is able to run over crawlers. 

**To Reproduce**
1. just play any map like normal.
2. get a crawler
3. try to run through them

**Expected behavior**
the player should only be able to jump over zombies. not run over them.

**Affected Platforms**
# Tested on Browser

**Comment by TBOINDSI** [comment]
you get trapped on top of its collision on psp, youre lucky if you get pushed out of its hitbox

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/5333722dec970dc80eba7d5657187f103356eec3
