### ISSUE TITLE
Mule Kick Not Always Removing 3rd Weapon

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#372]
**Describe the bug**
Mule kick doesn't always remove the 3rd gun. if you have the 3rd gun out when you go down it removes one of the two guns you had before getting the 3rd gun. i think buying betties or bowie can sometimes cause this too when you have a 3rd weapon.

**To Reproduce**
1. go to a map with Mule Kick
2. obtain weapons
3. obtain Mule Kick and a third weapon
4. hold 3rd weapon as you get downed

**Expected behavior**
should only and always remove the weapon in 3rd slot

**Affected Platforms**
# Tested on Browser

**Additional context**
it made me lose the Waffe in a run when i was trying to get a good 3rd weapon out of the box :zentreSoSad:

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/1f3280a10fb461212df5fcb9854e7c08ba1acb53
