### ISSUE TITLE
Colt M1911 cant be upgraded on psp 

### ISSUE THREAD

**Issue by botnumber3** [nzp-team/nzportable#375]
**Describe the bug**

When trying to upgrade the colt m1911 the game crashes and takes me to the main menu I tested it 3 times on different maps

**To Reproduce**
1. Load into any map
2. Save up enough points
3. Get to pack a punch
4. Upgrade colt m1911

**Expected behavior**

When trying to pack a punch the colt m1911 the game continues to play out normally 

 
**Affected Platforms**

PSP GO

**Additional context**

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/4057357c423f5aa5c9a1d5c54be1bc1100dc5971
