### ISSUE TITLE
issues when running 2 maps in 1 session

### ISSUE THREAD

**Issue by masterpl4n** [nzp-team/nzportable#376]
Basically, if I play on more than one map in a single session, issues will start occurring. I’m guessing they are RAM related.
These are listed below:
- Game freezes and PSP turns off when loading models
- Zombies turn gray, or some zombies are pitch black with only a tv static looking texture on their arm
- Game freezes and psp turns off during gameplay
- Zombies bob up and down into the ground when breaking barriers
**To Reproduce**
1. Play Nacht or F4LL for a bit
2. Die or exit and switch to another map (like Nacht or F4LL)
3. Wait a bit, or don’t, it might occur immediately
4. (Maybe) see some errors

**Screenshots/Footage**
![IMG_0534](https://github.com/nzp-team/nzportable/assets/143304484/8733863e-e36d-40bb-8010-8a3d610fde65)

https://github.com/nzp-team/nzportable/assets/143304484/30a3acad-1880-42c3-bd80-9c3e88642cfa

https://github.com/nzp-team/nzportable/assets/143304484/58bc6448-bf0a-4bc9-8afe-593bb0944f78

**Affected Platforms**
No issues on anything but PSP 1K. Don’t have any other models, PC and web work fine, and my Vita version is broken but nothing seems to work improperly on it.

**Comment by masterpl4n** [comment]
Also, this happens when using the flamethrower and spinning the mystery box at the same time I believe 
![IMG_0689](https://github.com/nzp-team/nzportable/assets/143304484/cd2a7d04-be60-4f0f-84f3-8d7ae4060b56)

**Comment by TBOINDSI** [comment]
3001 does this too, and still

**Comment by TBOINDSI** [comment]
when i posted that, i was either on latest or one version behind
