### ISSUE TITLE
Ballistic Knives Wall Buy

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#377]
**Describe the bug**
when you have two weapons and are switching one out for the ballistic knives from a wall buy, it won't immediately remove the weapon you had out. instead you have to change weapons and then it will remove the weapon you originally were gonna drop.

**To Reproduce**
1. Go to firing range
2. buy two weapons
3. buy ballistic knives
4. see original gun still there
5. press button for changing weapons

**Expected behavior**
should work like other wall buys where it immediately switches out the gun on hand

**Affected Platforms**
# Tested on Browser

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/56567d7e30e8b0b3c7b716a16b894d24db3698b0
(NOtE: this doesnt add proper ballistic knife support, just fills in necessary defs to make it not 100% broken)
