### ISSUE TITLE
PaP Temporarily Breaks ADS 

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#378]
**Describe the bug**
when you PaP a gun and try to ADS with the other gun you have while the gun is being PaPed, the ADS will be very off center

**To Reproduce**
1. go to any map with PaP
2. get two guns and enough points to PaP
3. use PaP
4. try to ADS with other weapon
5. see it off center

**Expected behavior**
ADS should always be center

**Affected Platforms**
# Tested on Browser

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/c659a649f9e95af5441100f308ca07513626ff2b
