### ISSUE TITLE
Reloading a Sniper While Scoped

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#379]
**Describe the bug**
Reloading a sniper while scoped in will zoom out the camera very slowly

**To Reproduce**
1. Go to to any map with a sniper
2. buy the sniper
3. scope in and shoot
4. reload while still scoped
5. see camera zoom out slowly

**Expected behavior**
the camera should be immediately zoomed out like if you were to unscope normally.

**Affected Platforms**
# Tested on Browser

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/ce93ef1d2dfcda36127456996197bb3d95a3576e
