### ISSUE TITLE
[SERVER] Wunderwaffe crashes game

### ISSUE THREAD

**Issue by bignoobus** [nzp-team/nzportable#38]
Sometimes while shooting the wunderwaffe at a group of zombies, large or not, the game will crash

The Wunderwaffe isn't supposed to crash the game

 Only tested in FTEQW (windows) so far

**Comment by MotoLegacy** [comment]
I've been unable to reproduce this since changes I've made to `W_Fire()`. It's possible the commits there have fixed this. I'm going to close this issue and if it arises again we can re-open it.
