### ISSUE TITLE
Low Ammo Message

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#380]
**Describe the bug**
the **Low Ammo** message appears when you still have enough ammo in reserve. in WaW. it only shows when there's now ammo in reserve. and the current mag/clip is actually low on ammo

**To Reproduce**
1. Go to any map
2. use up most of your ammo until you're on your 2nd to last mag/clip
3. use more ammo until the **Low Ammo** message appears

**Expected behavior**
**Low Ammo** message should only show if you're on the absolute end of your ammo

**Screenshots/Footage**
![image](https://github.com/nzp-team/nzportable/assets/34180180/26408e28-e1a0-41a2-ac38-5c1303947b47)
![image](https://github.com/nzp-team/nzportable/assets/34180180/160bf2e7-a131-43c1-baf7-38e832ce6eb5)
![image](https://github.com/nzp-team/nzportable/assets/34180180/ccf716eb-093f-4426-a060-8e1316a41359)
![image](https://github.com/nzp-team/nzportable/assets/34180180/614c7162-5a7a-49af-a80d-8f693afc3c54)

**Affected Platforms**
# Tested on Browser

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/4e88aa404aaa9c1351305137d28356a2b3f9ae30
