### ISSUE TITLE
Cannot perform any actions after PaP

### ISSUE THREAD

**Issue by botnumber3** [nzp-team/nzportable#381]
**Describe the bug**
Once I PaP I can no longer run or buy anything like perks,guns,ect.

**To Reproduce**
1. Load into any map
2. Buy doors to PaP
3. Gain 5000 points 
4. PaP

**Expected behavior**
Once I PaP I can still buy perks,guns,ammo, doors, and have the ability to run instead of just walking

**Affected Platforms**
PSP GO

**Additional context**
This only happens after PaP not before and its with any weapon on any map

**Comment by SilentShadows77** [comment]
Omw me too! I play on web gl

**Comment by SilentShadows77** [comment]
It allows me to mbox though

**Comment by LexiAshe** [comment]
Just adding to this, have been able to replicate on PSP, Vita and PC

**Comment by TBOINDSI** [comment]
psp 3001 64mb. 
cannot; run, prone, buy wall chalks, perks, ammo.
can; buy pap, box, walls, aim, fire, walk, crouch, uncrouch, grenade, swap weapon, reload, jump, pick up powerups, perks still function

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/1f3280a10fb461212df5fcb9854e7c08ba1acb53
