### ISSUE TITLE
Mustang and sally ammo using the same ammo for quick revive

### ISSUE THREAD

**Issue by botnumber3** [nzp-team/nzportable#382]
**Describe the bug**
When using PaP mustang and sally while alive once out of ammo I found that ammo is also depleted when gone down with quick revive.

**To Reproduce**
1. Buy quick revive
2. Upgrade colt m1911
3. Use all ammunition 
4. Go down 

**Expected behavior**
When I go down with quick revive it shouldn't use the ammo I already have with my current mustang and sally but have a separate set.

**Affected Platforms**
PSP GO

**Additional context**
This only happens once you already have mustang and sally while alive

**Comment by MotoLegacy** [comment]
Can you provide proof from Call of Duty: Black Ops that its not supposed to take ammo from the standard obtained Mustang & Sally? Every other weapon the player obtains has this behavior in Black Ops, so I am unsure why M&S could be a unique case.

**Comment by botnumber3** [comment]
Black ops has this feature though. I used all the ammo I had of my M&S then downed myself. When i went down the pistols reloaded with the quick revive I had so like I said it should do the same here if y'all are tryna replicate the game unless thats what y'all are going for.

**Comment by MotoLegacy** [comment]
I asked if you could provide any proof (i.e. video evidence) of Mustang & Sally not using inventory ammo when in Last Stand on Solo in Black Ops and instead you send a nothing message. Yes, parity is important and integral to this project, however I can't just take random people at their word, I either need to investigate myself in the off time or rely on a reporter to show me concretely if there is anti-parity behavior.

Please be respectful, and read what I provide. If you aren't willing to just send something like a video back, just leave it be and someone else or myself will. 

Thanks.

**Comment by botnumber3** [comment]
https://github.com/nzp-team/nzportable/assets/136146372/b7e59121-5c95-4ae1-81f9-a116da36b2c5

Is this enough proof or would like the coding files as well?
