### ISSUE TITLE
Sniper FOV

### ISSUE THREAD

**Issue by TheSubPlayer** [nzp-team/nzportable#383]
**Describe the bug**
1 - The viewmodel's fov don't change (only the kar98 scope changes normally)
2 - Aiming with scope resets the fov to minimum, breaking the viewmodel's visibility.

**To Reproduce**
1. Take the scoped kar98 and another gun
2. Change the fov value
3. Aim with a scoped weapon
4. Tadaaaaaa
5. Change the fov again

**Expected behavior**
1 - The viewmodel should adjust to the fov
2 - The kar98's scope should align with the weapon
3 - The fov shouldn't reset after aiming with a scoped weapon

**Screenshots/Footage**

https://youtu.be/z00n2inwshA?si=FxOCzrpL9rWUkG2i

**Affected Platforms**
PSP

# Please also make note of any platforms you DID NOT test on.

- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/bf3a5f835516f7415195247c4442c75f98493cb8 and https://github.com/nzp-team/dquakeplus/commit/60103d3bb33048973e3b2df76f0b1ca3c74b574b
