### ISSUE TITLE
bug on Map Christmas Special

### ISSUE THREAD

**Issue by MuzakyGood** [nzp-team/nzportable#384]
# [PSP] [BUG]
**Describe the bug**
When in this area all zombies will be silent and not move, only happens on Map Christmas Special

**To Reproduce**
Steps :
1. Play on Map Special Christmas
2. Walking Towards Electric Power
3. Bug Only Occurs in That Area
4. See error (NextPatchingFind Failure)

**Screenshots/Footage**
![Screenshot_20230928_075623_PPSSPP Gold](https://github.com/nzp-team/nzportable/assets/112367361/bfc06e70-08da-4a0e-9eba-7424053289df)

**Platform :**
PSP

**Addition :**
Hopefully you can fix this bug :D

**Comment by MotoLegacy** [comment]
#355
