### ISSUE TITLE
Analog nub move/look toggle

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#386]
**Describe the bug**
I'm unable to toggle cnub aiming on/off on the most recent 3ds version of the game

Which leads to me being unable to play the game at all

**To Reproduce**
1. Open the game into a map
2. Check how the controls are layed out (Circle pad movement by default)
3. Check the settings for options

**Expected behavior**
I'd expect to have an option to toggle between the two control settings in the settings 

**Screenshots/Footage**

Image of the game version 

![IMG_20230930_222145.jpg](https://github.com/nzp-team/nzportable/assets/13917665/ebbc7c48-856e-4c2a-abb0-92e04c64a5c2)

Sorry the video is too large to show on here directly

https://youtu.be/bmKY_cSUuPI?si=PTmCXFYWFx-yoUpj

**Affected Platforms**

- Nintendo 3DS New

Haven't tested old

**Additional context**

I'm pretty sure there was an option at some point to toggle it, but it went missing at some point, I could be wrong on this

Also, it was mentioned in issue #337

**Comment by MotoLegacy** [comment]
User clarified this is only an issue because of faulty hardware.
