### ISSUE TITLE
MP3 Stream Loop

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#388]
After playing the music easter egg song once, it then started playing the song again. Regular music, like the Round Start/End themes also began playing again beneath it.

https://github.com/nzp-team/nzportable/assets/139988968/54404445-eaf9-4051-9c08-e5068422e640

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/33dc5e3c9f6c49a0abf759845d5d8b6752a5ac14
