### ISSUE TITLE
[SERVER] Lack of support for other player spawn points in Solo

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#39]
when using the Info_Player_doctor/taeko etc. you spawn at what appears to be the origin and you fall forever

**To Reproduce**
1. make a map with the 4 info_player_* entities
2. compile and run the map 

**Expected behavior**
you spawn in one of the 4 specified locations

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/13917665/177421822-aed4888b-426a-42ae-a981-80b15c5ac9bb.png)
![image](https://user-images.githubusercontent.com/13917665/177421896-c89ae8d4-4ed5-472b-a573-30d0dc48aa6a.png)

**Affected Platforms:**
Only tested on FTEQW

**Additional context**
yeet

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/29f3ca484921b43cb2826b61c1b96df4b0646bdf
