### ISSUE TITLE
[SUGGESTION] Coop Lobby on PC/WebGL

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#390]
**Describe your suggestion**
just think it'd be helpful if there was a lobby system for coop. i know its not priority. but coop is another big part of zombies in my opinion. and having a working lobby would probably help people load maps together instead of having someone start the match. and then the other person having to wait for next round and stop host from being able to buy quick revive when they start.

**Expected behavior**
a lobby system where players can connect before a match has started and wait for the host to pick a map. 

**Screenshots/Footage**
![image](https://github.com/nzp-team/nzportable/assets/34180180/cf57295d-0ccb-4f53-babb-0a6c6df133f4)
![image](https://github.com/nzp-team/nzportable/assets/34180180/fb006f25-eaf8-44a6-86d4-0d69d2963e20)

**Comment by MotoLegacy** [comment]
I'm going to close this since as already stated co-op is already a priority and this would also be a must feature for it to be seen as completed.
