### ISSUE TITLE
Waypointing soft crashes game

### ISSUE THREAD

**Issue by masterpl4n** [nzp-team/nzportable#392]
When trying to make a waypoint on a custom map, the game will restart. Re-entering the custom map after this happens makes the game run faster, which is unintentionally funny as hell

**To Reproduce**
Open a custom map
Enter console command Impulse 100, and try placing a waypoint.
Press start, then go back into the map. The zombies are now superspeed 

**Expected behavior**

Waypoints work as usual

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.

Tested on PSP 1000 model and PPSSPP

**Additional context**

**Comment by masterpl4n** [comment]
As

**Comment by TBOINDSI** [comment]
on psp 3001 64mb.
the title image turns into a light blue placeholder image with "sky" on it after i hit start?
textures were replaced with wad data what?
this is freaky but i cant record right now.
yeah its super fucking fast, like FAST what>?!?!?/1/?!

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/c14e2345bdda6de711f5af7ece900077c7e00e6a
