### ISSUE TITLE
Crosshairs show when you ADS

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#393]
**Describe the bug**
when you ADS, you can still see you crosshairs.

**To Reproduce**
1. go to any map of your choice
2. Aim Down Sight
3. see that the crosshairs still show.

**Expected behavior**
Crosshairs should be hidden whenever you ADS

**Screenshots/Footage**
![image](https://github.com/nzp-team/nzportable/assets/34180180/4f9aa663-e7ee-47e5-8617-836d519c923e)

**Affected Platforms**
# Tested on PC

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/979611e9e14b4e2ddb9b3e590fa9f28628cf0b68
