### ISSUE TITLE
Explosions hurt you through walls

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#394]
**Describe the bug**
Explosions hurt you through walls. barrels and grenades.

**To Reproduce**
1. go to any map with thin-ish walls that you can access from front and back.
2. throw a grenade to one side.
3. run back to the other side before it explodes.
4. get hurt by explosion.

**Expected behavior**
explosions should not be able to hurt you through walls at all. it should work as cover.

**Screenshots/Footage**
![downbybarrel](https://github.com/nzp-team/nzportable/assets/34180180/7a4e8a95-bb68-4bfe-9395-acfaa6fc3048)
![downbygrenade](https://github.com/nzp-team/nzportable/assets/34180180/b4db3dce-0346-4b72-a9c1-586375149a4f)

**Affected Platforms**
# Tested on PC

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/5caf23cf4abafd0aa3f0ab824de0db283842e72b
