### ISSUE TITLE
PaP duplicates gun

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#396]
**Describe the bug**
while i'm using Pack a Punch, i still have the gun that i'm pack-a-punching

**To Reproduce**
1. Go to any map with Pack a Punch
2. use Pack a Punch
3. see that you're still holding the gun that you put in Pack a Punch

**Expected behavior**
you should be holding your second weapon while PaP is working

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/34180180/bf22de7e-7589-4b61-a7d1-eeb322c8763a

https://github.com/nzp-team/nzportable/assets/34180180/51f6148d-ed21-46dc-9a21-8c3968f9e9fd

**Affected Platforms**
# Tested on PC

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/e58ffeb60acc2929fc6e31c71da4919573b11e2b
