### ISSUE TITLE
Can't Get PaPed Weapon

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#397]
**Describe the bug**
i'm not able to pick up my weapon i fed into Pack-a-Punch.

**To Reproduce**
1. Go to any map with a Pack-a-Punch Machine
2. Get enough points to use it
3. attempt to pick up gun

**Expected behavior**
should be able to pick up gun after PaPing it.

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/34180180/e34a35a4-260d-4b49-b5c6-d7fd2b108b0b

https://github.com/nzp-team/nzportable/assets/34180180/0ee3831c-9ffd-4a4b-a924-d2be9503cd84

**Affected Platforms**
# Tested on PC

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/6fe33b26d9f50edc4ab58ff5e2b9e4cf746e0999
