### ISSUE TITLE
[SUGGESTION] Add Wii support

### ISSUE THREAD

**Issue by WebSnke** [nzp-team/nzportable#398]
**Describe your suggestion**
I suggest adding support for the Nintendo Wii.

**Additional context**
I would love to work on this issue but I am not that familiar with porting to other platforms.

**Comment by TBOINDSI** [comment]
tru booting into some other OS or emulator on the wii, try it out and lose braincells, im trying it on ps2 linux lmao,

**Comment by MotoLegacy** [comment]
Port recommendations are better suited to [Discussions](https://github.com/nzp-team/nzportable/discussions) (see https://github.com/nzp-team/nzportable/discussions/365 and https://github.com/nzp-team/nzportable/discussions/385). Feel free to open up a Discussion thread about this there, that way you can engage with more people about this idea and running the project under more obscure architectures. Thanks!
