### ISSUE TITLE
Old Nintendo 3ds is all pixels and unreadable 

### ISSUE THREAD

**Issue by Ellis243454** [nzp-team/nzportable#399]
Describe the bug
To put it simply every texture seems to be downgraded a lot and every bit of text is unreadable 

To Reproduce
1. Update the game 
2. Load the game 

Expected behavior
Should look all pixelated 

Screenshots/Footage
![2023-10-20_16-12-25 164_top](https://github.com/nzp-team/nzportable/assets/132875822/0e12ae06-07bf-4193-9901-225398fe0959)
![2023-10-20_16-12-31 891_top](https://github.com/nzp-team/nzportable/assets/132875822/4717c634-ecd0-4952-98e8-24272c47f795)
![2023-10-20_16-12-50 479_top](https://github.com/nzp-team/nzportable/assets/132875822/aa3b6e3f-9e3c-4181-ac47-60ab328e7744)
![2023-10-20_16-13-21 989_top](https://github.com/nzp-team/nzportable/assets/132875822/94d66236-9e85-4354-8cd1-41fac882da87)

Affected Platforms

- Nintendo 3DS (Old)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/glquake/commit/bf47e38936f93a14c1aac2487de5b95bfa61516f
