### ISSUE TITLE
Broken skyboxes on Christmas Special and Warehouse

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#401]
Tested on the 64mb version of NZP running through Adrenaline on Vita. With the latest update, skyboxes are now broken on Xmas Special and Warehouse. This issue persisted between reboots. No special steps required to replicate, happened as soon as I loaded in on Xmas Special.
![vlcsnap-2023-10-23-14h32m34s373](https://github.com/nzp-team/nzportable/assets/139988968/8d71f869-d757-4892-a504-632792cbd8f0)
![vlcsnap-2023-10-23-14h32m22s782](https://github.com/nzp-team/nzportable/assets/139988968/43c12109-57a1-44dd-8649-b685a4331ef4)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/dquakeplus/commit/b50603d1b6e2b21fb8791ce2f7426c163bc68a2b
