### ISSUE TITLE
Crosshair doesn't reappear after reloading left weapon

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#403]
**Describe the bug**
when you have a dual wield weapon, and you reload just the left one, the crosshair doesn't reappear until you interact with the right one

**To Reproduce**
1. get Mustang and sally
2. fire just the left one
3. reload the left one
4. the crosshair shouldn't reappear until you fire the right weapon

**Expected behavior**
I'd expect the crosshair to reappear after the reload animation is finished

**Screenshots/Footage**

[Youtube link](https://youtu.be/-VJPhLdRQa4)

**Affected Platforms**

-PSP
-FTE

I believe this is a server bug and will happen on all platforms

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/206120f01e376caca768749a338c8f322e332d2f
