### ISSUE TITLE
New chandlier prop

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#406]
**Describe the bug**
the model for the kino Chandelier doesn't have transparency at all. there's orange-ish looking areas in the model.

**To Reproduce**
1. Go to the map Kino
2. look up at the Chandelier
3. notice that it does not transparent

**Expected behavior**
there should not be huge orange-ish spaces in the model.

**Screenshots/Footage**
![image](https://github.com/nzp-team/nzportable/assets/34180180/b1b3b126-45a1-4b28-9946-90add31b01c1)
![image](https://github.com/nzp-team/nzportable/assets/34180180/b0166241-e85d-49e0-9340-9fb17d091fa7)

**Affected Platforms**
# Tested on PC

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/3f2060a149e92e9d4bb8fab73a21b4d7929c213d https://github.com/nzp-team/quakec/commit/053906edebdff782be923ca38fd8c6c3499d255f
