### ISSUE TITLE
Zombie pathfinding randomly breaks during gameplay

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#408]
Have tested on NDU, Temple and Warehouse. Randomly, often once per round, the zombie pathfinding will break, causing all currently spawned in-map zombies to ignore the player and walk towards origin. They will still swipe when close, but won't return to regular pathfinding.

No steps to recreate, happened at random.

https://github.com/nzp-team/nzportable/assets/139988968/520c084c-26b7-4db2-8d32-ba4b5a7dfab2

https://github.com/nzp-team/nzportable/assets/139988968/c2c04366-efb2-4ef5-af25-e611e3bfe725

https://github.com/nzp-team/nzportable/assets/139988968/9ba61e19-d458-492c-ac94-4b8d83d50d52

**Comment by 0xLLUUKKEE** [comment]
this bug is also present on the 3ds version

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakespasm/commit/e9f3139f0e0e9e82b4d34b95bd246390163264de

**Comment by DerpedCrusader** [comment]
This also happens on 3ds
