### ISSUE TITLE
3ds hard crashes when loading most maps

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#410]
**Describe the bug**
3ds hard crashes when loading most maps, including but not limited to warehouse, Christmas special, boxxer, warehouse 

**To Reproduce**
1. Load into warehouse or above listed map
2. See error

**Expected behavior**
The game would load

**Affected Platforms**

- Nintendo 3DS New

.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/assets/commit/8d1d6e660048c514e855143062b059445bad8092
