### ISSUE TITLE
Dual Weilding Left gun reload stutter

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#412]
**Describe the bug**
When you are reloading specifically the left gun, and then you fire the right one (it doesn't work the other way around) the left gun stutters during its animation, causing it to take longer

**To Reproduce**
1. load into any map
2. use console command `give 28` to spawn mustang and sally
3. reload the left gun and fire the right gun during the animation

**Expected behavior**
The reload would carry on as normal 

**Screenshots/Footage**

[Youtube Link](https://youtu.be/E_ixnTMBiyA)

**Affected Platforms**

-FTE
-Vita

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/9d4e39c0cbb40f5c348d7481ea7a2b2551b23855
