### ISSUE TITLE
Make Vita Auto-updator optional

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#418]
**Describe your suggestion**
Ask the user if they want to download the update 

I think this could work well in one of two ways

1. Basic Yes or No

2. A "Starting update" text, with a timer, and let the user cancel the update process 

**Expected behavior**
When you boot the game up on your vita, you'd be given the option to either update right now, or do it later

**Additional context**
Sometimes you only have a few minutes to play, taking the dog out to potty,

Yes you can just turn off WiFi and reboot, but it can be annoying to do so if I only have a brief moment to play, and then I leave it off, and I'm accidentally 3 days out of date

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakespasm/commit/c9d2fde12822fc60c3b2ebf80e3e2c874ae3faf3
