### ISSUE TITLE
[New 3ds, webgl] Zombies dont take damage when attacking through barrier

### ISSUE THREAD

**Issue by SilentShadows77** [nzp-team/nzportable#419]
**To Reproduce**
1. Go to any map barrier
2. Let zomboi attack you
3. Try to shoot zomboi 

**Expected behavior**
Shots hit, deal damage, and show red and hit marks in crosshair.

Happens as tested on new 3ds xl and webgl versions.

Additionally, the zombie will deal damage a lot faster (due to animation cooldown?) and with what seems like one animation but it most likely a looped animation that looks like one long animation. In all I think the zombie attack from a barrier should be fixed all around.

**Comment by MotoLegacy** [comment]
Can't reproduce. Video attached.

https://github.com/nzp-team/nzportable/assets/26030250/6406e1bb-7c82-4a30-ae1e-0061f7748bc8
