### ISSUE TITLE
[FTEQW] No hlrendermodes for most entities

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#42]
**Describe the bug**
only 1 of the func brushes becomes transparent when given rendermode 5

**To Reproduce**

1. place a brush
2. make func_brush or func_door_nzp
3. change the rendermode to value 5 (translucent) and renderment around 200ish
4. compile and whatever

**Expected behavior**
the brush becomes translucent

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/13917665/178082551-85d37e58-132a-4f07-8d3f-cbdd7aabaa9b.png)
![image](https://user-images.githubusercontent.com/13917665/178082566-525fe8ef-f97e-4976-86ba-41e8044ebb08.png)

**Affected Platforms:**
tested on FTEQW

**Additional context**

**Comment by MotoLegacy** [comment]
Fixed in https://github.com/nzp-team/quakec/commit/216d6124a4bad994dfaf5628b045de6298b072e9
