### ISSUE TITLE
[Webgl (coop)] death in coop leaves 2nd+ player stuck and frozen

### ISSUE THREAD

**Issue by SilentShadows77** [nzp-team/nzportable#421]
Playing coop I joined another person and died, then they died reviving me. Afterword, the 1st player disappeared and I was stuck in downed position, but walk animations could play. Sometimes the end screen wouldnt appear and once the audio went very quiet. This could be because the server terminates the host but bot the joiners. 

Player should also dissapear and see end screen with full audio and background should be normal.

Tried and tested several times on webgl coop.

**Comment by MotoLegacy** [comment]
This description makes no sense. Feel free to re-open this issue if you actually follow the template and give a concise description so I know what you're talking about.
