### ISSUE TITLE
[Webgl] command "nzp_maxai" doesnt exist

### ISSUE THREAD

**Issue by SilentShadows77** [nzp-team/nzportable#422]
Iirc the update log thing said this was added but when I go to the console it is not a command option and doesnt work when I put it in anyway.

It should (most likely) exist

Webgl

**Comment by MotoLegacy** [comment]
As the post describes, `nzp_maxai` is not a "command"/cvar. It is a builtin used by non-FTE (not PC) to determine max zombie count at once.
