### ISSUE TITLE
[All platforms] command demands

### ISSUE THREAD

**Issue by SilentShadows77** [nzp-team/nzportable#423]
Some simple QoL bits for the console would be to organize commands so that it is easy to find them (show all commands, have similar commands with similar root words so it is easy to find commands that are similar, and a command to give player money and/or activate God mode)

 All platforms

**Comment by MotoLegacy** [comment]
FTE features `find` which you can use to parse commands. A lot of your desired "cheats" originate from Quake, so it is out of scope for me to list them here. Additionally, the source code documents any special "cheat" (debug) commands here:

https://github.com/nzp-team/quakec/blob/9866a529b07f48d0662b774d643591c181aa6937/source/server/utilities/command_parser.qc#L197
