### ISSUE TITLE
Flamethrower Makes You Infinitely Melee

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#425]
**Describe the bug**
when you have the flamethrower equipped, then knife. the animation for knifing loops forever until you swap to your other gun or shoot.

**To Reproduce**
1. Go to a map that has the M2 Flamethrower
2. Obtain the M2 Flamethrower
3. with the M2 Flamethrower in your hands. try to knife/melee

**Expected behavior**
it should go back to the M2 Flamethrower after you knife

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/34180180/272221db-b663-45c2-9449-29e02e4a8759

**Affected Platforms**
# only tested on PC

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/bcc6131f2eeee9de7088cb7c3aeb17c68c15df45
