### ISSUE TITLE
The Ammo Box doesnt work they way its supposed to.

### ISSUE THREAD

**Issue by Laser327** [nzp-team/nzportable#426]
**Describe the Bug**
Ammo Box gives you ammo, but instead of doing it as its supposed to, instead you buy it once every frame and on 60Fps it results in a very loud alarm-like noise (And you also dont even obtain ammo from it either, it only SHOWS that it gives you ammo but its just a decoy).

**To Reproduce**
How to Re-Produce it:

1. Go to a map that has a ammo box in it
2. Shoot with your weapon to lose some ammo
3. Try to buy ammo

**Expected Behaviour**
Ammo box should give you full ammo.

**Screenshot/Footage**

https://github.com/nzp-team/nzportable/assets/83584785/55c4fdce-c08f-4464-b18e-aa366fb323d1

**Affected Platforms**
Only tested on PSVita Version (Model PCH-110x A.K.A OLED 3G Model)

**Comment by MotoLegacy** [comment]
Can you confirm you are on the latest version? (Turn on WiFi to use the VITA's Auto Update feature). This was already reported and marked fixed in #415. Thanks.

**Comment by MotoLegacy** [comment]
Tested and confirmed this was fixed.
