### ISSUE TITLE
View skin for weapons overrides Perk-A-Cola bottles

### ISSUE THREAD

**Issue by MotoLegacy** [nzp-team/nzportable#427]
**Describe the bug**
QuakeC currently overrides `self.weaponskin` with `self.weapons[0].weapon_skin`, so when purchasing a Perk-A-Cola, the skin index of your current weapon is always used instead. Only applies to `STANDARD` progs.

**Comment by Laser327** [comment]
Yea i noticed and as a result now every Perk-a-Cola uses Quick Revive's Bottle texture no matter what.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/c8e5a75ed956b3ce058868cb373576e7e22f7c7f
