### ISSUE TITLE
[New 3ds] the lower screen butrons dont work well

### ISSUE THREAD

**Issue by SilentShadows77** [nzp-team/nzportable#429]
Simply put the lower screen buttons are interfered by the fact that the lower screen also works to look around by dragging the lower screen, so when you try pressing a button it moves the camera and rarely toggles the button.

What should happen: the lower screen should not be used for looking around or have a toggle for such a use to allow the buttons to work properly.

How to do it
Load any map
Try pressing button
Unless you're really quick, the button won't work and the player will be looking around (usually ends looking up)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/glquake/commit/8ce113ecaa9ddfad1a3118442f67e0a156f981ed
