### ISSUE TITLE
[SERVER] Double Tap does not reduce pump/bolt time

### ISSUE THREAD

**Issue by bignoobus** [nzp-team/nzportable#43]
If you buy Double Tap in nzpr, it will double your bullets' dmg, but it wont increase the fire rate
The expected behavior is that it would also increase the fire rate by 33% along side the double bullet dmg

I have not tested on any device other than psp and windows

Video of bug or missing feature in question

https://user-images.githubusercontent.com/105007743/178082912-997a7787-027d-432f-8161-c1035aa50989.mp4

unimportant note *ignore if you wish*
the video has some jaw dropping quality for my standards

**Comment by bignoobus** [comment]
word is double tap also causes the waffe to crash the game apparently

**Comment by MotoLegacy** [comment]
Edited title to reflect correct problem at hand.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/9e8293b2eb6a1a499284431036baf65b6357b4b2
