### ISSUE TITLE
MOVETYPE_PUSH with a non-bsp model

### ISSUE THREAD

**Issue by twylightproto** [nzp-team/nzportable#430]
When playing getting hit (probably nearing death) I get the error in the title, freezing my N3dsXL completely, requiring a full power off.

**Comment by TBOINDSI** [comment]
this used to exist on psp a month ago but is now fixed, odd that its swapped its platform victim lmao

**Comment by DerpedCrusader** [comment]
Please follow the included template when creating issues

**Comment by twylightproto** [comment]
Lmao

> this used to exist on psp a month ago but is now fixed, odd that its swapped its platform victim lmao

Lmao

**Comment by twylightproto** [comment]
> Please follow the included template to the best of your ability when creating issues

Alright, I'll keep it in mind.

**Comment by MotoLegacy** [comment]
Presumably fixed in https://github.com/nzp-team/quakec/commit/847556d5f1873acf50a8cd73e91fb79c622cf7bb, feel free to re-open if incorrect.
