### ISSUE TITLE
Max Ammo Makes You Reload

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#431]
**Describe the bug**
when you pick up a max ammo. and your gun has some spent bullets in the magazine/clip. you will automatically start reloading.

**To Reproduce**
1. just play any map like usual until a max ammo spawns
2. check that your gun has spent bullets in the magazine/clip
3. pick up the max ammo
4. notice that you automatically start reloading

**Expected behavior**
it should not make you reload when you pick up a max ammo

**Screenshots/Footage**
![Maxammo](https://github.com/nzp-team/nzportable/assets/34180180/baecdc69-348b-44ac-b88c-fdc6e31abdd4)

**Affected Platforms**
# Tested on PC and PSP

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/c18c1c126140588b71ee70e07321951078e434a8
