### ISSUE TITLE
incorrectly auto-places MP spawn

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#433]
**Describe the bug**
The script that auto-places a spawn for the player spawned inside a wall in a test map i'm working on

**To Reproduce**
1. Download [this map](https://github.com/nzp-team/nzportable/files/13300169/dogtest.zip) and run it 
2. restart until you spawn inside a wall

**Expected behavior**
the script would find a safe place for me to spawn

**Screenshots/Footage**

![image](https://github.com/nzp-team/nzportable/assets/13917665/c827aeec-4a6d-4195-a814-12fe60a8a0a8)

**Affected Platforms**

-FTE

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/9593c550d6c58ad47156780dfe60527272ec420f
