### ISSUE TITLE
Teddy bear EE music doesn't play on WebGL

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#434]
**Describe the bug**
On webGL, when shooting the teddy bears, specifically on the House map (for reproducing purposes), when you shoot all 3, the song doesn't play

**To Reproduce**
1. Load Up the map House
2. Shoot 3 teddy bears
3. the music should play, but doesn't 

**Expected behavior**
I would expect the music to play out

**Affected Platforms**

WebGL

**Additional context**
This does appear to be WebGL specific, it seems to play fine on FTE

**Comment by SilentShadows77** [comment]
I played house today and the music did play out, it started a few seconds after I killed the teddy tho so there was a small delay
