### ISSUE TITLE
Team rockets do team damage when also damaging other things

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#435]
**Describe the bug**
When the all explosives (Grenades, Rockets, Mustang/Sally explostions, and Betties when the host places them(?)) damage either a player or a zombie nearby teammates can receive explosion damage as well as team damage

**To Reproduce**
1. go to Firing range test map
2.  have one player get an explosive weapon
3. have a second player stand near a zombie
4. player one shoots between player 2 and zombie with splash damage
5. player two takes team damage

**Expected behavior**
I would expect the teammate to not take any damage from friendly explosives

**Screenshots/Footage**

The other player (Shout out to Revnova) is saying when they do/don't take damage

https://github.com/nzp-team/nzportable/assets/13917665/83aa59eb-308b-4d3e-ae79-b7f7002ce98a

https://github.com/nzp-team/nzportable/assets/13917665/e57e5621-07a7-4f8e-8ccc-18c2199f94aa

**Affected Platforms**

Only tested on FTE, but is likely a server issue

**Additional context**
The betties didn't seem to damage the host when placed by a second player (client) but host betties would damage other players (clients), which might be in relation to issue #369

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/30de102ee30fc347167537b34c09ddf3291004b7

**Comment by DerpedCrusader** [comment]
https://github.com/nzp-team/nzportable/assets/13917665/2a9983c0-31dc-465b-a3a1-78dbeb4a6d09

reproduced using same reproduction steps as seen above

**Comment by MotoLegacy** [comment]
No, what occurred is you reported two separate issues into one unknowingly, with two separate reproduction steps. The initial reported bug was solved, as evident by this clip:

https://github.com/nzp-team/nzportable/assets/26030250/c05444db-9e81-44ed-866a-8e3d46a54f01

Please, in the future, if two items seem only half related, report them separately as to avoid this from occurring again. REGARDLESS, the separate bug you have re-opened this issue to report has been resolved in https://github.com/nzp-team/quakec/commit/4be7dbcce610ca4d2323478b46d1247435905c21
