### ISSUE TITLE
World renders in front of sky brushes

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#44]
**Describe the bug**
brushed loaded behind a sky brush draw in front of the sky brush

**To Reproduce**

1. make a map with a sky brush, with brushes behind them
2. compile map
3. observe

**Expected behavior**
the sky should be rendered in full, without seeing stuff in the background

**Screenshots/Footage**
![image](https://user-images.githubusercontent.com/13917665/178083193-e67e4acf-70c3-422c-8ee0-6e3d3219c78c.png)

**Affected Platforms:**

Affected: FTEQW, PSP
 
doesn't affect Vita, NX

**Additional context**
This technically isn't a guaranteed feature in every engine, but i was told it should be for NZP

**Comment by MotoLegacy** [comment]
Fixed in FTEQW with https://github.com/nzp-team/assets/commit/3db20b4a0420ad5a8b1e9a7303b8c500ddb8cf80; PSP fix still absent.

**Comment by MotoLegacy** [comment]
With the considerably more efficient skybox implementation on all other platforms, this unfortunately is not possible anymore, sorry :(

**Comment by DerpedCrusader** [comment]
Any chance we could instead make it consistent on all platforms then?

Because there's some benefits to having stuff behind sky brushes render
