### ISSUE TITLE
[FTE] Settings never get saved

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#442]
# When giving your report a title, please prepend a [LABEL], example [LABEL]s include:
# [SERVER] (for game code), [CLIENT] (for HUD elements or other client side stuff),
# [PSP/3DS/NX/VITA/FTE] (for engine based code specific to the platform).
# If related to CO-OP, prepend "CO-OP/" to the label, (e.g. [CO-OP/SERVER]).
**Describe the bug**
Settings never get saved

**To Reproduce**
1. Adjust settings
2. Exit
3. Restart
4. Settings are default again

**Expected behavior**
I expected the settings to save.

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
Make sure you're on the latest version. Also please re-open this issue when you learn how the template works, thanks!
