### ISSUE TITLE
Sprint Timing

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#444]
**Describe the bug**
I can sprint non stop

**To Reproduce**
1. Start a game
2. Sprint

**Expected behavior**
I expected to have a break.

**Affected Platforms**
PC

**Comment by MotoLegacy** [comment]
Not sure why you closed this issue. Re-opened and will investigate later today.

**Comment by McNuttGaming2** [comment]
> Not sure why you closed this issue. Re-opened and will investigate later today.

Actually, I think it was on an older version.

**Comment by McNuttGaming2** [comment]
It happens randomly

**Comment by MotoLegacy** [comment]
After some testing I've concluded this is non-reproducable/notabug. I've been unable to get an "indefinite" sprint duration and timings seem in line with Call of Duty (4 seconds maximum, 8 with Stamin-Up). Closing.
