### ISSUE TITLE
Ray Gun crosshair spread

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#445]
**Describe your suggestion**
Improve the crosshair by changing size or look.

**Expected behavior**
-crosshair of ray gun is too big and it shouldnt change size too much by moving
-crosshair of waffe is too small
-crosshair of ballistic knife needs to look different (maybe a dot and 2 lines) or make it smaller, its easy to miss the target

**Comment by MotoLegacy** [comment]
I'm not going to touch the Ballistic Knife crosshair as the weapon as a whole isn't in a finished/working state. However I've adjusted the size of the Circle crosshair (for the wunderwaffe) in https://github.com/nzp-team/quakec/commit/7271e93337fe95af0c27229381c4cb65ca4976dd and I'll investigate the spread of the Ray Gun later.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/37d963980f74f825dd6fe80973e2bd3270f5b28c
