### ISSUE TITLE
[SUGGESTION]Double Barrel Alt Fire

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#446]
**Describe your suggestion**
would be super cool if the double barrel shotguns had an alt fire where it lets you shoot both barrels at once. kinda like Killing Floor 2 does it. or make it a select fire type thing

**Expected behavior**
Shoots both barrels combining damage.

**Additional context**
being able to fire both barrels would probably be a bit OP. but it would cost more ammo in return in my opinion. it'd probably make the PaPed Sawed Off even more stronger now that i think about it.

**Comment by MotoLegacy** [comment]
This is a neat idea but sorta out of scope for the project and also doesn't really have a good way to select between your fire mods like you suggest. Controls are a huge limitation for unique features
