### ISSUE TITLE
[FTE] Waffe reloads instantly

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#447]
**Describe the bug**
The waffe reloads instantly.

**To Reproduce**
1. Start a game
2. Get the waffe
3. Reload

**Expected behavior**
I expected it to reload after switch on animation starts.

**Screenshots/Footage**
https://www.mediafire.com/file/bf8z10d303me5qy/waffe+bug.mp4/file

**Affected Platforms**
PC

**Comment by MotoLegacy** [comment]
changed to when the tubes are inserted to match world at war https://github.com/nzp-team/quakec/commit/5e0a9af0ade7d7d51f0c0688c237004e591116f6
