### ISSUE TITLE
[SUGGESTION]Max Ammo Refills Current Mag

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#448]
**Describe your suggestion**
Just like Black Ops 4, Cold War, and Vanguard. i would like if Max Ammo also refilled the current magazine of all weapons so that you can just pick up max ammo without waiting for someone to reload.

**Expected behavior**
Max Ammo refills both Magazine and Stock

**Screenshots/Footage**
from the [wiki](https://callofduty.fandom.com/wiki/Max_Ammo#:~:text=Finding%20Max%20Ammo,must%20touch%20the%20power-up.)
![image](https://github.com/nzp-team/nzportable/assets/34180180/1958fbe4-b642-42d4-bac3-9bad63d75531)

**Additional context**
this would be for quality of life i think.

**Comment by MotoLegacy** [comment]
Planned for NZD
