### ISSUE TITLE
[SUGGESTION] Winters howl

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#449]
**Describe your suggestion**
Add winters howl, there was a freeze powerup once where zombies turned into ice, maybe implement it as a weapon. It would be nice to have another wonder weapon and I think it would be the most realistic way to add one.

**Expected behavior**
Just having the freeze effect would be nice but there is no need for a model (maybe use the 357 as a placeholder?)

**Comment by MotoLegacy** [comment]
This project primarily targets World at War. Please don't suggest out of scope additions.
