### ISSUE TITLE
Broken zombie waypointing after loading new map

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#451]
After playing one map and loading a new one, the zombies pathfinding will break.

To reproduce, play a bit of one map, exit to menu and load into a new map.

![vlcsnap-2023-11-15-17h26m56s046](https://github.com/nzp-team/nzportable/assets/139988968/38c74fc6-6c19-49ab-a3b2-e625cb671d21)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakespasm/commit/e9f3139f0e0e9e82b4d34b95bd246390163264de
