### ISSUE TITLE
Broken fog effect after dog round

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#452]
After a dog round finishes, fog doesn't reset to how it should be.

**To Reproduce**
1. Load up Bunker Defence
2. Fight dogs
3. Fog doesnt restore correctly

**Expected behavior**
Not to have fog misbehave

![vlcsnap-2023-11-15-17h26m09s540](https://github.com/nzp-team/nzportable/assets/139988968/f32b33b7-cc8c-48f3-a174-36e8c1be86cb)

Bunker Defence - Before dogs

![vlcsnap-2023-11-15-17h26m25s409](https://github.com/nzp-team/nzportable/assets/139988968/20f6c5a2-3750-4151-be41-b1f8d2c22312)

Bunker Defence - During dogs

![vlcsnap-2023-11-15-17h26m31s426](https://github.com/nzp-team/nzportable/assets/139988968/7f895fda-af88-4f28-8008-a6fb5151e43c)

Bunker Defence - After dogs

**Comment by MotoLegacy** [comment]
Edited for clarity and obscenity

**Comment by MotoLegacy** [comment]
I'm not able to reproduce this at all, please re-open if clearer reproduction steps are discovered!
