### ISSUE TITLE
[SUGGESTION] Jump sound

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#454]
**Describe your suggestion**
Hearing huh everytime you jump can be annoying, especially in coop. Imo it would fit better if its played when dolphin diving (like how it is in cod).

**Expected behavior**
Play the jump sound when dolphin diving.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/6a955e322d28c08490b239137f42c2f155b6a5df
