### ISSUE TITLE
Documentation on doors and zombie spawns

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#456]
**Describe your suggestion**
I feel like documentation on doors, and specifically how doors triggering zombie spawns, and  setting zombies in other rooms to start inactive

Probably should be tied into referencing that player spawns can now target zombie spawns to activate them

**Comment by MotoLegacy** [comment]
I plan to write a section specifically on Zombie active/inactive states when the zone-esq system is completed. `func_door_*` firing targets on open is out of scope (general Quake functionality), however I did add a section to player spawns noting that they now fire targets on use: https://docs.nzp.gay/mapping/player-spawns#targeting

Considered completed.
