### ISSUE TITLE
func_door_nzp Targetname

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#457]
**Describe the bug**
Giving a func_door_nzp entity a targetname will make the door unusable.

**To Reproduce**
1. in a map editor, give a func_door_nzp a targetname.
2. compile the map
3. go to that door in game
4. see that the door is unusable now

**Expected behavior**
should be able to use door as normal.

**Screenshots/Footage**
![func_door_nzp](https://github.com/nzp-team/nzportable/assets/34180180/51a6a450-bbdc-44a9-8a73-a9aa7d81c2b4)
![image](https://github.com/nzp-team/nzportable/assets/34180180/01cfd318-510a-4dfc-85d0-a488c420db64)

**Affected Platforms**
# Tested on PC.

**Comment by MotoLegacy** [comment]
Technically, not a bug:
```
"targetname" if set, no touch field will be spawned and a remote button or trigger field activates the door.```

As such, I've added this as an enhancement instead under the assumption that if it has an associated cost, it MUST be touched to trigger.

https://github.com/nzp-team/quakec/commit/31fcb8270eaf07efa2a22a72b6650c406f508cb0
