### ISSUE TITLE
Panzerschrek clips through camera when ADS

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#458]
When aiming down sights with the Panzerschrek on Vita, it comes too close, causing part of the sight to clip through the camera.

![vlcsnap-2023-11-16-15h07m08s106](https://github.com/nzp-team/nzportable/assets/139988968/9e3211ed-075f-40dd-86f8-f7a4db65f0a3)

**Comment by MotoLegacy** [comment]
Not able to reproduce with latest commit, feel free to re-open is more complicated steps are discovered/this isn't fixed.
