### ISSUE TITLE
[SERVER] Easter Egg Teddy doesn't play sound effects

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#46]
**Describe the bug**
When placing a teddy_spawn for easter eggs, you're given an option for a noise option, it doesn't seem to play at all when shot, which i *believe* is the intended behavior

**To Reproduce**

1. Make a map, place a teddy_spawn entity
2. change the `noise` setting to point to a .wav file (i think mine should work)
3. shoot the lad
4. no sound

**Expected behavior**
I would assume that when the teddy bear is shot, a noise would play

**Screenshots/Footage**
included map example:
![image](https://user-images.githubusercontent.com/13917665/178166867-fece7f5f-a519-4cae-b9f5-d3efcf763de6.png)

https://user-images.githubusercontent.com/13917665/178167324-7fee2a32-ba6f-49b8-888c-1e44b939b8ff.mp4

my personal map (turned volume up to see if that was the issue)
![image](https://user-images.githubusercontent.com/13917665/178167356-6fb1a47e-919c-47ab-9550-a7637962c87f.png)

https://user-images.githubusercontent.com/13917665/178167375-7f73e5d6-48c1-426f-89f0-cb8e29badec9.mp4

**Affected Platforms:**
- FTEQW (Windows, Mac, Linux, etc)

I didn't test on any other platforms

**Additional context**
I don't know if this is intended behavior, but i hope not, as i think it'd be very amusing

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/5df73e8431af8fb83e22ece06dd0b0b47989ecda

**Comment by DerpedCrusader** [comment]
https://user-images.githubusercontent.com/13917665/216474980-c2b2f248-3e8f-4aeb-9f83-5952597a7cc2.mp4

tested with volume 100, 1, and no volume command at all, it's not working at all


https://user-images.githubusercontent.com/13917665/216475384-a0688ef5-d6ae-44e7-8a9a-5a793cdf83d5.mp4

i can confirm that the sound works in engine in this clip

**Comment by MotoLegacy** [comment]
problem wasn't that the sound wasn't playing — the teddy was removed so the sound was subsequently stopped immediately. fixed with https://github.com/nzp-team/quakec/commit/4ce1beb29e0d5b02cfdbf00f39f672906ed06bd8
