### ISSUE TITLE
[FTE] Unlimited sprinting still

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#460]
**Describe the bug**
I can sprint non stop.

**To Reproduce**
1. Start a game
2. Sprint

**Expected behavior**
I expected a break.

**Screenshots/Footage**
https://www.mediafire.com/file/610t8anjem4fpsi/sprinting.mp4/file

**Affected Platforms**
PC

**Additional context**
Not making it up

**Comment by MotoLegacy** [comment]
I can't reproduce this even with a simulated low framerate and packet loss. Please don't reopen again unless you can identify some difference in causality. Video attached.

https://github.com/nzp-team/nzportable/assets/26030250/cc1b3f92-dd75-4184-91c0-b51223ca9313
