### ISSUE TITLE
[FTE] Prone shooting

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#461]
**Describe the bug**
If you are shooting while prone, you will move fast.

**To Reproduce**
1. Start a game
2. Go prone
3. Shoot and move

**Expected behavior**
I expected to not be able to move while being prone and shooting.

**Affected Platforms**
PC

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/e768f285300527880180d0a02c6b81ad77cc9ed5
