### ISSUE TITLE
Land sound while walking downstairs

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#462]
**Describe the bug**
The land sound is repeated while walking downstairs which is annoying, it should be silent. Perhaps it can be fixed by increasing the height to trigger the sound?

**To Reproduce**
1. Start a game
2. Go downstairs

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/8701eb45e10be82ede6779714fafd1291a179cc4
