### ISSUE TITLE
Running animation

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#463]
**Describe the bug**
Running animation
The running animation stops if you switch your weapon while running

**To Reproduce**
1. Start a game
2. Run
3. Switch weapon

**Expected behavior**
I expected to see the running animation

**Comment by DerpedCrusader** [comment]
Animation blending isn't supported by quake MDL, 

We might be able to look into this when IQM is implemented

**Comment by DerpedCrusader** [comment]
User clarified off platform this was about view models, and not 3rd person animations (which he had been posting about off platform)

**Comment by MotoLegacy** [comment]
Can't reproduce.

https://github.com/nzp-team/nzportable/assets/26030250/27ab2f74-ddfe-45c7-9765-dc66cd612c26
