### ISSUE TITLE
Gibbing one part gibs all parts

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#466]
**Describe the bug**
When you gib 1 body part, it gibs all of them

**To Reproduce**
1. Get the m1a1
2. Shoot arms/head
3. All gubbable parts gib

**Expected behavior**
Just the limb you shot should gib

**Screenshots/Footage**

[YouTube link](https://youtu.be/tEKyU7T8qvM?si=obDNyeW8rNIIUkaD)

**Affected Platforms**

- Nintendo 3DS (Old, New)

**Comment by DerpedCrusader** [comment]
They seem to get sent to world origin, this is visible on house and hangar

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/glquake/commit/faed910a9c7e2c31141821dc607b500ce58ddced
