### ISSUE TITLE
[SUGGESTION] Ideas for achievements

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#467]
**Describe your suggestion**
Add rewards for completing some or all achievements like a new map that was greyed out or a pap skin.
Add leaderboards for achievements and highest rounds (or speed runs something like quickest round 100, since psp crashes a lot).

**Comment by MotoLegacy** [comment]
I very much support an open filesystem — no hidden or unexposed items, as this project aims for transparency. We already have leaderboards tracked via Discussions too.
