### ISSUE TITLE
[VITA/NX] Sprinting enables Gyroscope when it's set to ADS Only

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#47]
**Describe the bug**
While running, the Gyroscope aiming gets enabled from spriting, when its only supposed to be enabled during ADS

**To Reproduce**

1. go to `control settings`
2. enable gyroscope, and set it to `ADS only`
3. go in game and walk forward
4. press down to start sprinting, and violently shake your vita like it owes you lunch money

**Expected behavior**
the gyroscope shouldn't enable while sprinting

**Screenshots/Footage**
sorry its a youtube video
https://youtube.com/shorts/0Kwp_AaFuf0?feature=share

**Affected Platforms:**
I tested on VITA, due to its similarity to switch, it might want to be tested on that as well, but i don't have one ready at the moment

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakespasm/commit/18a5ae1fb91998513851758078f48c4d9cbf33eb
