### ISSUE TITLE
Music Easter eggs crash the game

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#472]
**Describe the bug**
Maps hangar and house both crashed with their teddy bear music EEs

**To Reproduce**
1. Play hangar
2. Shoot the teddy bears
3. crash

**Expected behavior**
The music should play

**Affected Platforms**

- Nintendo 3DS (Old, New)

This is the only platform I've had it happen on

**Comment by MotoLegacy** [comment]
Going to re-open it — regardless of its lack of a finished implementation crashing is definitely an issue

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/glquake/commit/6164c42ce3a2387bb07a452ea143b9698fb7d1d7
