### ISSUE TITLE
Zombies stop following waypoints occasionally 

### ISSUE THREAD

**Issue by tyleryoung88** [nzp-team/nzportable#478]
**Describe the bug**

Zombies occasionally lose their waypoint path and walk towards world origin. This seems to be specific to handheld waypoint system. 

**To Reproduce**

1. Go to any map on any handheld platform
2. Play the game until round 7 or 8
3. Observe that you now have to hunt zombies down every round 
4. Cry

**Expected behavior**

We should expect the zombies to always choose and follow waypoint paths, or fallback to a new plan if stuck in the same position for too long. 

**Screenshots/Footage**

![2023-11-23-112046](https://github.com/nzp-team/nzportable/assets/7098194/dc624f78-37ce-45f8-a375-734b29c640b6)
![2023-11-23-112012](https://github.com/nzp-team/nzportable/assets/7098194/dab074a4-dd18-42d8-9084-bbbad072d3e5)
![2023-11-23-111603](https://github.com/nzp-team/nzportable/assets/7098194/5ff847ee-7464-40f0-a4fc-3b2329ae07d5)
![2023-11-23-111535](https://github.com/nzp-team/nzportable/assets/7098194/27fb0dce-370c-4500-8eaf-1bc259362837)
![2023-11-23-111903](https://github.com/nzp-team/nzportable/assets/7098194/0449acdf-5bfb-4cdd-933a-db5f6e11b9b6)

**Affected Platforms**

All handheld consoles which exclusively use waypoints for AI 

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional context**
N/A

**Comment by DerpedCrusader** [comment]
This started occurring on this commit 

https://github.com/nzp-team/quakec/commit/7b0c11586a4453074bb68547c9376d84ce1fb7d1

it does not occur on this commit

https://github.com/nzp-team/quakec/commit/835fdcb1e262c1bf939fc0c69b3bab3a6241aefa

testing methodology:
booting up ndu, playing until around round 3/4 open the "help" door, and hang out in the second room, but frequently popping into spawn room to check out the corners in front of the curved stairs, and infront of Mulekick (twoards world origin) if i haven't found any stuck zombies after round 6, I've assumed it's worked 

I'll usually find a stuck zombie anywhere between round 3-4, so i've been doing end of round 6 "just in case"

**Comment by MotoLegacy** [comment]
Thanks to your diligence in testing, we have finally been able to fix this. https://github.com/nzp-team/quakespasm/commit/d1200a3956281509fb9df6ee76db92292bdff725 https://github.com/nzp-team/dquakeplus/commit/8bc298bfb61f4faaf77e2616c84796b9e295c935 https://github.com/nzp-team/glquake/commit/b147b1d68164c30b71dd0a88096bbb205e0f7b28
