### ISSUE TITLE
[SUGGESTION] Improve teleportation

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#479]
**Describe your suggestion**
-Add a lightning, then a black screen while teleporting.
-Add a teleportation and link sound.
-You get fall damage after teleporting
Teleportating is lame without any effects.

**Comment by MotoLegacy** [comment]
One of these is a duplicate of an issue you've already made (#455). Why did you post again? Feel free to re-open fall damage as a bug report. And sounds as a new suggestion.
