### ISSUE TITLE
[FTEQW] G-Sync causes unexpected behavior

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#48]
**Describe the bug**
when starting the game with G-Sync enabled, some weird stuff occurs, like gl_blendsprites being turned off, and weird frame interpolation

the interpolation errors only happen when above 60hz

**To Reproduce**

1. turn on G-sync
2. run the game

**Expected behavior**

you'd expect it to be like any other frame rate cap or limiter, where it caps it around the refreshrate (which it does at 60hz)

and to leave certain commands uneffected

**Screenshots/Footage**
in this footage, the application on the right was started up *without* G-Sync enabled, and the one on the left was started *with* G-Sync enabled, as indicated by the icon in the top right corner of the application

the only command i entered was show_fps to make give proof to everything working properly

https://user-images.githubusercontent.com/13917665/178315456-66e3512f-af4b-4c5b-aa74-72b02f8fb62e.mp4

**Affected Platforms:**

- FTEQW (Windows, Mac, Linux, etc)

**Additional context**
I don't know if this is something than can be fixed, I'd say for the time being, try to find a way to disable G-Sync specifically for NZP, and it should run smooth as butter

**Comment by MotoLegacy** [comment]
Can you take another video with G-Sync enabled and `show_fps` set to `2`? Is this problem alleviated when fullscreen is enabled? This may be an nVidia issue ultimately, according to Spike.

**Comment by DerpedCrusader** [comment]
It is alleviated when fullscreen is enabled

heres what it looks like with `show_fps 2`

https://user-images.githubusercontent.com/13917665/178596082-0edca95d-ad5f-41fc-bf56-72c7b76cfbec.mp4

also... some other... weird oddity...

**Comment by MotoLegacy** [comment]
Going to close this as it's better suited being posted on the FTE repo: https://github.com/fte-team/fteqw. You can probably use the same footage and most of the same details there and get an actual fix.
