### ISSUE TITLE
[SUGGESTION] Separate dog sounds

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#480]
**Describe your suggestion**
We have 8 sounds for attacking zombies, 8 for dying, 10 for walking and 10 for running.

I think it would be better, if all zombie sounds are kept at 8 and if the new memory is used for other sounds like new sounds for dogs (die, spawn and taunt), the regular sounds can be used as a placeholder so we can use our own sounds in advance

Imo it sounds out of place if dogs use the same sounds as zombies.

**Comment by MotoLegacy** [comment]
Dogs don't use existing Zombies sounds. They're unique already.
