### ISSUE TITLE
Teleportation sound effects

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#482]
**Describe your suggestion**
-Add a teleportation and link sound.

**Comment by MotoLegacy** [comment]
Edited to again only specify sounds. #455. The lightning effect is the same. The "black screen" is a level creator teleporting the player to a box and then to the destination. Thanks for listening to me.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/da75f77d3b82c357e1eb550b7d648337f2282a9f
