### ISSUE TITLE
[FTE] Wrong perk bottle textures

### ISSUE THREAD

**Issue by McNuttGaming2** [nzp-team/nzportable#484]
**Describe the bug**
Since the last update, the perk bottles have the wrong texture.
It is either quick revive or juggernog.

**To Reproduce**
1. Start a game
2. Buy a perk
3. See perk bottle with wrong texture

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/nzportable/assets/26030250/3e5e277b-0ca8-4ac3-8afe-48dc95bdde8d

Clean download of today's build. Can't reproduce.
