### ISSUE TITLE
Raygun crosshair

### ISSUE THREAD

**Issue by TheRebreathing** [nzp-team/nzportable#487]
**Describe the bug**
Raygun crosshair
for some reason the raygun crosshair jumps after shooting and after switching the weapon it reverts back to normal.

**To Reproduce**
1. Get the raygun
2. Shoot
3. Move
4. See crosshair jumping

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/ee349fcc6cbe8fccb0abb3733e3ec1a4a1be2ad5
