### ISSUE TITLE
the game does not start

### ISSUE THREAD

**Issue by Anviic** [nzp-team/nzportable#49]
# When giving your report a title, please append a [LABEL], example [LABEL]s include:
# [PSP], [NX] (Nintendo Switch), [VITA], [SERVER] (for game code), [CSQC] (for PC hud or viewmodel stuff), [MENU] (for PC menu)
# If related to CO-OP,  append "CO-OP/" to the label, (e.g. [CO-OP/SERVER].

**Describe the bug**

I have an error when starting the game on switch, when I start it it closes and returns me to the hombrew menu, I checked the folder on the sd card and an error appeared telling me that I did not have enough memory when I have on the sd card available 20gb

https://user-images.githubusercontent.com/110195327/181614994-f0242d6d-3fa5-4fad-be1e-644bd1e7c125.MOV

**To Reproduce**

**Expected behavior**

**Screenshots/Footage**
If applicable, add screenshots or video to help explain your problem.

**Affected Platforms:**

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch
- FTEQW (Windows, Mac, Linux, etc)

**Additional context**

**Comment by DerpedCrusader** [comment]
Please read the readme/install directions 

You're currently in applet mode, which doesn't give the game enough memory 

You must open the homebrew menu by holding the R button on an installed title, and you should be able to run it just fine

**Comment by Anviic** [comment]
Thank you very much, although now I got an error when opening any map (Host_Error: PR_LoadProgs: Couldn´t Load Progs.dat)
