### ISSUE TITLE
Invalid Selection in the Map Selection Menu crash

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#491]
**Describe the bug**
Selecting an invalid selection due to an empty Menu of the maps and trying to start it crashes the PS Vita back to the Live Area.

**To Reproduce**
1. Go fill up only 1 Menu of maps. (Maybe unneeded)
2. Go to the next menu.
3. Unselect „Next Menu“.
4. Press X.
5. Crash.

**Expected behavior**
Starting the Invalid Selection should do nothing or put you to the main menu to avoid issues.

**Screenshots/Footage**
Got none sorry.

**Affected Platforms:**

- PS Vita

# Please make note of any platforms you DID NOT test on.

- Nintendo Switch

**Unneeded Comment**
Add any unnecessary and unwanted Comment about the problem here.

This reminds me a lot about #67!

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakespasm/commit/2545fffde31c03fd0ce4997ac8b9fdf84ecec1a3
