### ISSUE TITLE
Add a round timer

### ISSUE THREAD

**Issue by turbiG** [nzp-team/nzportable#494]
**Describe your suggestion**
I would like to have a round timer in the game.

**Expected behavior**
It should appear below the normal timer, start counting on round start and go back to 00:00:00 on round end.

**Screenshots/Footage**
(https://cdn.discordapp.com/attachments/1021404849042112606/1179953556439183490/image.png?ex=657ba862&is=65693362&hm=06fb4c8a60fa7edb4a333c762778fd25b56979b9c85107c5e390e38045e75ad3&) It's not the exact same font but you get me.

**Additional context**
I would like it to be white instead of yellow.

**Comment by MotoLegacy** [comment]
`scr_serverstopwatch 2` to enable: https://github.com/nzp-team/quakec/commit/c5a401418158a6cfc0db8468e25b79e465d6ccad
