### ISSUE TITLE
Perk machine clip brush removal 

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#496]
**Describe your suggestion**
When a perk machine is used up, and it disappears, it's clip brush stays behind

I think a way to fix this is to make the clip brushes similar to how teddy bears used to work

The mapper would have the perk machine target the clip brush, and it'd disappear when the perk machine does

**Comment by MotoLegacy** [comment]
This is not possible, clips are not like triggers, they are not entities and don't exist in the world.

**Comment by DerpedCrusader** [comment]
you can make any brush, including one with a clip texture into an entity

this is no different than buying an nzp door (which you can make using clip textures)

**Comment by DerpedCrusader** [comment]
that's crazy

![image](https://github.com/nzp-team/nzportable/assets/13917665/9a8ac207-1655-4ecf-9a17-63386b06ba94)



https://github.com/nzp-team/nzportable/assets/13917665/261fbd08-08e1-4ce8-affb-c3aa2089342e

**Comment by MotoLegacy** [comment]
Considering the discussion that occurred here, I'm considering this implemented in https://github.com/nzp-team/quakec/commit/a17b21151a72386d63dc570f6b941f618a8a6570. Note also that you can now do this plus all the other fancy Quick Revive stuff (specific prices, leaving after amount of uses, starting on, all co-op and solo sensitive) in https://github.com/nzp-team/quakec/commit/ba2f2f225a7c2e2c8cdb36721b8fb25260309b73. Have a blast.
