### ISSUE TITLE
Allow specifying hostname on Create Game menu

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#499]
**Describe your suggestion**
i was thinking. what if you set the default hostname for PC/WebGL to say what platform people are playing on so its not confusing trying to find a server thats for PC and a server for WebGL through the server browser or the frag-net server list. since PC can't play with WebGL and reverse

**Expected behavior**
set a default hostname that tells what platform the server is being hosted on

**Screenshots/Footage**
![image](https://github.com/nzp-team/nzportable/assets/34180180/192f18f5-b034-48e5-a10e-0102b627ea1a)

**Additional context**
just like in the screenshot. but without the part after [PC]

**Comment by MotoLegacy** [comment]
The lack of compatibility between the two is a fixable problem, however I am happy to generally add a text box to specify server name.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/a3de55e07105f5a149393063c94005106c0dd375
