### ISSUE TITLE
[PC] Accidentally starts map when clicking custom map menu

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#5]
This issue has been present for a while but now the new organisation is set up, I might as well post it here.
Often times when I click the custom map menu, I accidentally load into the map that shows up in that spot even though I only click once.
Video attatched for demonstration purposes:

https://user-images.githubusercontent.com/29164668/163673747-1e6887f5-b823-42b7-8383-1a2495f7fe03.mp4

**Comment by MotoLegacy** [comment]
Closing as all potential menu issues will be addressed with https://github.com/nzp-team/nzportable/issues/7.
