### ISSUE TITLE
NDU: EE Song Not Playing

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#501]
**Describe the bug**
On Nacht Der Untoten. After exploding all explosive barrels. The easter egg won't trigger.

**To Reproduce**
1. Go to Nacht Der Untoten
2. As you play. explode all barrels on the map.
3. Notice that the Easter Egg Song hasn't triggered/played

**Expected behavior**
Easter Egg Song should play after exploding all explosive barrels.

**Affected Platforms**
# only tested on PC

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/ccfb80af205226225d052b32d5ddfad5f4a7cbc4
