### ISSUE TITLE
[All platforms?] Perk buy prompts are stingy and differ between perks/machines

### ISSUE THREAD

**Issue by SilentShadows77** [nzp-team/nzportable#508]
I couldn't decide whether to have this as a suggestion or a bug but I think its understood that it is less than intentional, so I lebeled it as a bug. I also understand that a previous update changed machine buy prompts so you have to be facing the machine. However, different machines have different tolerances to the player standing near them, for instance, the pack a punch will only let the play pap their weapon if they are facing the pap, and a specific distance back, while the speed cola will let the player buy it from much closer and looking more to the side than *perfectly* strait. I would like for the machines to be a little more lenient (like the speed cola machine) on purchases, allowing the player to look a little to the sides and purchase the machine while being very close to it, as some machines only let you buy them from a distance. If anything, could the machines all have the same or similar *rules* for lack of a better term, as to how you need to position yourself to buy the machine.

**To Reproduce**
1. Go to any machine
2. Move around and look around a bit to see what the preferences are for that machine to show the buy prompt
3. Go to another machine and do the same
4. Notice the preferences are different for each machine (mostly) 

**Expected behavior**
Each machine has the same or similar preferences to which the player must comply for the buy prompt to show, as well as the preferences to be slightly more lenient, to allow the player to "grab and go" and not have to fiddle with the stingy machine to get the prompt, within reason.
**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

**Affected Platforms**
For as much as I know, this is true for PC and WebGl, but most likely all systems.

**Additional context**
The mbox allow purchase while facing backwards, this may or may not be intentional.
Mbox is also generally stingy with prompts, having the player wait even after the box closes for the prompt to appear, also not sure if this is intentional. Sorry about the talk abt the mbox, it seemed close enough related to include as a sidenote.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/eaabc6b3a85dd0aec1e8c7619b84561c55d1d121
