### ISSUE TITLE
Zombies don't chase me, they all go to the same place and stay bugged

### ISSUE THREAD

**Issue by Anviic** [nzp-team/nzportable#51]
# When giving your report a title, please append a [LABEL], example [LABEL]s include:
# [PSP], [NX] (Nintendo Switch), [VITA], [SERVER] (for game code), [CSQC] (for PC hud or viewmodel stuff), [MENU] (for PC menu)
# If related to CO-OP,  append "CO-OP/" to the label, (e.g. [CO-OP/SERVER].

**Describe the bug**
Zombies don't chase me, they all go to the same place and stay bugged
happens to me on any map

**Screenshots/Footage**
If applicable, add screenshots or video to help explain your problem.

**Affected Platforms:**

# Please make note of any platforms you DID NOT test on.

- Nintendo [Switch]

https://user-images.githubusercontent.com/110195327/181794307-30f7238b-bc80-4367-ab08-f1903c87d051.mp4

**Comment by MotoLegacy** [comment]
This seems to be an issue of not having the waypoints in the map. There was a similar issue with them not pathfinding at all in Quakespasm, but this has been resolved. closing.
