### ISSUE TITLE
Firing range perks hard crash

### ISSUE THREAD

**Issue by Trickygamers** [nzp-team/nzportable#512]
(N2DSXL)When I load into the map I sprint to turn on power once on I sprint to the mule kick perk wile drinking the perk then turn to the right then it will crash also it will sometimes not work due to the perks eating the points and doing nothing

**Comment by Trickygamers** [comment]
Getting video recording

**Comment by MotoLegacy** [comment]
That video is private.

**Comment by Trickygamers** [comment]
crap I was going too fast and I did not have a device so I could not respond but the video is now unlisted insread f private.
