### ISSUE TITLE
Win32 Movement Inversion issue

### ISSUE THREAD

**Issue by InkPaw** [nzp-team/nzportable#519]
Tested on an IBM Thinkpad T42 (Pentium M model)
OS: Windows XP w/ SP2

**To Reproduce**
1. Open Single-Player on any map
2. Walk around for a little while, fight zombies for a minute or less
3. movement seems to invert itself for no particular reason
4. shit pants, hope it goes back to normal
5. it doesn't
6. you die, and remain upset

**Expected behavior**
Be able to move around just as I was on the win64 version of NZP

**Screenshots/Footage**
https://cdn.discordapp.com/attachments/1137940054682128425/1180931656253722714/IMG_0834.mov?ex=657f374f&is=656cc24f&hm=aa3b4320df400b249a27b43c5f57fd03e4b0313a676bc034373d2f053d096d59&

**Affected Platforms**
I've only experienced this on the win32 platform of NZP 

DID NOT TEST ON:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**
This seems to make nzp somewhat irritating to play on retro windows machines :( (( ( (

**Comment by MotoLegacy** [comment]
Hi, just to confirm, this is via our prebuilt nightlies and not an attempt to build FTEQW yourself?

**Comment by InkPaw** [comment]
> Hi, just to confirm, this is via our prebuilt nightlies and not an attempt to build FTEQW yourself?

Correct, If compiling it myself would somehow give me better luck, I'll try that some other time :)

**Comment by MotoLegacy** [comment]
Just wanted to see if it was a difference in build environment — thanks for the report, will investigate.

**Comment by MotoLegacy** [comment]
surprise! https://github.com/nzp-team/quakec/commit/6d9b976f2fe472c3ba1529a06229491a84195c59
