### ISSUE TITLE
Going down with mulekick takes all your guns

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#521]
**Describe the bug**
If you go down with mulekick and quick revive, and all 3 guns, when you go down and come back, it takes all your guns

**To Reproduce**
1. firing range
2. get mule kick, and quick revive
3. get 3 weapons,
4. go down
5. get up
6. see bug

**Expected behavior**
the void would consume the 3rd weapon, but you'd keep the other two

**Affected Platforms**

tested on
- FTEQW

but it believe its a server issue

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/57fb071bd5239f61fb1b2d9b4b3eb72dd47cf961
