### ISSUE TITLE
[SERVER] Jitter/Lag whenever jumping/moving

### ISSUE THREAD

**Issue by aimslut** [nzp-team/nzportable#522]
**Describe the bug**
The game either lags or jitters whenever you move, but moreso when you jump.

**To Reproduce**
1. Start any game, Solo/Co-Op ( Any map )
2. Movement lags ( doesn't matter which fps or graphical settings are being used, happens on every fps from 125-500 ( didn't test any lower ))

**Expected behavior**
Smoother gameplay

**Screenshots/Footage**
https://streamable.com/p1zj1u

**Affected Platforms**
Win x64 ( haven't tried 32-bit yet )

**Additional context**
Game would genuinely be a 10/10 otherwise 😭 (( i love it so much, thankyou for making it ♡ ))

**Comment by melatowonin** [comment]
same thing is happening to me 😭. version is also a fresh download/install of x64 windows

**Comment by MotoLegacy** [comment]
You're bunny hopping to increase velocity beyond what's recommended, and above what looks smooth with the server tick rate. Not a bug.

`sc_mintic` defines the time between server frames in seconds. If you want a more "hop-friendly" experience, you can lower the value, at the cost of performance and multiplayer fluidity.

**Comment by aimslut** [comment]
Could you suggest some sensible values?
I tried lowering it but it seemed to have no impact, thanks in advance

**Comment by MotoLegacy** [comment]
`0.033` would be a server update rate of 30Hz. Wouldn't suggest going any lower (higher?) online. `0` will have the server run "as fast as possible" (usually 72Hz). These are server controller variables, so if you're not the host, they aren't for you. Additionally, if you have more clients in session the match might need restarted. Hope this helps.

**Comment by aimslut** [comment]
Sadly I have a feeling it's a separate issue as it happens even without bunnyhopping at all, just sprinting, sorry for the confusion
https://streamable.com/3fw25f

**Comment by MotoLegacy** [comment]
And this is with a *clean* configuration file? I cannot reproduce any behaviors like this unless I turn on `sv_nqplayerphysics`, which we ship to `0` by default. You also have texture filtering set to linear, which is not the default (non-chunk pixels). I've attached a video.


https://github.com/nzp-team/nzportable/assets/26030250/9b5fa13e-15d7-48b1-8a6d-63b457a29ba4

**Comment by aimslut** [comment]
all I did was alter the settings within the game menus themselves, I haven't altered the configs at all otherwise ( except when trying `sv_mintic` like you suggested )

**Comment by aimslut** [comment]
`sv_nqplayerphysics` is set to 0, and gets worse when it's set to 1
This is the closest thing I can find to what I'm experiencing: https://github.com/fte-team/fteqw/issues/208

**Comment by MotoLegacy** [comment]
Makes sense why this would be a Windows-only issue then. Thanks for the shout — looks like I have to wait for a fix over there for me to pull from upstream.

**Comment by aimslut** [comment]
The issue doesn't occur if you cap your framerate to 72 ( Quake's native framerate ), but then it's _72 fps_ and I was hoping to record 360fps clips😭

**Comment by Paindeluxe** [comment]
> **Describe the bug** The game either lags or jitters whenever you move, but moreso when you jump.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Start any game, Solo/Co-Op ( Any map )
> 2. Movement lags ( doesn't matter which fps or graphical settings are being used, happens on every fps from 125-500 ( didn't test any lower ))
> 
> **Expected behavior** Smoother gameplay
> 
> **Screenshots/Footage** https://streamable.com/p1zj1u
> 
> **Affected Platforms** Win x64 ( haven't tried 32-bit yet )
> 
> **Additional context** Game would genuinely be a 10/10 otherwise 😭 (( i love it so much, thankyou for making it ♡ ))

I would like to add to this, the movement is slightly rubberbandy at around 26.0 to 26.9fps and really rubberbandy at 5fps (happens in Firing Range when the Zombies spam Pathfinding Error)
