### ISSUE TITLE
Firing range hard crash

### ISSUE THREAD

**Issue by Trickygamers** [nzp-team/nzportable#524]
Video https://youtube.com/shorts/vnyhNKB888Y

**Comment by Trickygamers** [comment]
don’t need to use power or perks to trigger crash.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/glquake/commit/9d29f00bc67f05bd7dfbb72e19fc9d6707dc0c59 https://github.com/nzp-team/dquakeplus/commit/b524455525793c1ad5daeaa5aab0a451b7a7f0b4
