### ISSUE TITLE
WebGL solo has sv_public enabled 

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#526]
**Describe the bug**
sv_public is still active by default on webGL builds of the game, which was fine and dandy when only some people knew how to connect, but now there's bad actors joining people's servers and being rude, and ruining their experience 

**To Reproduce**
1. Go to nzp.gay
2. Open a solo game
3. Go to frag-net.com/servers on another browser tab 
4. Connect to your server

**Expected behavior**
When the game is started in solo mode, no one should be able to connect 

**Affected Platforms**
- FTEQW WebGL

**Comment by MotoLegacy** [comment]
I've removed your derogatory comment from this issue, there is no place for that here. Additionally -- `sv_public` *is* off. But `sv_listen_qw` was on. Fixed that in https://github.com/nzp-team/quakec/commit/8980f74830a76c9cfe3211ec682fbd054618ce29
