### ISSUE TITLE
CRASHING AND ERRORS ON PSP 1000 . LATEST BUILD

### ISSUE THREAD

**Issue by TristenDon** [nzp-team/nzportable#528]
So I got a psp 1000 with cfw recently and ofc got nzp as I been a big fan since 2014 on my potato desktop with the beta 1.1 build 100s of custom maps . But anyways on my 1000 some maps like warehouse and a couple the custom maps can't really name them all but a lot the ones that came with the psp build , are crashing a lot and some are saying a pap machine error or something. Some maps load and just crash my whole system and cuts it off . Other than that a couple are playable 60 fps . And tips or ideas on why ?

![image](https://github.com/nzp-team/nzportable/assets/153771069/c0a4354d-d1a3-4f09-af1e-907b3c9df34e)

https://github.com/nzp-team/nzportable/assets/153771069/85100f4c-dd51-4a3a-a379-7021c3585e1a

**Comment by MotoLegacy** [comment]
Feel free to re-report whenever you want to not blatantly ignore the template created for bug reporting.

**Comment by TristenDon** [comment]
I'm sorry about that I'm new to this GitHub I didn't know how

**Comment by TristenDon** [comment]
Sorry about that I’m new to this GitHub so I didn’t know how to do it
correctly
