### ISSUE TITLE
[PSP] Map crashing 

### ISSUE THREAD

**Issue by TristenDon** [nzp-team/nzportable#529]
Maps crashing PSP 1K or not loading . Pap file error

https://github.com/nzp-team/nzportable/assets/153771069/719dda12-3afb-4a07-a754-c7fec9f71401

![image](https://github.com/nzp-team/nzportable/assets/153771069/8da8fb02-fe36-4555-871a-dd981092f690)

**Affected Platforms**

Only tested on psp1000

**Additional context**

So I got a psp 1000 with cfw recently and ofc got nzp as I been a big fan since 2014 on my potato desktop with the beta 1.1 build 100s of custom maps . But anyways on my 1000 some maps like warehouse and a couple the custom maps can't really name them all but a lot the ones that came with the psp build , are crashing a lot and some are saying a pap machine error or something. Some maps load and just crash my whole system and cuts it off . Other than that a couple are playable 60 fps . And tips or ideas on why ?

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/766d9423e1ae85db0c37fa741bccb67c185f053f

**Comment by TristenDon** [comment]
Ok thanks . What about the maps crashing tho and some just not working ?

**Comment by MotoLegacy** [comment]
According to what you've sent, that change is the fix, it will be rolled out in tomorrows update.

**Comment by TristenDon** [comment]
I appreciate it amazing team
