### ISSUE TITLE
Mystery box tp spot rotated 90 degrees

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#53]
Whenever the mystery box teleports to a new location, the rotation is off by 90 degrees.

**Expected behavior**
![image](https://user-images.githubusercontent.com/29164668/183120131-1a036fe3-fec8-403f-b02d-a09f8ab737eb.png)

**Actual Behaviour**
![fte-20220804214944-0](https://user-images.githubusercontent.com/29164668/183120271-2512ee91-15d7-4ddf-ae24-a9743b229af8.png)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/4b62411685f4e600c7299ee7551e1e13db22d01a
