### ISSUE TITLE
[BUG/SUGGESTION] Automatically kill leftover zombies after some time

### ISSUE THREAD

**Issue by jack5github** [nzp-team/nzportable#531]
**Describe your suggestion/Expected behaviour**
There is a possibility for zombies to become stuck behind walls near their spawn points, or for players to purposefully prolong the ends of rounds by leaving a single crawler alive and racing around to repair barricades or upgrade weapons. If there are less than a certain number of zombies for too long, say <= 5 zombies for > 45 seconds, then the game should automatically kill these zombies all at once so the next wave can begin.

**Additional context**
I understand that this feature is not for everyone, as there are some people that prefer their waves to be prolonged until they are fully ready for the next wave. It is still rather silly for them to have to keep a zombie alive in order to do all of this. Instead, I think that in the future, there should be a new feature implemented that does not immediately start new waves, rather requiring confirmation from all players before starting the wave (e.g.: by pressing F4 as done in other wave-based games). Some achievements where necessary can be updated to require the server to be running with automatic waves to preserve the need for a challenge.

**Comment by Naievil** [comment]
I agree somewhat with the principle of auto removal and believe we should implement a general origin check to respawn the zombies if they have not moved in a general region for some duration. I believe that traditional Call of Duty zombies operates this way.

**Comment by MotoLegacy** [comment]
Yes, if a Zombie is "idle" in the play space for 30 seconds it'll "die" and respawn. 

The behavior suggested by this user was a mechanic in Black Ops 4 but was universally hated — The gist for that is, in what is undoubtedly intended to be a user controlled sandbox, removing control from the player as to however long they'd want to take to start the next round is counter intuitive. Black Ops II also has this feature specifically for crawlers, which was _also_ deemed problematic and is why crawlers in that game became useless.

The whole "press X to start the next wave" is an interesting concept, but other platforms are lacking buttons, and also this would probably be prefaced with some kind of forced timer if people don't ready up in time, which again contradicts the nature of the sandbox

**Comment by jack5github** [comment]
I don't think this issue should be discounted entirely. On certain maps, not auto-killing the zombies causes problems as some spawn points may become so broken as to not allow them to enter the line of fire. How about rather than checking for a new button, check for a combination of buttons in succession, for example, reload + melee?

**Comment by MotoLegacy** [comment]
> I don't think this issue should be discounted entirely. On certain maps, not auto-killing the zombies causes problems as some spawn points may become so broken as to not allow them to enter the line of fire. How about rather than checking for a new button, check for a combination of buttons in succession, for example, reload + melee?

This specific lack of a parity feature from CoD was added today in https://github.com/nzp-team/nzportable/issues/125 .. If a Zombie is stuck for ~30s in one spot, it will die and then auto respawn at a new point.
