### ISSUE TITLE
Bullet decals don't fade with fog

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#532]
**Describe the bug**
When you shoot a wall, the bullet decal is fully visible through the fog.

**To Reproduce**
1. Load up `ndu` or another map featuring fog.
2. Shoot a wall.
3. Observe the bullet decal as you walk away from it.

**Expected behavior**
The bullet decal should fade along with the rest of the wall due to the fog.

**Screenshots/Footage**
![fte-20231214185322-0](https://github.com/nzp-team/nzportable/assets/29164668/6e97d767-3901-4a44-8040-f07b9b0d8db4)
![fte-20231214185332-0](https://github.com/nzp-team/nzportable/assets/29164668/629a1b37-b749-4c48-80e1-07f7ea6b72ae)

**Affected Platforms**
Only tested on FTE Linux.

**Comment by MotoLegacy** [comment]
Hey there -- this was confirmed by spike to be an FTEQW engine bug, so I'm going to go ahead and close it.
