### ISSUE TITLE
Is it just me or the Vita version likes to crash? A LOT.

### ISSUE THREAD

**Issue by Laser327** [nzp-team/nzportable#533]
Idk why but ever since the latest update the game now not only crashes when trying to change a map.
Which happenes when i exit to the menu and try to play another map and when the loading screen says "executing spawn functions" the game just, closes itself which wasnt annoying but was kind of a bummer.

But now the game will also crash if i try to restart the map
For example: (when i was playing F4ll having difficulties with knifing the zombies due to their attcking improvements i died at round 3 and when i clicked restart, the game just froze for a split second and then close itself which considering the fact that im still trying to get used to new attcking improvements for zombies it just makes this a slight annoyance to deal with).

But then again NZ:P on Non-FTE Platforms was never the most stable so crashes like this arent much of a suprise and then also with the fact that on how much platforms this game is on, crashes like this are pretty much a understatement (lets be thankful that the game doesnt crash when dying on a high round anymore cuz it was painfully annoying to deal with).

**Comment by MotoLegacy** [comment]
Hi, this is not the general discussion section. This is for properly filing bug reports.

These issues have been around for a while, and no one has been wanting to write proper reports for them :) Nothing to do with roll-outs yesterday. Thanks.
