### ISSUE TITLE
Trigger_Hurt spawnflag for not damaging zombies

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#536]
**Describe your suggestion**
A spawnflag for trigger_hurt that doesn't damage zombies, only the player

This stems from behavior which I noticed zombies would instantly die when both they're in trigger hurt, and instakill is on

**Expected behavior**
When the player is in them, it'll still damage them, but when a zombie is in it, they won't take any damage 

**Additional context**
N/A

**Comment by MotoLegacy** [comment]
Trimmed out your fat there, and added in https://github.com/nzp-team/quakec/commit/ec76c768cd51680b87ea227b11ba18eda6d97a1b
