### ISSUE TITLE
Zombie spawns randomly don't target their windows

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#538]
**Describe the bug**
especially around round 10-ish, if you go in wireframe, you will see a lot of zombies either standing still not moving, or walking towards world origin, tested on House, Hangar, and Warehouse new, all these maps had known good spawn points

**To Reproduce**
1. open any map
2.  == to skip rounds, it might take a round or two after for it to happen consistently
3. look for stuck zombies

**Expected behavior**
All zombies would correctly path

**Screenshots**

SS from MP, but it also happens in singleplayer
![bug_1](https://github.com/nzp-team/nzportable/assets/13917665/fd6590cc-e972-4558-b2e5-d23c886f48bc)
![bug_2](https://github.com/nzp-team/nzportable/assets/13917665/0e6e6dea-6ab6-4ee5-bc34-1de4ca8f673d)

**Affected Platforms**
FTE

**Additional context**
This has started occurring within a week

**Comment by BCDeshiG** [comment]
Here's a test map I cooked up which demonstrates this. Consistently happens on round 2 despite the spawn + barrier having plenty of space (24 units either side of the barrier bounding box.
[barrierTEST.zip](https://github.com/nzp-team/nzportable/files/13695776/barrierTEST.zip)

**Comment by MotoLegacy** [comment]
> Here's a test map I cooked up which demonstrates this. Consistently happens on round 2 despite the spawn + barrier having plenty of space (24 units either side of the barrier bounding box.
> 
> [barrierTEST.zip](https://github.com/nzp-team/nzportable/files/13695776/barrierTEST.zip)
> 

Thanks for creating a test map for this, for me. This is very helpful.

**Comment by MotoLegacy** [comment]
This one issue was actually three separate issues, so sorry it took 3 days to fix. Here you go, though: https://github.com/nzp-team/quakec/commit/0874299cafcd5f30d35ad98db293e077df055eaf
