### ISSUE TITLE
[SERVER] Soft_Restart doesn't clean up as it should

### ISSUE THREAD

**Issue by tyleryoung88** [nzp-team/nzportable#543]
**Describe the bug**
While playing Trapped in NZ:P I noticed that Mulekick was still opened after a soft restart

**To Reproduce**
1. Play Trapped in NZ:P
2. Play long enough to open up Mulekick
3. Restart game or go down and let the player respawn

**Expected behavior**
The map would get fully reset. 

**Screenshots/Footage**
![2023-12-18-181717](https://github.com/nzp-team/nzportable/assets/7098194/a9afa1f0-cfa9-4ca9-96fe-89cd9d304eeb)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.

- PS Vita (1k, 2k)

**Comment by MotoLegacy** [comment]
Feel free to make a comment on the pinned issue about this. https://github.com/nzp-team/nzportable/issues/59
