### ISSUE TITLE
"set fire" spawnflag for trigger hurt

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#545]
**Describe your suggestion**
I think a spawnflag for `trigger_hurt` that sets zombies/dogs on fire would be nice

However, it being a separate trigger volume could work

**Expected behavior**
When a zombie/dog walks on these, it sets them on fire

However, I would want this to still set zombies on fire when the "noAI" spawnflag is enabled? I don't know if that's possible

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/3ea3d20e67ea0a3302cc9b31e89cabf7611628ff
