### ISSUE TITLE
Opens main menu after buying first debris in nacht der untoten

### ISSUE THREAD

**Issue by ElJones44** [nzp-team/nzportable#548]
If playing on 3ds and buying the debris in start room in nacht der untoten, the game goes back to main menu after walking through the cleared debris.
(Sorry for my bad english)

**Comment by MotoLegacy** [comment]
For future reference, use the report template GitHub basically demands you use, and do your due diligence and look for the log dump or something, "game crash" isn't very useful. Regardless, https://github.com/nzp-team/quakec/commit/997d6748e9f678153179f649f7ffe80ba588d539
