### ISSUE TITLE
`scale` unimplemented

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#55]
**Describe the bug**
in TB, I have a sprite, and it uses the null.spr in order to save resources for the external texture used, that however, makes the sprite small, so i want to use the scale function to make it larger, 

however

on PSP it stays the same size regardless 

**To Reproduce**

1. make a map
2. place a renamed null.spr with an external texture .tga pointing to it
3. set the scale to a desired size
4. 
![Screenshot 2022-08-23 153859](https://user-images.githubusercontent.com/13917665/186278841-7a1bafa9-eb17-4879-82c2-0e7f020a529d.png)

5. compile and enjoy

**Expected behavior**
this is how it looks on PC, while it does have an upper limit that's kinda small, its fine
![Screenshot 2022-08-23 153725](https://user-images.githubusercontent.com/13917665/186278823-55fc1a80-f341-4088-be03-50da0102e5dc.png)

as you can see it scales up with the different values to make the size better

**Screenshots/Footage**
this is how it looks on PSP (picture taken in PPSSPP, but I've tested on hardware, it behaves the same)
![Screenshot 2022-08-23 153814](https://user-images.githubusercontent.com/13917665/186279041-0b7d99dc-6d26-44e4-b34b-89e77b8ec937.png)

**Affected Platforms:**
I have at the moment only tested on PSP and PC (but it works on PC)

I haven't tested on Vita/switch as im having some issues with them at the moment

**Comment by MotoLegacy** [comment]
Added to glQuake/3DS with https://github.com/nzp-team/glquake/commit/96773c9fc44cbe9b61c3be1a693aa2c1d968d5ab

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/dquakeplus/commit/23a9dc0b9a0cc80ac822c1db336b1aecd11c5787 https://github.com/nzp-team/quakespasm/commit/3c15d7d6e9e282a255ecff78ab68be44b7b966d7 https://github.com/nzp-team/glquake/commit/79ce3c6bc307885cfae057ddbcb15432baebfec8
