### ISSUE TITLE
player model stays when a player disconnects

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#554]
**Describe the bug**
when a player leaves the player model stays

**To Reproduce**
1. have players join
2. have a non-host player leave
3. the model stays

**Expected behavior**
The model would disappear and its hitbox would also disappear 

**Screenshots/Footage**

![image](https://github.com/nzp-team/nzportable/assets/13917665/13b6aae9-c7b4-4a22-afa6-6c17f0c56a44)

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**
The player hitbox is also still there, but it you can walk through it?

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/981cd3a5ad124fbaf7489e7f6e94e20eb0de207e
