### ISSUE TITLE
Players points stay after disconnect

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#555]
**Describe the bug**
When a player disconnects their points stay on the screen, and in the tab menu

**To Reproduce**
1. host a game
2. have players join
3. have a non-host leave

**Expected behavior**
the points would disappear

**Screenshots/Footage**

![image](https://github.com/nzp-team/nzportable/assets/13917665/2c491a88-662b-48a7-9f8d-6cae318dfc8c)

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**
When the player rejoins, they do not get to keep the points, idk i tested it, it sounded like a fun time

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/49dbd80fa4c7454630b7728c8319b53f9dac3c85
