### ISSUE TITLE
When MP players disconnect the server goes back to SP gamemode

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#557]
**Describe the bug**
When an MP server is open, and people, connect, and then leave, the server turns back into an "SP" server

**To Reproduce**
1. host map with QR
2. players join
3. non-host players leave
4. QR is now buyable

**Expected behavior**
I believe the server should stay MP

**Screenshots/Footage**

![image](https://github.com/nzp-team/nzportable/assets/13917665/4039e28c-a0a4-48b7-9a8b-5a355c5b174d)
![image](https://github.com/nzp-team/nzportable/assets/13917665/3c1efe00-8b24-49ea-8896-c68a87f8bd4d)

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**
I don't actually know what it should do, I'm mostly posting this just so if you decide one way or the other, we have something to point to of it the question being asked

**Comment by MotoLegacy** [comment]
This is a CoD parity feature
