### ISSUE TITLE
Dead players don't get game over screens

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#558]
**Describe the bug**
When players die, and then the host goes down, the dead players don't get a game over screen

**To Reproduce**
1. host mp game
2. have non-host players die (might happen in other scenarios, but i haven't tested)
3. have the host go down
4. dead players shouldn't see one

**Expected behavior**
I'd expect all players to see a game over screen

**Screenshots/Footage**

![image](https://github.com/nzp-team/nzportable/assets/13917665/aeea0257-1f60-4cb3-b0c1-aa3109924c83)
![image](https://github.com/nzp-team/nzportable/assets/13917665/5f68dec0-ea36-4fba-83ab-fc4c08a545d0)

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**
I found this trying to find another bug, where even downed players didn't see it, but it didn't happen

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/e5372d310787fa9067e63097e19174751c7e8862
