### ISSUE TITLE
Maps without power can't buy perks

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#559]
**Describe the bug**
When a map without a power switch (specifically Lexi_house) has perk machines, which should work without needing power, they don't work (with an exception of QR)

**To Reproduce**
1. open House
2. use `=` to get points
3. go to second room, and try to get DT

**Expected behavior**
the perk would be buyable

**Screenshots/Footage**

![image](https://github.com/nzp-team/nzportable/assets/13917665/f856c614-cc0f-4676-adc9-abfd1205af6c)

**Affected Platforms**

only tested on

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/cf8e8a23de8028a9f39a86d3514240c46a14ae1d
