### ISSUE TITLE
[Suggestion] Waypoint QOL

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#56]
I had the fun task of waypointing a map, and I realized... wow... there's quite a few small issues that make messing everything up super easy. So I thought I'd write some stuff down so they can be looked into

1. 2 waypoint formats is clunky and confusing, especially because many mappers might not have access to a system to waypoint for them, leaving their map to be PC only. I'd probably say just stick with the PSP format, because all the others use it, and reading them is already supported in FTE

2. A confirmation for saving over your existing waypoints, currently the default binds for save and load are right next to each other (And `Shift` is bound to save as well, causing someone to try to run right when they enter waypoint mode.... and completely erase all their waypoints) 

those are like, the two biggest things that would go a long way, the next two, are EXTRA QOL suggestions that aren't necessary, but would really help with figuring out whats going on in their map

1. Lines between linked waypoints in the editor
![image](https://user-images.githubusercontent.com/13917665/188487373-5d2f8576-8566-4de5-82ed-59d6273ffe69.png)
with this change, i can now see at a glance while flying around the map, that these waypoints aren't linked, without having to manually check each and every one

2. a `Zombie` and `Player` Placement that lets you see what path zombies would take to get to the player,  its great for checking why a zombie might go to a certain path or something like that

Nav mesh had something similar to it, so I'm posting a video for reference https://youtu.be/kK-QkFNE8SQ

**Comment by MotoLegacy** [comment]
Hi, I don't have much time to respond to all of this but I want to make quick note that completely abandoning a waypoint format is a bad idea and leaves the maps that were made with the "revised" system unplayable, leaving compatibility concerns.

Will respond again to the other comments.

Thanks,
Moto

**Comment by BCDeshiG** [comment]
Of note, the PSP waypoint format is more primitive as well since it's limited to 8(?) links and you have a whole bunch of extra lines in the file due to the redundant `targetN=<blank>` when you don't use all of the links e.g. if it's only linked to 2 points.

**Comment by DerpedCrusader** [comment]
I'm sure it could be changed to be different, what I meant more was, having a unified waypoint system, instead of having it split,

I'm also editing the original to point out a bug

**Comment by MotoLegacy** [comment]
I've removed support for exporting waypoints in the "new" way Jukki had come up with in 2017. They now save using the legacy system. I didn't decrease the vector precision, hopefully the other ports don't care! heh.

There is now a save confirmation system on FTE. Trying to save prompts you to hit it again for it to go through, or the Load bind to cancel the action.

SHIFT/SPRINT no longer triggers saving.

https://github.com/nzp-team/quakec/commit/981a8ec43dabe807f20fac897519298a75e07233
https://github.com/nzp-team/assets/commit/47ca35951ce9960e87ae892f24c22bb78a835569

Your suggestions concerning walking through and highlighting links were noted, but it feels like a time in shader Hell that is just going to get nullified when Waypoints are depreciated. I hope these do enough for the time being.
