### ISSUE TITLE
Player keeps a weapon when they die and respawn

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#561]
**Describe the bug**
When a player (non-host in this case) dies, and comes back next round, they appear to keep a weapon

**To Reproduce**
1. host MP
2. have a non-host player buy a weapon
3. have same player go down
4. have them die
5. they respawn next round
6. i believe the weapon in slot 1, should be in slot 2 of the re spawned player

**Expected behavior**
they should only have the colt when they respawn

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**
when i did the test, i didn't realize it would be the slot 1 weapon, so i had 2 colts that i could swap between, so, i ended up not posting screenshots, because it wasn't visually obvious

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/6a2cdf5f2db35f4bc8ddd172a154dafc366b8232
