### ISSUE TITLE
When reviving with a 2 handed weapon, the left gun cycles its animations

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#562]
**Describe the bug**
When reviving a player in MP with a dual wield weapon, the left gun stays on screen and plays it's animation during the revive animation

**To Reproduce**
1. host MP server
2. have a player go down, while you have dualies
3. you should see the gun

**Expected behavior**
the gun wouldn't be visible

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/13917665/f6fefa71-3209-4e84-9fbc-5626b6ce3a9c

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/8004caccfb86c96778c5904357766c094a2c0ee0
