### ISSUE TITLE
Swaping weapon animation speed not effecting left weapon

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#563]
**Describe the bug**
When holding a heavy weapon, and a dual wield weapon, and swaping weapons, the animation speed doesn't effect the left weapon

(or, if I'm incorrect on how weapon swapping speed is effecting the other weapons animation, then the inverse of this?)

**To Reproduce**
1. get Mustang and Sally
2. get the browning
3. swap weapons
4. bug should be visibile

**Expected behavior**

for the animation to be consistent between both left and right weapons

**Screenshots/Footage**

With heavy weapon
https://github.com/nzp-team/nzportable/assets/13917665/0a4e0582-427b-44eb-925e-a121c1b0b891

With light weapon
https://github.com/nzp-team/nzportable/assets/13917665/d0d7c8fe-e828-4518-81f2-764f6043aed4

**Affected Platforms**

Only tested on

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
I don't see a bug here, is the M&S not supposed to order left-then-right?

**Comment by DerpedCrusader** [comment]
> I don't see a bug here, is the M&S not supposed to order left-then-right?

Specially look at the speed difference of the left and right gun, the left happens almost instantly, while the right one has a delay

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/nzportable/assets/26030250/6b270ef0-1ce4-4672-890e-9555c03575b0

https://github.com/nzp-team/nzportable/assets/26030250/fcb87a3c-4396-4c1d-99e3-70103c8d88b3

I can't notice a difference here, they seem to match fine.

**Comment by DerpedCrusader** [comment]
That shows it perfectly actually!

With the type 100, the right gun starts showing up before the left gun is finished

While with the browning, the right gun doesn't even appear until the left guns fully out

**Comment by MotoLegacy** [comment]
I see what you mean however I can't get this to reproduce consistently. Sometimes they match in animation playback start, other times they do not. Feel free to re-open if you find something I missed.
