### ISSUE TITLE
zombies spawn behind blocked off areas whe

### ISSUE THREAD

**Issue by Trickygamers** [nzp-team/nzportable#566]
# When giving your report a title, please prepend a [LABEL], example [LABEL]s include:
# [SERVER] (for game code), [CLIENT] (for HUD elements or other client side stuff),
# [PSP/3DS/NX/VITA/FTE] (for engine based code specific to the platform).
# If related to CO-OP, prepend "CO-OP/" to the label, (e.g. [CO-OP/SERVER]).
**Describe the bug**

**To Reproduce**
1. Go to '....'

**Expected behavior**

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**

**Comment by Trickygamers** [comment]
oops didn't finish due to a misclick and can't edit due to only having my 3ds browser so I'll say here what I ment: zombies will spawn behind blocked off areas after you first unlock the blocked area then restart.

**Comment by MotoLegacy** [comment]
You've already reported this https://github.com/nzp-team/nzportable/issues/59#issuecomment-1869162237

**Comment by Trickygamers** [comment]
and the 3ds will not crash when spam restarting now thought I should mention it.

**Comment by Trickygamers** [comment]
its a different part of the bug
