### ISSUE TITLE
shooting at the ground with Mustang & Sally kills the player

### ISSUE THREAD

**Issue by Trickygamers** [nzp-team/nzportable#568]
# When giving your report a title, please prepend a [LABEL], example [LABEL]s include:
# [SERVER] (for game code), [CLIENT] (for HUD elements or other client side stuff),
# [PSP/3DS/NX/VITA/FTE] (for engine based code specific to the platform).
# If related to CO-OP, prepend "CO-OP/" to the label, (e.g. [CO-OP/SERVER]).
**Describe the bug**

**To Reproduce**
1. Go to '....'

**Expected behavior**

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.

- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**

**Comment by Trickygamers** [comment]
on the map shooting range after packapunching the pistal and then immediately shooting at your feet kills the player.

**Comment by MotoLegacy** [comment]
Explosives hurt.

**Comment by Trickygamers** [comment]
lol didn't know the bullets were explosives. So the bullets not killing me is the bug.
