### ISSUE TITLE
[3DS]Packapunch iss

### ISSUE THREAD

**Issue by Trickygamers** [nzp-team/nzportable#569]
# When giving your report a title, please prepend a [LABEL], example [LABEL]s include:
# [SERVER] (for game code), [CLIENT] (for HUD elements or other client side stuff),
# [PSP/3DS/NX/VITA/FTE] (for engine based code specific to the platform).
# If related to CO-OP, prepend "CO-OP/" to the label, (e.g. [CO-OP/SERVER]).
**Describe the bug**
A clear and concise description of what the bug is.: The packapunch cookie eating animation does not play but the audio dose and the option to pickup the gun doesn't properly give the option to pickup the gun.

**To Reproduce**
1. Go to a map that can packapunch
2. turn on power then packapunch what wepon your holding
3. move and look around for a sec
4. now getting the option to pickup the gun won't be right and the cookie eating animation won't play

**Expected behavior**
A clear and concise description of what you expected to happen.: a animation of the player eating a cookie should play and picking back up the gun should be the same as the perks.

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.

- Nintendo 3DS New

**Additional context**

**Comment by MotoLegacy** [comment]
I wish when I say "follow the template" you'd actually fill it out in full and trim all of this dummy text out that serves as instructional text. Anyway, make sure you're on the latest version before complaining about the Pack-A-Punch pickup prompt.
