### ISSUE TITLE
ADS Mode Toggle changes all the perk bottles to blue

### ISSUE THREAD

**Issue by Skibbo** [nzp-team/nzportable#573]
**Describe the bug**
When setting the "ADS Mode" to "Toggle" all the perk bottles in your hand while drinking are changed to blue.

**To Reproduce**
1. Go to Settings and Control Settings
2. Set "ADS Mode" to "Toggle"
3. Start a game and buy any perk except for quick revive (which is a blue bottle already)
4. See a blue bottle in your hand while drinking

**Expected behavior**
Every perk bottle should have their own color, like when "ADS Mode" is set to "Hold".

**Screenshots/Footage**
![fte-20240105005332-0](https://github.com/nzp-team/nzportable/assets/71838397/05a66c80-b8c6-45cf-b93e-30ddcd1e943f)

**Affected Platforms**
Occurs on:
- FTEQW (Windows, Mac, Linux, WebGL etc)

Not tested on:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/671ee73a19dd06f353374a8c632f7e64839193ef
