### ISSUE TITLE
ADS Mode Toggle does not allow changing stance while aiming

### ISSUE THREAD

**Issue by Skibbo** [nzp-team/nzportable#574]
**Describe the bug**
When the "ADS Mode" is set to "Toggle" it is not possible to change your stance (crouching, going prone, standing up) while aiming.

**To Reproduce**
1. Go to Settings and Control Settings
2. Change "ADS Mode" to "Toggle"
3. Start a game and aim
4. Try to change your stance to crouch
5. The character won't crouch until you disengage aiming

**Expected behavior**
When "ADS Mode" is set to "Hold" you can aim and change your stance simultaneously.
The same should happen while aiming with the "ADS Mode" set to "Toggle".

**Affected Platforms**
Occurs on:
- FTEQW (Windows, Mac, Linux, WebGL etc)

Not tested on:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/671ee73a19dd06f353374a8c632f7e64839193ef
