### ISSUE TITLE
Getting downed while aimed in will preserve viewzoom

### ISSUE THREAD

**Issue by Naievil** [nzp-team/nzportable#576]
**Describe the bug**
Getting downed while the gun is aimed down sights will preserve the FOV change. The gun is then put out and we are no longer ADS, but the FOV is still changed. Using ADS again will fix the issue. 

**To Reproduce**
1. Start map
2. Zoom in with colt
3. Get downed by zombie
4. FOV is fixed to the same value during ADS.

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/8d159b9ec3b19a04f7afbb4b81901521b4da98a0
