### ISSUE TITLE
Knifing while downed can lunge the player

### ISSUE THREAD

**Issue by Naievil** [nzp-team/nzportable#577]
**Describe the bug**
While downed in a multiplayer session, if a player knifes a zombie, they can lunge across the map toward the zombies while still downed

**To Reproduce**
1. Start map in multiplayer session
2. Get downed
3. Knife toward zombies that are above or walking away from you
4. Player knife lunges while downed

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/7d4ccdea604832860c4a53a904ef552daa6e1371
