### ISSUE TITLE
[SUGGESTION] Mobile Touchscreen support

### ISSUE THREAD

**Issue by Omer-Farooqui** [nzp-team/nzportable#581]
**Describe your suggestion**
Could there possibly be a way to add touch screen support. It doesn't have to be native Android, but if you were able to install the game as a PWA and then have touch controls that would be awesome!

**Expected behavior**
It doesn't have to be a native Android port, but if you were able to install the game as a PWA and then have touch controls appear on screen, that would be awesome! Just SOME way to play cod zombies anywhere.

**Comment by MotoLegacy** [comment]
Hi, FTEQW currently does not support any sort of enhanced building for web apps beyond standard WASM (potentially a limitation of emscripten?). Sorry about that.
