### ISSUE TITLE
[SERVER] Shooting a teddy with the Wunderwaffe DG-2 / Wunderwaffe DG-3 JZ causes the game to crash

### ISSUE THREAD

**Issue by Skibbo** [nzp-team/nzportable#582]
**Describe the bug**
When shooting a teddy with the Wunderwaffe DG-2 / Wunderwaffe DG-3 JZ the game crashes and says "Unable to connect to internalserver, giving up".

**To Reproduce**
1. Start a game on any map with a teddy (for easy testing I recommend "Bunker Defense")
2. Open the console and type "give 56" or "give 57"
3. Shoot the teddy in the start room
![fte-20240106224018-0](https://github.com/nzp-team/nzportable/assets/71838397/99826d84-6263-4a6a-bad7-14c2fc280d2a)
![fte-20240106224021-0](https://github.com/nzp-team/nzportable/assets/71838397/98bed861-25da-4723-b985-b5238e321541)
![fte-20240106224602-0](https://github.com/nzp-team/nzportable/assets/71838397/0a3bd4f5-028a-4661-a394-befc243534ae)

**Expected behavior**
The teddy should disappear and count like any other bullet based weapon.

**Affected Platforms**
Occured on:
- FTEQW (Windows, Mac, Linux, WebGL etc)

Not tested on:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Comment by Skibbo** [comment]
The crash got fixed with the pull reqeust https://github.com/nzp-team/quakec/pull/67

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/4579bd78845747f8c4f92beac2cb2ed5ce433567
