### ISSUE TITLE
[SERVER] Shooting a barrel with the Wunderwaffe DG-2 / Wunderwaffe DG-3 JZ counts as a kill and gives money

### ISSUE THREAD

**Issue by Skibbo** [nzp-team/nzportable#584]
**Describe the bug**
When shooting an explodable barrel with the Wunderwaffe DG-2 or Wunderwaffe DG-3 JZ it will blow up and award the player with a kill and 50 points.

**To Reproduce**
1. Start a game on "Nacht der Untoten"
2. Type "give 56" in the console to give yourself the Wunderwaffe DG-2
3. Shoot at an explodable barrel outside of the bunker
4. You will get 50 points and a kill

**Expected behavior**
The barrel explodes and nothing else happens.

**Screenshots/Footage**
![fte-20240107011716-0](https://github.com/nzp-team/nzportable/assets/71838397/25521b75-2315-4c1a-99be-829f3ec0ea08)
![fte-20240107011818-0](https://github.com/nzp-team/nzportable/assets/71838397/9a9c47ae-9d49-434d-9147-15103c468990)

**Affected Platforms**
Occurs on:
- FTEQW (Windows, Mac, Linux, WebGL etc)

Not tested on:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/68bfc0f6958fae6ea24a5cc91af934a5736efbbc
