### ISSUE TITLE
[SERVER/3DS] Perk machines don't give perks

### ISSUE THREAD

**Issue by Trickygamers** [nzp-team/nzportable#586]
Describe the bug: When going to get a perk the points will be taken. But the effect of the perk will not be given.

1. Go to christmass special
2. run straight to the blue perk machine
3. quickly press select

Expected behavior: Consistent obtaining of perks.

Footage:
https://m.youtube.com/shorts/rpsfQj9_3to

Affected Platforms:
Tested: 
- Nintendo 3DS (Old, New)

Didn't Test:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by Skibbo** [comment]
This can also be replicated on the PC when sprinting to the quick revive machine and spamming use.

**Comment by DerpedCrusader** [comment]
> I just tested this on PC and it can be reproduced by sprinting to the quick revive machine and spamming use.

I want to specifically note

I meant to report this a while ago, but I kept forgetting to 

It has to be while the sprinting animation is being cancelled

If you just sprint into it, it won't work

https://github.com/nzp-team/nzportable/assets/13917665/9f245f04-7034-42bb-a5f2-55daf8840e42

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/2ccd55a2b510a5d3de0b301150ed94c66de51b46
