### ISSUE TITLE
[SERVER/3DS]game console does nothing while in a map

### ISSUE THREAD

**Issue by Trickygamers** [nzp-team/nzportable#588]
Describe the bug: When trying to inputting a command while in a map nothing happens.

1. Go to a map
2. Go to settings
3. open console
4. input a command like give 56

Expected behavior
When I put in a command I should get a error saying command doesn't work or a gun or something.

Affected Platforms:
Tested: 
- Nintendo 3DS New
Not Tested:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS Old
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by Trickygamers** [comment]
Since the topic is the console, what other commands exist besides give 56?

**Comment by MotoLegacy** [comment]
give command is fte specific.
