### ISSUE TITLE
Auto reload doesnt work

### ISSUE THREAD

**Issue by kieferbrecher** [nzp-team/nzportable#589]
**Describe the bug**
Some weapons do not auto reload if you empty the clip and switch weapon

**To Reproduce**
1. Buy sawn off shotgun
2. Empty clip
3. Switch weapon
4. Switch again
5. You have to manually reload

**Affected Platforms**
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/35bbd002ff2d383f62876911c04488577ef9bd18
