### ISSUE TITLE
[SUGGESTION] movements speed ballistic knife

### ISSUE THREAD

**Issue by kieferbrecher** [nzp-team/nzportable#593]
**Describe your suggestion**
In cod your movement is faster with the ballistic knife than with a pistol so it is the best for training

**Expected behavior**
Move faster with ballistic knife

**Additional context**
I dont like vanila, the ballistic knife would be the best weapon for training, otherwise it is kinda useless

**Comment by MotoLegacy** [comment]
The Ballistic Knife isn't finished in any regard, it's not designed to be used at all at the moment, so closing as issues like this will automatically be resolved when it is.
