### ISSUE TITLE
[SUGGESTION] Hitting players with a knife

### ISSUE THREAD

**Issue by kieferbrecher** [nzp-team/nzportable#595]
**Describe your suggestion**
Hitting players with a knife makes the same sound as hitting a wall it would be better if it plays the normal sound

**Expected behavior**
Play the hiting zombie sound instead of hittng object when knifing a teammate

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/5b4af6caeb8a956d2894e6d050a6eb264e337585
