### ISSUE TITLE
[SUGGESTION] Sprite for typing

### ISSUE THREAD

**Issue by kieferbrecher** [nzp-team/nzportable#596]
**Describe your suggestion**
It's not too important but it would be nice to have a sprite above the characters head so you know if they are typing something

**Expected behavior**
A sprite above the characters head while typing

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/a41eeb23c6a238a7a33dc9b4e655d0a86e117cd6


https://github.com/nzp-team/nzportable/assets/26030250/de6bf9c7-4aa3-4d72-91b9-a3dddb98784d
