### ISSUE TITLE
Zombie sprint animation doesn't loop properly

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#597]
**Describe the bug**
The zombie's sprint animation doesn't loop seamlessly so there's a visible hitch.

**To Reproduce**
1. Load up any map.
2. Progress to a round where zombies start sprinting.
3. Observe animation.

**Expected behavior**
There shouldn't be any visible hitches.

**Screenshots/Footage**
[https://youtu.be/twYvsPKhoTs](https://youtu.be/twYvsPKhoTs)

**Affected Platforms**
Only tested on FTE Linux.

**Additional context**
My FPS is capped to 165 to match the refresh rate of my monitor.

**Comment by BCDeshiG** [comment]
Confirmed this still occurs with FPS cap set to 60.

**Comment by BCDeshiG** [comment]
Recorded more test footage including testing at various framerate caps.
https://youtu.be/9p52dRw6z20
Main takeaway is that the issue only exists at 'low' framerates (doesn't seem visible at 500+ fps) with it getting worse the lower the framerate is.

**Comment by MotoLegacy** [comment]
There is definitely an interpolation bug in FTEQW with low-ish tick rates that is causing this. I'm going to mark this as wontfix. We will eventually be moving to IQM and I'm not inclined to fix or deeply investigate interpolation bugs in FTE pertaining to low server tick rates...
