### ISSUE TITLE
[PC] Zombies alive during Nuke can still damage Player

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#6]
Zombies last a while before being wiped out by the nuke and can still attack player (This actually got me killed at one point).

~Tested on the navmesh branch so unsure if present on main branch.~
Can confirm this affects the main branch as well as navmesh.

Video link - https://youtu.be/mAa9LsZOjwg

**Comment by MotoLegacy** [comment]
Zombies remaining alive for a short while is working as intended — this is functionality in parity to CoD in which Zombies are picked off one by one with a random interval time in between kills. Them being able to attack the player is not intended, however.

**Comment by BCDeshiG** [comment]
You might wanna add a visual indicator to show they're dying then e.g. some sort of flame effect.
