### ISSUE TITLE
[SUGGESTION] Grenade or explosive stun

### ISSUE THREAD

**Issue by kieferbrecher** [nzp-team/nzportable#602]
**Describe your suggestion**
In cod if you hurt yourself with a grenade you dont just get damage but the screen turns grey and your movement is slower

**Expected behavior**
Move slower after getting explosive damage

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/7e9490fad76fee3849de682da429a090a548c275
