### ISSUE TITLE
I can't start the game

### ISSUE THREAD

**Issue by Mrskydrox** [nzp-team/nzportable#604]
hello, when I launch the game on 3ds from homebrew launcher it shows me this, can you help me
![IMG_20240113_160930](https://github.com/nzp-team/nzportable/assets/156528631/0be13c93-64f0-4334-8377-83efe38df761)

**Comment by MotoLegacy** [comment]
https://3ds.hacks.guide/finalizing-setup.html#section-iv---rtc-and-dsp-setup
