### ISSUE TITLE
Sniper zoom flashes briefly when tapping ADS

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#605]
**Describe the bug**
When pressing ADS briefly with a sniper, the screen zooms in for a split second even though the animation barely plays.

**To Reproduce**
1. Load up any map (F4ll has a wallbuy at spawn).
2. Obtain Scoped Kar98k or any other sniper.
3. Briefly press the ADS button.

**Expected behavior**
The ADS animation should begin but should end quickly before reaching the point that the zoom occurs.

**Screenshots/Footage**
https://youtu.be/PTbfP1z-KiU

![image](https://github.com/nzp-team/nzportable/assets/29164668/1654d46c-d0fd-463d-b98d-f28fadf42fd6)

**Affected Platforms**
Only tested on FTE Linux.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/136e92511d812347f431180bcd725c17c0f03b9f
