### ISSUE TITLE
Walking downstairs

### ISSUE THREAD

**Issue by kieferbrecher** [nzp-team/nzportable#610]
**Describe the bug**
You cant run or jump when walking downstairs

**To Reproduce**
1. Go to stairs
2. Go downstairs
3. Try to run or jump

**Expected behavior**
Being able to run or jump

**Affected Platforms**
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by BCDeshiG** [comment]
This heavily depends on the map itself and how it does stairs, just loaded up ndu for example and I can sprint down the stairs most of the time depending on where I start sprinting.
