### ISSUE TITLE
[SUGGESTION] Idea for future verruckt and der riese

### ISSUE THREAD

**Issue by kieferbrecher** [nzp-team/nzportable#612]
**Describe your suggestion**
It would be nice to have a second door sound for metallic doors since both verrückt and der riese only have metal doors.
right now we only have the wooden door sound and i just feel like it would help make map makers make their maps more distinct.

**Expected behavior**
Have a second door sound

**Comment by MotoLegacy** [comment]
Thanks, but this really isn't the time to think about this.
