### ISSUE TITLE
Mouse stops working after being afk

### ISSUE THREAD

**Issue by kieferbrecher** [nzp-team/nzportable#614]
**Describe the bug**
This one was driving me nuts. Everytime I take a break and come back after 10 minutes, I cant click anything. The keyboard works, the cursor works but when I resume I cant look around nor shoot.

**To Reproduce**
1. Start a game
2. Pause
3. Wait for 10 minutes
4. Cant click, cant shoot, cant look around

**Affected Platforms**
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
This probably belongs in https://github.com/fte-team/fteqw instead, if you can consistently reproduce it.
