### ISSUE TITLE
Invert Y mouse option in the menu

### ISSUE THREAD

**Issue by Snoucher** [nzp-team/nzportable#615]
Hi, I like to play with inverted mouse Y axis in every game I can, and I am disappointed to tell you that I cannot find the Invert Y option in your settings. It should be settings/control settings/invert Y and it should invert up and down movement of the mouse in game.
Not only would this be useful for PC players, I hope you make this applicable for controller players as well.

Thank you for reviewing my issue.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/a77a7f780799331495c01634cc464deed035e753
