### ISSUE TITLE
[SERVER] Wunderwaffe DG-2 / Wunderwaffe DG-3 JZ reward the wrong amount of points

### ISSUE THREAD

**Issue by Skibbo** [nzp-team/nzportable#616]
**Describe the bug**
When shooting zombies with the Wunderwaffe DG-2 there are no points reward.
When shooting zombies with the Wunderwaffe DG-3 you only get rewarded with 10 points, regardless of the number of kills.

**To Reproduce**
1. Start a game on "Nacht der Untoten"
2. Type "give 56" / "give 57" into the console
3. Shoot one or multiple zombies
4. The Wunderwaffe DG-2 doesn't reward any points / The Wunderwaffe DG-3 JZ only rewards 10 points regardless of the number of kills

**Expected behavior**
Like in the older version of NZP, each zombie kill should award points.

**Screenshots/Footage**
![fte-20240115213556-0](https://github.com/nzp-team/nzportable/assets/71838397/16e76584-4430-4d76-b947-a5aaaaf8c8af)
![fte-20240115214508-0](https://github.com/nzp-team/nzportable/assets/71838397/e18eb1df-666e-4b24-854f-75f40ba1d7b2)

**Affected Platforms**
Occured on:
- FTEQW (Windows, Mac, Linux, WebGL etc)

Not tested on:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/4741ffed2f690af05b9c646fbb2cff836d53b31c
