### ISSUE TITLE
[CLIENT] Three window boards have inverted normals

### ISSUE THREAD

**Issue by Skibbo** [nzp-team/nzportable#617]
**Describe the bug**
The new window board model has a few inverted normals.

**To Reproduce**
1. Start a game on any map
2. Go to any window and look at the marked boards from the screenshot
3. You will see some boards are inverted

**Expected behavior**
The three marked boards should look the same as the other boards.

**Screenshots/Footage**
![grafik](https://github.com/nzp-team/nzportable/assets/71838397/673c8539-b17f-4d1b-b072-466ff41a5d3f)

**Affected Platforms**

Occured on:
- FTEQW (Windows, Mac, Linux, WebGL etc)

Not tested on:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Comment by DerpedCrusader** [comment]
fixed in https://github.com/nzp-team/assets/commit/baf8427c1764c7d2214274b058746b54f36e49d6
