### ISSUE TITLE
ADS Toggle breaks dual wield fire action

### ISSUE THREAD

**Issue by Skibbo** [nzp-team/nzportable#618]
**Describe the bug**
When the ADS Mode is set to Toggle in the options, it is no longer possible to shoot the right weapon when dual wielding.

**To Reproduce**
1. Go to Settings
2. Go to Control Settings
3. Set ADS Mode to Toggle
4. Start any map
5. Type "give 28" or "give 42" into the console
6. Try to shoot the right weapon with right click
7. Nothing is happening

**Expected behavior**
The right weapon should shoot, just like when ADS Mode is set to Hold.

**Affected Platforms**
Occurs on:
- FTEQW (Windows, Mac, Linux, WebGL etc)

Not tested on:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/1e1925ffa6ffba79b77a580f94e77cd272aef561
