### ISSUE TITLE
[CLIENT] Weapon bobbing is too exaggerated

### ISSUE THREAD

**Issue by Skibbo** [nzp-team/nzportable#619]
**Describe the bug**
Restarting the game after downloading a "clean" copy of the game, sets the weapon bob way too high.

**To Reproduce**
1. Download the game
2. Start the game
3. Choose any map
4. Observe normal behaviour / Open the console and see that cl_bobup is set to 0.02
5. Close the game completely
6. Start the game
7. Choose any map
8. Walk a few steps and observe way too high bobbing of the weapon / Open the console and see that cl_bobup is set to 0.5

**Expected behavior**
The default bobbing should be way lower. / The default for cl_bobup should be 0.02.

**Screenshots/Footage**
![fte-20240115220634-0](https://github.com/nzp-team/nzportable/assets/71838397/a40c670c-8db9-4d7f-8a28-984e32d12320)
![fte-20240115220635-0](https://github.com/nzp-team/nzportable/assets/71838397/1c6319e8-7b45-4004-8656-7a1a177a946a)

**Affected Platforms**
Occurs on:
- FTEQW (Windows, Mac, Linux, WebGL etc)

Not tested on:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Comment by obtainbean** [comment]
not an issue on ps vita, also happens when running the windows version on linux through GE-Proton 23

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/b1e70d7eb56d640505c9b8a0a796bda213bae3fa
