### ISSUE TITLE
[3DS] The world gets Rendered incorrectly sometimes

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#62]
**Describe the bug**
It's like playing the lottery, either you have everything render right... or the textures are missing and the lighting is messed up.

**To Reproduce**

1. Pick a map
2. See results
3. If that didn't happen repeat step 1.

**Expected behavior**
Everything should look fine as in the PC or PSP or NX or VITA versions.

**Screenshots/Footage**
[Screenshots.zip](https://github.com/nzp-team/nzportable/files/10099119/Screenshots.zip)
I had to upload it as a .zip due to githubs file constraints

**Affected Platforms:**
Maybe only the N3DS but it can affect the whole 3DS/2DS Family.

# Please make note of any platforms you DID NOT test on.

-2DS/N2DS, O3DS

**Additional info**
This was a issue that existed in the Beta aswell.

**Comment by Paindeluxe** [comment]
Even more examples /:
[Screenshots.zip](https://github.com/nzp-team/nzportable/files/10099156/Screenshots.zip)

**Comment by MotoLegacy** [comment]
Believe this was fixed here: https://github.com/nzp-team/glquake/commit/8ddeedc913816ab0de1e8122566ae49f80f995d3
