### ISSUE TITLE
[SERVER] Scoped Kar-98k scope does not move while looking around

### ISSUE THREAD

**Issue by Skibbo** [nzp-team/nzportable#620]
**Describe the bug**
When looking around with the Scoped Kar-98k equipped moves only the Kar-98 itself, not the scope.

**To Reproduce**
1. Start any map
2. Type "give 11" into the console
3. Look around with the Scoped Kar-98k in hand
4. The scope does not move with the weapon itself

**Expected behavior**
The scope should also lag behind the movement, just like the weapon itself.

**Screenshots/Footage**
https://github.com/nzp-team/nzportable/assets/71838397/e222cd2b-9936-49f0-a0e5-c54555b47860

**Affected Platforms**
Occurs on:
- FTEQW (Windows, Mac, Linux, WebGL etc)

Not tested on:
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/6f5889d169c9e533703640631f01bae3e6355b0f
