### ISSUE TITLE
Hellhound detection removed

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#623]
**Describe the bug**
Dog rounds don't occur when they should 

**To Reproduce**
1. Play a map with dogs (warehouse, hanger)
2. Play until past round 7/8
3. A dog round should have occurred by then

**Expected behavior**
A dog round would happen 

**Affected Platforms**

Only tested on
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/b9b5d2be4a53f1e034836aa8401b40531fa93c3d
