### ISSUE TITLE
Bowie Knife reports to "Buy Ammo"

### ISSUE THREAD

**Issue by kieferbrecher** [nzp-team/nzportable#624]
**Describe the bug**
String of bowie knife is wrong

**Expected behavior**
It should say buy bowie knife instead of buy ammo for bowie knife

**Affected Platforms**
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/96de5e4d16aad8e1c172b3dac5777b709c714044
