### ISSUE TITLE
[3DS] The game is incapable of finding some models.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#63]
**Describe the bug**
During the loading process of certain maps the game errors and can't see a certain model. *(even if it's in the correct Directory and also existing in that Directory.)*

**To Reproduce**
1. Try to play Boxxer.
2. See that it's missing the model for Power.

**Expected behavior**
The game finds the necessary models and let's the player play the picked map.

**Screenshots/Footage**
[Screenshots.zip](https://github.com/nzp-team/nzportable/files/10099140/Screenshots.2.zip)

**Affected Platforms:**
Most likely the whole 3DS/2DS Family.
# Please make note of any platforms you **DID NOT** test on.

O3DS and the 2DS Family.

**Additional context**
This also happened for custom made maps using the prepackaged models like perk machines?

**Comment by BCDeshiG** [comment]
Probably because older maps might be looking for the old model path? Just my guess since I don't have a 3ds.

**Comment by Paindeluxe** [comment]
> Probably because older maps might be looking for the old model path? Just my guess since I don't have a 3ds.

This also happens for my Map and I made it recently so I don't think so.

**Comment by MotoLegacy** [comment]
Deshi is correct - the issue with Boxxer is that it's looking for an old path that does not exist anymore, `models/machines/power_switch.mdl`. It is stored in `models/machines/<some>_scale/power_switch.mdl` nowadays. I will make a change to ctrQuake to not just outright crash anymore, however.

**Comment by Paindeluxe** [comment]
Although I don’t understand why that happens with my map as I put the model into the props Folder and the model is there.
