### ISSUE TITLE
Does not bind to audio device

### ISSUE THREAD

**Issue by Weigurde** [nzp-team/nzportable#632]
**Describe the bug**
On Windows, the game does not seem to let me use VOIP since it cannot find my microphone
**To Reproduce**
1. Select an input device for audio
2. Enable voice activation
3. Look in console

**Expected behavior**
The game would be able to access my microphone for voip ingame.

**Screenshots/Footage**
![vgnt1k2u](https://github.com/nzp-team/nzportable/assets/83884361/8161eb6b-8489-4380-b7f7-788665353fd7)
![c96dpve3](https://github.com/nzp-team/nzportable/assets/83884361/2b0624ab-3dfc-4746-b51e-63b7c8898e41)

**Affected Platforms**
- [ ] PSP (1k, 2k, 3k, Go, Street)
- [ ] PS Vita (1k, 2k)
- [ ] Nintendo Switch
- [ ] Nintendo 3DS (Old, New)
- [X] FTEQW (Windows, Mac, Linux, WebGL etc)
(specifically on windows - this doesn't seem to happen to a friend playing on steam deck)

**Comment by Revnova** [comment]
voip isn't meant to work i think. but i found if you go into a map from the menu twice. it does work. if the capture device field is empty, it should select your default device.

**Comment by Weigurde** [comment]
i used that default to select it, i just took the screenshot there to show that it's set to the right device

**Comment by Revnova** [comment]
ah. i forgot you also have to set the codec to 1 in the cfg. but again. i don't think voip is supposed to work in the first place
