### ISSUE TITLE
Revives take a long time to start

### ISSUE THREAD

**Issue by Weigurde** [nzp-team/nzportable#633]
**Describe the bug**
When a player is downed, +use needs to be held down for several seconds before a player starts to be revived.
**To Reproduce**
1. Go in coop with a player
2. Have them get downed
3. Attempt to revive them
4. Observe

**Expected behavior**
The player begins to be revived when the player holds E on them.
**Screenshots/Footage**
<video src="https://github.com/nzp-team/nzportable/assets/83884361/b7c8aa7a-81a1-47f9-9f47-985ea5b9785f">
**Affected Platforms**
- [ ] PSP (1k, 2k, 3k, Go, Street)
- [ ] PS Vita (1k, 2k)
- [ ] Nintendo Switch
- [ ] Nintendo 3DS (Old, New)
- [X] FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
> seems to be fixed

No it is not. Do not assume magical fixes without a commit link.

**Comment by MotoLegacy** [comment]
I was able to reproduce this locally last night. Please stop bloating this issue. It working for you means you've discovered (intentionally or not) some workaround. I should not have to explain this..

**Comment by Tibzyyy** [comment]
I have the same issues, does trigger that I am trying to revive him

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/0abf4b18f9fad78cba0f400b66ea025568ff497b
