### ISSUE TITLE
Downing with Quick Revive near power door opens it

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#634]
**Describe the bug**
When you get downed with Quick Revive next to a door that requires power (damage source doesn't matter), the door opens.
Although the power text lingers where the door was, the triggers do get activated including spawns.

**To Reproduce**
1. Load up a map featuring Quick Revive and power doors (Warehouse is a good example).
2. Obtain Quick Revive.
3. Stand next to a door that requires power.
4. Get downed (Grenade is easiest).

**Expected behavior**
The door should not open.

**Screenshots/Footage**
https://www.youtube.com/watch?v=5U41m9iBOaw

**Affected Platforms**
Tested on FTE Linux and WebGL.

**Additional context**
This does not apply to regular doors that are bought with points.
Also attached a test map: [powerReviveTEST.zip](https://github.com/nzp-team/nzportable/files/14002086/powerReviveTEST.zip)

**Comment by Trickygamers** [comment]
works on 3ds.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/8eb0eabb5d6a6b2b4f0806bc4c42dc741df4d6f2
