### ISSUE TITLE
Double Tap doesn't increase fire rate of automatic weapons

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#636]
**Describe the bug**
When using either Double Tap 1.0 or 2.0, the fire rate of automatic weapons does not increase.

**To Reproduce**
1. Load up attached test map.
2. Obtain PPSh on the wall.
3. Mag dump, observing length of trigger time (how long you hold it until needing to reload).
4. Repeat step 3 after buying Double Tap.

**Expected behavior**
When you have Double Tap 1.0, the ammo should deplete faster.
(Can't remember exact behaviour of Double Tap 2.0).

**Screenshots/Footage**
https://youtu.be/PHf8myQFWHo

**Affected Platforms**
Only tested on FTE Linux, though a few other people have apparently encountered this issue.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/8abb8feeef4bc795920657cfef8398d98c82af39
