### ISSUE TITLE
[CLIENT] [PC-Windows10] Player hits the griddy while walking or running

### ISSUE THREAD

**Issue by xstarian5** [nzp-team/nzportable#637]
**Describe the bug**

The player's walking/running animation makes the player throw their arms up and down.

**To Reproduce**
1. Load into any map
2. walk/run
3. See error

**Expected behavior**
The players arms should not be waving up or down.

**Screenshots/Footage**

https://www.youtube.com/watch?v=fdO5ogaeink

**Affected Platforms**
The only platform tested with this bug is PC windows10
Version: 2.0.0-indev+20240117071758

**Comment by MotoLegacy** [comment]
your build is considerably out of date, this was fixed with https://github.com/nzp-team/quakec/commit/b1e70d7eb56d640505c9b8a0a796bda213bae3fa

additionally, titles like this for bug reports aren't welcome here. keep it serious.
