### ISSUE TITLE
[FTE] Texture corruption on map load on Linux

### ISSUE THREAD

**Issue by tanuki-billie** [nzp-team/nzportable#641]
**Describe the bug**
On Linux, when loading into a map, the loading screen tends to corrupt right before the map loads and fades in.

**To Reproduce**
1. Open the game on Linux
2. Load into your favorite map
3. Voilà, you have just experienced texture corruption

**Expected behavior**

**Screenshots/Footage**
[YouTube video](https://www.youtube.com/watch?v=I6F9NI8x8Hs)

**Affected Platforms**
- FTEQW (Linux, x86_64)

**Unaffected Platforms**
- FTEQW (Web)

**Untested Platforms**
- FTEQW (Windows)
- PSP (1k, 2k, 3k, Go, Street)
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)

**Additional context**
System specs:
Fedora 39
AMD Ryzen 5 2600
32 GB DDR4 Ram
AMD RX 580 w/ 4GB VRAM

**Comment by MotoLegacy** [comment]
Video is broken. But this just sounds like the loading screen is flickering..? No "corruption"

**Comment by tyleryoung88** [comment]
https://www.youtube.com/watch?v=I6F9NI8x8Hs

**Comment by MotoLegacy** [comment]
Yeah looks like flickering, and then something with your system/configuration is just making FTEs screen clear mess around. Guess it's time to move to menuQC :p
