### ISSUE TITLE
[VITA] Various PSVita 1&2K issues and bugs

### ISSUE THREAD

**Issue by VuduFOX** [nzp-team/nzportable#642]
**Describe the bugs:**
1. Corner & Wahnsinn always crash when trying to play them.
2. All maps have a chance of crashing when switching from one to another.
3. You can try to go to the next page on an empty page by pressing 
up on the Dpad or stick. Doing so crashes the game.

**To Reproduce**
 1.
   a. Hover over Corner or Wahnsinn
   b. Press X to start the map
   c. Watch the game crash and send you back to Livearea
 2.
   a. Play a game of NZ:P
   b. Try to launch a different map
   c. Crash and get sent to Livearea
 3.
  a. Open solo (not like you have a choice)
  b. Go to custom maps and press next page
  c. Press up on the dpad so it looks like no text is selected
  d. Press X, crash then get sent to Livearea

**Expected behavior**
The game should not crash in any of the above cases.

**Screenshots/Footage**
can't

**Affected Platforms**
As far as I know these only affect the PSV 1k and 2k

**Additional context**
idk

**Comment by MotoLegacy** [comment]
Steps are unclear here, no provided footage, and combined issues. Make these separate and be more concise.
