### ISSUE TITLE
[CLIENT] Guns deform during animations

### ISSUE THREAD

**Issue by VuduFOX** [nzp-team/nzportable#643]
**Describe the bug**
When any weapon plays an animation it will deform. This
behavior is most notable in the reloads of the Type 100 and
Wunderwaffe DG-2.

**To Reproduce**
1. Go to the Firing Range.
2. Fire the starting Colt, and notice the deformation on the right side of the slide when firing.
3. Equip the Wunderwaffe and Type 100 and reload them.
4. Observe the deformations during the reload animations.

**Expected behavior**
Weapons and their components should maintain their shape and form at all times.

**Screenshots/Footage**
nah

**Affected Platforms**
I tested on Windows, PSV 1&2k, and WebGL.
I would assume this affects all platforms.

**Additional context**
Oddly enough though, it seems like this bug affects smaller models less.
For example the 357. doesn't deform at all even though it has a complex animation.
Also this isn't too much of an issue considering it's only noticable in most weapons if you're looking for it.

**Comment by DerpedCrusader** [comment]
This is an artifact of qmdl format, and it's something we've arrived to mitigate, but it's not possible to get rid of entirely

The only chance of that is with a new model format
