### ISSUE TITLE
[3DS] Zombies won't attack you through Barricades.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#65]
**Describe the bug**
The zombies never attack you through the barricade letting you farm points of of repairing the barricades or letting you stall rounds.

**To Reproduce**
1. Go on any map.
2. Repair barricades with zombies behind it.
3. Hold down Select and never let it go
4. See error and a lot of points untill you hit the barricades point cap of the round.

**Expected behavior**
The zombie attacks you through the barricade.

**Screenshots/Footage**
https://youtu.be/-ZMuXZfFYgY
**Affected Platforms:**

3DS and the 2DS Family.

**Additional context**
Fix pls.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/5378bafa182f0fca5d6e44ca56a389ac87758204
