### ISSUE TITLE
[SERVER] Piercing doesn't seem to work with shotguns

### ISSUE THREAD

**Issue by bignoobus** [nzp-team/nzportable#652]
**Describe the bug**
A shot fired with any form of a shotgun will not/very rarely hit or kill multiple zombies

**To Reproduce**
1. load up a map of your choice, preferably one that has a shotgun
2. Buy a shotgun
3. get a nice long conga line of zombies and unload into them
4. find out the shotguns don't pierce and swap it out for a PTRS

**Expected behavior**
The shotgun should pierce roughly between 3 - 4 zombies if i recall correctly

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/105007743/b29199e6-d804-436c-923e-fd5fd42c0b34

as seen in the video, I use the M1911 for a bit, it (kinda) pierces the normal 2, but the shotgun doesn't pierce anything at all.

**Affected Platforms**
So far ive seen it occur on: 
*FTEQW [Windows etc etc]*
*PSP*
I however did not test on any ds or switch at all.

**Additional context**
Sometimes when they get ***REALLY*** bunched up you could score multi kills but i believe thats because of the pellets, still something to watch out for.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/818ccac2c7a09d408d21f7492a69ff423214be0c
