### ISSUE TITLE
Multiplayer Port forward ... which port?

### ISSUE THREAD

**Issue by Siccity** [nzp-team/nzportable#653]
Which port do i need to forward to play online? I have a static IP and doing this would be easy if i knew the ports used by the game, but i can find no mention of this anywhere.

**Comment by MotoLegacy** [comment]
Default FTEQuake port is 27500, NZ:P doesn't change it.

**Comment by Siccity** [comment]
I suggest you add it to the documentation somewhere, or in-game. Makes multiplayer much easier
