### ISSUE TITLE
Deadshot's Price on PC

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#654]
**Describe the bug**
Deadshot's price on PC is the same as on  handhelds even though cost2 is set to 1000. also cost 2 on deadshot now shows the info of Quick Revive's description of cost2.

**To Reproduce**
1. go to any map that has Deadshot.
2. check the price on both handhelds and pc
3. see that the price is the same on both.

**Expected behavior**
Deadshot's price on pc should be different than on handhelds.

**Screenshots/Footage**
![fte-20240212154344-0](https://github.com/nzp-team/nzportable/assets/34180180/21885eb1-0467-4506-b058-174737f630fe)

![image](https://github.com/nzp-team/nzportable/assets/34180180/d61cb220-0f5b-431d-8ce9-f635ab4ea70e)

**Affected Platforms**
# PC

**Comment by MotoLegacy** [comment]
This is intentional to decrease platform parity gap -- all Perk Machines now behave as though `cost2` is a different price when in Co-Op (additionally, they can all also have purchase limitations set, hoorah!)
