### ISSUE TITLE
Fegefeuer map issue

### ISSUE THREAD

**Issue by UserWardog** [nzp-team/nzportable#658]
When I launch the Fegefeuer (wich already take a long time to launch ) and spawn my game start freezing and I hardly can move around the map,just like having high Ping issues online

When I spawn in the Fegefeuer map

Will the map stop having freeze, rollback,.. and will I manage to play normally ?

https://github.com/nzp-team/nzportable/assets/160277552/07159e5c-cec1-4618-8759-9db4555f7121

PSVITA 2000

**Comment by MotoLegacy** [comment]
Can't reproduce on latest clean version
