### ISSUE TITLE
The corner map inexistent

### ISSUE THREAD

**Issue by UserWardog** [nzp-team/nzportable#660]
By going throughout the customs map available I saw the corner map wich had no photo and clear image of the map, then I tried to launch it and my game crashed

Uploading 20240216_212806.mp4…

Will it be a new map that's not available yet or is it a bug ?
Will I play this map one day ?

PSVITA 2000

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/7e441e3ae982472076ba3dd5ad496c518d079d8f
