### ISSUE TITLE
The House map won't launch

### ISSUE THREAD

**Issue by UserWardog** [nzp-team/nzportable#664]
When I try to select and play the House map, I get the loading screen but then my game crash/stop

https://github.com/nzp-team/nzportable/assets/160277552/ecb7d24b-282b-4557-ae3a-86f2bc55ca4e

Will I be able to launch the game and play it without getting a game crash?

PSVITA 2000

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/601fe15ee8e327bfb5f353a175d6e7fe41b8073c
