### ISSUE TITLE
When you shoot while dying you don't die?? ( Interesting bug ) 

### ISSUE THREAD

**Issue by Ellis243454** [nzp-team/nzportable#665]
Describe the bug
So after dying cause of the knifing controls on 3ds I shot and wasted my entire mag only to still be alive the round didn't change after killing everyone but I'm still alive

To Reproduce
1. Load into a map
2. Shot your gun after downing without quick revive 

Expected behavior
You should "die" but your unable to move but you can look around and still knife and zombies will still come to you but can't attack you and once you kill them all the round doesn't change 

Affected Platforms

Nintendo 3DS (Old)

Additional context
I did shoot a zombie during insta kill while emptying my mag after dying so that might have also had something to do with it and I did have footage but couldn't upload it

**Comment by MotoLegacy** [comment]
Can't reproduce.
