### ISSUE TITLE
Fegefeuer map issue

### ISSUE THREAD

**Issue by UserWardog** [nzp-team/nzportable#666]
At round 5 in the Fegefeuer map, my game starts to stutter, like i am lagging in a online game with 500ping

https://github.com/nzp-team/nzportable/assets/160277552/a151a075-79c6-42cb-91ed-5e9811e16a04

Be able to play normally when I try to get High round games

To Reproduce just play until round 5 in the map Fegefeuer

PSVITA 2000

**Comment by MotoLegacy** [comment]
Can't reproduce.
