### ISSUE TITLE
Glitch to Spawn in round 2, when you restart

### ISSUE THREAD

**Issue by UserWardog** [nzp-team/nzportable#667]
I was playing with my knife at round 1 and died while picking the nuke power up, decided to restart and ended up spawning in round 2 with the 400points bonus from the nuke power up 

NO Footage

To reproduce

Take the Nuke power Up when there is only one zombie or the right amount to kill to go to the next round when they are all dead and restart your game

PSVITA 2000

**Comment by MotoLegacy** [comment]
Could not reproduce
