### ISSUE TITLE
[SUGGESTION] To had a new page into the menu and organize 

### ISSUE THREAD

**Issue by UserWardog** [nzp-team/nzportable#668]
I was playing and saw a Pro tip explaining that I could create my own map, 

shouldn't we put a page in the menu explaining how can we do that, in the customs map menu
And shouldn't we re organize everything there ? 

For exemple in the custom map menu : 

CUSTOM MAPS 

Custom map By NZ:P Team
Custom map By the Community
-------------------------------------------------------
How to make a custom map

...And for the SOLO menu no idea but yeah it looks decent

**Comment by MotoLegacy** [comment]
if its made by nzp team, its not a custom map....

additionally, https://docs.nzp.gay/

**Comment by UserWardog** [comment]
What about the guys that don't know about the discord and everything who are just playing for fun but wants to make a custom map ?

Shouldn't we inform them,in the menu, that a discord or github exist for the ones who wishes to get information about the 
" how to make acustom map "
