### ISSUE TITLE
Old Bugs PSP version

### ISSUE THREAD

**Issue by Yoi003** [nzp-team/nzportable#669]
The game is a gem, very good maps, especially the custom maps, the weapons are incredible but... they must continue working on it, I have realized that there are still bugs that existed from the first versions of the game and they have not yet been fixed. solved, I am referring to the bug that the zombies get stuck, they go straight against the wall, they do not know how to follow the player and they do not know how to go around obstacles such as walls, the performance has improved a lot but they must continue improving it, on the Kino der Totem map the box appears in an incorrect position, there are custom maps that are still unplayable, they must be finished or else eliminated until they are finished, like Corner that cannot be played, I really like the game but they must continue improving it

**Comment by Yoi003** [comment]
Then you aren't going to fix the bugs 😑?

**Comment by BCDeshiG** [comment]
A lot of the bugs you listed have already been reported or aren't relevant.
Also please keep issues concise (one bug report per github issue).

**Comment by MotoLegacy** [comment]
> A lot of the bugs you listed have already been reported or aren't relevant.
> 
> Also please keep issues concise (one bug report per github issue).

aka, follow the template that github holds your hand through...

**Comment by Yoi003** [comment]
Well sorry but try to fix that bugs because they are annoying 🙈
