### ISSUE TITLE
Invalid Selection in the Map Selection Menu crash

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#67]
**Describe the bug**
Selecting an invalid selection due to an empty Menu of the maps and trying to start it crashes the 3DS/2DS Family

**To Reproduce**
1. Go fill up only 1 Menu of maps. (Maybe unneeded)
2. Go to the next menu.
3. Unselect „Next Menu“.
4. Press A.
5. Crash.

**Expected behavior**
Starting the Invalid Selection should do nothing or put you to the main menu to avoid issues.

**Screenshots/Footage**
Got none sorry.
**Affected Platforms:**

# Please make note of any platforms you DID NOT test on.

Old 3DS and the 2DS Family.

**Comment by Paindeluxe** [comment]
I have no idea why I just randomly Filled up a menu unintentionally and then tried this but NEW BUT BOIISSSS

**Comment by Paindeluxe** [comment]
Note Step 3 is obsolete

**Comment by MotoLegacy** [comment]
fixed https://github.com/nzp-team/glquake/commit/d1b6f95a4548b2e24eaddecd0688b9c7c8c9c983
