### ISSUE TITLE
Ps vita issue analogue in certain games

### ISSUE THREAD

**Issue by GrosBg** [nzp-team/nzportable#672]
i downloaded nazi zoimbie via vpk, on my ps vita.
once in the game's menu, my ps vita controllers don't work, whereas in the other games there's no problem with the controllers, i can move as i wish. 
I can't choose anything... 
this controller problem also persists in games such as risk of rain (ps vita).

thx u for ur awnsers...

**Comment by GrosBg** [comment]
wich ones ?

**Comment by BCDeshiG** [comment]
I wouldn't know what plugins you have installed on your vita but try disabling  all of them first and if that works, then re-enable them one by one until you find the one that breaks things.

**Comment by GrosBg** [comment]
you Had right , i love u so much bro
