### ISSUE TITLE
TrenchBroom Profile Issue

### ISSUE THREAD

**Issue by Mx-Crowe** [nzp-team/nzportable#678]
### Discussed in https://github.com/nzp-team/nzportable/discussions/676

New TrenchBroom Profile introduced a new problem with TrenchBroom. I've attached a screenshot of the error message it is showing me.

![310698677-874240a7-36aa-42a2-8f4a-cf9c49c84d97](https://github.com/nzp-team/nzportable/assets/162517385/f98d9a90-aef8-4ee4-a030-9c549a2c3d52)

<div type='discussions-op-text'>

<sup>Originally posted by **Mx-Crowe** March  6, 2024</sup>
I'm trying to get Trenchbroom working with the NZ:P Profile that's on the landing site. When I tried to restart Trenchbroom to get it working and load the compiler, it gave me this error message: 

"Some game configurations could not be loaded. The following errors occurred:
Failed to load game configuration file 'nzp\GameConfig.cfg': At line 2, column 16: Unsupported game configuration version 5; valid versions are: 7, 8"

I even re-downloaded both Trenchbroom and the NZ:P Trenchbroom profile to try and get it working, but nothing I've tried has worked. Any help would be appreciated. I've also attached an image of the error message in case that helps.
![Capture](https://github.com/nzp-team/nzportable/assets/162517385/44295944-71dc-4bb2-8827-f30f77d97fae)
</div>

**Comment by eGax** [comment]
I will take a look at this right now for the team if they don't mind. :)

**Comment by Mx-Crowe** [comment]
@eGax Only change that I see was fixing the Version from 5 to 7. Nothing regarding the "Expected Map Entry: 'root'" issue though. If you know the fix for this I'd really appreciate if you could share.

**Comment by MotoLegacy** [comment]
Sorry about that! Fixed for real with https://github.com/nzp-team/trenchbroom-profile/commit/f1eefb888794230e99747422eeac6e394f8cba83

**Comment by Mx-Crowe** [comment]
![image](https://github.com/nzp-team/nzportable/assets/162517385/44a46174-95c0-4e0f-a127-910cc7472717)

It works now :D

Thank you ^.^
