### ISSUE TITLE
Double movement speed oversight

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#679]
On 3DS, when I hold up on the analog stick and press X, my character moves at a faster speed than they would be able to usually!

This is on a new3DS, if that makes any difference to controls.

**Comment by VuduFOX** [comment]
Is this while in a sprint, or in a walk? Because sprinting is an implemented feature.

**Comment by LexiAshe** [comment]
Sorry, let me clarify and add some things I forgot to mention in the original post!

this is when walking, yes. If I hold up on the analog stick and press the X button, the sprint animation doesn’t play and the movement speed is still increased.

this also works with other directions too. For example, if I hold up on the analog stick and press the B button, the movement speed is massively reduced 

I think I can also do this while sprinting to get an extra speed boost, but the boost isn’t as pronounced as it is when just walking!

**Comment by LexiAshe** [comment]
Sorry, misclicked <_<

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/glquake/commit/ea706d1aa9834771fc45ddb6d0d885d9abde1ef2
