### ISSUE TITLE
[3DS] Restarting a map doesn’t fully reset the map.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#68]
**Describe the bug**
It’s just like #59 

**To Reproduce**

Bootup Boxxer buy the door and open the other half restart and save points 

**Expected behavior**
The maps loaded up just like picking it from the map selection screen.

**Affected Platforms:**
3DS and 2DS Family
# Please make note of any platforms you DID NOT test on.

O3DS and the 2DS Family.

**Comment by MotoLegacy** [comment]
closing as this is aware of being a duplicate of issue #59
