### ISSUE TITLE
[SUGGESTION] Different Models between the two double barrels

### ISSUE THREAD

**Issue by VuduFOX** [nzp-team/nzportable#681]
**Describe your suggestion**
The full sized double barrel shotgun should be an over-under shotgun while the sawed-off remains as a side-by-side.

**Expected behavior**
This would generally be just a cosmetic change, unless spread patterns need to be changed.

**Screenshots/Footage**
I don't have any, besides I believe you know what I mean.

**Additional context**
Add any other context about the suggestion here.

**Comment by MotoLegacy** [comment]
Defies WaW parity, closing
