### ISSUE TITLE
Port xbox original or PS2 Wii [SUGGESTION]

### ISSUE THREAD

**Issue by zhoratxd** [nzp-team/nzportable#683]
Hello, I have a question: is it very simple or would it be too complicated to port that game for the PS2 Wii or original Xbox consoles?  I would like to see this game on one of those consoles and also see and know if they can make a local multiplayer/split screen mode for those consoles or for the same PC version, which is the most versatile.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/nzportable/discussions/592
