### ISSUE TITLE
Improper hunk management

### ISSUE THREAD

**Issue by LexiAshe** [nzp-team/nzportable#691]
Working on my new map, but am running into memory issues on 3DS where the game will crash. Bottom screen produces this error message: _Sys_Error: Mod_Extradata: caching failed_

Steps to Reproduce:

Either:
1) Buy Quick Revive
2) Buy Trench Gun or STG off of wall

![IMG_5189](https://github.com/nzp-team/nzportable/assets/139988968/692c3fd0-d47f-4074-8da3-e526b7bf5fe2)
![IMG_5188](https://github.com/nzp-team/nzportable/assets/139988968/3e6269c9-e122-40ea-9955-2549c4923c8f)
ortable/assets/139988968/35db00d4-a57a-4129-ba67-68a06c91c216)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/glquake/commit/7ac48429491ad480548cde3d4ff76e726ede63ec
