### ISSUE TITLE
Flame Thrower on Insta kill

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#697]
**Describe your suggestion**
when insta kill is active. it'd be great of zombies died as soon as they're set on fire. not as soon as you get points for setting them on fire

**Expected behavior**
when insta kill is active. zombies insta die when set on fire.

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/34180180/a1a9a675-b730-45fe-961f-7e66dcfc7f9f

**Additional context**
it was something WaW did for sure.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/bc2aec1a96a506d8f8cd9916e920c88886baa29c
