### ISSUE TITLE
Buying ammo changes secondary reserve ammo

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#70]
When buying ammo for your primary weapon, it also changes the reserve ammo for your secondary.
This allows you to obtain much more ammo than intended or can end up removing ammo from your secondary.
![image](https://user-images.githubusercontent.com/29164668/205494991-facdac62-1a02-44a4-97ab-6c42017a2d81.png)
[Video demonstration here.](https://youtu.be/oz5TcNZdbeo)

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/a53ad310f4fb4afdd2ddde00e22cc7d7a7b7c569
