### ISSUE TITLE
[SUGGESTION] Blood Splatter

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#700]
**Describe your suggestion**
would be neat if shooting zombies also creates blood splatter on walls/floors

**Expected behavior**
when shooting zombies with bullets or their limbs getting shot off. their blood will splatter on surfaces like walls or floors.

**Additional context**
just thought maybe the game needs a tad bit more gore at least.

**Comment by MotoLegacy** [comment]
This is off the table due to how expensive decal rendering is, sorry
