### ISSUE TITLE
Ching.wav sound precaching not working

### ISSUE THREAD

**Issue by Bobthebob5** [nzp-team/nzportable#702]
Describe the bug
When repairing barricades or grabbing an item from the mystery box a string appears on top saying ching.wav pre caching not working 

To Reproduce
On 3ds or psp with my map I created it gave this error 

Expected behavior
This string should not appear and the audio should simply play

Screenshots/Footage
![IMG_9768](https://github.com/nzp-team/nzportable/assets/167271269/06416539-67ed-4ca8-b564-93838aa843ba)

![IMG_9769](https://github.com/nzp-team/nzportable/assets/167271269/210b011f-b759-4d78-bcee-c6128c9f9cd6)

Affected platforms
I tested and saw this on new 3ds and psp ( using ppsspp)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/3dffb7f24560930a11099a7277ccd6f392e40b22
