### ISSUE TITLE
Loading house in PPSSPP [SERVER]

### ISSUE THREAD

**Issue by JustinKyle11** [nzp-team/nzportable#703]
**Describe the bug**
The map house won't load in PSP.

**To Reproduce**
1. Go to the Menu.
2. Select 'Solo'
3. Select the map 'House'
4. Press START multiple times while loading.

**Expected behavior**
Map will not load, then by pressing start, the HUD will glitch

**Screenshots/Footage**
https://github.com/nzp-team/nzportable/assets/96884191/92480526-bc2a-4bca-9fc7-ac5e2019dbc5

https://github.com/nzp-team/nzportable/assets/96884191/a9ea23ed-bced-4ec2-8bc8-a1b5cbb49875

**Affected Platforms**
PSP (PPSSPP)

Have not tried with other devices such as :
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**
None

**Comment by MotoLegacy** [comment]
Why no log? Please share the log.

**Comment by MotoLegacy** [comment]
User confirmed to be out of date, issue not present in shipped builds.
