### ISSUE TITLE
[SUGGESTION] misc_model targetname

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#705]
**Describe your suggestion**
giving a misc_model a targetname will cause the model to now show up. i assume its intended. so my suggestion is to have it so that when giving misc_model a targetname. it does not cause the model to vanish unless something targeting it triggers. like a door or something.

**Expected behavior**
giving a misc_model a targetname will not cause the model to be removed unless triggered.

**Comment by MotoLegacy** [comment]
`misc_model` is made to be compatible and was sourced from [progs_dump](https://github.com/progs-dump-dev/progs_dump), so changing behavior of this entity would cause compatibility issues with `progs_dump` itself. It's also possible this is a bug, so feel free to investigate whether or not PD behaves the same way and re-open if that is the case. 

NOTE: There are some spawnflag controls for starting hidden and toggling activity. Did you give these a look? :)

**Comment by Revnova** [comment]
the spawnflags only have the option to start the model hidden. and alrighty then.
