### ISSUE TITLE
Menu displays incorrect build date

### ISSUE THREAD

**Issue by YoiAlex** [nzp-team/nzportable#707]
Why the PSP version keeps in the version 1.0?

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/dquakeplus/commit/6b69210d0337699ad8854ed92344bb089cb6d234

**Comment by YoiAlex** [comment]
Thanks for fix it but look at the image of those maps don't appear 
![Screenshot_2024-04-28-11-52-58-261_org ppsspp ppssppgold](https://github.com/nzp-team/nzportable/assets/167627556/275fff74-6a40-4099-b14d-553d875d1e0e)
![Screenshot_2024-04-28-11-53-09-417_org ppsspp ppssppgold](https://github.com/nzp-team/nzportable/assets/167627556/840944c5-9acb-45f2-b9fa-4bf76b844741)
![Screenshot_2024-04-28-11-53-28-751_org ppsspp ppssppgold](https://github.com/nzp-team/nzportable/assets/167627556/feb7d76b-07a5-4efd-93ea-ecf50621b516)
