### ISSUE TITLE
[SERVER] Barrel won't explode if hit by explosives

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#71]
No matter how much you shoot an explosive barrel with explosive weapons (e.g. Ray gun, Panzerschreck, Grenades etc.), the barrel will never explode.

1. Load up a map with explosive barrels (NDU and B1ooDv4).
2. Obtain a weapon that deals explosive damage.
3. Shoot barrels with said weapon.

**Expected behavior**
The barrel should explode.

Video demonstration:

https://user-images.githubusercontent.com/29164668/205504397-fe4cb7d9-8122-44ec-a9fa-db6cfd2c6148.mp4

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/327c9cdc43f2cdeda4926f2f2b9a2155808af885
