### ISSUE TITLE
Points and Scoreboard on Co-op

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#714]
**Describe the bug**
when a player is out of view to the point where you can't see their name. their points on the side of the screen also disappear. same with the bar their stats are on when you open up the scoreboard.

**To Reproduce**
1. play a game with another person.
2. play enough to where you can buy some doors.
3. one of you stay at spawn while the other goes to the other side of the map
4. see that every evidence of them disappears.

**Expected behavior**
the points and scoreboard should still be visible when a teammate are out of view

**Affected Platforms**
# FTEQW

**Comment by MotoLegacy** [comment]
Can't reproduce with the steps provided

<img width="1790" alt="image" src="https://github.com/nzp-team/nzportable/assets/26030250/36605511-b46e-430b-831f-fbf27f81a154">

**Comment by DerpedCrusader** [comment]
You can see the player name above their head, which means they are still loaded in where you're standing?

**Comment by MotoLegacy** [comment]
> You can see the player name above their head, which means they are still loaded in where you're standing? 
> 
> I could be wrong, but the original post should have been worded to make sure to specify it's when the other player is in an area unloaded, where the name above the head would disappear,
> 
>  which is intended behavior 
> 
> But the points/scoreboard shouldn't disappear 

I am taking this screenshot in an enclosed box in a completely different PVS, from across the entire level. There are no indications of the client being unable to get the state of other clients. The scoreboard remains visible and so to is the client name, as shown in the screenshot.
