### ISSUE TITLE
Zombies Spawning at Origin when no spawns exist/are active

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#720]
**Describe the bug**
Zombies spawn at world origin and die on the spot if there is no zombie spawn currently active.

**To Reproduce**
Steps to reproduce the behavior
Easiest method:
1. create a test map of your own at or near origin.
2. have no zombie spawns or make all zombie spawns inactive.
3. Compile map and open in NZP.
4. See zojmbies spawn and die on the spot.

**Expected behavior**
zombies should not spawn at all

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/34180180/aec2d71d-81f1-420d-b3b9-7ee58a42f07d

**Affected Platforms**
# FTEQW

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/5e2b8026354580172e2afa8d5769c69774fb13d3
