### ISSUE TITLE
Can't Move Waypoints

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#721]
**Describe the bug**
when in waypoint mode. you can not move waypoints.

**To Reproduce**
1. Go to any map with waypoints.
2. Go into waypoint mode.
3. Load waypoints.
4. Select a waypoint.
5. Use key shown on screen to move waypoints
**Expected behavior**
you should be able to move a waypoint when one is selected.

**Affected Platforms**
# FTEQW

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/6c7cad8e515dd91f1f00abfa6eeb55f4db81aff4
