### ISSUE TITLE
Continues sprinting even when I'm not moving

### ISSUE THREAD

**Issue by ALIENxGITHUB** [nzp-team/nzportable#722]
I find it that my character continues to sprint a second after I stop, and it causes me to make misinputs. Like, whenever I'm running up to a zombie to knife them, I end up dolphin diving into them and die. Also, I am able to sprint on all directions. Although, I'm not sure if this is intentional.

**To Reproduce**
Just sprint and stop moving. You'll see that your character continues to sprint.

**Expected behavior**
I expect the character to stop sprinting whenever I stop moving, pull a grenade out, ADS, or melee/ knife.

**Screenshots/Footage**
If applicable, add screenshots or a video to help explain your problem.

**Affected Platforms**
I've only had this issue on a New 3DS XL, and I haven't tested it on any other platforms.

https://github.com/nzp-team/nzportable/assets/157551843/146f488e-8ace-4539-9406-cdecc52fcbd3

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/97a69ef6920700f374f12bb51d266bf6c72d5b1a
