### ISSUE TITLE
Entering Last Stand while not standing gives incorrect view height

### ISSUE THREAD

**Issue by LancelotTempest** [nzp-team/nzportable#723]
**Describe the bug**
My pov is near the ground
Being able to run and prob jump in my lying position 

**To Reproduce**
1) Have the quick revive
2) while lying on the ground you have to get killed by the zombies around you 

**Expected behavior**
When I die and get revive I want to be able to play normally without being in a lying position 

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/169270229/c6becbc9-c96f-44a7-b411-4e2d86403a1b

**Affected Platforms**
I only play on PSVITA 2000

**Additional context**
I was playing on the ???? map ( a small map that I forgot the name of)

**Comment by MotoLegacy** [comment]
Can't reproduce, feel free to re-open if you're able to give consistent reproduction steps.
