### ISSUE TITLE
PaPed Flamethrower Sound

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#724]
**Describe the bug**
the sound for the M2 Flamethrower Pack a Punch uses the PaP Firing Sound when it shouldn't.

**Expected behavior**
it should not use the PaP firing sound when using the flamethrower Pack a Punched.

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/34180180/3387e32e-79c9-411e-9cf2-768052621b61

https://github.com/nzp-team/nzportable/assets/34180180/a6583b81-c7a2-43b8-83fc-68e97adeaa1b

**Affected Platforms**
# FTEQW. Possibly all others too...

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/dcf6ab7809a5bbb472a417fd111be538d377ca2a
