### ISSUE TITLE
Give command no longer works

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#73]
The give command just outputs entity information  now:
![fte-20221204115636-0](https://user-images.githubusercontent.com/29164668/205525501-20f1cca4-228a-415d-880b-d32598bcac73.png)

1. Load up any map.
2. Open up console commands (`~`).
3. Type in `give 33`.
4. Hit the `Enter` key.

**Expected behavior**
The player should receive an upgraded raygun.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/7702f79b3586a5ec9c03853efdd6eb694e51eaf7
