### ISSUE TITLE
Achievements don't unlock

### ISSUE THREAD

**Issue by Reznar705** [nzp-team/nzportable#730]
### Achievements do not unlock

**To Reproduce**
Steps to reproduce the behavior **(we'll use the achievement "ready" for the example)**:
1. go into any game
2. reach round 5
3. you should unlock the achiement "ready"
4. however upon checking your achievements it simply does **not unlock**

the only version i use and have knowledge over is the browser **webGL** version
so I dont know if this relates to other versions

**Comment by MotoLegacy** [comment]
Works as intended, was added due to the inability to save them anyway. Ended up forgetting about this, made it more clear with https://github.com/nzp-team/quakec/commit/3ad99583df04da01e438f784e982232c5fa94c20
