### ISSUE TITLE
[SUGGESTION] Downloading the Web version to play locally.

### ISSUE THREAD

**Issue by nthclick** [nzp-team/nzportable#731]
**Describe your suggestion**
I would like for us to download the web version locally so that it can be played on machines that have both blocked the website which hosts the web version and that have blocked running unrecognized executables.

**Expected behavior**
I want for the web version to be downloaded and stored locally and to be ran by opening the .html file in a browser. As I've found that most games, that have a web version ,can be easily downloaded, stored locally and ran by opening the html file in a browser.

**Comment by MotoLegacy** [comment]
People with enough willpower to be a poor student in school and rather play the web versions of NZ:P will discover the fact that the web version in its hosted form is, in fact, stored here on GitHub in a downloadable and subsequently runnable form.

**Comment by Reznar705** [comment]
I love this idea since im generally to dumb to be able to figure out how to download this game, and an html file sounds like a great idea!

**Comment by Peter0x44** [comment]
> As I've found that most games, that have a web version ,can be easily downloaded, stored locally and ran by opening the html file in a browser.

This is not possible with emscripten, afaik. It needs a web server to function, which if you know how to use/install isn't any less effort than downloading an executable.
