### ISSUE TITLE
[FTE] Lunge Out of the Map

### ISSUE THREAD

**Issue by NZKorn** [nzp-team/nzportable#733]
**Describe the bug**
Simple. Knife a zombie falling on you and hope that you lunge, which will shoot you into the air, breaking you out of the map. All you have to do to get back in is walk in.

**To Reproduce**
1. Go to any of the zombie spawns and wait for a zombie to spawn.
2. Knife the zombie as it is falling and pray that you lunge at it.
3. Hold W as you are lunging.
4. You're outside of the map.

**Expected behavior**
I expected to knife the zombie and kill it.

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/164850642/9db96df9-6575-4115-bff3-b67200df833d

**Affected Platforms**
# Bug occurred on Windows.
# I don't know if this works on any other platform.

**Comment by NZKorn** [comment]
I forgot to mention, the map is Blood 4.

**Comment by Reznar705** [comment]
odd

**Comment by blubs** [comment]
Intended functionality for WaW parity /s
