### ISSUE TITLE
[SUGGESTION] Medal of Honor Heroes style turn speed on PSP

### ISSUE THREAD

**Issue by masterpl4n** [nzp-team/nzportable#738]
**Describe your suggestion**
In Medal of Honor: Heroes for the PSP, there was a control feature where if you double clicked then held down one of the look buttons quickly, you would be able to look around much faster until you let go. This is helpful in combat scenarios by balancing speed of turning with fine tuned aim accuracy. I believe this would work well in NZP for similar reasons.

**Expected behavior**
Control settings on NZP PSP has an option to enable this, possibly just for face button looking or for analog nub looking as well. Works similarly to how it does in Medal of Honor.

**Screenshots/Footage**

**Additional context**
I can send footage of this feature in action on Medal of Honor if you’d like.

**Comment by MotoLegacy** [comment]
Thanks for the suggestion, face button look is very much a legacy feature though that I'm not looking to expand, since a-nub look is generally much better suited for the gameplay. Neat feature though!
