### ISSUE TITLE
[PC] Scroll Wheel Fast Fire

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#74]
If you scroll the mouse wheel (change weapon) while firing full auto weapons (as well as the PTRS and Wunderwaffe) then you can shoot much faster than intended. This does not apply to semi-auto/bolt action weaponry.

https://user-images.githubusercontent.com/29164668/206018022-cfde2ff5-0c28-42df-b24f-60aedac1d99c.mp4

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/ad4f0a8963bc515d9a762017ffc18bfda36cb9ca
