### ISSUE TITLE
Reduce lunge, extend range

### ISSUE THREAD

**Issue by HakuM8** [nzp-team/nzportable#742]
**Describe your suggestion**
I was hoping that when knifing a zombie, the lunge wouldn't be so far forward. And extend the range of the knife by just a little bit I guess.

**Expected behavior**
Lunge will stop in front of the zombie, not behind it, akin to actual COD

**Comment by HakuM8** [comment]
This applies for PSP. Dunno if the other ports got this as well.

**Comment by nnnnt21** [comment]
> This applies for PSP. Dunno if the other ports got this as well.

Web version faces same issue, and zombie's attack the instant you get in their range, there"s no "wind up" for the zombies swing>

**Comment by HakuM8** [comment]
Would it be possible to replicate the knifing of the 1.0 version, where the lunge isn't as intense?

**Comment by MotoLegacy** [comment]
Can you clarify what you're expecting a bit here? The high lunge and range is modeled after Black Ops. Closing for now, re-open if you continue the discussion.
