### ISSUE TITLE
No pack a punch animation (3ds ) 

### ISSUE THREAD

**Issue by Ellis243454** [nzp-team/nzportable#743]
Describe the bug
So this has been going on for a while but just thought it was removed for optimization but I was told to report it so the bug is there is no pack a punch animation on any map 

1. Load into a map
2. Pack a punch a weapon 

Expected behavior
There is zero animation not even a animation without texture there is nothing 

Screenshots/Footage
I sadly don't have footage 

Affected Platforms 
- Nintendo 3DS (Old)

Additional context
I don't know about any other platform it is affected on I want to assume it's the mobile platforms like psp but I'm not sure as I don't own a PSP

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/glquake/commit/39cc0a6655def6a08b9c34dacd09661b3ef6df8d
https://github.com/nzp-team/dquakeplus/commit/ce50b0f8e10d3187abf0f26383847a47c96ffc62
