### ISSUE TITLE
Electric Traps non-functioning

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#746]
**Describe the bug**
Electric traps don't zap at all (no visual effect, or damage to players/zombies)

no errors in the console

**To Reproduce**
1. Boot up warehouse
2. buy the trap when you can
3. bug should be visible

**Expected behavior**
the zapping effect should happen, and things that walk through them should take damage

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/13917665/cc4e77d5-84c3-4e79-996c-d13cb1eec1ef

**Affected Platforms**
- Nintendo 3DS (New)

(tested on FTE, but the bug wasn't present)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/4c5aded4529ba4258516f5d23552e4484aa5e2fd
