### ISSUE TITLE
Replace "HOLD" sprint key with "TOGGLE"

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#747]
**Describe your suggestion**
Parity suggestion with CoD, which uses toggle sprint by default

**Expected behavior**
Tap the sprint button to sprint, and the player will run until they stop moving, are stopped, or run out of stamina

**Comment by MotoLegacy** [comment]
User clarified off-platform this is a request for the FTE platforms.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/b9cda0f079e13d5e7555cd4c2630ff8e11fc4359 & https://github.com/nzp-team/assets/commit/d0f9f0fd468e62a19eebbf7dbb5aba1e09216bce
