### ISSUE TITLE
Massive Frame Drops 

### ISSUE THREAD

**Issue by Big-Chonky** [nzp-team/nzportable#748]
**Describe the bug**
When loaded in-game, I get massive and consistent frame drops.
Everytime I get a frame drop, the text "Default audio device changed. Restarting audio. Initiating OpenAL: Generic Software."

**To Reproduce**
1. Load into any map
2. Get framedrops

**Expected behavior**
The game to run at a consistent framerate.

**Screenshots/Footage**
![image (18)](https://github.com/nzp-team/nzportable/assets/75202248/caa85184-ce5e-4ef9-a06e-ef2335059c3e)

**Affected Platforms**
I've only tested on PC.
This does not account for any other platform.

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
Sounds to me like you have a funky audio device that's constantly (de)activating, causing OpenAL to re-initialize every time. Feel free to re-open if you can confirm this is NOT the case
