### ISSUE TITLE
[SERVER] Raygun is no longer fully automatic

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#75]
In previous builds, you could hold down the fire button to continuously shoot the raygun.
Currently, it functions like a semi-auto weapon which is a disparity with COD.
I'll need to figure out which commit the regression happened though.

**Comment by MotoLegacy** [comment]
Fixed in https://github.com/nzp-team/quakec/commit/6afcdc3ecb2da5c348242654202b879118e493ee
