### ISSUE TITLE
[SUGGESTION] Interupt Sprinting

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#753]
**Describe your suggestion**
these are ones i know is in CoD. having it so that ADS, Melee, or throwing a grenade can cancel/interrupt sprinting. it looks like for nzp shooting and crouching already do this(crouching makes you dolphin dive ofc). these are the only things i noticed thus far.

**Expected behavior**
while sprinting. pressing one of these buttons should cause sprinting to stop

**Screenshots/Footage**
# knifing while sprinting
https://github.com/nzp-team/nzportable/assets/34180180/003347d9-49f6-41d2-a788-4889fecb7a40

# ADS while sprinting
https://github.com/nzp-team/nzportable/assets/34180180/6b597bdf-bdcc-4cbc-908d-461143cffe9b

# grenade button while sprinting
https://github.com/nzp-team/nzportable/assets/34180180/b93f3992-93fa-4f4d-acd3-85c3a8f5619a

**Additional context**
i recorded on black ops. but it works the same on waw. there are probably a few more stuff that do this.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/29c1be162c663a83d772f95c74eb6dc7ff473b4c
