### ISSUE TITLE
Updated PhD Flopper Icon

### ISSUE THREAD

**Issue by PHDFLOPPERGUY56** [nzp-team/nzportable#756]
I thought the PhD Icon looked a little goofy so I fixed it in photoshop and uploaded it to other content and a team member told me I should make a pull request to make it an official change so here I am!
[gfx.zip](https://github.com/nzp-team/nzportable/files/15478363/gfx.zip)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/f5997d310a48d269667e43753904c6194371f528

**Comment by PHDFLOPPERGUY56** [comment]
Thank you!!! I thought i submitted it right but im new to github so this site is confusing to me sometimes lol
