### ISSUE TITLE
[PSP, SERVER]Dog round doesn't guarantee a Max Ammo

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#76]
was just testing my map. got a dogs on round 7. but at the end. i got a Double Points instead of a Max Ammo.

**To Reproduce**
just play casually or however you prefer. on a map that has Dogs.

**Expected behavior**
always get a max ammo

**Screenshots/Footage**
still unable to get screenshots

**Affected Platforms:**
only tested on PSP

**Comment by BCDeshiG** [comment]
Can confirm, got an instakill from dogs.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/16a77c1e0f1f1be122c912d5021ed157d6d4eb73
