### ISSUE TITLE
[CLIENT] menu music stops playing after changing graphics settings

### ISSUE THREAD

**Issue by Peter0x44** [nzp-team/nzportable#761]
**Describe the bug**
Menu music stops playing after changing graphics settings

**To Reproduce**
1. Go to 'settings'
2. Click on 'graphics settings'
3. Click on 'save and apply'
4. Observe that menu music has stopped playing

**Expected behavior**
The menu music would keep playing, or restart.

**Screenshots/Footage**
N/A

**Affected Platforms**
I only tested FTEQW. This might not be applicable to other platforms that don't have graphics settings.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/e6195276ae8ab6507962e9314d215b350dfcb43a
