### ISSUE TITLE
[CO-OP/SERVER] Names of players switch when restarting the round

### ISSUE THREAD

**Issue by AppzyCat** [nzp-team/nzportable#764]
**Describe the bug**
I was playing with two other people. When I restarted the map using 'restart' in the console (don't know if it happens when the map restarts automatically when all players die), their names would swap. If I restarted again, the names would swap back and so on. Host's name always stayed consistent. They joined using the console as well (though I don't think that matters). I've only tested with 2 others, so I don't know if it happens with more than that.

**To Reproduce**

1. Get people to join you
2. Once everybody is in, type 'restart' into console
3. Stealing somebodies identity is a crime.

**Expected behavior**
Each player keeps their name, instead of having an identity crisis.

**Affected Platforms**
This happened on PC x64 version, I haven't tested anything else.

**Comment by Peter0x44** [comment]
I noticed the color of the player's name in chat stayed consistent.

**Comment by DerpedCrusader** [comment]
I've also had this happen when multiple people connect at almost the same time, it's very hard to replicate

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/25832d650ec00bf7531f3b8c26efb5764a01b42f
