### ISSUE TITLE
Trigger_hurt doesn't make hurt sound

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#765]
**Describe the bug**
When going through a trigger_hurt and taking damage, the player doesn't make the taking damage sound

**To Reproduce**
1. go to a map with a trigger hurt 
2. walk through it and take damage

**Expected behavior**
The player should make the hurt sound

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/13917665/fcebb83c-8efd-444b-92b6-5c6046c5d895

**Affected Platforms**

Only tested on FTE

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/8b06b68c21e6c16d3d2cdbbcc96a1a2057fe4327
