### ISSUE TITLE
[SERVER] Crawlers can only be knifed while prone

### ISSUE THREAD

**Issue by Peter0x44** [nzp-team/nzportable#769]
**Describe the bug**
See title

**Screenshots/Footage**
https://youtu.be/j16LASpwZno

**Affected Platforms**
I only tested FTEQW

**Comment by Peter0x44** [comment]
https://discord.com/channels/1182081152073351228/1187590268120203304/1248081700370649219

Footage of testing in BO2 here. Zombies can be knifed both standing and crouched.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/10baffed84e97a6e74d6b36cda0dd4ea36cf8f87
