### ISSUE TITLE
[PSP. SERVER] No fog on dog rounds

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#77]
**Describe the bug**
Dog Rounds have no fog. thats just it

just play like normal on a map that has dogs

**Expected behavior**
should have dog round fog

**Affected Platforms:**
only tested on PSP

**Comment by BCDeshiG** [comment]
In my case on PC, the dog round did have fog which didn't go away afterwards.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/4b757631545a8faf4b2be642f3263d894b28797d
