### ISSUE TITLE
button mapping not working

### ISSUE THREAD

**Issue by bajelinek** [nzp-team/nzportable#773]
# [SERVER] 
# [3DS]
After switching button mapping on a new 2ds XL, then resetting to default, the screen size is set too low and the button mapping is screwed up somehow.

1. Startup nzp through the homebrew menu icon
2. Start the first level then pause the game
3. Go to settings > customize controls 
4. Bind the following keys: jump/ swim up = A, change weapon = X
5. Unpause the game
6. Shoot a dirty nazi
7. Pause the game and go to settings 
8. Select reset to defaults
9. Unpause your game
10. The attack and aim bindings as well as screen size and potentially other unnoticed settings are no longer suited for the new 2ds xl controller scheme.

**Expected behavior**
The button mapping and other effaced settings should return to the startup default settings for new 2ds xl.

**Affected Platforms**
# New 2ds xl
# no other console has been tested 

**Additional context**
I'm trying to set jump to 'B', change weapon to 'X'.

Plz hallp.

**Comment by 2mono7** [comment]
I've got to ask, have you been able to bind the knife to a button? It seems like it's not possible on a 3ds

**Comment by bajelinek** [comment]
Nope or crouch either

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/ce3f8c4950fc91f242e1cca4fc1a52907874bb65
