### ISSUE TITLE
kino der toten achievements

### ISSUE THREAD

**Issue by venatus9** [nzp-team/nzportable#777]
I would regard this more as an oversight than a bug, but regardless something isn't working.

When looking through achievements, listed are achievements regarding kino der toten - a map which isn't included in the base download.

Upon downloading kino seperately and installing, completing the goal listed on the achievement doesn't earn the actual achievement (tested with 'play 10 rounds of kino' and 'get 5 crawler kills with one trap'). I assume this is because it was downloaded seperately? But then why are the achievements listed when the map isn't included in the base download?

Nonetheless I had to cheat the achievements in myself.

This was only found and tested on windows 10.

**Comment by MotoLegacy** [comment]
Unfortunately we had a change in development plan that made the Kino achievements obsolete, the achievements system is not really earnable-ready. Sorry.

**Comment by venatus9** [comment]
Ah okay, thank you very much for elaborating. I was going insane over it!
