### ISSUE TITLE
Coop Barricade Points

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#778]
**Describe the bug**
when repairing barricades. the points should be earned individually. but in nzp, when one person repairs barricades to the point that they can't earn points anymore. other players can't earn anymore either.

**To Reproduce**
1. Go to any map with barricades
2. let zombies open a few windows
3. have one person repair barricades until they no longer earn points
4. have another player repair barricades
5. see that they don't get any points either.

**Expected behavior**
players should both be able to repair until they both reach the point. not when only one of them reaches that point.

**Affected Platforms**
# FTEQW

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/d646d7eb191e5942969cecdbe0a18d7ed854115f
