### ISSUE TITLE
Coop PaP Weapon Can Be Stolen

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#779]
**Describe the bug**
when someone PaPs their gun. if their gun is still in the Pack-a-Punch machine. anyone is able to pick it up.

**To Reproduce**
1. Go to any map in Coop with Pack-a-Punch
2. have someone get enough points to use PaP
3. use PaP
4. when the weapon is PaPed but still in the machine have another player try and pick it up
5. see that they have it now

**Expected behavior**
only the person who PaPed should be able to pick up their gun

**Affected Platforms**
# Tested on FTEQW

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/cbe69fc2699be4e72268dfd566d90997b9fa1e04
