### ISSUE TITLE
[NX] some visual bugs 

### ISSUE THREAD

**Issue by shamenlol** [nzp-team/nzportable#78]
[NX] (Nintendo Switch)
When using the scoped kar98k the scope png is in the top left corner making it look really broken and when you take damage the blood around the screen image is also in the top left corner. Also some sounds dont work like jumping and powerups dont have a green background or anything its just black and blocks anything behind it. 

Only found these bugs in the nintendo switch version.

**Comment by MotoLegacy** [comment]
fixed in various quakespasm commits.
