### ISSUE TITLE
Missing binaries in release 2.0.0-indev+20240616071911

### ISSUE THREAD

**Issue by coreybruce** [nzp-team/nzportable#781]
Hey guys your new release [2.0.0-indev+20240616071911](https://github.com/nzp-team/nzportable/releases/tag/nightly) that you did no longer has binaries while the last version 2.0.0-indev+20240611071920 which did and now this version is missing binaries on multiple architectures/OS  versions

![image](https://github.com/nzp-team/nzportable/assets/8393780/b8c63357-eb56-400f-8a69-e69e1511c7ea)

 Also please don't delete the releases history and please properly version the releases even if it's a nightly release :smile: 

Use this as an example  for nightly versioning with releases and tags 
https://github.com/ruffle-rs/ruffle/releases

Awesome project and super addicted btw :smile:

**Comment by Peter0x44** [comment]
Yikes. This is probably because we started using SDL and the names of the executables changed.
https://github.com/nzp-team/fteqw/actions/runs/9530821223
In the meantime, you can download the binary you want from here, and copy it next to the "nzp" directory.

**Comment by MotoLegacy** [comment]
fixed, new releases are up
https://github.com/nzp-team/nzportable/commit/a34fb0ae6ca9e9532535ae2a619630a21324012e

**Comment by coreybruce** [comment]
Thanks for fixing this!

Also I would recommend  on adding separate releases pages and tags instead of editing the same one if that is what your doing so users can go back to what ever version in case anything does happen or a bug exists :P 

I also wanted to make a AUR package for this and it would be so much easier to manage version to version if it had proper versioning
