### ISSUE TITLE
[SERVER] Spam ping m1 garand

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#79]
When your clip is empty, you can spam the fire button to repeatedly interrupt the reload, making the funny ping sound every time.

1. Obtain m1 garand
2. Empty the clip
3. Keep shooting

https://user-images.githubusercontent.com/29164668/208761409-e989d8b9-8402-4f93-a6f8-4547496d4551.mp4

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/efc577410eba4a6a45deaf7987b3c1cf0bf6f020
