### ISSUE TITLE
[3DS] My waypoints work on pc but not on N3ds

### ISSUE THREAD

**Issue by Cybrock9000** [nzp-team/nzportable#793]
**Describe the bug**
the zombies try to go to 0,0 instead of folowing there waypoints on 3ds, but on pc it works fine

**To Reproduce**
1.if you dont have a N3ds download citra
2.download my map https://github.com/Cybrock9000/M.R.S.-Titanic-Nzp-Map
3.watch the zombies walk into walls

**Expected behavior**
The zombies to walk on there path on the N3ds

**Screenshots/Footage**
![IMG_9852](https://github.com/nzp-team/nzportable/assets/118949998/69d11602-8e3b-4e58-973c-e47259edb5dc)
![IMG_9853](https://github.com/nzp-team/nzportable/assets/118949998/fcf487d7-8966-43ad-be8c-6ca724f4605e)
pc video: https://drive.google.com/file/d/1H_A38rb_GK3Ui7zac0NboWQlGm8n331f/view?usp=drive_link

**Affected Platforms**
i only tested it on pc (windows) and the N3ds XL

- Nintendo 3DS (New)
- FTEQW (Windows)

**Comment by DerpedCrusader** [comment]
Are you putting the waypoints into nzp/maps on the 3ds?

**Comment by Cybrock9000** [comment]
well i just copied the .way file over, i dont know how to put waypoints on the 3ds.

**Comment by Cybrock9000** [comment]
oh, wait. do you mean data/maps because when i looked on there on the pc ver there was a titanic.way file there

**Comment by Cybrock9000** [comment]
im completly redoing the waypoint system because the map got so big that i had to move the center to 0,0 or it would crash.

**Comment by Cybrock9000** [comment]
im ending this
