### ISSUE TITLE
cant join coop game with friends

### ISSUE THREAD

**Issue by forge-jpg** [nzp-team/nzportable#797]
i type in the password and the server name and im greeted with "unable to resolve server address" same thing happens on my friends side. were playing on the downloaded version

**Comment by Peter0x44** [comment]
Likely, whoever is hosting will need to port forward.
Either way, this is not really a bug but more a support request.
Discord would be a more relevant place to ask that.

**Comment by coreybruce** [comment]
Hey @forge-jpg press the ~ and type in help and use that hidden menu to create and join games as the default join menu does not work unless you type in the ip address and I could never get it to work and found the lobby server menu being way better, I don't know why this menu is a hidden menu and not a default thing as it's way better to be able to see the server menu and then have a option to insert a IP manually if you wanted to but I am sure this is all being actively worked on.
