### ISSUE TITLE
[Server] Change Weapon Rapid Fire Glitch

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#8]
Another bug that's been around for a while.
Essentially, if you hold down CTRL (change weapon) then you can shoot at absurd rates depending on the gun.

While holding the CTRL key:
Bolt action weapons (except the PTRS for some reason) require you to mash reload and the fire button.
Semi-auto weapons only require you to mash fire.
Fully automatic weapons require you to hold down the fire button.

[Video demonstration with various weapons here](https://youtu.be/m5nYerVvwzA)

**Comment by BCDeshiG** [comment]
Possibly present on other platforms too but untested

**Comment by MotoLegacy** [comment]
Confirming that this is reproducible on more platforms, title edited to reflect this.

**Comment by MotoLegacy** [comment]
Fixed in https://github.com/nzp-team/quakec/commit/8b54e632f24f5709cba1883896c7c696844c10cc.

**Comment by BCDeshiG** [comment]
The glitch can still be abused by holding the fire button before holding down CTRL [as demonstrated here.](https://youtu.be/ftmsJGjquIE)

**Comment by BCDeshiG** [comment]
Oh wait nvm wrong build
