### ISSUE TITLE
[SERVER] Degraded Waypoint targeting

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#80]
**Describe the bug**
Sometime between July 11th and now Zombies are less reliably landing on the first waypoint out of a window, and are stuck walking towards world origin

**To Reproduce**
1. load up any map (tested extensively on NDU)
2. go into and stay in a second room, and wait for zombies to stop walking towards the player
3. go into the first room, and look at a bundle of zombies running into a corner 

**Expected behavior**
I would expect the zombies to follow waypoints, and find their way to the player, reguardless of where they are on the map

**Screenshots/Footage**

![image](https://user-images.githubusercontent.com/13917665/209196864-73938a21-350a-4942-a87b-28d8ac74e40d.png)
this is a screenshot of the date of build with working waypointing

realistically, this doesn't need screenshots, but i can provide some later if needed

**Affected Platforms:**

FTE

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch
- 3DS

**Additional context**
this is not to be confused with zombies getting stuck on each other
which does still happen on some platforms

**Comment by Revnova** [comment]
zombies aren't following waypoints at all in any map. only once they see the player will they start following them.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/c8c57f25f79adbf0af258382ce8210d623c445b0
