### ISSUE TITLE
What is sys_error: allocBlock : full and how do i fix it

### ISSUE THREAD

**Issue by Cybrock9000** [nzp-team/nzportable#805]
### Discussed in https://github.com/nzp-team/nzportable/discussions/804

<div type='discussions-op-text'>

<sup>Originally posted by **Cybrock9000** June 25, 2024</sup>
The question </div>
i ment to put it in here

**Comment by DerpedCrusader** [comment]
https://developer.valvesoftware.com/wiki/AllocBlock:Full

Please Google things to make sure they're specific issues to our game
