### ISSUE TITLE
[SUGGESTION]Custom perks with machines

### ISSUE THREAD

**Issue by Cybrock9000** [nzp-team/nzportable#806]
**Describe your suggestion*
A template of a perk machine and the perk itself.

**Expected behavior*
You code the behavior in a code like python or whatever you code with and it will act like any other perk machine with your design and your custom perk.

**Comment by Peter0x44** [comment]
You would likely have to edit this file if you wanted a custom perk:
https://github.com/nzp-team/quakec/blob/main/source/server/entities/machines.qc

I'm not clear on what exactly you are asking for.

**Comment by Cybrock9000** [comment]
i think thats the file im looking for, thanks

**Comment by Cybrock9000** [comment]
where do i put it in nazi-zombies-portable-windows-x86_64, or is it not the right version

**Comment by Cybrock9000** [comment]
wait i get it. nvm what i said
