### ISSUE TITLE
[SUGGESTION] More variants of zombies

### ISSUE THREAD

**Issue by Cybrock9000** [nzp-team/nzportable#809]
**Describe your suggestion**
More variants of zombies (like the ice, fire, lightning, poison zombies variants in codbo4) to make the game more difficult later on.

**Expected behavior**
they work like the normal zombies except for the ice one
ice: runs at the closest zombie and increases there health from 100% to 150%
fire: just like the classic but explodes when close
lighting: shoots a lighting beam that hurts the player (not accurate to codbo4)

**Screenshots/Footage**
could not find any :(

**Additional context**
this might be asking a little much but plz do add another variant to the game

**Comment by DerpedCrusader** [comment]
This project is focused on being a re-implementation of WaW, features like this are far out of scope
