### ISSUE TITLE
Alpha is clipped on `moneyback` UI element

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#815]
**Describe the bug**
Only the fully fully opaque parts of the Points background show on in the UI

**To Reproduce**
1. open weapon test
2. look into the bright light to see the contrast best

Using a [modified Points background](https://archive.org/download/points_202406/Points.zip)

**Expected behavior**
to have the full range of alpha displayed

**Screenshots/Footage**
How it looks on the Vita:
![2024-06-26-212239](https://github.com/nzp-team/nzportable/assets/13917665/09845ac4-9917-4d50-8544-70ed4eec489a)
How it looks on other platforms
![image](https://github.com/nzp-team/nzportable/assets/13917665/d3efac89-a352-44cc-a49c-f0529e71cce2)

**Affected Platforms**

- PS Vita (1k, 2k)
- (presumably) Nintendo Switch

Only tested on vita

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakespasm/commit/cc0a33ccecdbd5cff54dcc3104146a2a2fc750ac
