### ISSUE TITLE
[SUGGESTION]Uhm i dont know if its a bug or suggestion but

### ISSUE THREAD

**Issue by GokuSuper120** [nzp-team/nzportable#819]
I would like that the console commands openned to portuguese or another keyboards language i just get to the console commands changing my keyboard to english version and i confuse everything

**Comment by Peter0x44** [comment]
I think it's a duplicate of:
https://github.com/nzp-team/nzportable/issues/95
We don't support any translation currently, subscribe to that issue if you're interested.

**Comment by GokuSuper120** [comment]
> I think it's a duplicate of: #95 We don't support any translation currently, subscribe to that issue if you're interested.

Yeah its almost that is just that i want the keybinds to commands the same like to get to this ` i need to do shift + ´ but if i do that i cant get to the console commands
