### ISSUE TITLE
[CO-OP/SERVER] When multiple players revive 1 downed person, the second reviver gets stuck

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#82]
**Describe the bug**
When a player is downed, and 2+ people attempt to revive him, once the first finishes, the others will freeze in place

**To Reproduce**

1. Player 1 goes down
2. player 2 starts reviving
3. player 3 starts reviving a second later
4. player 2 finishes reviving player 1
5. player 3 is stuck and cannot move

**Expected behavior**
I would expect player 3's revive to be canceled once player 1 has been revived by player 2

**Screenshots/Footage**
sadly, I don't have any footage atm because i would need multiple testers to get footage, but it did happen 3 times

**Affected Platforms:**

only tested on WebGL

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/c16629e04a60c745f206ebb7551515213af55bbd
