### ISSUE TITLE
[BUG] Invincible dogs on latest release of PC version 

### ISSUE THREAD

**Issue by Tktyt13** [nzp-team/nzportable#820]
On the dogs round of every map (round 5/10 (can't get higher than that due to the bug im mentionning)) the dogs are basically invincible unless we're downed with quick revive. And sometimes the dogs don't have the fire on them.

**Comment by Peter0x44** [comment]
I have a vague memory of playing and only being able to kill does with explosives (m&s) although it doesn't happen every time.

**Comment by DerpedCrusader** [comment]
Cannot reproduce

https://github.com/nzp-team/nzportable/assets/13917665/ad1193cd-1998-4bf2-ad13-fa351c937cc3
