### ISSUE TITLE
[MAP] Nuketown or Kino der Toten Zombies 

### ISSUE THREAD

**Issue by Tktyt13** [nzp-team/nzportable#821]
Please add Nuketown zombies or Kino to the game especially kino bc there's achievement for it but the map isn't there
<img width="575" alt="image" src="https://github.com/nzp-team/nzportable/assets/113549057/704f19ed-59f2-4664-9266-79c6888ba467">

**Comment by headachez** [comment]
the map is in the game in the custom maps tab, its just a wip (its mostly playable just a few issues here and there)
also if you want nuketown just make it yourself there a guide at https://docs.nzp.gay/landing/#mapping-modding-documentation

**Comment by DerpedCrusader** [comment]
https://github.com/nzp-team/nzportable/discussions/708

There's a kino release available
