### ISSUE TITLE
tree_swamp.mdl has broken transparency

### ISSUE THREAD

**Issue by acronmd** [nzp-team/nzportable#824]
**Describe the bug**
The prop ```tree_swamp.mdl``` has broken transparency in trenchbroom and in-game

**To Reproduce**
1. Create a place_model
2. Set ```model``` to ```models/props/tree_swamp.mdl```
3. See error

**Expected behavior**
The peach-ish color to be transparent

**Screenshots/Footage**
![image](https://github.com/nzp-team/nzportable/assets/78101120/4ae3f89c-8ff5-4584-aad6-0b09d4d1c141)

![image](https://github.com/nzp-team/nzportable/assets/78101120/0a88bd31-0103-4607-8c96-b640565f92da)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.

Only tested on FTEQW but since its broken in trenchbroom I assume this affects every other platform

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/9a1952eb13f6e072cf1865de2f705dbe1bf677f1
https://github.com/nzp-team/quakec/commit/143ee16c792d10bedaab8226b131ae1018e7506a
