### ISSUE TITLE
ambient_generic keeps looping sound

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#825]
**Describe the bug**
ambient_generic keeps looping .wav when the "start silent" spawnflag is disabled. triggering it with anything will not stop it.

**To Reproduce**
1. create a quick simple map
2. add ambient_generic with the track of your choice
3. do not enable "start silent" spawnflag.
4. hear that the sound will loop

**Expected behavior**
shouldn't always loop

**Screenshots/Footage**
![image](https://github.com/nzp-team/nzportable/assets/34180180/2f67d328-7203-43bf-8b30-bb401032dfa3)

https://github.com/nzp-team/nzportable/assets/34180180/02bb19cf-97c3-46a8-a76f-69c8b54e4bbd

**Affected Platforms**
# only tested on fte

**Comment by MotoLegacy** [comment]
Isn't the "Not looping" spawnflag supposed to achieve this desired effect? Feel free to re-open to clarify if needbe.
