### ISSUE TITLE
[SUGGESTION] Let radios fire triggers after being interacted with

### ISSUE THREAD

**Issue by acronmd** [nzp-team/nzportable#829]
**Describe your suggestion**
Have an option for radios to fire a trigger when interacted with.

**Expected behavior**
After being shot, fire a trigger if the target field isn't null, optionally set to fire once or multiple times.

**Screenshots/Footage**
![image](https://github.com/nzp-team/nzportable/assets/78101120/607f6d50-c9d9-425a-89c4-4ea272c742d4)

**Additional context**
Could be useful for map makers who want to tie any kind of event or "progression" with radio completion.

**Comment by DerpedCrusader** [comment]
I think it'd also be nice to be able to activate a radio with a trigger

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/3a991477aee2b49253cae2447f83e1001fea18f9
