### ISSUE TITLE
[CO-OP/SERVER] Downed players don't bleed out

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#83]
**Describe the bug**
when a player is downed, they don't slowly bleed out, and effectively have infinite revive time

**To Reproduce**
1. Die
2. Wait
3. cursed with immortality 

**Expected behavior**
I would expect the downed player to die after around 45 seconds

in included footage, it does hit the 45 second mark, but only barely, in testing, we had a player wait multiple minuets 

**Screenshots/Footage**
Have to use a youtube link, because the file is too large to put in github

https://youtu.be/KhvHcjE1NNw

**Affected Platforms:**

# Please make note of any platforms you DID NOT test on.

Only tested on WebGL build

**Comment by Paindeluxe** [comment]
Players can bleed out when I was playing with my friend he bled out in 20-30 seconds but the revive sign didn't change colors.

**Comment by Paindeluxe** [comment]
Bleeding out _may_ be ping related as my friend had no ping issues we were also playing on the web version

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/54d857232109b30cbe29d1bfb1401e7413ff25f7
