### ISSUE TITLE
Models reset to frame 1 when turning on interpolation

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#835]
**Describe the bug**
When walking up to an animated model, it'll flicker to its first frame and then back to where it should be 

this happens when it switches from not having interpolation, and then it turning on

**To Reproduce**
1. boot NDU
2. wait for barricades to break down
3. walk from spawn area to the other end of the first room
4. you should see the barricades twitch to fully repaired

**Expected behavior**
It'd stay on the existing frame when it transitions

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/13917665/bed0aabc-e53a-4342-8677-b08b39e9fe47

**Affected Platforms**

- Nintendo 3DS (Old, New)

**Comment by DerpedCrusader** [comment]
It seems like the interpolation was disabled when combining the PSP/3ds engines

**Comment by MotoLegacy** [comment]
> It seems like the interpolation was disabled when combining the PSP/3ds engines

Interpolation doesnt kick in until a certain threshold. I'm not sure I understand your comment.

**Comment by DerpedCrusader** [comment]
what kind of threshold? i was under the impression it was distance from the player, is there another threshold i should be aware of?

**Comment by MotoLegacy** [comment]
That is correct.

**Comment by DerpedCrusader** [comment]
after further examination, it is working, and this issue in particular doesn't seem to happen anymore

closing with this unless something else is seen
