### ISSUE TITLE
Sparkle sprite not rendered Fullbright

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#837]
**Describe the bug**
Some Sprites that were previously fullbright aren't anymore

In this issue i'm using the wunderwaffe sparks as an example, but I'm certain there's other sprites this happens to

**To Reproduce**
1. open a map
2. get the waffe
3. fire at a zombie

**Expected behavior**
Sprites like these should be full bright

**Screenshots/Footage**
![image](https://github.com/user-attachments/assets/d964d81d-fd7b-46d5-88f0-7604b75d2511)

**Affected Platforms**

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Additional context**
This is because of the change to `mod_litsprites_force`

**Comment by MotoLegacy** [comment]
We should handle this on a per-sprite basis as I'm not confident there are enough instances of this to be largely impactful

**Comment by MotoLegacy** [comment]
What about other platforms?

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/dfd5e6787e314abdfdbb8be7d730df65c636e603
