### ISSUE TITLE
[CO-OP/SERVER] When downed with raygun, you are given a colt

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#84]
**Describe the bug**
normally, when you go down with raygun, you have the raygun when you're downed instead of a Colt

**To Reproduce**
1. get raygun (can be achieved with give command)
2. go down
3. say "I have raygun pls revive" (optional)
4. notice that you no longer have raygun

**Expected behavior**
I would expect that if you have the raygun, and you go down, that you'd have the raygun to use

**Screenshots/Footage**

https://user-images.githubusercontent.com/13917665/209413572-0f990aa8-1839-40d2-b36e-430067d78aeb.mp4

**Affected Platforms:**

Only tested on WebGL

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/a1f07c75f0970544130e67bff6bdab8108d91a84
