### ISSUE TITLE
Power up sprite not rendered fullbright

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#840]
Follow up on #837 

**Screenshots/Footage**
![image](https://github.com/user-attachments/assets/6a10f6c1-02b0-4161-a497-f5148497b4a4)

**Affected Platforms**
- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/1138c79519149e112fcdde8698330a4e3d673c68
