### ISSUE TITLE
[Server][FTEQW Linux64]  nightly build returns date: invalid date 'null'

### ISSUE THREAD

**Issue by whoisfiji** [nzp-team/nzportable#842]
**Additional context**

Expected it to install requirements and launch the  game as intended,  chatgpt wasn't smart enough to fix the issue in vim so I'm posting here for support

**fiji@penguin:~$ cd nzportable-main/
fiji@penguin:~/nzportable-main$ sudo ./generate-nightly.sh**
_date: invalid date ‘null’
date: invalid date ‘null’
date: invalid date ‘null’
date: invalid date ‘null’
date: invalid date ‘null’
date: invalid date ‘null’
./generate-nightly.sh: line 34: [: : integer expression expected
./generate-nightly.sh: line 39: [: : integer expression expected
./generate-nightly.sh: line 44: [: : integer expression expected
./generate-nightly.sh: line 49: [: : integer expression expected
./generate-nightly.sh: line 54: [: : integer expression expected
./generate-nightly.sh: line 59: [: : integer expression expected
Nothing to do._
**fiji@penguin:~/nzportable-main$ sudo vim generate-nightly.sh
fiji@penguin:~/nzportable-main$ chmod +x generate-nightly.sh
fiji@penguin:~/nzportable-main$ sudo ./generate-nightly.sh**
_date: invalid date ‘null’
date: invalid date ‘null’
date: invalid date ‘null’
date: invalid date ‘null’
date: invalid date ‘null’
date: invalid date ‘null’
./generate-nightly.sh: line 34: [: : integer expression expected
./generate-nightly.sh: line 39: [: : integer expression expected
./generate-nightly.sh: line 44: [: : integer expression expected
./generate-nightly.sh: line 49: [: : integer expression expected
./generate-nightly.sh: line 54: [: : integer expression expected
./generate-nightly.sh: line 59: [: : integer expression expected
Nothing to do._
**fiji@penguin:~/nzportable-main$**

**Comment by MotoLegacy** [comment]
Why aren't you using the releases? That shell script is ran by CI to generate them. Its not designed to be used by end user.
