### ISSUE TITLE
[SUGGESTION] Voice lines

### ISSUE THREAD

**Issue by Tadeoelbeo** [nzp-team/nzportable#848]
It would be cool to play natch der toten or any map with voice lines like richtofen, nikolai, Takeo and dempsey 

It can have voice lines from the game like when you die, get a gun, turn on the power, get a perk

**Comment by Mr49-SE** [comment]
i feel like that mostly depends on the map creators if they feel like adding voicelines when certain things happen and trigger a sound like getting perks

**Comment by MotoLegacy** [comment]
Closing, this is on the docket
