### ISSUE TITLE
[SERVER] Fire Objects from TrenchBroom doesn't appear In-Game

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#85]
**Describe the bug**
_A clear and concise description of what the bug is._

The TrenchBroom Entitys/Objects with fire in their name don't appear In-Game

**To Reproduce**
1. Open TrenchBroom.
2. Place the any Fire Object.
3. Compile.
4. See no Fire.
5. Damn the Firefighters for extinguishing the flames!

**Expected behavior**
A Fire should appear at the spot of the fire Object is located at in TrenchBroom.
**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

![The .png](https://user-images.githubusercontent.com/104042185/209757095-56fedeca-436b-4e45-988b-d5e98a09a96e.png)

**Affected Platforms:**

_# Please make note of any platforms you **DID NOT** test on._

- PSP
- PS VITA
- Nintendo Switch
- The 3DS and 2DS Family

**Additional context**
_Add any other context about the problem here._

Fix pls

**Comment by BCDeshiG** [comment]
It's used in Fegefeuer above the barrel near double tap.

**Comment by MotoLegacy** [comment]
Closing as I can confirm `place_fire` is functioning correctly. The fire effects in FTE are a little sub-par compared to our other platforms and sometimes they aren't displayed, they show up for about a second and then dissipate for a second, repeatedly.
