### ISSUE TITLE
mustang and sally broken

### ISSUE THREAD

**Issue by conbobcob** [nzp-team/nzportable#850]
### Discussed in https://github.com/nzp-team/nzportable/discussions/849

<div type='discussions-op-text'>

<sup>Originally posted by **conbobcob** July 19, 2024</sup>
I noticed when you reload your last bullets in reserve it adds more than 6 bullets into the left gun. Has anybody else noticed this?
![Screenshot 2024-07-19 11 54 14 AM](https://github.com/user-attachments/assets/81bd7517-1a7e-45ca-a9e6-392244e80171)
</div>

**Comment by Mr49-SE** [comment]
Yes the same happens to me when i reload and get a max ammo , i usually
 end up with 7 bullets in the left one

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/b257777f8600c1ac63658fb83349b0376063c75d
