### ISSUE TITLE
Perk animation cancel [bug]

### ISSUE THREAD

**Issue by Exponentlink** [nzp-team/nzportable#856]
**To Reproduce**
1. Buy a perk
2. Sprint, knife, or shoot. (Idk which ones does it off the top of my head but those are three ways of canceling an animation)

**Expected behavior**
You wont have the perk you just bought, you will also not be able to buy other perks, wall weapons, sprint, or prone (lay on the ground)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/1566782705862e0f8b0ea4bbc701eb9480e69f23
