### ISSUE TITLE
[SUGGESTION] Update the Ballistic Knife and Type 100 models

### ISSUE THREAD

**Issue by capuccin0** [nzp-team/nzportable#861]
**Describe your suggestion**
While the rest of the weapon models look relatively polished, the Ballistic Knife and Type 100 stand out for how "raw" and inconsistent they look compared to the the rest of NZP weapons.

**Expected behavior**
Update the Type 100 and Ballistic Knife view models and world models to match the style of the rest of the NZP weapon models

**Screenshots/Footage**
![fte-20240805132537-0](https://github.com/user-attachments/assets/b2979605-8dad-4d0e-b42a-e9ebcb57283a)
![fte-20240805132600-0](https://github.com/user-attachments/assets/b9109f73-9e8f-4de0-8c6e-4af58a40ce96)
![fte-20240805132712-0](https://github.com/user-attachments/assets/db184601-e059-4a5a-8e7b-7a2895ac36df)
A screenshot of the M1 Garand is an example of how other models of weapons in the NZP look like compared to the Type 100 and Ballistic Knife

**Comment by DerpedCrusader** [comment]
You're free to tackle this if you want, it's all open source :)
