### ISSUE TITLE
[CLIENT] Scope in Scoped Kar98k moves choppily

### ISSUE THREAD

**Issue by capuccin0** [nzp-team/nzportable#862]
**Describe the bug**
When reloading the Scoped Kar98k, I noticed that the scoped moved choppily, while hands and the rest of the weapon moved smoothly

**To Reproduce**
1. Launch NZP
2. Choose Firing Range map
3. Buy Scoped Kar98k from the wall
4. Shoot and reload the weapon

**Expected behavior**
The scope on the Kar98k should move smoothly, just like the rifle and hands.

**Affected Platforms**
FTEQW (Linux), haven't tested on other platforms, but I assume they have the same issue, as the problem may be in the Scoped Kar98k assets, not the code

UPD: its not a problem in PSP version

**Additional context**
I don't know if the problem is in all Scoped Kar98k animations or if it appears only in the reload animation

**Comment by MotoLegacy** [comment]
Can't reproduce, either that or I don't understand what you mean. Videos or imagery could be of help.
