### ISSUE TITLE
[Help Wanted] nzportablearmhf-sdl requires specific versions of GLIBC.

### ISSUE THREAD

**Issue by MixerFLX** [nzp-team/nzportable#867]
Hello, so I've wanted to get NZ:P running on my Miyoo A30, but it's been quite a hassle. Both of the PSP versions run quite badly after about 2 rounds, so I'm going to use the ARMHF build. I already have SDL2, but I'm missing specific versions of GLIBC. It is a 32 Bit Arm Linux handheld with an Allwinner A33 SoC (if that helps), and I do have a Steam Deck as my main machine, so I can compile stuff, I'd just need some assistance. I do have this log if you'd like to inspect it. (A lot of this was done with the help of AI cause I'm a beginner, but I do understand some stuff.)

> Starting launch_nzp.sh script
HOME=/mnt/SDCARD/Roms/PORTS
PATH=/mnt/SDCARD/Roms/PORTS/libs:/mnt/SDCARD/miyoo/app:/usr/miyoo/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH=/mnt/SDCARD/Roms/PORTS/libs
Current directory: /mnt/SDCARD/Roms/PORTS/nzp
Running uname -a
Linux MIYOO282 3.4.39 #1075 SMP PREEMPT Sat Jul 13 02:15:57 UTC 2024 armv7l GNU/Linux
Contents of libs directory:
ld-linux-armhf.so.3
libGLESv1_CM.so
libSDL2-2.0.so.0
libSDL2_gfx-1.0.so.0
libSDL2_image-2.0.so.0
libSDL2_mixer-2.0.so.0
libSDL2_ttf-2.0.so.0
libasound.so.2
libdl.so.2
libdtr.so
libfreetype.so.6
libglib-2.0.so.0
libharfbuzz.so.0
libjson-c.so.5
libm.so.6
libnss_dns.so.2
libnss_files.so.2
libpcre2-8.so.0
libpng16.so.16
libpthread.so.0
librt.so.1
libstdc++.so.6
libz.so.1
libSDL2-2.0.so.0 is present
Executing nzportablearmhf-sdl
./nzportablearmhf-sdl: /lib/libc.so.6: version `GLIBC_2.33' not found (required by ./nzportablearmhf-sdl)
./nzportablearmhf-sdl: /lib/libc.so.6: version `GLIBC_2.28' not found (required by ./nzportablearmhf-sdl)
./nzportablearmhf-sdl: /lib/libc.so.6: version `GLIBC_2.34' not found (required by ./nzportablearmhf-sdl)
Execution completed

**Comment by Peter0x44** [comment]
What version of glibc does your system have?
Could you give us some information about the distro it uses?

**Comment by Peter0x44** [comment]
I think this is the sort of issue better suited to real time support. I would prefer doing this on the discord server, but I understand if you don't have and don't want to make an account.

**Comment by MixerFLX** [comment]
> I think this is the sort of issue better suited to real time support. I would prefer doing this on the discord server, but I understand if you don't have and don't want to make an account.

I've joined the NZP discord if you're there. My username is mixerflx#0

**Comment by Peter0x44** [comment]
Supporting this is actually more complicated than just the glibc version, and no one has been able to figure it. This issue should either be converted to a discussion or closed.
