### ISSUE TITLE
When creating a new game lobby is always full with random ghost players [SERVER] [Windows]

### ISSUE THREAD

**Issue by OliveRanger** [nzp-team/nzportable#868]
Every time I create a new game the lobby spawns in full so no one is able to join. I've tried removing the ghost players but nothing happens. I'm still able to join other servers just unable to star one. 
![NZP screen cap](https://github.com/user-attachments/assets/76d82efe-8d00-4a82-9874-85216f476972)

**Comment by MotoLegacy** [comment]
Can't reproduce, we recently made some changes to our config workflow that, if you manually updated and neglected to notice this, could cause this. Clean builds should be fine. Re-open if no fix.
