### ISSUE TITLE
[SUGGESTION] Can you put the song Zombie Bells on the Christmas map?

### ISSUE THREAD

**Issue by sammsq** [nzp-team/nzportable#869]
**Describe your suggestion**
A clear and concise description of what feature you'd like to be added.

**Expected behavior**
What you expect to happen or how it'll work in-game.

**Screenshots/Footage**
If applicable, add screenshots as a mock-up to help demonstrate what you want.

**Additional context**
Add any other context about the suggestion here.

**Comment by MotoLegacy** [comment]
We don't steal assets or other material. As such there will be no lifting that song as it is fully licensed by Activision. Hope this helps.
