### ISSUE TITLE
[3DS] Crash upon startup

### ISSUE THREAD

**Issue by Peter0x44** [nzp-team/nzportable#872]
**To Reproduce**
Update with universal updater
Start nzp

**Screenshots/Footage**
![image](https://github.com/user-attachments/assets/ee47d89b-32fa-4fb9-b293-625bc2020f12)

**Affected Platforms**
I tested O3DS.

Crash dump file:
[crash_dump_00000000.dmp](https://github.com/user-attachments/files/16575883/crash_dump_00000000.dmp)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/glquake/commit/e0310852d49ebd16be2070615080fa438aea2fdf
