### ISSUE TITLE
shit doesnt work

### ISSUE THREAD

**Issue by koneko** [nzp-team/nzportable#873]
cant connect with my friends, he cant connect and he cant host. fix your shit bro

**Comment by katniny** [comment]
not very nice ☹️

anyways, here's what they've **already** said:
"something ive mentioned in the past — tl;dr is peer to peer networking without any port forwarding whatsoever is basically abusive and uses a bunch of sneaky tricks and depending on a bunch of different factors it may just flat out not work for you.
the browser version (https://nzp.gay/) may have better success rate as it uses web sockets"
"yes at the end of the day you're bruteforcing p2p play with no port forwarding. it's not going to work for absolutely everyone based on tons of different factors.
it's not something i can just tell you 'do XYZ to fix'.
that is why, again, and respectfully, i genuinely cannot tell you what to do, and it's nothing to do with things on my end."

so, connect via https://nzp.gay/, port forward, or attempt to fix it yourself

**Comment by koneko** [comment]
im not trying to be mean, just angry that i wasted 30 minutes for it not work, as i did everything i could think of.
i tried both on the desktop client and the webgl one (i could connect to myself, but my friend could not connect for the life of me)
i also tried port forwarding on the client, nothing (via ngrok)
then i also hosted the webgl client and wanted him to connect via port forwarding. which he could but the client defaults (i think?) to the default websockets instead of hosting a websocket server and letting him connect that way (and there is no documentation for the webgl client, so even if i wanted to change it to host it for me, idk how (bravo on that)). any way we tried (mentioned above, room code, room name, with or without password) did not work and there is no explaination why. i tried older guide, i tried the 30 sec vid on twitter and nothing worked.
i just made this cause im frustrated, no ill will meant.

**Comment by Peter0x44** [comment]
This isn't actionable. If you want support, join the discord server. And try to control your frustration, helping agitated people only spreads the frustration to the helper.

**Comment by MotoLegacy** [comment]
Just commenting that no one is going to want to help you because you'd rather send long tangents telling us to fix [our] shit rather than trying to be respectful and asking questions and being patient towards the devs who have lives and other things to do that are more important than you being frustrated you spent 30 minutes bruteforcing a problem.
