### ISSUE TITLE
[3DS] Incorrect textures on entities

### ISSUE THREAD

**Issue by AthleticSeafood** [nzp-team/nzportable#874]
Many objects have an incorrect texture. Most commonly replaced by textures for perk bottles/stations.
Affected objects include:
- Weapon and player models
- Power-ups and their glow effect
- The mystery box
- Perk stations
- Light sources
Occurs inconsistently. Objects are affected differently (or not at all) depending on the map, and affected objects change when relaunching game.

Seen on Old 3DS. Tested maps were NdU, Dung3on, Warehouse, and Bunker Defense, but issue likely occurs on other maps as well.

Only started occurring since most recent patch.
![IMG_20240813_191148](https://github.com/user-attachments/assets/1794687f-9675-4931-98de-6832cdf70cc1)
![IMG_20240813_191234](https://github.com/user-attachments/assets/fd4d1881-92ab-45ef-ba6f-8d0be183af90)
![IMG_20240813_191107](https://github.com/user-attachments/assets/ef2d3851-4f0d-4399-b40f-b9e02a3f3cef)
![IMG_20240813_191142](https://github.com/user-attachments/assets/97c6da8c-9e34-46c8-8a98-4f19600d5a5a)

To reproduce:
1. Launch game
2. Enter Nacht der Untoten (or any map)
3. Instances should be easy to spot

**Comment by MotoLegacy** [comment]
Thanks, can you write out the steps to reproduce this? I noticed you left that out. Start to finish would be great. Thanks!

**Comment by AthleticSeafood** [comment]
No problem 👍 Updated with steps to reproduce and some extra information

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/glquake/commit/21e0494fe99939e36bbf7fe79d9e6cae698e2f79
