### ISSUE TITLE
Trenchbroom doesn't save compiler profiles

### ISSUE THREAD

**Issue by KennethFay** [nzp-team/nzportable#875]
**Describe the bug**
When creating a compiler profile for Trenchbroom, it won't save, and the console will show the error claiming that it tried to create a folder but couldn't due to it's name being invalid

1. Open Trenchbroom after a fresh v2024.1 install
2. Make a new map with a fresh gameconfig.cfg file
3. Try creating a new compiler profile
4. The error will come up

**Expected behavior**
I was expecting to be able to save the compiler profile, as i already had a folder named "NZP" for that matter specifically

**Screenshots/Footage**
![image](https://github.com/user-attachments/assets/e0a5207f-d36b-49cf-b276-a5b3285233b2)
(image from user Dudus366 on the NZP discord, as i found a fix for it already)

**Additional context**
When you open up the gameconfig.cfg file and edit the "name" tag to a valid name, it now works. i used NZP to use my v2023.1 compiling profile, which worked.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/trenchbroom-profile/pull/1
