### ISSUE TITLE
[PC] Zombie pathing issue

### ISSUE THREAD

**Issue by GirlySpider** [nzp-team/nzportable#878]
**Describe the bug**
Half the zombies of any map I play can't seem to know how to get to me. They will walk towards walls non-stop until I kill them, get close enough for them to hit me or they have been alive too long and despawn. I have a video of an example [here](https://youtu.be/uOZ64CO5CeU). If I play on a custom map or official map, I still get this issue all the time. I am on the 64 bit version of the game if that matters. I also did try only this map on the 32 bit version of the game and the issue still happened the same way, I have not tried the other platforms. I am also running the game at 500FPS if that matters. 

**To Reproduce**
1. Go to any map
2. Some windows will have the zombies completely lost. 

Sometimes it's not just when they come out of a window, they can be chasing me then turn around and walk towards a wall forever.

**Comment by MotoLegacy** [comment]
You are playing a map that very clearly states "(WORK IN PROGRESS, NOT FINISHED)" in the menu of the game. Feel free to open a report about any AI issues on maps that are actually finished/not labeled broken.

**Comment by GirlySpider** [comment]
I did state that it happens on any map I play, no matter if it's WIP or not.
