### ISSUE TITLE
[CO-OP/PC] Player names should be enabled by default

### ISSUE THREAD

**Issue by Naievil** [nzp-team/nzportable#88]
**Describe the bug**
All need to be set by default in order to have player names be displayed above the player: 

`teamplay` to 1
`team` to "1"
`scr_autoid_team` to 1

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/assets/commit/f58a23c37e961a04070e00401fc1ea21c5f0441c

**Comment by DerpedCrusader** [comment]
Just tested on WebGL build player names didn't show up
