### ISSUE TITLE
[VITA] Custom maps not appearing

### ISSUE THREAD

**Issue by HalfBlu3** [nzp-team/nzportable#886]
**Describe the bug**
Installed maps no longer appear on PS Vita. Started when I updated to the 2.0.0 nightly, and now I cant get them to come back. I've tried reinstalls and clean installs, nothing works. The version I was using previously was probably at least 6 months old. Even deleting the data folder, installing the .vpk, then dragging the new data folder doesn't work. I tried using VitaDB in case the GitHub version was broken, but it didn't make any difference.

**To Reproduce**
1. Install PS Vita version
2. Drag map files into the correct data folders
3. Open game and go to custom maps
4. Maps are not there

**Expected behavior**
The maps should be there

**Screenshots/Footage**
N/A

**Affected Platforms**
PS Vita, the same files work just fine on my PC install

**Additional context**
N/A

**Comment by MotoLegacy** [comment]
Can't reproduce. Why did you open this after not responding to me attempting to solve your support ticket for this for over a week?

**Comment by HalfBlu3** [comment]
I don't remember opening a support ticket, are you sure that was me?

I was able to solve the issue by restarting my Vita
