### ISSUE TITLE
Zombies that bleed out can drop powerups

### ISSUE THREAD

**Issue by HalfBlu3** [nzp-team/nzportable#887]
**Describe the bug**
Zombies that bleed out can drop powerups

**To Reproduce**
I was playing Kino Der Toten, turned a corner, saw a zombie die (presumably from bleeding out since I hadn't shot or knifed it at any point), and it dropped a carpenter

**Expected behavior**
I don't think they're supposed to drop powerups, but I could be wrong

**Screenshots/Footage**
Unfortunately the "record last 30 seconds" button on my computer didn't work

**Affected Platforms**
Happened on PC

**Additional context**
I was on round 6, if that's relevant

**Comment by glitcheking** [comment]
it happens in cod to

**Comment by MotoLegacy** [comment]
No it doesn't. This is a legitimate issue.

Thanks, though in the future please attempt to reproduce instead saying "could not record this specific moment". Footage is helpful.

**Comment by HalfBlu3** [comment]
I'll try to recreate the issue. Unfortunately between long bleedout times and the rarity of powerups I couldn't recreate it at the time, I'll try again tonight.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/fbfcb8ac841733af43d4ce07809d323e25e2cba3
