### ISSUE TITLE
[SUGGESTION] Toggle Sprint

### ISSUE THREAD

**Issue by Blake-Izayoi** [nzp-team/nzportable#890]
Just like how we have a toggle between "hold" and "tap" for ADS, it would be really nice to have a toggle between "hold" and "tap" for sprinting. If this were to be added, a toggle for it could be added to the "settings" menu in game. When changed to "tap", the player should only need to tap the sprint button for the in-game character to sprint, and the in-game character should only stop sprinting if the player stops moving or if the player taps the sprint button again.

This would be **incredibly** useful for players who want to reduce hand fatigue while playing, as you wouldn't need to continuously hold down the sprint button to continue sprinting. It could also be considered an accessibility feature by some, such as those with chronic hand pain.

**Comment by MotoLegacy** [comment]
Sprint should already be toggle, make sure you aren't using an old config and re-open as a bug report if it isn't working correctly.
