### ISSUE TITLE
Going down small drops interrupt sprinting

### ISSUE THREAD

**Issue by Peter0x44** [nzp-team/nzportable#896]
**To Reproduce**
1) Load up Nacht der Untoten.
2) Begin sprinting on the tiles and run onto the dirt.
3) Notice your sprint gets interrupted.

**Expected behavior**
The sprint continues as normal.

**Screenshots/Footage**
https://youtu.be/z_li2_ba6N4

**Affected Platforms**
I tested this only on FTEQW.

**Additional context**
The sprint does not get interrupted when running from the dirt to the tiles.

**Comment by Peter0x44** [comment]
This happens with stairs too, it is more general than that.
You can sprint up stairs but not down them.

**Comment by blubs** [comment]
My best guess is this relates to player physics more than it being a map issue. The abrupt change in geometry must be toggling the player's "onground" flag, interrupting the sprint (as if the player has walked off a ledge). I'm not sure what the fix might look like, but core features such as player movement require pretty thorough testing.

Two fixes come to mind: 
1. Only allow sprinting to be interrupted on some more strict condition(s)
    - Falling farther than some vertical distance?
    - Downward speed greater than some threshold?
    - "onground" flag missing for more than 0.1 seconds? 
4. Adjusting the player physics movement to provide some sort of "stiction" when walking down stairs?

**Comment by Peter0x44** [comment]
> My best guess is this relates to player physics more than it being a map issue.

Yes, this was my conclusion too. The title was wrong, will update.

**Comment by MotoLegacy** [comment]
Can we get this tested on a platform that isn't FTE?

**Comment by Peter0x44** [comment]
The case for NDU is a 2 unit drop
![image](https://github.com/user-attachments/assets/8e818b36-1c07-47ee-b25b-bb38f93edc0e)

**Comment by MotoLegacy** [comment]
Okay, but can we get this tested on a platform that isn't FTE?

**Comment by MotoLegacy** [comment]
Tested myself and confirmed this is a global issue.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/81b12b2118a2f363053c0bfdf490596153e8b5da
