### ISSUE TITLE
Max ammo text stuck on screen

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#899]
**Describe the bug**
the text max ammo will be stuck on screen when doing the steps listed below

**To Reproduce**
1. open a map (i used NDU)
2. play until you get a max ammo
3. quit and go back to main menu (haven't testing what happens if you die)
4. start a new map (I selected a different map, warehouse)
5. text will be stuck on screen

**Expected behavior**
for there to not be the text on screen

**Screenshots/Footage**

![image](https://github.com/user-attachments/assets/ff2123ec-504e-4c45-812f-ac241b348af7)

**Affected Platforms**

- Nintendo 3DS (Old, New)

only tested on 3ds, probably also applicable to PSP

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/vril-engine/commit/25df6ca0c816431a175a6b16d006fabb1dd0f5b6
