### ISSUE TITLE
Zombie gets stuck in the floor if you shoot his legs off while hopping barrier

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#9]
If you shoot a zombie's legs off using explosive weapons while they're climbing over a barrier, the resulting crawler will get stuck inside the floor. [Video demonstration here.](https://www.youtube.com/watch?v=hth9AEmtFfU)

**Comment by MotoLegacy** [comment]
What do you believe an appropriate functionality would be? Would the force of the explosion force the Zombie to fly forward (beyond the window) a bit? Would they just be immune to becoming a crawler?

**Comment by BCDeshiG** [comment]
I can't remember what COD does off the top of my head but perhaps the former would do.

**Comment by DerpedCrusader** [comment]
Since they're already climbing over, I think it should be fine if they just drop directly to the floor on the players side, 

It'd look slightly jank, but I feel that's a good medium

**Comment by blubs** [comment]
Zombies are currently coded to wait to transition to crawler after finishing the barrier hop. Looks like there’s a bug in this feature, likely forgot to update bbox and/or goal origin.

**Comment by MotoLegacy** [comment]
> Zombies are currently coded to wait to transition to crawler until after finishing the barrier hop. Looks like there’s a bug in this feature, likely forgot to update bbox and/or goal origin.

Thanks for the tip. Shall I assign this to you, since you are currently focusing on AI changes?

**Comment by blubs** [comment]
Yep, zombies are going to undergo some hefty changes in the navmesh branch prior to merge. This’ll be addressed then.

**Comment by BCDeshiG** [comment]
Just confirming I can still reproduce the bug: [https://youtu.be/iXP_EutguuE](https://youtu.be/iXP_EutguuE)

Steps to Reproduce:
1) Load up the map `4all`
2) Set the round to 21 (`impulse 22` 5 times)
3) Obtain Upgraded Ray Gun (`give 33`)
4) Shoot zombie while they are hopping over the barrier (Try not to accidentally kill)
5) Observe Zombie being stuck and not moving closer to you

**Comment by BCDeshiG** [comment]
The barrier's placement (though pretty much all the barriers in my maps are like this):

![image](https://user-images.githubusercontent.com/29164668/212563437-242656a5-21d7-4d3f-90f1-e5366d334fc8.png)

**Comment by MikeyRay** [comment]
Just did some checking in Call of Duty (Black Ops 3 to be specific, but it's not much different in the older CoDs) - if a Zombie is made a crawler mid hopping through the barrier, they will just continue their animation and become a crawler once the animation is complete. Considering NZ:P and it's accuracy towards older titles, we might want to implement the exact same functionality both for accuracy and fixing this issue.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/db90c9fd7b621e813554a2922af61d9e8b9d7313
