### ISSUE TITLE
Zombies float when their spawn is under the World Origin

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#90]
**Describe the bug**
_A clear and concise description of what the bug is._

Zombies Disobey Gravity when their Spawn Is under the World Origin causing them to float in place after they spawn this only is the case for Portable Devices.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Place a Zombie Spawn under the world origin.
2. Compile and place the map into a Portable Devices Copy of NZP.
3. Boot up the map.
4. See Space Physics on Zombies.

**Expected behavior**
_A clear and concise description of what you expected to happen._

They spawn and walk up to either you or a Barricade.

**Screenshots/Footage**

![9B54124C-E381-4CB7-BC4E-2C1943D0E437](https://user-images.githubusercontent.com/104042185/209889634-3f03e6f5-6df3-42bb-9232-caa46cafc826.jpeg)
![58CBB5DA-98A0-49AE-82A6-85CE2957B869](https://user-images.githubusercontent.com/104042185/209889643-01958266-7fff-4d38-83c0-8488528f7489.jpeg)

**Affected Platforms:**

All Portable Devices that can run NZP?

# Please make note of any platforms you DID NOT test on.

- PSP (I only tested it in PPSSPP.)
- PS VITA
- Nintendo Switch

**Additional context**

_This is WIERD…_

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/dquakeplus/commit/c0326bf2c99a4c8c3293894d5ea48df946d7cb66 https://github.com/nzp-team/glquake/commit/f044d12ce589d289b5324e82023710c2714a84ff https://github.com/nzp-team/quakespasm/commit/f5ed62245c8a0eee1239f7adde7a1420f1dc63bc
