### ISSUE TITLE
[PSP] Toggled Sprinting 

### ISSUE THREAD

**Issue by DiabloGane45** [nzp-team/nzportable#905]
**Describe the bug**
Sprinting will not stop on PSP. You will keep moving forward until you enter the "-forward" console command to stop moving at all.

**To Reproduce**
1. Launch NZP on PSP 2K
2. Use the Sprint via Triangle
3. Keep using sprint via triangle
4. Figure out how to stop running without entering console command.

**Expected behavior**
I expected to stop moving whenever I let go of the analog stick or movement key. 

**Screenshots/Footage**
N/A

**Affected Platforms**
- PSP 2k

**Non-Tested Platforms**
- PS Vita (1k, 2k)
- Nintendo Switch
- Nintendo 3DS (Old, New)
- FTEQW (Windows, Mac, Linux, WebGL etc)
/
**Additional context**
N/A

**Comment by DiabloGane45** [comment]
Sorry if I didn't add a label, I dunno how to

**Comment by MotoLegacy** [comment]
Can't reproduce on a clean copy of the latest build.

**Comment by DiabloGane45** [comment]
What does that mean?

**Comment by MotoLegacy** [comment]
I downloaded the fresh, unmodified and latest version we offer and couldn't reproduce the issue, letting go of `TRIANGLE` stops sprinting as it should.
