### ISSUE TITLE
Link on a Github Page is either Dead or misconfigured.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#91]
**Describe the bug**
_A clear and concise description of what the bug is._

On this link to the assets —> https://github.com/nzp-team/assets/releases/tag/newest there is a link directing you to another github page for people who accidentally clicked the wrong link while looking for the newest precompiled NZP version is old and most likely got it’s repo deleted in favor for [this](https://github.com/nzp-team/nzportable) NZP‘s repo but it wasn’t updated.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to https://github.com/nzp-team/assets/releases/tag/newest
2. Click on [here](https://github.com/nzp-developers/nzportable)
3. See that it sends you to a old repo from the NZP Developers but not the NZP-Team.

**Expected behavior**
_A clear and concise description of what you expected to happen._

The link should either bring you [here](https://github.com/nzp-team/nzportable) or [_here_](https://github.com/nzp-team/nzportable/releases/tag/nightly)

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

I mean you got the link it’s a 3 second job you got this!
I believe in you! (;

**Affected Platforms:**

Every Device that can access Github without getting handicapped by a old browser.

# Please make note of any platforms you DID NOT test on.

- PSP
- PS VITA
- Nintendo Switch
- Mac
- Linux
- 3DS
- N3DS
- N3DSXL
- 2DS
- N2DS
- N2DSXL

**Additional context**
_Add any other context about the problem here._

This should be fixed quick so that some curious noobies that are trying to find NZP releases for their first time won’t get lost and give up trying to play NZP.

**Comment by Paindeluxe** [comment]
That took me wayy too long to write this.

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/assets/commit/160b34dcca9e1ab9a12f5dffcd3a6e2e32e63d59
