### ISSUE TITLE
[CLIENT] Kerning behaves strangely when loading a map

### ISSUE THREAD

**Issue by Peter0x44** [nzp-team/nzportable#910]
**Describe the bug**
In the map loading screen, the kerning has a strange behavior, the text "flickers" between kerning on and off.

**To Reproduce**
Load any map

**Screenshots/Footage**
Video:
https://youtu.be/7IzksMr1ZiQ?&t=11

**Affected Platforms**
I only tested FTE.

**Comment by MotoLegacy** [comment]
Marking as wontfix, this will be automatically fixed when we move to MenuQC
