### ISSUE TITLE
custom maps not working on browser

### ISSUE THREAD

**Issue by FrostyXPP** [nzp-team/nzportable#911]
i am trying to play custom maps but i am just getting this error code every time 
somebody please help

![Screenshot 2024-09-26 10 50 10](https://github.com/user-attachments/assets/acec1b28-da25-48ee-a183-a1125377c46d)

**Comment by MotoLegacy** [comment]
not following template.

**Comment by FrostyXPP** [comment]
what do you mean by that is there a totoral i can watch for the chrome browser port?
