### ISSUE TITLE
[CLIENT] [Old 3DS XL] Incorrect Reticle Position 

### ISSUE THREAD

**Issue by ZaraPhu** [nzp-team/nzportable#919]
**Description**
On my Old 2DS XL, the aiming reticle when aiming down sights for any gun is noticeably different from where the bullets actually go. The bullets seem to go above and to the right of the sights when aiming down sights, and also when hip firing. 

**To Reproduce**
1. Load into a map.
2. Fire the gun from the hip, notice where the bullets actually.
3. Aim down sights and fire, notice where the bullets go.

You usually need to significantly over-correct by always aiming to the bottom left of enemies for bullets to hit them.

**Expected behavior**
Bullets should land approximately around the firing reticle or the sights.

**Affected Platforms**
I've seen it on my Old 3DS XL, not sure about any other 3DS models. 

I tested the linux build on my laptop and it does not have the same issue.

**Comment by MotoLegacy** [comment]
Please provide your build version and visuals to scribe what you mean

**Comment by MotoLegacy** [comment]
Closing as user never followed up, please re-open at your discretion.
