### ISSUE TITLE
[PSP/3DS] Bowie knife not precached when on wall

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#92]
**Describe the bug**
When you place a Bowie knife, it doesn't precache it in the files, causing the game to crash on some platforms

**To Reproduce**

1. make a map with a Bowie wall weapon
2. load the map on PSP/3DS (to cause the crash)
3. buy the weapon
4. crash

**Expected behavior**
you buy the weapon, and you get to keep playing

**Affected Platforms:**

PSP
3DS

I didn't test on PSP, but i know it cant handle loading un-precached files
i also didn't test on any other ones

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/4a419999154eab8f4d552f63144b7525e8a57fd5
