### ISSUE TITLE
[CLIENT] Revive icon lingers after revive

### ISSUE THREAD

**Issue by Peter0x44** [nzp-team/nzportable#923]
**Describe the bug**
The revive icon is still over the player's head after being revived

**To Reproduce**
I don't know! but it happened.

**Expected behavior**
The revive icon would disappear

**Screenshots/Footage**
https://youtu.be/ZcE-HHZHaSw

**Comment by MotoLegacy** [comment]
I cannot really do anything here without steps to reproduce. Feel free to re-open if you can figure that out.
