### ISSUE TITLE
ability to set `gravity` in world spawn

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#925]
**Describe your suggestion**
when making a map, to be able to set `gravity` in the `worldspawn` section

**Expected behavior**
set ingame gravity to an amount

[.map .bsp and custom wad](https://github.com/user-attachments/files/17267982/Maps.zip)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/0a86a64995d96c0057faf2398c6f6c3537986b30
