### ISSUE TITLE
[CLIENT] Stopwatch round timer command breaks if round takes longer than 2 minutes.

### ISSUE THREAD

**Issue by bignoobus** [nzp-team/nzportable#928]
Well its in the title, if a round takes longer than 2 minutes, god forbid you go a second over, the next round it will spontaneously combust, and go into negatives 

*Steps to reproduce whatever this is*
1. Select a map, any map you want
2. type in **scr_serverstopwatch 2**
3. wait around till it goes past the 2 minute mark
4. inform the zombies on their expired subscription to life (kill them, for those who have no humour at all :/)
5. cry because the timer is in the negatives now

**Expected behavior**
It should just reset back to 0, like any good stopwatch

**Screenshots/Footage**
https://youtu.be/gHL91uxjxCk

**Affected Platforms**
- FTEQW (Windows, Mac, Linux, WebGL, blah blah blah you get it already)

**Additional context**
Nothing much more to it.

**Comment by YUHev2BeMed** [comment]
@bignoobus I figured out something.
***SO*** I left my game open on accident, and the timer auto-fixed itself.

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/937b8b588f739ee3576718f5af087e93f4c3e8e0
