### ISSUE TITLE
[CO-OP/SERVER] Teleporter Issiues

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#93]
**Describe the bug**
theres a few

Only the first player can teleport

when any other player tries to teleport they get stuck, and player 1 is teleported to end platform (even if they aren't in the teleporter)

**To Reproduce**

1. get a squad in the teleporter
2. press the use button
3. cry when you're the only person teleported (assuming you're player 1)

**Expected behavior**
the entire squad inside the teleporter should teleport to each location, and *only* the people in the teleporter

**Affected Platforms:**

I would assume all, but only tested on WebGL

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/ed504180255efbe062ca244447fe1ba93ea07e78
