### ISSUE TITLE
`chase_active` not implemented in CSQC

### ISSUE THREAD

**Issue by JCR64** [nzp-team/nzportable#931]
**Describe the bug**
Third person view does not work correctly in FTE. Camera appears to be stuck to the player.

**To Reproduce**
1. Launch latest build of FTE or open the web version
2. Type chase_active 1 in the console when in a map

**Expected behavior**
To look similar to the PSP version

**Screenshots/Footage**

FTE:
![fte_chase_active](https://github.com/user-attachments/assets/79e93e13-edc0-4344-882f-c4909833be5a)

PSP:
![psp_chase_active](https://github.com/user-attachments/assets/df802391-9151-467a-b91c-6090a703aeb5)

**Affected Platforms**
FTE (Windows, Web)

Untested on Vita, Switch, 3DS

**Additional context**
chase_up has no effect in FTE but does in the PSP version

**Comment by MotoLegacy** [comment]
![image](https://github.com/user-attachments/assets/afa900f2-3794-4782-855a-65f4645aad77)
![image](https://github.com/user-attachments/assets/b87ffbf5-f957-49e2-a2ca-609659accd58)

https://github.com/nzp-team/assets/commit/3cd494d2ee5962eb60371bbbee9c0422b846b7dd
https://github.com/nzp-team/quakec/commit/c0bd852198a68445bbc859d89b81a2aeb083c470
