### ISSUE TITLE
[WEBGL] Screen goes black while switching weapons

### ISSUE THREAD

**Issue by kmorris1077** [nzp-team/nzportable#934]
**Describe the bug**
I'm hesitant to submit this bug, because I'm not sure the exact cause/steps to reproduce.

Was playing Rev's Adventure in the mbox room on WebGL (Firefox, Mac).  Just obtained Wunderwaffe, but didn't equip it.  Switched and fired with my other weapon and screen went black.  Dev Console is flooded with TypeError: WebGL2RenderingContext.bufferData: Argument 2 can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB [ftewebgl.js:1:105899](https://nzp.gay/ftewebgl.js)

Note there is no  HUD either. I can go into and out of full screen, but that's it.

**To Reproduce**
See above

**Expected behavior**
No black screen

**Affected Platforms**
Only tested on WebGL

**Comment by MotoLegacy** [comment]
I can't reproduce anything of the sort, feel free to re-open if you can give solid steps to repro
