### ISSUE TITLE
Some Nacht der Untoten bugs

### ISSUE THREAD

**Issue by Chinolox** [nzp-team/nzportable#939]
**Describe the bug**
Some bugs found in Nacht der Untoten related to the pathfinding of the zombies and the use of dolphin dive to access areas that should be inaccessible.

**To Reproduce**
- Dolphin dive in the sections shown in the video
- Hiding behind objects such as columns, boxes, etc.

**Affected Platforms**
Only tested on Windows

**Screenshots/Footage**
https://youtu.be/DU3L--axep0

**Additional context**
Version 2.0.0-indev+20241006072024

**Comment by MotoLegacy** [comment]
Please fill out the report details. Just having a video is not sufficient.

**Comment by JCR64** [comment]
The .map file is missing some clip brushes which allows the player to jump on the file cabinet and out the window:

![missingclip1](https://github.com/user-attachments/assets/a5ec7ac5-13bc-47be-8174-7857a943c235)

![missingclip2](https://github.com/user-attachments/assets/52eba3f6-ac0a-429a-8d8f-b45098e6172e)

As for the issues with hiding behind objects and the waypoints, it seems to be FTE specific as I wasn't able to replicate any of the issues in PPSSPP. Some notes:

- When you go out of sight of a zombie in FTE it appears to interrupt their path, so they backtrack to a previous waypoint before going to the next. In PPSSPP they carry on going to the next waypoint regardless.

- Slopes behave differently between the FTE and PSP version, this in addition to the previous point is causing the issue seen at the beginning (the debris they're standing on in a slope).
