### ISSUE TITLE
[NX/VITA] Crash when loading Custom Maps Menu

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#94]
**Describe the bug**
When selecting "custom maps" the game hard crashes back to home menu (on switch)

**To Reproduce**

1. open game
2. select solo
3. select custom maps
4. observe

**Expected behavior**
I would expect a list of all the custom maps installed to be presented in front of me for my choosing

**Affected Platforms:**
Vita/NX

I only tested on switch, but there are reports of it happening on the vita as well

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakespasm/commit/634b9a7dd40de0ec08fa3da0f41ef019bf992e9a
