### ISSUE TITLE
[FTE] The Solo menu is still selectable during the loading screen

### ISSUE THREAD

**Issue by JCR64** [nzp-team/nzportable#943]
**Describe the bug**
When loading a map selected from the "Solo" map list, you can still click and load maps from the list while the loading screen is displayed.

**To Reproduce**

1. Click Nacht der Untoten from the list in "Solo"
2. Move your mouse cursor to where Warehouse would be in the list
3. Click your mouse to now load Warehouse

(can use any of the maps from the list in "Solo")

**Expected behavior**
For clicking your mouse to not have an effect during the loading of map so that the one originally selected is the one played.

**Screenshots/Footage**

https://github.com/user-attachments/assets/16e7343e-3288-473d-a9cf-5c1d3f2fd988

**Affected Platforms**
FTE (Windows, Web)

**Additional context**

- Doesn't happen if selecting maps in the "Custom Maps" menu
- During the loading screen you can select "Back" at the bottom (sound confirmation) but that doesn't seem to do anything.

**Comment by MotoLegacy** [comment]
Marking as wontfix as this will be a non-issue when MenuQC branch is merged.
