### ISSUE TITLE
[FTE] Pressing the Escape key while loading a map causes the player to lock

### ISSUE THREAD

**Issue by JCR64** [nzp-team/nzportable#944]
**Describe the bug**
When loading a map pressing the Escape key will cause the player to start in a locked position unable to move.

**To Reproduce**

1. Load into any map
2. When the loading screen is on screen press the Escape key

**Expected behavior**
For the Escape key to have no effect during the loading screen to allow the game to finish loading successfully or for it to take the player back to the Map selection menu.

**Screenshots/Footage**

Player locked and unable to move:

https://github.com/user-attachments/assets/20f8cd00-6322-43a1-a565-73833c28fb5e

Sometimes this menu screen comes up instead:

![menuscreen](https://github.com/user-attachments/assets/ff4cd96d-f8f3-4198-b572-2d34a5ee7a63)

**Affected Platforms**
FTE (Windows, Web)

**Additional context**

- Happens in both map lists, "Solo" and "Custom Maps"
- The loading screen is very fast so the timing can be tricky to reproduce sometimes. Too early and the player will be fine.

**Comment by MotoLegacy** [comment]
Marking as wontfix as this will be a non-issue when MenuQC branch is merged.
