### ISSUE TITLE
[WEBGL] Gamepad buttons X/Y are wrong way round

### ISSUE THREAD

**Issue by JCR64** [nzp-team/nzportable#945]
**Describe the bug**
Pressing X on your gamepad will be Y in-game and pressing Y will be X in-game.

**To Reproduce**

1. Connect a gamepad and open the website
2. Enable gamepad preset and notice reload and swap are wrong way round while playing

Alternatively instead of enabling the gamepad preset, using the controls menu to change controls manually you'll see X/Y are wrong way round.

**Expected behavior**
For X to be X and Y to be Y.

**Screenshots/Footage**

Showing it happen in controls menu:

https://github.com/user-attachments/assets/a5fb5bc7-1ac1-4ea9-86f8-1a4d2fa236e0

**Affected Platforms**
FTE (Web)

**Additional context**

- Doesn't affect FTE (Windows)
- The input showing as "Joy1" also sometimes happens in the WebGL version

**Comment by Peter0x44** [comment]
Which controller and which browser are you using?

**Comment by JCR64** [comment]
Microsoft Edge and Xbox Series X/S Controller (via Bluetooth)

**Comment by MotoLegacy** [comment]
Please file this to https://github.com/fte-team/fteqw instead.
