### ISSUE TITLE
[SUGGESTION] [FTE] [CLIENT] The ability to add maps to web version

### ISSUE THREAD

**Issue by YUHev2BeMed** [nzp-team/nzportable#946]
**Describe your suggestion**
Hi there. I was looking through the maps in the discussions tab and thought they look interesting. Unfortunately, I only have access to the online version, and as far as I've checked, you cant add custom maps to it. A nice feature to add would be to be able to add the maps in their `.zip` folder.

**Expected behavior**
When you enter the game, click on solo or multiplayer, then custom maps, then there should be an `Add custom map (experimental)` button. Click, and choose the zip file that has the map.

**Screenshots/Footage**
None available

**Additional context**
N/A

**Comment by DerpedCrusader** [comment]
you actually can do it with any maps that follow install standard

take the `.zip` file, rename it to a `.pk3` file, and drag and drop in. now, it might not show up in the custom map list, but if you open the console, and type in the name of the map, it works just fine


https://github.com/user-attachments/assets/e6101955-c719-40a8-9dd9-702f571b5c3b

**Comment by MoltenWolf85** [comment]
It doesn't run the map

**Comment by MoltenWolf85** [comment]
![Screenshot 2024-11-12 4 00 25 PM](https://github.com/user-attachments/assets/ca6ee490-ad90-4622-8e8b-3b03ef3dee41)
