### ISSUE TITLE
`Boxxer` map spawns

### ISSUE THREAD

**Issue by YUHev2BeMed** [nzp-team/nzportable#948]
**Describe the bug**
Whenever I load into Boxxer and it is the first round, zombies spawn behind the wall that blocks the power-ups.

**To Reproduce**
1. Click "Solo"
2. Click "Custom Maps"
3. Load "Boxxer"
4. Play first round
5. Observe bug

**Expected behavior**
The expected behavior is that the zombies will spawn in the cramped space instead of behind the wall for the first wave.

**Screenshots/Footage**
I cannot currently provide footage right now (damn you, QuickTime...)

**Affected Platforms**
Only WebGL
I have not tested any other platforms.

**Additional Info**
Eventually, after a bit, the zombies despawn and spawn from the ground in the space.

**Comment by MotoLegacy** [comment]
This map is just kinda badly designed. @DerpedCrusader can I assign this to you to either make the teddy thing more obvious or to just make the extra spawns inactive until the door is open?

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/d1c4a0c7d34969652ec4cb21353a8aa73fda52d7
