### ISSUE TITLE
[SUGGESTION] unblocked webgl version of nzp

### ISSUE THREAD

**Issue by eliasyior** [nzp-team/nzportable#956]
Can you show us how to make our own webgl version or make an unblocked version please? I would love it thank you.

**Comment by DerpedCrusader** [comment]
What do you mean unblocked? I can Access it just fine on my machine

**Comment by eliasyior** [comment]
I mean like I want to play it at school and they blocked they website.

**Comment by MotoLegacy** [comment]
Focus on your schoolwork friend

**Comment by eliasyior** [comment]
I do I get it done and then I have like 20 extra mins to do something but instead I do nothing because everything is blocked.

**Comment by eliasyior** [comment]
damn it

**Comment by eliasyior** [comment]
Why did you close it the issue still stands.

**Comment by eliasyior** [comment]
Okay well sorry.

**Comment by eliasyior** [comment]
I won't bother you guys anymore.
