### ISSUE TITLE
Some files don't get downloaded during MP

### ISSUE THREAD

**Issue by DerpedCrusader** [nzp-team/nzportable#96]
**Describe the bug**
When connecting to an MP host, the client doesn't download enough files for the map to work properly 

These files include: ambient BGM, Skybox textures,  external textures for models

**To Reproduce**
1. Have a map with one of the above file types
2. Host a server
3. Have Someone without those files connect
4. Observe 

Expected behavior**
you would expect that it would detect these files and download them as well

**Affected Platforms:**

I tested this on PC,

I'd probably just recommend when people play together, you just have everyone have the map downloaded

**Comment by MotoLegacy** [comment]
Unfortunately I can't do anything about this, after having a discussion with Spike about it. Sorry.
