### ISSUE TITLE
Multiple targets on buy_weapon only triggers the first target

### ISSUE THREAD

**Issue by F0mx** [nzp-team/nzportable#961]
Setting multiple targets for a buy_weapon weapon wall will only trigger the first target on purchase and not subsequent targets.
Pictured below with Mustang and Sally, using 2 M1911 weapon_wall's

![Capture1](https://github.com/user-attachments/assets/9c9754f0-e38d-4d95-ad17-f264eeec21b2)
![Capture2](https://github.com/user-attachments/assets/402a464d-b164-44b2-b46f-88d1165884c5)
![Capture3](https://github.com/user-attachments/assets/f34810ee-2cc0-42a0-81c0-fec2dbd515d6)
![Capture4](https://github.com/user-attachments/assets/4cd0151f-f906-4f9f-8fc9-db7c6fcbe177)

Attached map files:
[MultipleBuyWeaponTargetBug.zip](https://github.com/user-attachments/files/17603159/MultipleBuyWeaponTargetBug.zip)

**Comment by MotoLegacy** [comment]
![fte-20241103095335-0](https://github.com/user-attachments/assets/51067fc8-bf23-4390-9545-6d62b948af49)


fixed in https://github.com/nzp-team/quakec/commit/35d887fb551d06db9a8b180c0348019f4f8a4aa6

(BTW, please use shorter map names next time :P)
