### ISSUE TITLE
Settings never save

### ISSUE THREAD

**Issue by coreybruce** [nzp-team/nzportable#962]
**Describe the bug**
When you change the settings like the resolution or other settings it will say ```Wrote $basedir/nzp/user_settings.cfg``` but once you restart everything is reset to the default setting. I have noticed this for a while and wanted to report this so it could be fixed, I just have the files in the .config folder.

Also I notice this message everytime I launch it in the terminal
```
./nzportable
Binary is located at "/home/corey/.config/NZP/"
couldn't exec config.cfg
couldn't exec nzportable.cfg
couldn't exec autoexec.cfg
```

**To Reproduce**
1. Open game
2. change game settings
3. restart game
4. game runs with default settings

**Expected behavior**
Saves settings

**Screenshots/Footage**
Before:
![image](https://github.com/user-attachments/assets/f7e714a2-d148-418e-9d7c-fe218897f623)
After:
![image](https://github.com/user-attachments/assets/22a814ea-925e-4d46-9a53-751b1e7e4f57)

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.
Linux

**Comment by MotoLegacy** [comment]
I can't reproduce this ever since I massively rewrote our menu system. Can you give the latest builds a try and re-open if this still reproduces for you?

**Comment by coreybruce** [comment]
I tried the latest version but I have the same issue, I'll set the resolution and even my multiplayer name and when I close it the resolution in the settings will be reset even tho the config shows it 

![image](https://github.com/user-attachments/assets/1332a67c-3152-4336-9afd-f9976db075e3)

![image](https://github.com/user-attachments/assets/d641e3d3-e7eb-44ba-a21c-ad8a6f25974b)

![image](https://github.com/user-attachments/assets/302c9387-6ea1-491e-9ee6-169521e8e079)

**Comment by MotoLegacy** [comment]
The resolution menu will always display the lowest supported at the start of the app, not the current/closest window resolution. Dumb bug I introduced myself :( I can't reproduce anything about the names or any other settings.

**Comment by coreybruce** [comment]
Ah I see that's a pain

So once you've set your name it stays? mine always resets to unknown solider 

Before:
![image](https://github.com/user-attachments/assets/c4908039-4206-47e8-bbdd-cf93878018d8)

After restart:
![image](https://github.com/user-attachments/assets/171e9053-79f8-4f7d-822c-41c6b9cf4402)

**Comment by MotoLegacy** [comment]
You have to first click apply on another settings screen see (https://github.com/nzp-team/nzportable/issues/986), but yes it is dumped to `user_settings.cfg` once this is done and appears on a re-load

**Comment by coreybruce** [comment]
Also the reset issue has to been happening with my nzportable-bin package for a while and will reset the Windows to a small window after you set the resolution

**Comment by coreybruce** [comment]
> You have to first click apply on another settings screen see (#986), but yes it is dumped to `user_settings.cfg` once this is done and appears on a re-load

Which settings screen exactly?

**Comment by MotoLegacy** [comment]
Any. They all run `saveconfig` which will dump all of the `cvars` (including `name`) to `user_settings.cfg`

**Comment by coreybruce** [comment]
Still having this issue

**Comment by coreybruce** [comment]
Fixed with latest launch script, it seems to have some weird issues if it copies the games files from a the system root location so I changed how the package is packaged and script works which fixed the issue.
