### ISSUE TITLE
Pack-A-Punch sting is missing entry in `FGD`

### ISSUE THREAD

**Issue by F0mx** [nzp-team/nzportable#965]
Currently PaP has inconsistent jingle functionality when compared to perk machines. It uses `powerup_vo` as an on-purchase jingle sting instead of `aistatus` like perk machines do, and `aistatus` does nothing when input.

**Comment by MotoLegacy** [comment]
Is this not properly documented on the `FGD`? I'm a little hesitant to tackle this since it would be a behavioral change that could add complexity to loading older maps.

**Comment by F0mx** [comment]
No, you have to manually add `powerup_vo` as it doesn't have it listed as an entity property by default. It does actually work when added though, playing any audio you define in the field on interact of the machine.

Honestly, it would be nice if it was a default option in the `FGD` that was there for map makers that might not be so willing to just stick in keys to see what works, since it does still enable adding a sting to pack-a-punch on use.

If it is to be integrated properly, it might need a delay adding on to it between interacts, since unlike perk machines you can chain use it, where audio might overlap as a result.

**Comment by MotoLegacy** [comment]
Thanks, I am going to convert this issue to this field not being present on the FGD. Could you report the lack of delay timings as a separate issue?

**Comment by F0mx** [comment]
Sure thing

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/df3d389851dd81ee05c23e1429daf38b85f23bb8
