### ISSUE TITLE
Muzzleflash offsets in ADS

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#97]
Was testing the MP5k finally. i noticed the Muzzle Flash when you ADS doesn't move from the Hip Fire position

To Reproduce:
just simply give yourself the mp5k using "give 54" in the console.

**Expected behavior**
it should move with the gun when you ADS

![image](https://user-images.githubusercontent.com/34180180/211273519-23df4cdc-72f9-4d70-852a-5c6aac7fcccb.png)

only tested on PC

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/f385a047127dc496de0090ed999189a77d23face
