### ISSUE TITLE
Custom Maps don't work on WebGL version

### ISSUE THREAD

**Issue by MoltenWolf85** [nzp-team/nzportable#971]
I try to drag the zip into the site, and it crashes, and everything else just doesn't load.
![Screenshot 2024-11-12 12 21 31 PM](https://github.com/user-attachments/assets/24132761-75db-4a7f-af99-0fdaf2a19997)
![Screenshot 2024-11-12 12 21 20 PM](https://github.com/user-attachments/assets/9c88106c-2470-4f68-a8da-a124a34d8b1e)

**Comment by ToasterPanic** [comment]
They do work, just Kino Der Toten doesn't work for some reason. As far as I can tell, you're supposed to rename the .zip to .pk3 before you drag it into the window. When loading Kino Der Toten properly, it gives this error:

![image](https://github.com/user-attachments/assets/f7c0e4ae-4eac-4c05-b77b-498eb32afd5c)
