### ISSUE TITLE
Keep freezing in the late game on f4ll

### ISSUE THREAD

**Issue by Kingjaxgaming420** [nzp-team/nzportable#972]
I've been trying to get the f4ll world record for a few weeks now, and have had multiple games in the 50's freeze for unexpected reasons. Every time I freeze, I dont get an error code or anything, so yeah, I'm a bit confused. 
![image](https://github.com/user-attachments/assets/33279e1f-3309-4599-8184-9b0daa9eb56a)

**Comment by MotoLegacy** [comment]
I can't really do anything without logs. Feel free to re-open if you attach some.
