### ISSUE TITLE
Controller glyph overlap

### ISSUE THREAD

**Issue by JCR64** [nzp-team/nzportable#973]
**Describe the bug**
The controller glyph for `Interact` overlaps the second line of the message shown at buyable doors and weapons.

**To Reproduce**
Play a map on FTE with controller options enabled and walk up to something buyable.

**Screenshots/Footage**

![fte-glyph1](https://github.com/user-attachments/assets/27ffee9f-d821-4958-a12a-8fd07c3c66ea)

![fte-glyph2](https://github.com/user-attachments/assets/9d9e4059-2647-40fd-a741-c6837b282c35)

**Affected Platforms**
FTE (Windows, Web)

Untested on Vita, Switch, 3DS

**Additional context**
I tested with some different controller glyphs options and all had the same problem.

PSP for reference:
![psp-glyph1](https://github.com/user-attachments/assets/6f3680fa-01a9-41a8-b4b9-adbaebd75357)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/514d98c6e84dca691e1d61a316b3cd86e87da27f

![fte-20241126114728-0](https://github.com/user-attachments/assets/48759951-cac2-4e28-a4a4-be5bfb5c527b)
