### ISSUE TITLE
FTE Skybox inherits game brightness 

### ISSUE THREAD

**Issue by F0mx** [nzp-team/nzportable#974]
Noticed it whilst working on a night time skybox, but it seems that on FTE, game brightness affects skybox textures improperly causing them to become washed out and too bright. If you set the brightness to as low as possible in-game, they display much more like what they should actually look like.

Even as a patchwork fix, it'd be nice if textures displayed correctly when brightness is at 50%, since that seems to be the most commonly used setting between players.

[Map to show this in action: Fomx_Skybox.zip](https://github.com/user-attachments/files/17771662/Fomx_Skybox.zip)

![image](https://github.com/user-attachments/assets/14d82437-676a-4fa0-a4de-00278c410cf9)
Skybox at 50% in-game brightness

![image](https://github.com/user-attachments/assets/0a4b4bd7-51d6-47c3-a79e-ba823cdc1d71)
Skybox at lowest in-game brightness

![image](https://github.com/user-attachments/assets/dbec0a07-88cf-4ac3-a8ba-e40e7bff5f44)
Raw skybox texture

**Comment by MotoLegacy** [comment]
I've forwarded this over to Spike to do what be will upstream
