### ISSUE TITLE
Zombies "Spawn" Noises, play from both the Zombie and World Origin.

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#976]
**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to any Map.
2. (Optional) Turn 1 Ear to the Zombies and 1 Ear directed at the World Origin.
3. Hear Schizophrenic Hallucinations of Zombies which are lurking inside of a Wall.

**Expected behavior**
_A clear and concise description of what you expected to happen._

I only hear Zombie Noises from the Zombie.

**Screenshots/Footage**
_If applicable, add screenshots or a video to help explain your problem._

https://youtu.be/9mKGyyINEUE

**Affected Platforms**

I have only tested this on FTEQW (AUR Build) and not on any other Platform/Device.

**Additional context**
_Add any other context about the problem here._

This is not Wave specific.
And a unrelated Question, how do you show your Speed, or Position in NZP? I can't get it to work... ):

**Comment by F0mx** [comment]
This is also true of perk jingles if you have them enabled on a map, prime example being my Croft Manor map where you can occasionally be jump scared by the deadshot theme blasting whilst by the front door

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/b3c25885ef5609bcdc75f3bfc0949b3b2e5e085e
