### ISSUE TITLE
A number of entities in the FGD do not automatically make use of the `angles` property, making them unrotatable by default

### ISSUE THREAD

**Issue by F0mx** [nzp-team/nzportable#980]
As title says, the following entities either use `angle` instead of `angles`, or do not default to either:
- `explosive_barrel`
- all four `func_teleporter` options
- `item_radio`
- `light_spot`
- both `mystery_box` variants 
- all variations of perk machine
- `place_model`
- `power_switch`
- `weapon_wall`
- all three components of `zapper`

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/a9dc7f7a46ee19956b27b28c3aef7349b17c9a08
