### ISSUE TITLE
Mystery box reorients its angle in-game

### ISSUE THREAD

**Issue by F0mx** [nzp-team/nzportable#981]
Mystery box does not retain it's `angles` property in-game, meaning any alternate orientations like an upside-down box (akin to those found in the map Die Rise) are not currently possible

![image](https://github.com/user-attachments/assets/8a5e017b-9262-41d4-bbd0-a4e83915d797)
![image](https://github.com/user-attachments/assets/0c0b3ffc-02d6-4bbd-8c2a-f0d2c2d58e9e)

Example map: 
[Fomx_Mysterybox.zip](https://github.com/user-attachments/files/17895102/Fomx_Mysterybox.zip)

**Comment by MotoLegacy** [comment]
Not a bug, what is happening here is that the engine prioritizes `angle` over `angles`, which is explicitly set to `0` with this ent. If I open the BSP in a hex editor and bug out the `angle` field, the box is as it should be (using `60 0 30` for `angles`).

![image](https://github.com/user-attachments/assets/f2ede653-00d2-4a39-9ed4-f623b319be75)

I will remove the `angle` key with https://github.com/nzp-team/nzportable/issues/980, making this not a problem during normal map usage.
