### ISSUE TITLE
Player names do not save

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#986]
**Describe your suggestion**
would be good if there was an apply button whenever you set your name so it saves for next time you start the game. same for when you set a servername

**Screenshots/Footage**
![image](https://github.com/user-attachments/assets/5f4a53e7-0d5e-4c44-98f9-6fb64fbfab7e)
![image](https://github.com/user-attachments/assets/162a4389-0e3b-498a-8faf-053a330cc65d)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/93cb148e2e1d8ff1cabb633b9204e5c08954661f
