### ISSUE TITLE
[PSP] Kar98k Scope animation is not matching the weapon animation

### ISSUE THREAD

**Issue by TheSubPlayer** [nzp-team/nzportable#99]
The Kar98k scope animation is not working as it should, it is "floating" on top of the gun.
Tested on PSP 3000 and Win64

https://user-images.githubusercontent.com/110436924/212230191-59ae3186-a8bc-4026-ab0a-d00eef774b8a.mp4

Not tested on:

- PS VITA
- Nintendo Switch
- 3DS

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/a088c5aa9d5d335c9189ab0121702b40ff4ab0ac
