### ISSUE TITLE
Visuals Breaking at 155FOV or Higher

### ISSUE THREAD

**Issue by katniny** [nzp-team/nzportable#991]
**Describe the bug**
When setting FOV at or above 155, visuals start to appear abnormally. Objects seem more distant and objects may stretch when looking up or down.
The higher the FOV, the worse the effects occur.

**To Reproduce**
1. Go onto any map
2. Press Escape
3. Go to Options >Video > Field of View 
4. Set Field of View to 155 or higher
5. Unpause, look around/move around, and observe bug

**Expected behavior**
Objects to not appear extremely distant and stretched, but for the game to appear normally--just at a higher FOV.

**Screenshots/Footage**
https://www.youtube-nocookie.com/embed/3Pn5-XmXmlM
[Sorry for YouTube link by the way, video somehow came out to 80MB and the Internet Archive won't let me verify my email, so this was pretty much my only option ):]

**Affected Platforms**
Only tested on FTE (Windows 64-bit)

**Additional context**
Bug only starts at 155FOV, and the bug worsens the higher the FOV is past that point.
This is also all with the in-game Field of View slider, I did not use any console commands to achieve this bug.

**Comment by MotoLegacy** [comment]
> I did not use any console commands to achieve this bug.

We don't cap the video settings at 120?

**Comment by katniny** [comment]
It was capped at 200

**Comment by MotoLegacy** [comment]
I see. I'm not sure why I decided to do that. I will cap it to 150 because anything higher is a bit silly. Regarding the bug itself please report it to upstream FTEQW: https://github.com/fte/fte-team

Looks to me like the world is intersecting with `RF_VIEWMODEL`

**Comment by MotoLegacy** [comment]
Since this is an upstream FTE issue I decided to just cap fov at 150, at least until its fixed:
https://github.com/nzp-team/quakec/commit/25b1e08b56d4d0c2f1d8b74f28b7c123b0666dd2
