### ISSUE TITLE
Spectating causes spectatee's screen to flicker between positions

### ISSUE THREAD

**Issue by Peter0x44** [nzp-team/nzportable#992]
**Describe the bug**
This is tough to describe, look at the videos

**To Reproduce**
1. Join CO-OP game
2. Go down and bleed out
3. Spectate a player
4. That player will notice weird flickering on their screen
5. This stops if you stop spectating the player and use the free cam

**Screenshots/Footage**
https://youtu.be/_AMUenlKKXw
https://youtu.be/CLKHaVYoWGY

**Comment by MotoLegacy** [comment]
Looks to me like the users position is desynced between the client and server. So the camera is constantly shifting between the two positions.

**Comment by Peter0x44** [comment]
I can see the door at the spawnpoint between the two positions, and you can see the model of the player drawn on the spectators screen (despite that the player is dead and not supposed to be there)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/25832d650ec00bf7531f3b8c26efb5764a01b42f
