### ISSUE TITLE
Ray gun reload doesn't complete if you shoot

### ISSUE THREAD

**Issue by Peter0x44** [nzp-team/nzportable#993]
**Describe the bug**
The ray gun reload can be interrupted towards the end if you hold fire.

**To Reproduce**
1. Shoot the ray gun
2. Press reload, then begin holding the fire button
3. Notice the next shot fired will interrupt the reload

**Expected behavior**
The reload would complete before firing the shot

**Affected Platforms**
I only tested FTEQW

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/6f1fecbb861d25d1c874f837751df4e51d640899
