### ISSUE TITLE
Nacht der Untoten: Some spots missing CLIP

### ISSUE THREAD

**Issue by JCR64** [nzp-team/nzportable#994]
**Describe the bug**
There's 3 spots in Nacht der Untoten missing CLIP, allowing the player to stand in a NOCLIP. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Play Nacht der Untoten
2. Walk (or crouch/crawl for 2 of them) into areas seen in screenshots

**Screenshots/Footage**
Two are in the first room with shelf models in first room:

![missingclip1](https://github.com/user-attachments/assets/5dfff5f5-cb49-4e79-b021-c67a77c68f11)

![missingclip2](https://github.com/user-attachments/assets/0e0d36f9-2890-4da3-88e1-e317abc068c6)

Fence/sandbags above stairs:

![missingclip3](https://github.com/user-attachments/assets/d810d48e-08c0-4830-9336-6a02d66b1bc5)

**Affected Platforms**
Tested on FTE (Windows, Web) and PPSSPP

**Comment by DerpedCrusader** [comment]
I'll take a look at this when I get home

**Comment by MotoLegacy** [comment]
Assigning this to @DerpedCrusader .

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/assets/commit/b5e1f9dad88182c95acd5bf200aa26550746be08
