### ISSUE TITLE
`Sys_Error: Failed to allocate SOC_Buffer`

### ISSUE THREAD

**Issue by Peter0x44** [nzp-team/nzportable#995]
**Describe the bug**
Starting NZP from the homebrew launcher logs the message:
Sys_Error: Failed to allocate SOC_Buffer
and hangs

**To Reproduce**
1. Open the homebrew launcher
3. Start NZP

**Affected Platforms**
I only tested the Old Nintendo 3DS

**Comment by MotoLegacy** [comment]
Can't reproduce on new hardware. Will wait for confirmation on old systems.

**Comment by Ellis243454** [comment]
> Can't reproduce on new hardware. Will wait for confirmation on old systems.


I am also having the problem with that exact same error message ![20241202_131847.jpg](https://github.com/user-attachments/assets/fba46155-8b79-4f65-a86b-dbe2c5f9f595)

**Comment by Davi16arcej** [comment]
Same poblem here

**Comment by Mustardnote3943** [comment]
I too having this problem on my old 3DS

**Comment by Hm07peatnis09** [comment]
Has anyone actually ever been able to solve the issue?i keep getting the error too on my old 3dsXL.
Also sorry for my bad grammar,english isnt my main language.

**Comment by Davi16arcej** [comment]
> Has anyone actually ever been able to solve the issue?i keep getting the error too on my old 3dsXL. Also sorry for my bad grammar,english isnt my main language.

Yes,it keep hapening,prob they gonna solve but we need to wait a litle bit,keep looking every day for updates of the game,every day at 3 AM or PM (i dunno wich one)

**Comment by Peter0x44** [comment]
The issue has been confirmed, there's no need to check daily
Just subscribe to the issue and you'll get a notification when it's fixed.

**Comment by codghost1696** [comment]
yeah same here. i just updated the game and when tried launching it. i run into the same problem

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/vril-engine/commit/60a930f132a35077b433c2edc9ddac0946b6815a

**Comment by w1lm34r** [comment]
Me ayudan por favor con mi problema lo que pasa es que el juego se me crashea como en la ronda 7 además tengo un problema que cuando estoy jugando en un mapa todo bien pero cuando me salgo al menu y entro a otro mapa y todo se ve oscuro y de repente se aclara todo esto en old 3ds
