### ISSUE TITLE
Misc_Model Animations

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#996]
**Describe the bug**
misc_model doesn't animate when you set a **first_frame** and **last_frame**. in fact it just makes the model disappear entirely.

**To Reproduce**
1. create a new map where you have enough space for you(the player) and the model can fit in.
2. place a misc_model with a model that can be animated.
3. set a first_frame and final_frame in where the model is animated
4. compile map and open it in NZP.
5. notice that the model doesn't show/run an animation

# Expected behavior
setting a first/last frame should not hide the model. it should run an animation. 

# Screenshots/Footage
**Footage of it working in Quake**

https://github.com/user-attachments/assets/7a8ceb27-4fce-4c7d-855e-80eaaa9e7200

**settings in TB**
![image](https://github.com/user-attachments/assets/54390d51-29ad-4054-a6ca-d92988f2e86e)

**image of it in NZP**
![image](https://github.com/user-attachments/assets/ee5a453f-f4e2-431a-9992-81a362c50794)
**settings in TB**
![image](https://github.com/user-attachments/assets/4e9d9035-2fd8-4855-a77f-c624382f2533)

# Affected Platforms
**FTE**
**did not test on other platforms**

**Comment by MotoLegacy** [comment]
Please provide the map file and model for testing.

**Comment by Revnova** [comment]
> Please provide the map file and model for testing.

for both games or just nzp's?

**Comment by MotoLegacy** [comment]
Just NZP, assuming the ents are identical. thanks

**Comment by Revnova** [comment]
[Animation-Testing.zip](https://github.com/user-attachments/files/17968228/Animation-Testing.zip)

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/dc8ff52c39894fb66225957c9f30158b98420372
